### ISSUE TITLE
Left-handed trait description

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#101]
Master branch

Left-handed trait description still talks that left-handed characters seen with suspicion by the clergy, but don't have any negative opinion effects.
<details>
<summary>Click to expand</summary>

![ck2_8](https://user-images.githubusercontent.com/46576860/52128511-3200f300-2646-11e9-9409-7d84e6945a68.png)

</details>

**Comment by DukeJeans** [comment]
Fixed
