### ISSUE TITLE
[BUG] | Night Elf Empire Plot for Claim 

### ISSUE THREAD

**Issue by Hamstarox** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1014]
**Your mod version is:**
Latest ModDB Version.

**What expansions do you have installed?**
All.

**Are you using any submods/mods? If so, which?**
No.

**Please explain your issue in as much detail as possible:**
'Plot for Claim' is unavaliable for the Kaldorei Empire despite meeting all the requirements.

**Steps to reproduce the issue:**
Be a king under Tyrande, click on the Empire's Coat of Arms, plot is greyed out despite the conditions being met. Unavailable in the plots part of the intrigue menu as well.

**Upload an attachment below: .zip of your save, or screenshots:**
![image](https://user-images.githubusercontent.com/22781636/71162843-090a4080-22a0-11ea-887d-91897663dbc5.png)

**Comment by zumbak04** [comment]
Looks like vanilla bug, though can be fixed.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/71558676-42e10100-2a6f-11ea-81aa-93805d215064.png)

</details>
