### ISSUE TITLE
[BUG] | d_uldum does not contain c_uldum

### ISSUE THREAD

**Issue by Hamstarox** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1018]
**Your mod version is:**
Latest ModDB Version.

**What expansions do you have installed?**
All.

**Are you using any submods/mods? If so, which?**
None.

**Please explain your issue in as much detail as possible:**
The duchy of Tol'nariv (d_uldum) does not contain Phetessin (c_uldum). It is unclear if this is intended due to the duchy being named Tol'nariv and it's duchy capital being marked as such but the tag is Uldum related.

**Steps to reproduce the issue:**
Check the tags.

**Upload an attachment below: .zip of your save, or screenshots:**

**Comment by zumbak04** [comment]
Not bug. `c_uldum` was renamed **Phetessin** exacly because it is beyond borders of `d_uldum` title.
