### ISSUE TITLE
Open old gods cultist are worried about being secret cultist

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#102]
Master branch

Either this event should not fire for open cultist, or have a different text.
<details>
<summary>Click to expand</summary>

![ck2_7](https://user-images.githubusercontent.com/46576860/52131286-7348d100-264d-11e9-9a4c-74d35a93b145.png)

</details>

**Comment by MemeWizard** [comment]
Event: MNM.10020

**Comment by DukeJeans** [comment]
Fixed
