### ISSUE TITLE
[SUGGESTION] | Kaldorei Religion Rename

### ISSUE THREAD

**Issue by Hamstarox** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1022]
**Describe your suggestion in full detail below:**
Renaming the Night Elf faith to "Elune" instead of "Kaldorei". Currently the culture and the religion are named the same which leads to confusion when attempting to differentiate (The game will say you are a Kaldorei Kaldorei for example

**Comment by MemeWizard** [comment]
Closed, since it's duplicate of #958
