### ISSUE TITLE
Temple-only counties go nomadic

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#103]
Master branch

Adventurer granted(?) county just with one temple to nomadic harpy.
<details>
<summary>Click to expand</summary>

![ck2_9](https://user-images.githubusercontent.com/46576860/52131764-a8a1ee80-264e-11e9-8db0-7b22cf669b75.png)
![ck2_10](https://user-images.githubusercontent.com/46576860/52131766-a8a1ee80-264e-11e9-838d-e8ca3b2ab2a5.png)
[nomad.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/2822192/nomad.zip)

</details>

**Comment by zumbak04** [comment]
Fixed?
