### ISSUE TITLE
Runeblades localization

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1036]
**Mod Version**
0804faa0

**Are you using any submods/mods? If so, which?**
Guardians of Azeroth

**Please explain your issue in as much detail as possible:**
Tooltip in this event is not really helpfull, since all runeblades have the same localization

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/71395645-d6f23900-2627-11ea-818e-586062cdb9d8.png)

</details>

**Comment by geffe1** [comment]
Could we make it so certain races gets different weapons ? A DK orc, getting a runeaxe instead ?

**Comment by sejtalk** [comment]
> Could we make it so certain races gets different weapons ? A DK orc, getting a runeaxe instead ?

no

**Comment by MemeWizard** [comment]
> Could we make it so certain races gets different weapons ? A DK orc, getting a runeaxe instead ?

That is really easy to to implement, but idk if someone will actually do it.

**Comment by geffe1** [comment]
> > Could we make it so certain races gets different weapons ? A DK orc, getting a runeaxe instead ?
> 
> That is really easy to to implement, but idk if someone will actually do it.

I think that there is nothing that says in lore that an orc would get a runeaxe when becoming a DK, but I think it would be cooler with certain races getting certain weapons depending on their race or culture. 

Or st least having an option to get a runeaxe
