### ISSUE TITLE
Pneumonic trait description

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#104]
Master branch

Pneumonic trait description talks about medieval times
<details>
<summary>Click to expand</summary>

![ck2_16](https://user-images.githubusercontent.com/46576860/52133513-88742e80-2652-11e9-8a1c-51263c38e566.png)

</details>

**Comment by DukeJeans** [comment]
Fixed
