### ISSUE TITLE
No religion sympathy

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#105]
Master branch

"We are more alike than we are different" option do nothing.

<details>
<summary>Click to expand</summary>

![ck2_15](https://user-images.githubusercontent.com/46576860/52135463-eb67c480-2656-11e9-8173-4a7e66983235.png)

</details>

**Comment by MemeWizard** [comment]
Event: WoL.7042

**Comment by DukeJeans** [comment]
Event disabled until creation of Warcraft sympathy traits. Closed.
