### ISSUE TITLE
Harpy Retinues

### ISSUE THREAD

**Issue by Lordmitch** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1054]
**Your mod version is:1.6.0

**What expansions do you have installed? All

**Are you using any submods/mods? If so, which? none

**Please explain your issue in as much detail as possible:**

**Steps to reproduce the issue:**

**Upload an attachment below: .zip of your save, or screenshots:**
![image](https://user-images.githubusercontent.com/47829580/71686343-d88fcf80-2d92-11ea-8a2b-a8a2d35b317f.png)

**Comment by zumbak04** [comment]
Fixed in 38f6fd02532ddb367f54aeb5e74f57bd57d04a31.
