### ISSUE TITLE
Dragon marriage

### ISSUE THREAD

**Issue by Lordmitch** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1056]
**Your mod version is:1.6.0

**What expansions do you have installed? All

**Are you using any submods/mods? If so, which? none

**Please explain your issue in as much detail as possible:**
 Dragons that are married at the start, divorce at the start of the game.

**Steps to reproduce the issue:**

**Upload an attachment below: .zip of your save, or screenshots:**
![image](https://user-images.githubusercontent.com/47829580/71694255-80fb5f00-2da6-11ea-992d-26f2cafbe5aa.png)
![image](https://user-images.githubusercontent.com/47829580/71694353-d5064380-2da6-11ea-973a-02e61f207b28.png)

**Comment by zumbak04** [comment]
Dragon governments are theocracies and can't marry, so WAD.
