### ISSUE TITLE
wargame_timer

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1060]
**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/71768755-5fc37b80-2f2a-11ea-9ff3-8e93d98b3d3d.png)

</details>

**Comment by arithon** [comment]
What is the "bug" in localisation that you want fixed? Can't spot it...

**Comment by zumbak04** [comment]
> What is the "bug" in localisation that you want fixed? Can't spot it...

Paradox forgot to localize `wargame_timer`.

**Comment by arithon** [comment]
But, isn't that only appearing with debug/charinfo mode? Never saw the wargame_timer...

**Comment by MemeWizard** [comment]
> Paradox forgot to localize wargame_timer.

Not quite, paradox forgot to hide this effect.

**Comment by arithon** [comment]
Huh, you're right... never paid attention to that

**Comment by zumbak04** [comment]
> Not quite, paradox forgot to hide this effect.

@arithon, no, Meme is right, you shouldn't see this modifier at all.
