### ISSUE TITLE
BUG: Founding of Theramore CTD + and losing tech.

### ISSUE THREAD

**Issue by babosh-gh** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1065]
Hi! this is my first submission, I don't know if this is the correct way to do it.

While playing the first war bookmark, I'm getting CTD whenever the founding of Theramore event fires.

I've uploaded my save game, the event should fire in a months after unpause.

[Theramore CTD.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/4023368/Theramore.CTD.zip)

Mod version: 1.6.0
expansions: all
submods: music, model, static portraits, modified leafwalker
My CK2 version is 3.3.0, my checksum is XDSW

Another issue:
When playing the third war bookmark, the founding of Theramore doesn't result in a CTD, but I found that Theramore is technologically downgraded for some reason, making it really weak.
Unfortunately I have no savegame to upload for this one.

**Comment by zumbak04** [comment]
@babosh-gh 

> Hi! this is my first submission, I don't know if this is the correct way to do it.

Hello!
Not really. When you click on **_New Issue_**, you see templates. You needed **_Re-Origination Request_** AKA **_Bug Report_**. Anyway, it's fine, thanks for report.

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/71782371-ae3c4d00-2ff2-11ea-9886-963902cfc312.png)

</details>

This https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/issues/942 issue is already reported though we needed save, so I'm linking your issue to the old one.

> When playing the third war bookmark, the founding of Theramore doesn't result in a CTD, but I found that Theramore is technologically downgraded for some reason, making it really weak.

Ye, we know, reported here https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/issues/962. Linking it as well.
