### ISSUE TITLE
Ymiron Laws

### ISSUE THREAD

**Issue by Lordmitch** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1068]
**Your mod version is:**
Master

**What expansions do you have installed?**
All
**Are you using any submods/mods? If so, which?**
none
**Please explain your issue in as much detail as possible:**
In the laws it changed to void magic and full status for woman 
**Steps to reproduce the issue:**
Awaken Ymiron then wait a few months then check the laws, this may take some time happen.
**Upload an attachment below: .zip of your save, or screenshots:**
![image](https://user-images.githubusercontent.com/47829580/71923744-9cd77a00-3185-11ea-938e-b3daa5e40874.png)
![image](https://user-images.githubusercontent.com/47829580/71924049-20916680-3186-11ea-927f-86b1a6a4b7a9.png)

**Comment by zumbak04** [comment]
Fixed in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/commit/df9e97f049e0049b168b954d2f00dfe1af547263.
