### ISSUE TITLE
Culture and religion switch

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1069]
Block `ask_wards_liege_to_allow_culture_religion_swap` and `change_wards_focus_to_heritage` decisions if you can't change ward culture.
Block `ask_wards_liege_to_allow_faith_focus` and `change_wards_focus_to_faith` if you can't change ward religion.

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/71951763-34bc7e80-31ed-11ea-980c-ddd330efc41f.png)

</details>

**Comment by zumbak04** [comment]
@MemeWizard 

> Block `ask_wards_liege_to_allow_faith_focus` and `change_wards_focus_to_faith` if you can't change ward religion.

Isn't it blocked? I'm Holy Light, the ward is Shath'gral.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/77956636-42147100-72e3-11ea-9275-6586c5bf400e.png)

</details>

**Comment by zumbak04** [comment]
> Block `ask_wards_liege_to_allow_culture_religion_swap` and `change_wards_focus_to_heritage` decisions if you can't change ward culture.

The same. I'm Sargerite Satyr, the ward is Shath'gral Nazja.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/77958523-38403d00-72e6-11ea-972a-e09e107426ec.png)

</details>

**Comment by MemeWizard** [comment]
> Isn't it blocked?

Can't confirm that it is blocked (69c8a2b0a)

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/78682904-477f4600-78f7-11ea-9e6c-4d156e11c172.png)

</details>

**Comment by zumbak04** [comment]
> Can't confirm that it is blocked ([69c8a2b](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/commit/69c8a2b0a69becbd7e6b65394fd1ac87c3c20c55))

@MemeWizard what was religion and culture of the murloc?

**Comment by MemeWizard** [comment]
Murloc/murloc

**Comment by zumbak04** [comment]
> Murloc/murloc

IIRC, he's not able to switch culture (to Satyr), but able to switch religion (to Sargerite).
