### ISSUE TITLE
[SUGGESTION] | Make Trolls Feminists

### ISSUE THREAD

**Issue by KingWenceslas** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#107]
**DO NOT REMOVE PRE-EXISTING LINES**
----------------------------------------------------------------------------------------------------------
### **One line summary of your suggestion:**
Change the Status of Women in Troll nations to Full.

**Describe your suggestion in full detail below:**
There appears to be no sexism in troll cultures in Warcraft lore, apart from the blood trolls. 'Womons' can be high priestesses, prophets, warriors, be on high councils, etc. There is no discrimination of women in these troll nations and as such, the Status of Women in any troll nation (once again, not counting the Blood Trolls) full, or at least notable.

**Comment by DukeJeans** [comment]
Will likely come update to Troll Government types

**Comment by zumbak04** [comment]
Implemented!
