### ISSUE TITLE
rival_skull desc

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1070]
**Mod Version**
b34d09e2

**Please explain your issue in as much detail as possible:**
 This may be not a human skull

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/71952109-8e717880-31ee-11ea-9f8d-44c1fc8a59ee.png)
![image](https://user-images.githubusercontent.com/46576860/71952117-94fff000-31ee-11ea-8431-9f549059afcc.png)

</details>

**Comment by zumbak04** [comment]
Fixed in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/commit/eabf9d50337da47153aa63b75278fc68d58844d3.
