### ISSUE TITLE
Missing Nickname Localisation

### ISSUE THREAD

**Issue by Daybreak-Mayor-Officer** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1077]
**Mod Version**
1.6
**Are you using any submods/mods? If so, which?**
Nothing besides included in main archive mods
**Please explain your issue in as much detail as possible:**
Nickname is cursed
**Upload screenshots of the problem localization:**
![Безымянный](https://user-images.githubusercontent.com/59335678/72277798-a52b2b80-3643-11ea-9a9a-1d58df7386d0.png)

**Comment by arithon** [comment]
that's no mod-issue, this nickname is given in the vanilla files. ReapersDue.csv in \steamapps\common\Crusader Kings II\localisation\ to be precise

**Comment by MemeWizard** [comment]
@arithon, looks like Russian localization issue to me.

**Comment by zumbak04** [comment]
> @arithon, looks like Russian localization issue to me.

@Daybreak-Mayor-Officer we need info.

**Comment by Daybreak-Mayor-Officer** [comment]
> > @arithon, looks like Russian localization issue to me.
> 
> @Daybreak-Mayor-Officer we need info.

Yes, I think it's a Russian loc problem, 'cause all other nicknames are working properly

**Comment by zumbak04** [comment]
Anyway, thanks for report! If you notice something else, you know what to do.
Closing the issue.
