### ISSUE TITLE
[SUGGESTION] | Expand Too Old to Give Birth Limit

### ISSUE THREAD

**Issue by KingWenceslas** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#108]
**DO NOT REMOVE PRE-EXISTING LINES**
----------------------------------------------------------------------------------------------------------
### **One line summary of your suggestion:**
Remove the "too old to give birth" negative modifier when marrying as a race that can still have children past the human ages.

**Describe your suggestion in full detail below:**
When I play as a female troll ruler that is 60+ years old, I can still have children. However, when I try to marry someone, he doesn't want to because I am too old to have children. If you can, please remove this.

**Comment by zumbak04** [comment]
Implemented in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/commit/4b5139d54460906764937c0d13c4702ac47b15cf
