### ISSUE TITLE
fort buildings has no loc

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1080]
**Mod Version**
56f4e2d9

**Are you using any submods/mods? If so, which?**
Guardians of Azeroth

**Please explain your issue in as much detail as possible:**
Looks like you moved something that you should't in #1062

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/72346950-073d6c80-36e8-11ea-995b-5b42fe16c54a.png)

</details>

**Comment by zumbak04** [comment]
Fixed in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/commit/ff90eefe814900d262accd21eb14e40fd3a319b5.
