### ISSUE TITLE
Twin headed ogre spelling

### ISSUE THREAD

**Issue by Lordmitch** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1085]
**Your mod version is:**
master

**What expansions do you have installed?**
all
**Are you using any submods/mods? If so, which?**
none
**Please explain your issue in as much detail as possible:**
Access missing an S
**Steps to reproduce the issue:**

**Upload an attachment below: .zip of your save, or screenshots:**
![image](https://user-images.githubusercontent.com/47829580/72655455-9c608f80-398c-11ea-83e1-ee77e94d3cbc.png)

**Comment by arithon** [comment]
fixed in next localisation crusade
