### ISSUE TITLE
Demon Hunter Class

### ISSUE THREAD

**Issue by babosh-gh** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1095]
**Describe your suggestion in full detail below:**

Hi!

Are there any plans for Demon hunters?

If you happen to implement it, consider giving him metamorphosis ability, and two specializations (similarly to druid forms)

**Comment by arithon** [comment]
You know that Metamorphosis was only after Illidan absorbed the skull of Gul'dan, right?

**Comment by sejtalk** [comment]
Some guy was working on it but he went missing.

**Comment by babosh-gh** [comment]
@arithon Yes. but why do you mention it? in the game, the skill could be tied to class level (like idk from lvl 7 you can use metamorphosis but not before)

**Comment by arithon** [comment]
@babosh-gh because levels can be gained easily. I'd rather link it to a powerful fel artifact, like ogres need powerful artifact to gain second head.

**Comment by arithon** [comment]
I was just thinking, maybe give metamorphosis at level 10, and possibility to absorb fel artifact raises you to level 10 as well? Destroying the fel artifact in the process...

**Comment by zumbak04** [comment]
> I was just thinking, maybe give metamorphosis at level 10, and possibility to absorb fel artifact raises you to level 10 as well? Destroying the fel artifact in the process...

Metamorphosis is a simple thing, a part of the training.
https://wow.gamepedia.com/Demon_hunter#Background

> Demon hunters have a constant craving for fel power and demonic flesh,[7] and live in constant torment from the sacrifices they've made.[18] Some succumb to the overbearing power of fel energy and lose all control of themselves. Their blood begins to burn and they unwillingly take on their demon form before lashing out at any nearby living beings.[19] Assuming Metamorphosis form is a very dangerous feat to undertake: unleashing the demon within is risking that the demonic power will take over. Should this happen, all semblance of the elf that was will be lost and only a demonic servant of the Burning Legion will remain.

**Comment by zumbak04** [comment]
Demons hunters were already suggested, so I'm uniting it with the first suggestion https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/issues/1095.

**Comment by arithon** [comment]
But all these Demon Hunters only existed after Illidan's transformation. Maybe he can teach them to transform, but without him as mentor, they'd probably need powerful artifacts for that.
> In horror at the sight, they tear their own eyes out, and usually puts them into a coma.[12] The fel power infusing their bodies after ingesting the demon's heart and blood causes the demon hunter to mutate, gaining demonic features such as scales, horns, or claws.[13] As with all chaos-touched creatures, the forms that these traits will take can be quite unpredictable.[14]
After the demon hunter awakens and their spectral sight begins to take effect, they are given tattoos which keep their inner demon from overwhelming them, but it is still always there, talking to them and trying to get them to turn to the Legion.[15]

And if you want to keep it close to the law, each DH should get blind and fall into incapable state for a while, before being a true DH. Oh, and everyone who wants to become a DH would have to personally kill a demon, so probably either in personal combat/duel or by imprisoning him before.

**Comment by zumbak04** [comment]
> But all these Demon Hunters only existed after Illidan's transformation. Maybe he can teach them to transform, but without him as mentor, they'd probably need powerful artifacts for that.

Illidan was the first and only demon hunter for a long time. So, without Illidan there shalln't be demon hunters at all... or some other character shall "invent" it like Illidan did.

> And if you want to keep it close to the law, each DH should get blind and fall into incapable state for a while, before being a true DH. Oh, and everyone who wants to become a DH would have to personally kill a demon, so probably either in personal combat/duel or by imprisoning him before.

Ye, kinda like that.
