### ISSUE TITLE
"Cessation of Violence Act" mentions wrong races

### ISSUE THREAD

**Issue by AltertronSteam** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#110]
**Mod Version**
1.2
**What expansions do you have installed?**
All of them
**Please explain your issue in as much detail as possible:**
The "Cessation of Violence Act" talks about hurting other human beings even though I am playing as Durotan of Frostwolf, an orc.

**Steps to reproduce the issue:**
1) Be a Lunatic
2)Be something other than human
3) When getting the event for 4 lunatic acts choose the one stated above.

**Upload an attachment below: .zip of your save, or screenshots:**
![20190202225626_1](https://user-images.githubusercontent.com/34240986/52169784-4c1dfc80-273e-11e9-99f0-38cedca6bb5e.jpg)

**Comment by zumbak04** [comment]
Fixed!
