### ISSUE TITLE
[SUGGESTION] | Add Forsaken Culture Shift

### ISSUE THREAD

**Issue by EdwardEdisan** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1103]
**Describe your suggestion in full detail below:**

The Forsaken in the World of Warcraft are truly unique culture. In the game it looks very strange that when playing for them the player remains the same retune and cultural buildings, which, for example, were in Lordaeron (human roster). It would be nice to add that, under certain conditions, a cultural conversion takes place. For example, it might look like this:

The ruler must have the religion of Forsaken_cult
Ruler must have trait "undead" (or equivalent)

Place of conversion:
e_Lorderon
e_Arator

Additional conversion conditions in the province itself:
Culture is a human group (to protect from the conversion of orcs or something else into "ordinary forsaken")
Religion - Forsaken_cult
Modifier - Land of the Dead

The ruler must have the religion of Forsaken_cult
Ruler must have trait "dead" (or equivalent)
The ruler must have a culture:
human group
or high elf
or blood elf

An important reason why this conversion is important: soon the developers will release a bookmark about the Frozen Throne, and Sylvanna will begin to occupy an important place in the game. In the event that there is no such conversion, then each time we will observe how Sylvanas throughout the Lordaeron will consistently place the elves, and, accordingly, convert everyone into an elven culture.

**Comment by zumbak04** [comment]
The culture itself is added in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/pulls.
The culture conversion to the Forsaken culture via liberation from the Lich King is WIP.

**Comment by zumbak04** [comment]
Everything added in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/pull/1125.
