### ISSUE TITLE
Request Army from Yogg-Saron

### ISSUE THREAD

**Issue by Aszrael** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1106]
**Your mod version is:**
1.6.0
**What expansions do you have installed?**
All
**Are you using any submods/mods? If so, which?**
Yes, some submods I made myself. They don't, however, have any effect on this bug.
**Please explain your issue in as much detail as possible:**
Under the request_army_offmap decision, in the allow block, the trigger for Yogg-Saron is missing an underscore between yogg and saron. It's written as yoggsaron_offmap_decisions_enabled_trigger = yes when it should be yogg_saron_offmap_decisions_enabled_trigger = yes. As a result, this prevents the decision from being able to be taken despite meeting the requirements. The same issues exists for the request powers decision in the same file.
**Steps to reproduce the issue:**
Take a look in the wc_offmap_decisions.txt file
**Upload an attachment below: .zip of your save, or screenshots:**

**Comment by zumbak04** [comment]
Hello! Thanks for report.
Fixed in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/commit/bf00889f270b2156efe9fe338bbe3046f38913f5.
