### ISSUE TITLE
Blackhand destroys the "High Tribe of Blackrock"

### ISSUE THREAD

**Issue by AltertronSteam** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#111]
**Mod Version**
1.2
**What expansions do you have installed?**
All.
**Please explain your issue in as much detail as possible:**
In January 583 the ai Blackhand always destroys the titular kingdom title "High Tribe of Blackrock" he possesses at the start of the game.

**Upload an attachment below: .zip of your save, or screenshots:**
![20190203094522_1](https://user-images.githubusercontent.com/34240986/52174836-481fc800-279a-11e9-9976-d402256886bf.jpg)

**Comment by zumbak04** [comment]
It's how AI works, it doesn't like to hold any kingdom title having an empire one.

**Comment by ManuSwaG** [comment]
It's because it's titular, it doesn't hold any De Jure land. 
There is no reason for the AI to hold the title with a Empire Title.

**Comment by AltertronSteam** [comment]
It would instead prefer to lose prestige by destroying the title? Very interesting.

**Comment by zumbak04** [comment]
Fixed in #717.
