### ISSUE TITLE
[BUG] | Genn become Heir to Gilneas and is son is the ruler

### ISSUE THREAD

**Issue by Lordsamuel80** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1114]
**Your mod version is:**
Crusader Kings 2 Frozen throne Github version
**What expansions do you have installed?**
every Expansion installed
**Are you using any submods/mods? If so, which?**
i use mostly music mods like Epic Medieval Music I. Epic Medieval Music II, Knight of Honor Soundtrack. i use the Github Warcraft Guardian of Azeroth version for now and as submod, i use the GK Static Portraits, the Leafwalker submod and Warcraft GOA models
**Please explain your issue in as much detail as possible:**
the thing is that i checked Gilneas like that and i did see that Genn was not the leader but is son but the weird thing is that genn was the ruler heir i don't know how that happened so i can't help
**Steps to reproduce the issue:**
i don't know how that happened maybe my save was bugged i don't know so i can't help 
**Upload an attachment below: .zip of your save, or screenshots:**
![th fuck](https://user-images.githubusercontent.com/60221147/72985595-49d00a80-3db4-11ea-8bdf-eb0a964c1d08.PNG)

**Comment by arithon** [comment]
could he have been replaced due to a rebellion he lost?

**Comment by Lordsamuel80** [comment]
don't know i didn't take care because i was doing a war

**Comment by arithon** [comment]
Seems like it could simply have been a thing that happened in your game... Would be different, if it was like that at the start.

**Comment by zumbak04** [comment]
Hello!
Genn lost to revolt. In my game the same happend.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/73013418-b9d0a600-3e31-11ea-87b0-a9b315f837a1.png)

</details>

Aight, closing. Anyway, thanks for report.
