### ISSUE TITLE
Series of bugs with the "Frostwolf" clan.

### ISSUE THREAD

**Issue by AltertronSteam** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#112]
### **One line summary of your issue:**
interfering with Durotan as Blackhand causes several bugs to occur.
(I think you can do pretty much the same with Cho'Gall and his Twilight Hammer.)
**Mod Version**
1.2
**What expansions do you have installed?**
All
**Please explain your issue in as much detail as possible:**

When you play as the warchief Blackhand you can do several things in order to cause remarkable issues in the Frostwolf quest chain. I have managed to find at least five of them:
1) Stopping it completely
2) Allowing Durotan go without the "Tribe of Frostwolf"" titular title.
3) Keeping Durotan in your prison while he has already escaped
4) Making Durotan stay in the Horde even though the "Frostwolf Exodus" has already fired.
5) Having the opportunity to do the event chain yourself as Blackhand.

**Steps to reproduce the issue:**
1) Imprison Durotan and execute him or revoke his title right at the beginning of the campaign.
2) Revoke the "Chiefdom of Dead Ravine" from Durotan either when he doesn't look for new allies or when the respective event for Blackhand has already fired so he becomes a courtier who then flees from the Horde without his duchy title.
3) That's simple. Just imprison him and let him complete the event chain. He will stay in your prison but as an independent ruler.
4) Durotan shall not escape! Make him revolt and wait until he finishes the quest chain. Afterwards win the revolt war against him. He will remain your vassal.
5) For this one, you need to revoke the "Frostwolf tribe" duchy title from Durotan. This allows you to complete the event chain and gain some free land  without losing anything. Should Durotan choose the 'look for allies" option in his original event, you will also gain all bonuses associated with Blackhand sabotaging Durotan's efforts. (Note: This works only if Durotan chooses the "Look for allies" option in the original event, otherwise he will escape without the duchy title.)

**Upload an attachment below: .zip of your save, or screenshots:**
1)
![20190203102722_1](https://user-images.githubusercontent.com/34240986/52175235-12caa880-27a1-11e9-9009-be5711334808.jpg)
2)
![20190203103504_1](https://user-images.githubusercontent.com/34240986/52175237-19f1b680-27a1-11e9-9c59-b985ef5fd6e7.jpg)
3)
![20190203103619_1](https://user-images.githubusercontent.com/34240986/52175261-3d1c6600-27a1-11e9-8605-681105e3b6f6.jpg)
4)
![20190203104129_1](https://user-images.githubusercontent.com/34240986/52175243-270ea580-27a1-11e9-9a0a-2894ab489d3e.jpg)
![20190203104147_1](https://user-images.githubusercontent.com/34240986/52175244-270ea580-27a1-11e9-9cbd-a0d46ee178e3.jpg)
5)
![20190203104623_1](https://user-images.githubusercontent.com/34240986/52175245-270ea580-27a1-11e9-9be4-180248287c13.jpg)
![20190203104636_1](https://user-images.githubusercontent.com/34240986/52175246-27a73c00-27a1-11e9-86bc-d5c325e2538e.jpg)
![20190203104646_1](https://user-images.githubusercontent.com/34240986/52175248-27a73c00-27a1-11e9-83bf-6ffa18a0a91c.jpg)
![20190203104705_1](https://user-images.githubusercontent.com/34240986/52175249-283fd280-27a1-11e9-8dde-99c302dd51e8.jpg)

**Comment by zumbak04** [comment]
Reworked the event chain. This should fix all five issues mentioned here.
