### ISSUE TITLE
[BUG] | BASE-UNIT-OVERHAUL MERCENARIES HOLY ORDER COMPOSITION

### ISSUE THREAD

**Issue by RiccoPT** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#113]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
### **One line summary of your issue:**
With the new units some mercenaries and holy orders are without or lacking some troops

**Mod Version**
github base-unit_overhaul 

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
With the new units some mercenaries and holy orders are without or lacking some troops

**Steps to reproduce the issue:**
Mercenary tabs for example hiring hemets hunters 

**Upload an attachment below: .zip of your save, or screenshots:**
No need

**Comment by zumbak04** [comment]
Fixed!
