### ISSUE TITLE
Endgame Screen Localization

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1133]
**Mod Version**
Any
**Are you using any submods/mods? If so, which?**
Guardians of Azeroth
**Please explain your issue in as much detail as possible:**
The Renaissance sweeps across Europe
**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/73643160-12027600-4684-11ea-9008-2d2dc4457123.png)

</details>

**Comment by arithon** [comment]
Isn't @geffe1 working on that? Plus, it's not a "localisation" bug I think...

**Comment by zumbak04** [comment]
> Isn't @geffe1 working on that? Plus, it's not a "localisation" bug I think...

Nope, he's working on the dynasty ladder on endgame screen.
It's fixed by editing vanilla loc.

**Comment by arithon** [comment]
@zumbak04 what do you mean? this is the endgame screen. and he's making texts for the dynasties, too, so this text would not appear anymore

**Comment by zumbak04** [comment]
> @zumbak04 what do you mean? this is the endgame screen. and he's making texts for the dynasties, too, so this text would not appear anymore

Nope, it's not dynasty text. If you haven't reached any dynasty, you see this text.
