### ISSUE TITLE
7785 Event for Lich King

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1141]
**Your mod version is:**
https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/pull/1007/commits/a595bde7c51926877d8925962553068339d3fe12

**What expansions do you have installed?**
All

**Are you using any submods/mods? If so, which?**
None

**Please explain your issue in as much detail as possible:**
`7785` event can fire for the Lich King and other filth.

**Steps to reproduce the issue:**
That's random murder attempt event.

**Upload an attachment below: .zip of your save, or screenshots:**
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/73928972-0e215e80-48e5-11ea-86e5-1c10e9ff1af6.png)
![image](https://user-images.githubusercontent.com/46576860/73928988-14afd600-48e5-11ea-808f-c9052ddf4a4c.png)

</details>

**Comment by MemeWizard** [comment]
Also, demons can die from poisoned wine

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/74060435-0653de00-49fb-11ea-9291-27ef62c3389d.png)

</details>
