### ISSUE TITLE
Relationship Сapitalization in WCDAC.150

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1142]
**Mod Version**
ebd5608b

**Are you using any submods/mods? If so, which?**
GoA

**Please explain your issue in as much detail as possible:**
1.) Are you sure relationship should be capped in this event?
2.) I don't have "non-existing priority" for this type of issues

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/73962902-5611a700-4920-11ea-982b-a097af3c4e81.png)

</details>

**Comment by arithon** [comment]
For some reason, [GetFromRelation] is capitalised in general. Should we remove capital in general?

**Comment by zumbak04** [comment]
> For some reason, [GetFromRelation] is capitalised in general. Should we remove capital in general?

I think... yes? Usually, a pronoun that can be capitalized goes before it like Your brother/mother/etc.

**Comment by arithon** [comment]
Just don't know where 😅

**Comment by zumbak04** [comment]
> Just don't know where 😅

@arithon 
I found some of them. The localization keys start with `REL_`.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/80476401-65baed80-895b-11ea-86fe-7f85135af087.png)

</details>
