### ISSUE TITLE
Blood of Alexander the Great bloodline can be obtained

### ISSUE THREAD

**Issue by babosh-gh** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1145]
![Névtelen](https://user-images.githubusercontent.com/59530343/73966527-789ec280-4916-11ea-8674-b7dfdbd9985c.png)

**Your mod version is:**
latest
**What expansions do you have installed?**
all
**Are you using any submods/mods? If so, which?**
all
**Please explain your issue in as much detail as possible:**
somehow a character in my run managed to get alexander the great's bloodline
**Steps to reproduce the issue:**
?
**Upload an attachment below: .zip of your save, or screenshots:**

**Comment by MemeWizard** [comment]
> latest

What exactly - 1.6.0 or master branch?

**Comment by MemeWizard** [comment]
If you mean 1.6.0, it was fixed in #987, after in was reported in #898

**Comment by babosh-gh** [comment]
But I'm using 1.6
And i havent tinkered with bloodlines in any way shape or form

**Comment by MemeWizard** [comment]
> But I'm using 1.6

Sorry, I meant if you play on 1.6, it was already fixed on master branch

**Comment by MemeWizard** [comment]
Anyway, thanks for reporting ❤️
