### ISSUE TITLE
Jaina static portrait

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1146]
**Your mod version is:**
ebd5608b

**What expansions do you have installed?**
All

**Are you using any submods/mods? If so, which?**
No

**Please explain your issue in as much detail as possible:**
Jaina static portrait changes to generic if you make her undead
Hovewer, turning her into demon don't change it

**Steps to reproduce the issue:**
Turn Jaina into demon/undead with static portraits enabled

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/73966386-f4a10680-4926-11ea-820d-012369a85cdf.png)
![image](https://user-images.githubusercontent.com/46576860/73966393-f79bf700-4926-11ea-998a-c5a9ade326bf.png)

</details>

**Comment by sejtalk** [comment]
closing it cause it was fixed some time aga
