### ISSUE TITLE
[SUGGESTION] | Add Queen Madelynne I

### ISSUE THREAD

**Issue by Bacus96** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#115]
**DO NOT REMOVE PRE-EXISTING LINES**
----------------------------------------------------------------------------------------------------------
**Describe your suggestion in full detail below:**

Add Queen Madelynne I. I was dissapointed to learn she wasn't in the base mod, seeing how famous she is.

**Comment by zumbak04** [comment]
HELL NO!

**Comment by zumbak04** [comment]
Forgot to close this suggestion. HELL YES!
