### ISSUE TITLE
"Burn Evil Being" Decision

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1161]
**Describe your suggestion in full detail below:**

I assume it's impossible to burn characters that you accused of apostasy, because you can just imprison them?
How about move that requirement about opinion modifier from allow block to potential?

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/74191533-d871d200-4c64-11ea-8515-32475b5554c2.png)
![image](https://user-images.githubusercontent.com/46576860/74191634-08b97080-4c65-11ea-9280-5c30ab240b14.png)

</details>

**Comment by zumbak04** [comment]
> How about move that requirement about opinion modifier from allow block to potential?

I guess it will raise even more questions.

**Comment by MemeWizard** [comment]
There will be the same amount of questions, moreover, the question will be the same - "why I can't burn evil character"?

**Comment by MemeWizard** [comment]
As another variant, we can remove this requirement.

**Comment by zumbak04** [comment]
> As another variant, we can remove this requirement.

Not remove, but change the condition. The decisions give Apostasy opinion of rulers.
