### ISSUE TITLE
Gamerule to disable faction unification

### ISSUE THREAD

**Issue by Varus211** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1162]
**Describe your suggestion in full detail below:**
Hey Devs, I love the mod and (Mostly) everything about it.
Something that really annoys me is that I barely play the later start dates because of the forced unification of the Alliance, which turns about 50-90% (depending on the run.) of the Eastern Kingdoms into a dark blue blob. 
So something I hope can be added is a gamerule to disable faction unification, if possible.
Thanks for reading :)

**Comment by zumbak04** [comment]
Added in 5e0e620369dd7799e3883c07c585ce0f766c9bb2.

**Comment by MemeWizard** [comment]
> So something I hope can be added is a gamerule to disable faction unification, if possible.

> It's added in 5e0e620.

@zumbak04, but It isn't?
There is no gamerule about faction unification, only gamerule about faction creation and size.

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/74412243-07976780-4e4e-11ea-8346-d8d20aaaa6af.png)

</details>

**Comment by Atridij** [comment]
I think you started in ROC start date when the Alliance was already established?

**Comment by zumbak04** [comment]
Oh, yes, @Varus211, my bad.
