### ISSUE TITLE
[LOCALIZATION] | A wild line break appears!

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#117]
**Mod Version**
Master branch

**Please explain your issue in as much detail as possible:**
Many mod story events (i think i don't attach them all) have line break in the middle of text.

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![ck2_18](https://user-images.githubusercontent.com/46576860/52222514-bbb5f800-28b4-11e9-9f48-6c0fde5f1f68.png)
![ck2_23](https://user-images.githubusercontent.com/46576860/52222519-bfe21580-28b4-11e9-98e1-b31a91c393a8.png)
![ck2_24](https://user-images.githubusercontent.com/46576860/52222521-bfe21580-28b4-11e9-9522-4d9fd866c3ac.png)
![ck2_25](https://user-images.githubusercontent.com/46576860/52222523-c07aac00-28b4-11e9-8255-a1b28fcefe4c.png)
![ck2_26](https://user-images.githubusercontent.com/46576860/52223068-f66c6000-28b5-11e9-86da-6409a7036780.png)
![ck2_27](https://user-images.githubusercontent.com/46576860/52223069-f66c6000-28b5-11e9-8b2d-989e8a4b9904.png)

</details>

**Comment by zumbak04** [comment]
Fixed!

**Comment by MemeWizard** [comment]
<details>
<summary>Click to expand</summary>

![ck2_16](https://user-images.githubusercontent.com/46576860/53094786-2a898700-352c-11e9-8b9d-aa722c5aadc6.png)

</details>

**Comment by zumbak04** [comment]
Fixed! Reopen the issue if you find more.

**Comment by MemeWizard** [comment]
<details>
<summary>Click to expand</summary>

![ck2_20](https://user-images.githubusercontent.com/46576860/53376386-2cf64180-396f-11e9-8aa6-3122f485fe2b.png)

</details>

**Comment by MemeWizard** [comment]
<details>
<summary>Click to expand</summary>

![ck2_3](https://user-images.githubusercontent.com/46576860/53382408-43a79300-3985-11e9-8ac7-57caf4c6f237.png)

</details>

**Comment by MemeWizard** [comment]
<details>
<summary>Click to expand</summary>

![ck2_4](https://user-images.githubusercontent.com/46576860/53385589-f8df4880-398f-11e9-998d-63e60066bb32.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
