### ISSUE TITLE
Kel'thuzad to the Frends of Arthas

### ISSUE THREAD

**Issue by karnedi** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1172]
I propose to add Kel'thuzad to the Frends of Arthas in TFT branch 

and Sylvana as a rival 

![image](https://user-images.githubusercontent.com/58479160/74583968-fafe4500-4fee-11ea-8c92-43a7c3965c81.png)

**Comment by zumbak04** [comment]
Done!
