### ISSUE TITLE
[SUGGESTION] | Limit Small Great War

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#118]
**Describe your suggestion in full detail below:**

Because of weak Lich-king mind control, many independent barons popped-up in Lordaeron.
So, i declare and won GREAT war on every BARON, which also results in addition ~800% moral authority to my character religion.
Currently, great wars have limit (you can't declare great war if you have insufficient gold/prestige/piety), but don't have cost (you don't lose any resources at war declaration.), so i propose:
Add war declaration cost and nerf moral authority boost.

<details>
<summary>Click to expand</summary>

![ck2_21](https://user-images.githubusercontent.com/46576860/52223956-e6ee1680-28b7-11e9-9c82-28a745c8c34a.png)

</details>

**Comment by zumbak04** [comment]
Imptemented! Changelog:

- Added war cost to "Scourge Subjugation", "Great War".
- You can't now declare "Scourge Subjugation", "Great War" against barons.
- Decreased moral authority from "Invasion of <NAME>" and "Great War" CBs.
