### ISSUE TITLE
AI Genocide Cooldown

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1185]
**Describe your suggestion in full detail below:**
Add genocide cooldown for AI that stops AI from genociding a lot of provinces at the same time. So there will be like 2-1 provinces with ongoing genocide anytime.
Also, would be nice to stop AI from genociding during the war.

**Comment by zumbak04** [comment]
Will be doing it together with #1225.

**Comment by sejtalk** [comment]
Make vassals genocide pls

**Comment by zumbak04** [comment]
> Make vassals genocide pls

That's a point. They do it now, but rare and random. I want to explain how to genocide and not destroy your liege realm.
