### ISSUE TITLE
[LOCALIZATION] | touch_of_elune

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#119]
**Mod Version**
Master branch

**Please explain your issue in as much detail as possible:**
Touch of Elune modifier don't have localisation

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![ck2_9](https://user-images.githubusercontent.com/46576860/52226650-9cbc6380-28be-11e9-9fb2-4934dc640665.png)

</details>

**Comment by sejtalk** [comment]
fixed
