### ISSUE TITLE
Poorly Translated Nightmare Events

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1198]
**Mod Version**
0317ee1deb744cfa454aa5f410a1fb475d84b255

**Are you using any submods/mods? If so, which?**
No

**Please explain your issue in as much detail as possible:**
`EVTDESC_WCVOD_9965` is poorly translated from Russian. Smort guys from Discord suggested replacing...
> no more power to escape

with
> You can run no longer

or
> You grow more weary with each step

Here is the original text in case someone wants to suggest changes/fixes:
> There is no more power to escape. With every breath, the ashes of the burnt forest settle in your lungs, making breathing more difficult. No... you cannot hide from Him. You fall without power into the half-rotten foliage, beside other bodies. Now... when it does not make any sense to escape, it seems to you that the stench of this place has become even stronger. There was a ringing silence, which is interrupted only by the sound of your heart and... a melodic voice in your head. You can hide from Him, but He will always be with you here... in your dreams... in your thoughts... until the moment you lie down in this forest near the other once living beings.

**Upload screenshots of the problem localization:**
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/74762412-3ae75580-5297-11ea-945e-47c25a4490e6.png)

</details>

**Comment by zumbak04** [comment]
A few more events to check/fix. Feel free to suggest changes in the comments or commit them:

<details>
<summary>EVTDESC_WCVOD_9950</summary>

In recent days you have started to go through terrible nightmares. In these dreams, you were alone in absolute darkness...\nOut of this darkness... voices whispered something to you, showed images of a strange world... You have clearly remembered these frightening landscapes: a stony relief, lined with lava flows, ashes in hot air, blooming in the air of the tower and the obelisks of the temple city are far away from you and... something gigantic was visible on the horizon... you felt His gaze upon yourself. You no longer understood where reality is, but where the dream is.

</details>

<details>
<summary>EVTDESC_WCVOD_9960</summary>

The air in the lungs was already beginning to end. Only a dim ray of light from the surface gave you the hope to swim out from under the thick of water... but deep down you knew that there was no hope... He would not let you escape. He wants you. Something tightly grabbed your leg and pulled you down into the abyss. You tried to resist, but He only squeezed your leg, breaking the bones. You screamed in agony, but no one heard your groans from under the water. He dragged you deeper and deeper until the ray of light from the surface completely disappeared. There is no light, no hope. Here, there's only Him and you.

</details>

<details>
<summary>EVTDESC_WCVOD_9970</summary>

You pressed against the icy stone column, hoping that it did not notice you. Loud tread, the creature slowly enters the spacious hall, dragging its hideous processes behind itself. And then... silence. Your body is shaking from wounds and throat cold, but you are struggling to not make a single sound. "I hear the beating of your heart" the monster says languidly. The column behind you is scattered to pieces, one of which falls on your hand and breaks the bone. The monster straightens, and then raises its gigantic foot above your head.

</details>

<details>
<summary>EVTDESC_WCVOD_9975</summary>

You hold the dagger in your hands, lifting it over the bound girl. She looks at you, tears flowing down her cheeks. For a moment you freeze in shock. What are you even doing here? A huge dark hall with a stone altar in the center. Around it were disfigured people with tumors. They sing something in an incomprehensible language, swaying from side to side. Where are you? Who are these people? You try to remember how you got here, but the last few hours have disappeared from your memory. You begin to shake, the grip weakens and the dagger starts to slip out of your hands. "Do it!" He says... Well... you cannot deny him.

</details>

<details>
<summary>EVTDESC_WCVOD_9991</summary>

Nightmares have not visited you for a long time. Dark temples, horrors from the Void, fear and panic - all this remained in your painful memories that left incurable wounds. You can never forget this. They were so detailed, so... real. Sometimes you really were on the verge of life and death, on the verge of insanity. But now everything is over. And whatever it is, whatever you see in these dreams, you hope that they have left you and will never return. However ... deep down in the soul, you still feel their eyes on yourself.

</details>

<details>
<summary>EVTDESC_WCVOD_9995</summary>

These dreams... You do not understand what is reality and what is not. There is something more powerful than you, more powerful than all mortals in this world. Locked and weakened. They want revenge... they want death. You saw them in dreams, you saw their underground dungeons. They showed you the prophecy - what to turn Azeroth into at the end of your life. And along with the prophecy of the end of the world, you saw your destiny. They want you not to resist destiny. You must fulfil the will of the Old Gods!

</details>

**Comment by LordSilvermane** [comment]
Fixed in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/pull/1261/commits/05a78e56b492b88aba8764f891ad95fd99b15172
