### ISSUE TITLE
is_landed Artifact Holder

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1204]
**Describe your suggestion in full detail below:**
Replace `is_ruler` with `is_landed` in the artifact spawns because of the artifact may spawn for unlanded mercenaries, holy orders, etc.

**Comment by arithon** [comment]
i think it's not bad if mercenaries/holy orders get items, too :)

**Comment by zumbak04** [comment]
Weeell, such artifacts are stuck. Because you can't revoke title or inherit it.
