### ISSUE TITLE
Old Gods in Quest

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1208]
**Mod Version**

**Are you using any submods/mods? If so, which?**
357273a8d7b9c5f7cee66cb272bceb9b19a3b54e

**Please explain your issue in as much detail as possible:**
It shouldn't mention Old Gods because I need to sacrifice a person who doesn't follow the Old Gods.

**Upload screenshots of the problem localization:**
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/74773067-9a9b2c00-52aa-11ea-87e2-5af6a05f0a46.png)

</details>

**Comment by MemeWizard** [comment]
If anything, it's `quest_the_devil_worshipers_sacrifice_holy_person_desc` and `quest_the_devil_worshipers_sacrifice_holy_person_tooltip`
