### ISSUE TITLE
[BUG] | Night elves die natural deaths at 60 and 70

### ISSUE THREAD

**Issue by Vandosz** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#121]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.2

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Night elves often die natural deaths at young ages, I end up having barely any family members left. That combined with the low fertility makes night elves almost impossible to play.

**Steps to reproduce the issue:**
Simply play a night elf dynasty.

**Upload an attachment below: .zip of your save, or screenshots:**
https://imgur.com/a/ucaEwZK

**Comment by Vandosz** [comment]
Yes, here it is. Note, I played with a small submod of my own. Though all it does is add a dynasty+a bit of gfx

https://drive.google.com/file/d/1J71cu0F_PWRcs4yAxgiNH2jL_5W2ha5w/view?usp=sharing 

I played for quite a long time on this save, you can see that an unusually large part of my family just died, I almost never have more than 8 family members alive at a time. It's far worse even if you dont set Reapers deseases to rare. If you don't, the game is impossible.

**Comment by zumbak04** [comment]
Fixed? There's still a chance to die if you don't have at least 7 health.
