### ISSUE TITLE
[SUGGESTION] | Give decision-spawned NPCS class traits.

### ISSUE THREAD

**Issue by CommissarPat** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#122]
Decision-spawned NPCs should have class traits. 
----------------------------------------------------------------------------------------------------------

Promoted commanders and summoned holy men should start with a level 2-5 class trait as appropriate (e.g. commanders could be warriors or hunters, while holy persons could be priests or druids depending on the religion)

**Comment by zumbak04** [comment]
Implemented!
