### ISSUE TITLE
[BUG] | Rulers can't order adult unlanded courtiers to take the vows

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#123]
**Mod Version**
Master branch
**What expansions do you have installed?**
All
**Please explain your issue in as much detail as possible:**
Rulers can't order adult unlanded courtiers to take the vows, since there is no such decision, but religion description says rulers can.
**Steps to reproduce the issue:**
Choose ruler with this religion feature and right-click on adult unlanded courtier portrait.
**Upload an attachment below: .zip of your save, or screenshots:**
<details>
<summary>Click to expand</summary>

![ck2_1](https://user-images.githubusercontent.com/46576860/52293681-84b11680-2988-11e9-9ea0-03f84d7e53b4.png)
![ck2_2](https://user-images.githubusercontent.com/46576860/52293682-84b11680-2988-11e9-9a59-daf7feee1948.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
