### ISSUE TITLE
Allow gifting lore artifacts

### ISSUE THREAD

**Issue by karnedi** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1237]
i Suggest add ability to give felomelorn to another character. In TFT branch (and in lore) felomelorn gets into the Treasury of lich king. sometimes after this Bolvar gives this sword to hero of azeroth.

**Comment by arithon** [comment]
https://wow.gamepedia.com/Felo%27melorn#History
And where did you get that idea from? Wowpedia says, it was brought to Silvermoon after Anasterian's Death and Kael reforged it. Only later (probably after the defeat of the Illidari) the weapon could end up in the Icecrown Citadel.

**Comment by karnedi** [comment]
Now you cannot give this item to another characters. If you start in TFT this artifact will be forgotten in the Treasury of lich king and if you play as lich king you cannot give felomelorne to another character. This is not Frostmourne you must be able to give this artifact to someone else.

**Comment by arithon** [comment]
How come, it ends in treasury of LK in your games? Just tried a game with Kael and he starts with the artifact in his treasury. Played a while, lost the war, went to Quel'Thalas, still got the blade.

**Comment by MemeWizard** [comment]
> How come, it ends in treasury of LK in your games?

Honestly, that don't matter at all.
The only thing that matter in this suggestion is that your character can't gift Felo'melorn (and other "not cursed" artifacts, like Atiesh) to other characters.
