### ISSUE TITLE
[SUGGESTION] | Moving to Capital after Plagueland Civil War

### ISSUE THREAD

**Issue by arithon** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1239]
Shouldn't Garithos move to Capital City once he reconquers Lordaeron?
![grafik](https://user-images.githubusercontent.com/47716948/75121481-a9138a00-5694-11ea-8d61-b70c0bcbbea6.png)

**Comment by zumbak04** [comment]
He moves. On your screenshot, he's at war and can't do it.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/75196330-2f070200-5775-11ea-8ea7-80f9a4607429.png)

</details>

**Comment by arithon** [comment]
Ok, I'll check again in peace time.
