### ISSUE TITLE
[BUG] | Vassal orcs exode with their titles

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#124]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
My vassal, Orgrim, exode with the Horde and his titles that i gave to him.

**Steps to reproduce the issue:**
Make Orgrim your vassal and wait for the Horde exodus.

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_5](https://user-images.githubusercontent.com/46576860/52305807-1a5b9e80-29a7-11e9-9f85-afc801c9a0e6.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
