### ISSUE TITLE
BUG Lover outcome in sway event is locked out

### ISSUE THREAD

**Issue by Leefizzy** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1241]
In the HF.21105 event, FROM = { can_has_sexual_relation_with_prev = yes } locks out the lover outcome for compatible races instead of locking it out for incompatible races.

**Comment by Leefizzy** [comment]
I just switched the yes to a no and got the result in the 2nd run, so the yes was the problem or I was very unlucky while it was on yes .

**Comment by zumbak04** [comment]
Wow, yes, true, I'm impressed you noticed.
