### ISSUE TITLE
[SUGGESTION] | Add Sapphiron as General for Arthas in TFT bookmark

### ISSUE THREAD

**Issue by arithon** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1242]
Since the new bookmark starts with Arthas already in Northrend, only a short amount of time before he climbs the Frozen Throne, he should already have slain and revived Sapphiron. Not sure, if he should be landed, maybe the counte of dragon's fall (c_dragons_fall) in Northrend.
As for his character, here's a suggestion:
Traits: creature_blue_wyrm, erudite, stubborn, scholarly_theoligian, proud, honest, brave, cynical, shrewd, being_undead, class_mage_7/8/9
Culture: scourge
Religion: death_god
loyal_servant modifier towards Arthas
Base stats:
Diplomacy: 7
Martial: 8
Stewardship: 6
Intrigue: 5
Learning: 5

**Comment by zumbak04** [comment]
Done though he's not undead yet.

> Traits: creature_blue_wyrm, erudite, stubborn, scholarly_theoligian, proud, honest, brave, cynical, shrewd, being_undead, class_mage_7/8/9

Dragons can't have classes so I didn't add it. Also, I replaced `scholarly_theoligian` with `skilled_tactician` since he's described as a gurdian of Northrend.
https://wow.gamepedia.com/Sapphiron
