### ISSUE TITLE
[BUG] | Arator the undead

### ISSUE THREAD

**Issue by karnedi** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1247]
**Your mod version is: TFT branch**

**What expansions do you have installed: All **

**Please explain your issue in as much detail as possible:
in TFT bookmark arator is a courtier of Sylvanas. His 15 years old and after 1 year his allways became undead and husband of Sylvanas  **

**Upload an attachment below: .zip of your save, or screenshots:
![image](https://user-images.githubusercontent.com/58479160/75453312-8edbf380-5995-11ea-9627-f73ab62bee65.png)
**

https://wow.gamepedia.com/Arator_the_Redeemer

**Comment by zumbak04** [comment]
Moved Arator to Dalaran in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/pull/401/commits/99a765fc3f7f86d33bae1bb23c0cf9bf588460d1.
