### ISSUE TITLE
[BUG] | The Invasion from Draenor can happen after destruction of Draenor

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#125]
**Mod Version**
Master branch
**What expansions do you have installed?**
All
**Please explain your issue in as much detail as possible:**
The Invasion from Draenor fire after creation of the Horde, so if you don't create the Horde in time, the Invasion from Draenor can happen after destruction of Draenor.

**Steps to reproduce the issue:**
Don't click on "Create the Horde" decision until Dreanor destruction.

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_1](https://user-images.githubusercontent.com/46576860/52349154-f8a9f800-2a36-11e9-9932-e4320f4fcca2.png)
![ck2_2](https://user-images.githubusercontent.com/46576860/52349156-f9428e80-2a36-11e9-8060-322e6191de52.png)

</details>

**Comment by MemeWizard** [comment]
Ooops, accidentally send it

**Comment by zumbak04** [comment]
Fixed! This random event was replaced by selectable decision and you can't fire it if the Dark Portal is closed.
