### ISSUE TITLE
Mistakes in Thrall description in the second bookmark

### ISSUE THREAD

**Issue by EdwardEdisan** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1250]
**Mod Version**

**Are you using any submods/mods? If so, which?**

**Please explain your issue in as much detail as possible:**
Well, as you see in screenshot, Durotan and Drek'thar names written incorrect.
**Upload screenshots of the problem localization:**
![Thrall](https://user-images.githubusercontent.com/24798562/75608852-f61bb400-5b0b-11ea-9c30-746ecae690d2.jpg)

**Comment by arithon** [comment]
Is fixed in the newest localisation crusade. Already under review, so will probably be merged soon
