### ISSUE TITLE
Clarification in Twilight's Hammer Cult Power Descriptions

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1251]
**Describe your suggestion in full detail below:**

Moved @bantheadmin suggestion from #943

> Twilight's Hammer Cult
Rank 3 power "Write Down Whispers" doesn't appear at all on portrait choices unless publicly following old gods worship. If that's intended, it should be mentioned in the rank's description in my opinion.

**Comment by zumbak04** [comment]
Counteroffer: move `religion = old_gods_worship` to `allow`.
