### ISSUE TITLE
Poorly Translated Xal'atath Events

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1255]
**Mod Version**
05750d8269cc8cac4d7754146aba43374deee825

**Are you using any submods/mods? If so, which?**
No

**Please explain your issue in as much detail as possible:**
`EVTDESC_WCVOD_2010`, `EVTDESC_WCVOD_2015`, `EVTDESC_WCVOD_2020`, `EVTDESC_WCVOD_2025`, `EVTDESC_WCVOD_2026`, `EVTDESC_WCVOD_2035`, `EVTDESC_WCVOD_2040` are poorly translated from the Russian. I copied all the texts, they can be found in the spoiler below. Feel free to suggest changes in the comments or commit them.

There's a typo in `EVTDESC_WCVOD_2015`, Xal'atath is she, not he.

**Upload screenshots of the problem localization:**
<details>
<summary>EVTDESC_WCVOD_2010</summary>
After you took over that ritual blade, you began to hear voices. During that couple of days, while it was in your hands, you were ceaselessly having nightmares, which were cut off by the gentle whispers of Xal'atath. Have you lost your mind? Or is this blade cursed and tries to speak to you? The blade beckons you!
</details>

<details>
<summary>EVTDESC_WCVOD_2015</summary>
One night, you secretly crept into the treasury, led by the whispers of Xal'atath. In there, the black blade told you about hundreds of dark secrets of Azeroth: in the farthest corners of this world, a true madness lives, the first-born evil. In ancient times, Xal'atath shed seas of blood in the name of dark elders... but now, these times are behind. Your determination entertains Xal'atath, she is ready to guide you... for now.
</details>

<details>
<summary>EVTDESC_WCVOD_2020</summary>
Xal'atath is a creation of the Void itself. Born of darkness, it knows a lot of secrets about the shadows and its creatures. The Void is one of the fundamental forces in the universe, one of its foundations, but one should not think that it is only an instrument in your hands.. At times your conversations with Xal'atath would last for hours, but your knowledge is still incommensurable small compared to its.
</details>

<details>
<summary>EVTDESC_WCVOD_2025</summary>
In the heat of battle for [target_province.GetName] you heard the whisper of Xal'atath: "Free the power of the Void, hidden in me! Let your enemies scream in agony!"
</details>

<details>
<summary>EVTDESC_WCVOD_2026</summary>
Darkness has covered the battlefield in [GetName.target_province]. As the first surge of Void energy rushed from the blade of the Black Empire, everyone who was in the path of the darkness, died in torment. Their screams and dark mutilated corpses instilled fear in those who were fortunate to survive it.
</details>

<details>
<summary>EVTDESC_WCVOD_2035</summary>
You discovered that an ancient ritual blade disappeared from your treasury. No one saw the thieves, although it was guarded all day and all night. It seemed to disappear into thin air... but you still hear the echoes of its sinister laughter.
</details>

<details>
<summary>EVTDESC_WCVOD_2040</summary>
Suddenly, you felt that an invisible force grabbed you by the throat. The sinister laughter of Xal'atath was ringing in your head: "You've become too weak!" With every moment of breathing it's getting harder... the darkness consumes you.
</details>

**Comment by LordSilvermane** [comment]
Fixed in  https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/commit/77ad9af4879e275c54b69a2a6bf7d628e60322d9
