### ISSUE TITLE
Unable to remove evil centaurs in your provinces

### ISSUE THREAD

**Issue by EdwardEdisan** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1263]
**Your mod version is:**
Latest from master branch
**What expansions do you have installed?**

**Are you using any submods/mods? If so, which?**

**Please explain your issue in as much detail as possible:**
It's simple. Nomad agitation disable option to purge nomads, and evil religion disable function to move proselytizer to province (and you unable to build castle, because province religion and your are diffirent). And evil centaurs live in this provinces until ruler die (or to the end of the game, if your ruler immortal).
**Steps to reproduce the issue:**
1. Wait, until some centaur become death-god/sargerite/shat'gral
2. Conquer it.
**Upload an attachment below: .zip of your save, or screenshots:**

**Comment by zumbak04** [comment]
> and you unable to build castle, because province religion and your are diffirent

@EdwardEdisan can't confirm it.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/75898306-533ca000-5e53-11ea-8fc5-ec1d81dea691.png)

</details>

**Comment by EdwardEdisan** [comment]
> 
> 
> > and you unable to build castle, because province religion and your are diffirent
> 
> @EdwardEdisan can't confirm it.
> Click to expand

Hm, at least, I'm have an variant to purge it. But its not the same simple and cool system, as anothers.

**Comment by zumbak04** [comment]
@EdwardEdisan what you think is a bug here?

**Comment by EdwardEdisan** [comment]
> 
> 
> @EdwardEdisan what you think is a bug here?

I just did not think about the option to just build another hold. I started from the fact that it was impossible to transfer the tribe to the castle.

**Comment by zumbak04** [comment]
@EdwardEdisan so I'm closing the issue? If you want to change something in balance, write [Suggestion](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/issues/new/choose).

**Comment by MemeWizard** [comment]
> so I'm closing the issue?

C'mon, just turn this one into suggestion

**Comment by zumbak04** [comment]
@MemeWizard wait, what, there's no suggestion.

**Comment by MemeWizard** [comment]
Suggestion to be able to genocide centaurs? It's really a problem that often come up in discord.

**Comment by zumbak04** [comment]
> Suggestion to be able to genocide centaurs? It's really a problem that often come up in discord.

Despite nomad agitation? Then we can just remove nomad agitation from the game because you can genocide them anyway.

**Comment by zumbak04** [comment]
Have a suggestion: if there's nomad agitation, you need to build a castle or city to be able to genocide. THO, it may be too problematic for the AI.

**Comment by arithon** [comment]
> Despite nomad agitation?
BECAUSE OF nomad agitation...^^

**Comment by MemeWizard** [comment]
> Despite nomad agitation? Then we can just remove nomad agitation from the game because you can genocide them anyway.

Tbh, I don't see any logic here. How are the first and second related?
Nomad agitation is needed in order for province to go nomadic, if character can't secure their conquests. In vanilla, you can change province culture in order to remove nomad agitation, why you can't do it in the mod with the mod main culture changing action?

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/75903570-d6a9c180-5e52-11ea-8049-7022bcca7b06.png)

</details>

**Comment by arithon** [comment]
In my experience, it takes way too long in the mod for the culture change. For example the tauren tribal monarchy can't use the councilor job...

**Comment by zumbak04** [comment]
> Tbh, I don't see any logic here. How are the first and second related?

What is the point of Nomad Agitation if everyone can get rid of it via Genocide way faster then in the vanilla? I don't see it. Except for something other blocks genocide.

**Comment by arithon** [comment]
Well, problem is more that Tauren can't genocide their centaur territories, and they can't culture-change them for that reason. Only after you built a city/temple/castle their, you can start genocide the region.

**Comment by MemeWizard** [comment]
> Only after you built a city/temple/castle their, you can start genocide the region.

No, you can't, since building a city/temple/castle don't remove nomad agitation

**Comment by zumbak04** [comment]
> Btw, "If X exist, but can be easily removed with Y, then we need to delete X, since is not needed" make no sense. Moreover, it's not that easy.

"If X exists, X should continue to exist" doesn't make any sense too if you follow the logic. But I hope we're here not to discuss philosophy, right?
https://en.wikipedia.org/wiki/Is%E2%80%93ought_problem

**Comment by arithon** [comment]
> No, you can't, since building a city/temple/castle don't remove nomad agitation
Sorry, my mistake, haven't played them in a while. So Tauren can never change the regions religion/culture they conquer from centaurs.

**Comment by zumbak04** [comment]
I said my point. Nomad Agitation will lose its purpose to keep nomad lands hard to civilize.

**Comment by arithon** [comment]
But then, there's no way the horde could own all that land in TFT start, starting from the first bookmark. All those Barren provinces would still be under nomadic agitation and be of centaur religion+culture...

**Comment by zumbak04** [comment]
> But then, there's no way the horde could own all that land in TFT start, starting from the first bookmark. All those Barren provinces would still be under nomadic agitation and be of centaur religion+culture...

Well, maybe it's better to just remove Nomad Agitation? If we don't want it anyway?

**Comment by arithon** [comment]
I don't mind nomadic agitation per se, but disallowing genocide because of it... Could we make it, if province is under nomadic agitation on succession, to change culture/religion of nomads again?

**Comment by zumbak04** [comment]
I would keep it... but...

> Have a suggestion: if there's nomad agitation, you need to build a castle or city to be able to genocide. THO, it may be too problematic for the AI.

**Comment by zumbak04** [comment]
> I don't mind nomadic agitation per se, but disallowing genocide because of it... Could we make it, if province is under nomadic agitation on succession, to change culture/religion of nomads again?

We could, but it seems CPU-heavy.

**Comment by MemeWizard** [comment]
> But I hope we're here not to discuss philosophy, right?

Idk, I'm here, as always, only because I don't like your argumentation, nothing more or less.

> THO, it may be too problematic for the AI.

I can suggest to allow characters purge provinces with nomad agitation if nomad agitation is X years old.

> Well, maybe it's better to just remove Nomad Agitation? If we don't want it anyway?

Nomad agitation was implemented by Paradox Interactive to make conquering nomads more difficult, so I'm against removing it and make conquering nomads easier. Moreover, this will make life of character that can't purge centaur provinces with nomad agitation, like tribal centaurs, significantly easier.
At the same time, I don't mind if you allow to genocide them.

> "If X exists, X should continue to exist" doesn't make any sense too if you follow the logic. But I hope we're here not to discuss philosophy, right?
https://en.wikipedia.org/wiki/Is%E2%80%93ought_problem

Yeah, I can give you the same link, but quoting 

> Despite nomad agitation? Then we can just remove nomad agitation from the game because you can genocide them anyway.

Since "X **is** useless, so it **need** to be removed" it's the same.

**Comment by arithon** [comment]
> I can suggest to allow characters purge provinces with nomad agitation if nomad agitation is X years old.

I'd be ok with that. Seeing a light at the end of the tunnel, only to die a month earlier :D

**Comment by zumbak04** [comment]
> I can suggest to allow characters purge provinces with nomad agitation if nomad agitation is X years old.

It sounds like an extra step to make Nomad Agitation X years long. Plus, how to do it? As I know, you can't check "age" of modifier.

**Comment by MemeWizard** [comment]
> It sounds like an extra step to make Nomad Agitation X years long.
If we make Nomad Agitation X years long, then it will be the same for those who can genocide province and those who can't do it.

> As I know, you can't check "age" of modifier.
Hmm, looks like I confused it with something else.

**Comment by MemeWizard** [comment]
> Have a suggestion: if there's nomad agitation, you need to build a castle or city to be able to genocide. THO, it may be too problematic for the AI.

Ok, that sounds not bad, I think.
