### ISSUE TITLE
[SUGGESTION] | Reward for Defeating Scourge

### ISSUE THREAD

**Issue by TheJinxleet** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1266]
**Describe your suggestion in full detail below:**
When you defeat the scourge in great war triggers event that gives bloodline or option to put on the helm of domination and take control of scourge

**Comment by zumbak04** [comment]
> **Describe your suggestion in full detail below:**
> When you defeat the scourge in great war triggers event that gives bloodline or option to put on the helm of domination and take control of scourge

Added the bloodline in 81b3cee8404136fa85e40c3c98c0a8e68eeba2a5 the helm option may (or may not) come later.

**Comment by arithon** [comment]
Reward similar to new crusade mechanism would be nice... But probably won't work, right?

**Comment by zumbak04** [comment]
> Reward similar to new crusade mechanism would be nice... But probably won't work, right?

Do you mean money sharing?

**Comment by arithon** [comment]
money, prestige, smaller artifacts

**Comment by zumbak04** [comment]
> Money, prestige, smaller artifacts. Best case even duchies/holdings in Scourge territory

Prestige is given, others - not. Better open a new suggestion.
