### ISSUE TITLE
Allow to Abduct Undead

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1273]
**Describe your suggestion in full detail below:**
You should be able to abduct weak undead, satyrs, naga. Maybe it's a good idea to add personal combat skill condition instead.

**Comment by arithon** [comment]
I'd throw in intrigue value as well... maybe intrigue of your spymaster, if that's possible?

**Comment by MemeWizard** [comment]
> maybe intrigue of your spymaster, if that's possible?

State intrigue?

**Comment by arithon** [comment]
> State intrigue?

I was thinking of only spymaster's intrigue, since you probably order him to do it... could use state intrigue too

**Comment by MemeWizard** [comment]
> since you probably order him to do it... 

What if your character is secret cultist and your spymaster is not?

**Comment by zumbak04** [comment]
Your spymaster does nothing, the event says other cultists help you.
