### ISSUE TITLE
WCVOD events has no loc

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1276]
**Mod Version**
9ffd52593

**Are you using any submods/mods? If so, which?**
GoA

**Please explain your issue in as much detail as possible:**
No loc

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/76043027-60e34a00-5f67-11ea-8ca5-f7d15958a19d.png)
![image](https://user-images.githubusercontent.com/46576860/76043115-97b96000-5f67-11ea-8d86-b0592b231bac.png)
![image](https://user-images.githubusercontent.com/46576860/76043121-9c7e1400-5f67-11ea-820b-f8fbaf894c47.png)
![image](https://user-images.githubusercontent.com/46576860/76043129-a273f500-5f67-11ea-95ab-f7c332edb256.png)

</details>

**Comment by zumbak04** [comment]
The issue appeared in 0bb395caedca3e2440b2e3214a0489a24eea37a5.
