### ISSUE TITLE
New Artifacts for Varian

### ISSUE THREAD

**Issue by babosh-gh** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1282]
**Describe your suggestion in full detail below:**
Hello there!

Lorewise, Varian and used the belt of Anduin Lothar.
Also he obtained the legendary sword Shalamayne.

Can you add these to the game, please?

Also, There are certain artifacts in the game which have some unique mechanics (like dark crystal and canticle of twilight)
Can you make it more obvious how to use them and what they do exactly?

Like I dont even know how to turn dark crystal into ashbringer, can you please tell me? :dagger:

**Comment by arithon** [comment]
"Varian and used the belt of Anduin Lothar" what do you mean here?

**Comment by arithon** [comment]
"Also he obtained the legendary sword Shalamayne."
_After Onyxia's death, Varian returned home with the new sword at his side._
https://wow.gamepedia.com/Shalamayne
Onyxia's dungeon is not in the tft startdate or earlier, IIRC

**Comment by sejtalk** [comment]
Remant of Caer Darrow and artifacts that are Powerful Magical Artifacts allow creation of ogre magi.

**Comment by zumbak04** [comment]
Hello, thanks for the suggestion!

> Also, There are certain artifacts in the game which have some unique mechanics (like dark crystal and canticle of twilight)
> Can you make it more obvious how to use them and what they do exactly?

There's a similar suggestion, I'll mention what you said there.
https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/issues/1259

> Like I dont even know how to turn dark crystal into ashbringer, can you please tell me?

You need to **_Wait_**.

**Comment by babosh-gh** [comment]
@arithon I mean exactly what i say, he used his belt, the belt i think could be quite an interesting artifact. Nothing more, nothing less, same thing can be said about the sword.

Im not arguing with you about the lore, you are completely right, I didnt specifically say that he should have those right from the start, im just suggesting that the items should be added in the game in the first place

**Comment by babosh-gh** [comment]
@sejtalk thank you very much

**Comment by babosh-gh** [comment]
@zumbak04 Oh i see, thank you for the quick respone

**Comment by arithon** [comment]
@babosh-gh "Varian and used..."

**Comment by arithon** [comment]
> Im not arguing with you about the lore, you are completely right, I didnt specifically say that he should have those right from the start, im just suggesting that the items should be added in the game in the first place

I can create them, but until we have a startdate, where anyone holds the blade, or an event-chain for Varian to get it, it wouldn't change a thing. And about the belt, I don't know what stats it should give, since lore (as far as i know) only say that both wore it, no wow-/wc3-ingame item/artifact...

**Comment by babosh-gh** [comment]
@arithon Ah I see. Completely understandable, sorry I didn't know.


As for the belt's stats, i have a few ideas:

it could certainly give opinion bonus with humans (since Anduin Lothar is famous and well respected and honored by all humans)

It could also give revolt chance risk reduction I think (like the Menethil bloodline)

it could also give a small vassal opinion bonus aswell.

MAYBE it could give diplo and or martial stat aswell. (really unsure about this tho)

As you pointed out, the belt really isnt a "strong" item, and it doesnt have that big of an impact on the lore, but it still has enough of significance to be in the game IMO

what do you think?

**Comment by arithon** [comment]
I'd not use vassal bonus, I think, since Anduin Lothar didn't have any vassals... The rest seems nice, maybe we can make that...

**Comment by arithon** [comment]
@babosh-gh you ok with these stats? 

monthly_character_prestige = 0.4
diplomacy = 2
stewardship = 1
human_group_opinion = 3
