### ISSUE TITLE
Cultures without unique retinue

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1290]
**Describe your suggestion in full detail below:**

Add unique retinue for forsaken

**Comment by zumbak04** [comment]
And Scourge culture.

**Comment by zumbak04** [comment]
A possible retinue for the Forsaken suggested here: https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/issues/1288.
