### ISSUE TITLE
Make librams stackable 

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1298]
**Describe your suggestion in full detail below:**

Delete `stacking = no` from generic librams, because right now:

1. Your char can't have more than 1 libram of the same type in inventory
2. If your char get second copy from "write libram" decision, it gets nothing instead and just waste 500 piety

**Comment by zumbak04** [comment]
I would also limit the type of book you create, so you can't create 2 books of the same type (like it's done with Old Gods' whispers).

**Comment by sejtalk** [comment]
> I would also limit the type of book you create, so you can't create 2 books of the same type (like it's done with Old Gods' whispers).

Problem is you can only make books depending on your traits so if you make one book you may never make another one with those changes.

**Comment by MemeWizard** [comment]
> I would also limit the type of book you create, so you can't create 2 books of the same type (like it's done with Old Gods' whispers).

Tbh, I would also remove that restriction from whispers, since it can be easily avoided, because your character can gift these artifacts to courtiers who could be killed later.

**Comment by zumbak04** [comment]
> Tbh, I would also remove that restriction from whispers, since it can be easily avoided, because your character can gift these artifacts to courtiers who could be killed later.

True, cooldown or flag that forbids it is better
