### ISSUE TITLE
Have Malfurion called to war with Tyrande

### ISSUE THREAD

**Issue by ManuSwaG** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#13]
with patch 1.2 the legion declares war on cenarius. Malfurion is a tributary of Kaldorei not him. So Kaldorei can't call malfurion to war. 

Malfurion can offer to join the war himself. But it shouldn't be that way. Malfurin or Tyrande should be able to call him.

**Comment by ManuSwaG** [comment]
mm after more testing kaldorei can call them but for somehow didn't do it. I closed the bug

**Comment by ManuSwaG** [comment]
mmm no i was wrong, the issue definitely exist. Malfurion was joining a uprising not the legion war itself.

**Comment by ManuSwaG** [comment]
Maybe create a event to call the trees to war when the legion invades?

**Comment by DukeJeans** [comment]
_Why not both?_

**Comment by zumbak04** [comment]
Closing since it depends on Tyrande AI. If she calls, he joins.
