### ISSUE TITLE
[SUGGESTION] | Allow conquest of coastal countries for raiders

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#130]
**Describe your suggestion in full detail below:**

I suggest to allow raiders (cultures that can raid with ships, e.g. vrykul, pirate, murloc, etc.) take coastal countries through conquest cb, like norse pagans in vanilla can take not only border, but also coastal countries.

**Comment by zumbak04** [comment]
Implemented! Changelog:

- Pirates and vrykul can now use "Conquest of <NAME>" CB against all neighbors and coastal counties.
