### ISSUE TITLE
[BUG] | The Horde vassals destroys the dark portal

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#131]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Llane destroyed the portal after i grant him county of dark portal.

**Steps to reproduce the issue:**
Kill Gul'dan
Win the great war against Stormwind
Make any Light province capital (e.g. Stormwind), right-click on your character portrait, convert to local religion
Invite Llane Wrynn to your court
Grand the Dark Portal to Llane

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_2](https://user-images.githubusercontent.com/46576860/52515955-d204e080-2c33-11e9-9b11-7a2cd65a3e1c.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
