### ISSUE TITLE
Demon Summoning is poorly tranlsated

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1312]
**Mod Version**
6ea1ebc478ed91639ad1d4789893e804655323fa, `Localisation-Crusade-12`

**Are you using any submods/mods? If so, which?**
No

**Please explain your issue in as much detail as possible:**
These events are poorly translated. Like, in `EVTDESC_WCFEL_9970`, it should be something like:
> The mental connection alone is enough to **FEEL** the power of this strange entity.

I copied all the texts, they can be found in the spoiler below. Feel free to suggest changes in the comments or commit them.
Note: `GetDemonTypeOutcome...` are different endings of `EVTDESC_WCFEL_9973` localization.

**Upload screenshots of the problem localization:**
<details>
<summary>EVTDESC_WCFEL_9970</summary>
Recently, you have begun to hear a malevolent voice in your head. This creature from another world, as it refers to itself, asks you to speak with it and carry out a mysterious ritual on its behalf. Perhaps you should actually make a deal with this creature. The mental connection alone is enough to fill you with power from this strange entity.
</details>
<details>
<summary>EVTDESC_WCFEL_9971</summary>
You have prepared for the ritual. You throw a strange green powder into the fire, which starts to sparkle green. In the flames you see a silhouette, enveloped in an aura of Fel magic. You have a talk with a powerful creature that you are sure is from the Twisting Nether, and it wants you to let it into Azeroth. But is that a good idea?
</details>
<details>
<summary>EVTDESC_WCFEL_9972</summary>
You have prepared for the ritual. You throw a strange green powder into the fire, which starts to sparkle green. In the flames you see a silhouette, enveloped in an aura of Fel magic. You have a talk with a powerful creature that you are sure is from the Twisting Nether, and it wants you to let it into Azeroth. But is that a good idea?
</details>
<details>
<summary>EVTDESC_WCFEL_9973</summary>
You are ready for the next ritual. By sacrificing someone's life, you managed to create a tear between Azeroth and the Twisting Nether. Reality was briefly distorted, and you saw the figure of [Root.GetDemonTypeOutcome]
</details>
<details>
<summary>GetDemonTypeOutcome_deceitful_nathrezim</summary>
a two-legged creature with wings. It stood upright and leaped upon you and - a few moments later - it firmly gripped your neck. ''Now I shall take your place in this world, worm!''
</details>
<details>
<summary>GetDemonTypeOutcome_ambitious_annihilan</summary>
a huge four-footed creature, but it was not alone: a small detachment of demons came into this world. The creature straightened up and stormed towards you. A few moments later its giant hammer hung over you. "Fool, now we will walk the flaming tread on this world!"
</details>
<details>
<summary>GetDemonTypeOutcome_deceitful_observer</summary>
a giant levitating creature with one glaring eye. A few moments later, it materialized near you and its eye became wreathed in green flame. "I do not need you anymore, mortal!"
</details>
<details>
<summary>GetDemonTypeOutcome_normal_case</summary>
a large demon. It straightened up and offered you a gift in gratitude for your help before disappearing.
</details>
<details>
<summary>GetDemonTypeOutcome_good_case</summary>
a large demon. It straightened up and offered you the previously agreed upon gift as well as its loyalty in gratitude for your help.
</details>

**Comment by LordSilvermane** [comment]
fixed in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/commit/5c4edcc6fe12f10916bc2b50161293c7eae2a291
