### ISSUE TITLE
[BUG] | Can't 'Request Power' or 'Request Army' from Old God

### ISSUE THREAD

**Issue by BlackTavi** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1317]
**Your mod version is: **
1.6.0
**What expansions do you have installed?**
Jade Dragon, Monks and Mystics, The Reaper's Due, Conclave, Horse Lords, Way of Life, The Republic, Legacy of Rome
**Are you using any submods/mods? If so, which?**
Autobuild sub mod, but it didn't work even before I installed this mod. I've included two saves which seem to have this problem. One of them before I installed the extra mod. I'm also using the included troop models from GoA, music etc...
**Please explain your, issue in as much detail as possible:**
Playing as AQ, and the "request army" and "request power" are grayed out. There seems to be an extra condition added?
**Steps to reproduce the issue:**
No idea...
**Upload an attachment below: .zip of your save, or screenshots:**

![Capture](https://user-images.githubusercontent.com/28164201/76685382-81f00e80-65e9-11ea-8c23-82fb6a5461b6.PNG)

[Ahn'qiraj682_12_25(safing).zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/4332949/Ahn.qiraj682_12_25.safing.zip)

[Ahn'qiraj608_01_04(AWAKENING(.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/4332996/Ahn.qiraj608_01_04.AWAKENING.zip)

**Comment by zumbak04** [comment]
Hello! Thanks for the report.
This bug has been reported in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/issues/1106. Should be fixed in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/commit/bf00889f270b2156efe9fe338bbe3046f38913f5.
