### ISSUE TITLE
[BUG] | The Horde feudalize after succession 

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#132]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Next ruler of the Horde become feudal if both successor and predecessor are not savages.

**Steps to reproduce the issue:**
Convert your orc and his son to light or convert your orc and his son to human culture
Kill your orc

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_1](https://user-images.githubusercontent.com/46576860/52517162-f4a0f480-2c47-11e9-99bd-740df96294b9.png)
![ck2_1](https://cdn.discordapp.com/attachments/406500578231975937/543640794507116554/ck2_4.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
