### ISSUE TITLE
Pandaria sea provinces

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1328]
**Your mod version is:**
e89020262

**What expansions do you have installed?**
All major

**Are you using any submods/mods? If so, which?**
GoA

**Please explain your issue in as much detail as possible:**
They are kinda broken

**Steps to reproduce the issue:**
Try using ships in south seas

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/76743962-84d33680-6784-11ea-8097-8743fdf2063b.png)

</details>

Also this:

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/76744202-ec898180-6784-11ea-82f2-8abaf4e3a79f.png)

</details>

**Comment by zumbak04** [comment]
> Also this:

Mentioned in a separate issue: https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/issues/1330.
