### ISSUE TITLE
[BUG] | Lich-king don't have frozen throne

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#133]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Lich-king don't get frozen throne (and it's upgrade - icecrown citadel) with event and don't build it.

**Steps to reproduce the issue:**
Just watch how Lich-king don't build frozen throne.

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_2](https://user-images.githubusercontent.com/46576860/52521746-f17c2780-2c8c-11e9-95dc-fb475745ea97.png)
![ck2_5](https://user-images.githubusercontent.com/46576860/52521747-f6d97200-2c8c-11e9-9724-43beb0e98a80.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
