### ISSUE TITLE
Dynasty Ladder Texts

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1339]
**Describe your suggestion in full detail below:**
Write texts for the end game dynasty ladder.
Up to 600 characters.
There should be 15 dynasties. The 15th should be the best, the 1st should be the worst.
I suggest [House Ellerian](https://wow.gamepedia.com/Ellerian) being the worst (or near the worst) and [Arathi or Thoradin's](https://wow.gamepedia.com/Thoradin) dynasty being the best.

Example from vanilla:
<details>
<summary>Click to expand</summary>

With a score of $SCORE$ you $FAILED$ beat House Capet, descended from Robert the Strong who was a power figure during the reign of Charles the Bald. His descendants would be Kings of France in 1066. Although by 1322 the main line would die out, cadet branches still ruled in 1337 as Kings of France, Portugal, Naples, Hungary and Navarre. Cadet branches would also hold the Duchies of Brittany, Burgundy, Bourbon, Provence and Achaea. One further cadet branch would hold the dignity of Emperor as Latin Emperors of Constantinople. Truly the greatest dynasty of medieval Europe.

</details>

**Comment by zumbak04** [comment]
A new candidate for the worst dynasty ever. Had everything, lost everything.
https://wow.gamepedia.com/Agamand

**Comment by zumbak04** [comment]
Plus one more candidate, they were lowborn but reached high ranks.
https://wow.gamepedia.com/Maiev_Shadowsong

**Comment by geffe1** [comment]
With a score of $SCORE$ you $FAILED$ to beat House Ellerian, one of Stormwind's smallest noble families. This house began their humble beginnings upon the fertile lands in Westfall originally only owning small chunks of lands within it's borders. Through the marriage of Tiffin Ellerian and King Varian Wrynn, a match pre-arranged at Tiffin's birth, the house managed to secure their spot in the Stormwind House of Nobles. The most notable achievement of this family is marrying into the royal family and producing an heir to the Throne, although not of their dynasty.

**Comment by geffe1** [comment]
With a score of $SCORE$ you $FAILED$ to beat House Agamand, once a rich family that settled in the Tirisfal Glades. They formerly possessed the Agamand Mills and large swaths of lands surrounding it, even having their own family crypt as well some prestigious weapons as family heirlooms. Their downfall came by the hand of the Scourge and Devlin Agamand, who allowed the Scourge access to the Mills. Deciding to hold fast to their home, even with their youngest brother's betrayal, it proved to be in vain as most of them were later arisen to the Scourge's servitude.

**Comment by geffe1** [comment]
With a score of $SCORE$ you $FAILED$ to beat house Shadowsong, despite having no noble blood this family rose to some relevant prominence during the War of the Ancients through hard work, with Jarod Shadowsong being a Captain of the Suramar Guard and later the Commander of the Kaldorei Resistance. In the meantime his sister Maiev was a senior priestess in the Sisters of Elune, after the conflict she volunteered to become the leader of a newly-formed elite force, the Watchers. The Shadowsong family only reached their prestigious position within Kaldorei society with blood, toil, tears, and sweat.

**Comment by geffe1** [comment]
Chosen Dynasties as of yet:
Ellerian(Human)
Agaman(Human)
Trollbane(Human)
Thoradin(Human)
Shadowsong(Night elf)
Frostwolf (Orc and chosen by the community)

Candidates:
Hellscream, Blackhand (Orc)
Ramkahen(Tol'vir thingie)
Rastakhan, Jin (Troll)
Windrunner, Drathir, Sunstrider(Blood/High elves)
Thaussarian, Anvilmar, Bronzebeards(Dwarf)
Black (Dragon)
Mechagon(Gnome)
Qirajid(Qiraji)
Dragonflayer(Vrykul)
Timbermaw(Furbolg)
Revilgaz(Goblin)
Maraudine(Centaur)
Gordunni(Ogre)
Bloodhoof, Grimtotem(Tauren)

**Comment by zumbak04** [comment]
I like...
> Sunstrider
> Anvilmars
> Maraudine
> Bronzebeards
> Bloodhoof
> Dragonflayer

**Comment by zumbak04** [comment]
Also, I would add Vashj dynasty somewhere in the middle.
https://wow.gamepedia.com/Lestharia_Vashj

**Comment by zumbak04** [comment]
Somewhere in the bottom.
https://wow.gamepedia.com/Stormpike_clan

**Comment by zumbak04** [comment]
> Mechagon
Somewhere in the bottom?

**Comment by geffe1** [comment]
With a score of $SCORE$ you $FAILED$ to beat house Anvilmar, the descendants of the last High King of all dwarves, Madimus Anvilmar, who ruled the kingdom with justice and wisdom. As their society grew too large within the safe confines of the mountain, three powerful factions rose within their people: the Bronzebeard, Wildhammer and Dark Iron clan. This eventually led to the downfall of the Anvilmar dynasty, for when Modimus passed away of old age, his son would not have enough time to be officially crowned before the dwarven civil war broke out between the three clans.

**Comment by geffe1** [comment]
With a score of $SCORE$ you $FAILED$ to beat house Mechagon, this family once in the distant past made up the monarchy of the Gnomeregan gnomes. King Mechagon abandoned his people in search for a mystical land of forgotten technology with some of his followers, which they later found and settled, Mechagon Island. Under his rule in Mechagon, their people have managed to remove a large problem of their society, an aging population, through partially turning themselves into mechanical versions of themselves.

**Comment by geffe1** [comment]
With a score of $SCORE$ you$FAILED$ to beat House Stormpike. This dwarven clan's origin is not well known, though it is safe to assume that they appeared some time after the War of Three Hammers as subjects of the ruling Bronzebeard clan. It is a well respected clan, and they are known for their fine and discerning tastes and their riches. Under Vanndar Stormpike's leadership, they would lead an expedition into Alterac valley to defend it from the savage Frostwolves while also keeping an eye out for relics of their past and their profitable mining endeavours.

**Comment by geffe1** [comment]
With a score of $SCORE$ you $FAILED$ to beat House Vashj. This Highborne family is fairly well known from Lestharia's leadership of Vashj'ir, which is named in honour of the prosperity Lestharia brought her lands under the reign of Queen Azshara. The Vashj dynasty is also quite known from Lestharia's daughter, Lady Vashj, regarded as a traitor to the Kaldorei.  Lady Vashj rapidly was promoted to became one of Queen Azshara's handmaidens. After the War of the Ancients, however, her beautiful appearance was defiled by the transformation into a Naga, leaving her reputation tarnished after the Great Sundering.

**Comment by geffe1** [comment]
With a score of $SCORE$ you $FAILED$ to beat House Trollbane. This human family started as a small tribe in the Alterac Mountains under Ignaeus Trollbane, who became a general of Arathor after pleading his allegiance to King Thoradin. After the collapse of Arathor, the first Trollbane ascended to the throne of what would become Stromgarde. One of their most prominent members, Danath Trollbane, served as the second in command of the Outland expedition, and eventually as the main leader of the Alliance fortress of Honor Hold. They are known for many things, though mainly slaying trolls.

**Comment by geffe1** [comment]
With a score of $SCORE$ you $FAILED$ to beat House Lothar. This house grew to prominence under Thoradin, who ruled a small tribe within the Arathi Highlands, a master strategist who united all of humanity through conquest along with diplomacy, forming the empire of Arathor. He was also the wielder of the legendary sword Strom'kar and founder of Strom. When Arathor began to crumble, Thoradin's last descendants went south, founding the Kingdom of Stormwind. The last living descendant, Anduin Lothar held the title of Supreme Commander of the Alliance before his demise against the Orcish Horde.

**Comment by geffe1** [comment]
With a score of $SCORE$ you$FAILED$ to beat House Sunstrider, the first known member being Dath'Remar. Born into wealth and power, he was obsessed with magic, causing the Night Elves to exile him and his kin after the War of the Ancients and thus he led his people across the sea, founding Quel'thalas and the Sunwell. His descendant, Anasterian ruled for around 2,800 years, as well as during the Troll Wars. Anasterian's death caused the downward spiral of the dynasty, his son, Kael'thas taking up the mantle and attempting to salvage what was left of the Kingdom after the Scourge invasion.

**Comment by geffe1** [comment]
With a score of $SCORE$ you$FAILED$ to beat House Frostwolf. This clan formed about 800 years before the First War, but very little is known of its early history. Eleven years before the First War, Chieftain Garad led the clan, who passed his ideals of family and community upon his three sons. Durotan was chosen as the heir and upheld these traditions, standing up against wrong doings like the Draenei extermination and drinking the blood of Mannoroth. Durotan's son, Go'el formed a new Horde on Azeroth long after his father's death, with the core ideals passed down through the generations.

**Comment by geffe1** [comment]
With a score of $SCORE$ you$FAILED$ to beat House Maraudine. A centaur clan founded by Maraudos, their first Khan, the fourth alleged offspring of Zaetar, son of Cenarius and Theradras, the Crown Princess of the Stonemother Therazane. One of the five main centaur clans, the Maraudine have settled in the Valley of Spears, the entrance to the temple of Maraudon and the tomb of Zaetar. They have occupied and maintained the temple of Maraudon, the shrine of to their first ancient Khan and their procreators where only the mightiest of the tribe are chosen to guard the tomb.

**Comment by geffe1** [comment]
With a score of $SCORE$ you $FAILED$ to beat House Bronzebeard. The clan's first appearance is forgotten to history, however, it grew to prominance during Thane Madoran Bronzebeard's reign, after the death of the last High King of the dwarves. The fragile peace between the clans broke down into a civil war for Ironforge, where the Bronzebeard clan was victorious. A family known for exploring, battles, drinking and good tales, the Bronzebeard reign over Ironforge has been prosperous, managing to find new allies like humans as well as mending the broken relationship with the Wildhammer clan.

**Comment by geffe1** [comment]
With a score of $SCORE$ you $FAILED$ to beat House Dragonflayer. The Dragonflayer Clan came to prominence under King Ymiron, famed for his tactical skills that gave the Vrykul the upper hand against their ancient rivals, the jalgar, in their struggle for domination of what is known as the Howling Fjord. Total victory was at hand with the jalgar almost extinct, but a tragedy, that struck the Vrykul once before, the curse of flesh, appeared once again. The women afflicted with the curse began giving birth to small, malformed children which struck fear into all the Vrykul clans.

**Comment by geffe1** [comment]
With a score of $SCORE$ you $FAILED$ to beat House Bloodhoof. This family's first historical records begins in the Barrens, where Cairne Bloodhoof was born and raised. The Bloodhoof tribe had nearly been driven to extinction by the Centaurs, until the Orcs of Thrall's new Horde went ashore. During Cairne's rule, the Bloodhoof tribe settled Mulgore and founded an alliance with the Horde. After Cairne's death, his son, as noble and wise as his father, took the reigns of the tribe, leading it with a sense of honour unrivaled by most other dynasties on Azeroth.

**Comment by geffe1** [comment]
1. Lothar
2. Trollbane
3. Bronzebeards
4. Frostwolf
5. Sunstrider
6. Anvilmar
7. Shadowsong
8. Bloodhoof
9. Dragonflayer
10. Vashj
11. Stormpike
12. Mechagon
13. Maraudine
14. Agaman
15. Ellerian

**Comment by zumbak04** [comment]
LGTM!
