### ISSUE TITLE
[BUG] | Ner'zul don't die after his defeat

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#134]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
If you use the great war instead of stop invader CB, Ner'zul don't get killed.

**Steps to reproduce the issue:**
Declare the Great war against Scourge as the Horde.

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_3](https://user-images.githubusercontent.com/46576860/52522366-897e0f00-2c95-11e9-8f9e-95f3bfb03938.png)
![ck2_4](https://user-images.githubusercontent.com/46576860/52522368-8be06900-2c95-11e9-9a66-fdc26a453a9c.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
