### ISSUE TITLE
[SUGGESTION] | Demon Hunter

### ISSUE THREAD

**Issue by HUNWing** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1340]
**Describe your suggestion in full detail below:**

There should be a new class demon hunter. I thought there should be an event chain, when you got enought fel corrution, then there should be an event when you need more power. Then you could decide you wanna serve the legion or not (like the illidari religion option.) If not then you go search for a master (Illidan or any demon hunter who is alive.) or (a demon lord.
Illidan gives you lesser stat but also lesser opinion minus and a demon hunter trait.
The demon lord gives you a lot of stat but huge opinion minus.

If you choose Illidan then you can become dh if you were rogue/warrior/warlock/mage
If you choose the demon then you become warlock (if you were mage or priest) or you gain +1 level in your spec master warrior--->expert warrior.

If you wanna be dh, there should be an event chain, when you need to succed at trials. These trials no matter what gives you - health. (blind yourself, hard training and read some demonic book.)

Hard training---> Extremly hard. Gives you minor -helath, but + to martial, PC and intrigue
Blind yourself---> moderate- health, but gives you + learning (you can detect magic)
Read the book--->(like in dh intro quest line) this is your final test. If you have enough stat then you should succed, but this cant be 100%. There should be always a low level risk (if you have enough stat) to die.

**Comment by zumbak04** [comment]
@HUNWing, hello!
There's one opened DH suggestion, I linked your suggestions to it.
