### ISSUE TITLE
Siege Engines might be a little bit too powerful.

### ISSUE THREAD

**Issue by scannik** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1342]
**Describe your suggestion in full detail below:**
Title. Fully upgraded these siege engines have 0.41/0.01/0.01. Just for comparison Cav has 0.02/0.11/0.08. Siege engines have more value in just the ranged phase, than Cav over the entire duration of the fight. Which I guess makes sense, given that some siege engines are literal tanks. But if you approach late game and have a retinue size of over 30k+ and just stack that one siege retinue for an army of 5k Tanks they just decimate everything the Ai throws at them. With ease at that (including armies 4x the size). So maybe that needs a little bit of fine tuning.

**Comment by zumbak04** [comment]
Made them 38% weaker.

**Comment by zumbak04** [comment]
@scannik if they still feel OP, reopen the issue.
