### ISSUE TITLE
[BUG] | Missing Map Assets

### ISSUE THREAD

**Issue by dokturprofesur** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1352]
**Your mod version is:** 1.6.0.3

**What expansions do you have installed?** All Ck2 expansions are installed.

**Are you using any submods/mods? If so, which?** Models and Music submods.

**Please explain your issue in as much detail as possible:** Just downloaded mod today and installed. Map emblems/flags for assorted powers/nations are missing when models submod is active. Tried redownloading mod with no success. No other mods are active. CK2 is up to date.

**Steps to reproduce the issue:** Activate Models Submod.

**Upload an attachment below: .zip of your save, or screenshots:**

![ah](https://user-images.githubusercontent.com/62527667/77271381-c9227300-6c6b-11ea-8bc5-623c9b5b5198.png)

![ah 2](https://user-images.githubusercontent.com/62527667/77271370-c3c52880-6c6b-11ea-80ea-03ea4e6af1e8.png)

![ah 3](https://user-images.githubusercontent.com/62527667/77271360-bf007480-6c6b-11ea-85d3-1dad2df034a3.png)

**Comment by zumbak04** [comment]
@dokturprofesur [download it from Steam](https://steamcommunity.com/sharedfiles/filedetails/?id=1909508119). We fixed it there, but not on GitHub or ModDB.
