### ISSUE TITLE
Culture province modifiers

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1377]
**Describe your suggestion in full detail below:**
Add `modifier` to cultures (that will affect provinces of the culture). For example, gnolls may have more troops in their provinces, but less morale.

**Comment by MemeWizard** [comment]
Also, we can remove some base troops from all holding, but add troops to cultural modifiers.
For example, we can remove base 50 infantry from every holding, but add 25 cavalry to every holding from dryad, centaur and magnataur cultural modifiers, add 25 mages to dalaranian culture modifier and add back these base 50 infantry to any other cultural modifiers.
Note that special units do **NOT** work correctly in cultural modifiers!
If you want more info, you can check 9019f0d0a642c3a74d47361dd7925467f1137cea

**Comment by arithon** [comment]
I like that idea :)

**Comment by zumbak04** [comment]
> Also, we can remove some base troops from all holding, but add troops to cultural modifiers.
> For example, we can remove base 50 infantry from every holding, but add 25 cavalry to every holding from dryad, centaur and magnataur cultural modifiers, add 25 mages to dalaranian culture modifier and add back these base 50 infantry to any other cultural modifiers.

Sounds fine, but I'm interested, the trade posts and family places are affected by these modifiers? The family places give 20 infantry, so it may replace 20 infantry by 25 cavalry.

**Comment by MemeWizard** [comment]
> the trade posts and family places are affected by these modifiers?

IIRC, yes.

**Comment by zumbak04** [comment]
Done in 52033933cb6f392a80d15d4403f12e73576f4ad3.
