### ISSUE TITLE
[SUGGESTION] | Night elf - Purge lands of demons

### ISSUE THREAD

**Issue by RougeAndNoir** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1382]
After defeating the Burning Legion, I launched a holy war to crush the demons permanently. The victory was simple, but I ended up with a dozen demon vassals. I had to assassinate them one by one. It would not be possible (by an event) to make them disappear suddenly? This sentence could also apply to Satyrs, right?

**Comment by zumbak04** [comment]
@RougeAndNoir can't confirm it. I used **Purge Lands of "Kingdom"** CB. What CB did you use?
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/78387363-421cb580-75f0-11ea-81a1-5f4932a0a2ba.png)

</details>

**Comment by RougeAndNoir** [comment]
> > After defeating the Burning Legion, I launched a holy war to crush the demons permanently. The victory was simple, but I ended up with a dozen demon vassals. I had to assassinate them one by one. It would not be possible (by an event) to make them disappear suddenly? This sentence could also apply to Satyrs, right?
> 
> @RougeAndNoir can't confirm it. I used **Purge Lands of "Kingdom"** CB. What CB did you use?
> 
> Click to expand
> ![image](https://user-images.githubusercontent.com/46384992/78387363-421cb580-75f0-11ea-81a1-5f4932a0a2ba.png)

I use the CB holy war. The purge of lands need too many things.

**Comment by zumbak04** [comment]
> I use the CB holy war. The purge of lands need too many things.

Can't confirm this too. Are you sure you use this CB?
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/78456070-bd46a000-76b2-11ea-889e-219ae098144a.png)
![image](https://user-images.githubusercontent.com/46384992/78456100-d0f20680-76b2-11ea-8ba9-168fd0f6e895.png)

</details>

**Comment by RougeAndNoir** [comment]
> > I use the CB holy war. The purge of lands need too many things.
> 
> Can't confirm this too. Are you sure you use this CB?
> 
> Click to expand

Hi, i make a new test with the CB Holy War and this time that's ok. Demon vassal are out. 
Idk, i think i do wrong thing first time. Sorry i close this.
