### ISSUE TITLE
Capitalize high god name here

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1386]
**Mod Version**
4e654312c230009e61a328e345b783ffd446c14b

**Are you using any submods/mods? If so, which?**
No

**Please explain your issue in as much detail as possible:**
the Old Gods (high god name) should be capitalized.

**Upload screenshots of the problem localization:**
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/78507560-b773bc00-7791-11ea-83b1-f01489647304.png)

</details>

**Comment by arithon** [comment]
Deleting "The" would make it sound better...

**Comment by zumbak04** [comment]
> Deleting "The" would make it sound better...

Don't know. It will result in deleting everywhere, even in the middle of the description like:
> Bla-bla-bla Old Gods abandoned him bla-bla-bla
