### ISSUE TITLE
Purged old Old God blessings

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1406]
**Describe your suggestion in full detail below:**
Purged old unused `cthun_blessing_build_1`, `yogg_saron_blessing_learning_1`, `yshaarj_blessing_levy_2`, etc.

**Comment by MemeWizard** [comment]
Like c4aa93a69 ?

**Comment by zumbak04** [comment]
> Like [c4aa93a](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/commit/c4aa93a692030031ccea7008678adef5b2d0b015) ?

Noice.
