### ISSUE TITLE
[BUG] | Demons can gain negative genetic traits

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#142]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Demons can gain negative genetic traits because some events check if character is a demon before effect of soul corruption.

**Steps to reproduce the issue:**
Eat soul shards until your character turn into demon, then get these events.

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_1](https://cdn.discordapp.com/attachments/406500578231975937/545720750938521611/ck2_3.png)

![ck2_1](https://cdn.discordapp.com/attachments/406500578231975937/545720722484494346/ck2_1.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
