### ISSUE TITLE
[BUG] | the devourer vanished

### ISSUE THREAD

**Issue by Arubata** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1442]
**Your mod version is:**
april 17

**What expansions do you have installed?**
all
**Are you using any submods/mods? If so, which?**
no
**Please explain your issue in as much detail as possible:**
i got this event called the ancient creature which summons the devouerer which has more than 10000 years, i got him normally but when i reload the save again and summon him again he appeared vanished. i can see him in my court but cant do anything with him
**Steps to reproduce the issue:**
follow the steps to summon the ancient creature and reload the save same day of when he says alas
![20200417232122_1](https://user-images.githubusercontent.com/63881444/79615779-cd736c00-8103-11ea-8dd4-3c4bcabe1e37.jpg)

**Upload an attachment below: .zip of your save, or screenshots:**

**Comment by zumbak04** [comment]
> i got this event called the ancient creature which summons the devouerer which has more than 10000 years, i got him normally but when i reload the save again and summon him again he appeared vanished. i can see him in my court but cant do anything with him

@Arubata the event said the creature would like to help you? What is your religion?

**Comment by Arubata** [comment]
what info do u need more?

**Comment by zumbak04** [comment]
> what info do u need more?

Dis.

> @Arubata the event said the creature would like to help you? What is your religion?

**Comment by Arubata** [comment]
Ursine (natural)

**Comment by zumbak04** [comment]
> Ursine (natural)

Oh, it doesn't look like a bug then. The event that spawned the creature should say that he like killed your people and ran away.

**Comment by Arubata** [comment]
but the first time i summoned him he was alive, i even marriage him to my daughter, so when i found out he cant make kids i reload the save

**Comment by zumbak04** [comment]
> but the first time i summoned him he was alive, i even marriage him to my daughter, so when i found out he cant make kids i reload the save

He can exist one day (or a few days if you're in the multiplayer).

**Comment by Arubata** [comment]
but the first time i summoned him he was alive more than 1 day, but i repeated like more than 20 times and none came alive

**Comment by Arubata** [comment]
![20200417235413_1](https://user-images.githubusercontent.com/63881444/79617036-d6197180-8106-11ea-9943-683ba7491461.jpg)

**Comment by zumbak04** [comment]
When you click the option, he dies.

**Comment by Arubata** [comment]
why. cause it is my religion?
is there any success chance of actually summoning him?

**Comment by zumbak04** [comment]
> why. cause it is my religion?
> is there any success chance of actually summoning him?

Yes, because of religion. You must be Old Gods' follower.

**Comment by Arubata** [comment]
i feel dumb for wasting ur time and effort trying to help me figure out how the mods events work, ur a great person indeed, thank u for ur time

**Comment by zumbak04** [comment]
> i feel dumb for wasting ur time and effort trying to help me figure out how the mods events work, ur a great person indeed, thank u for ur time

No, no problem, you're welcome.
