### ISSUE TITLE
[LOCALIZATION] | Ancient warcraft philosophy

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#145]
**Mod Version**
Master branch

**Please explain your issue in as much detail as possible:**
AFAIK, there is no Plato is warcraft
EVTDESC94108

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![ck2_9](https://user-images.githubusercontent.com/46576860/52853734-866b9e80-312d-11e9-8d71-c62e8a4aac25.png)

</details>

**Comment by zumbak04** [comment]
The event was removed.
