### ISSUE TITLE
Alas after turning yourself

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1456]
**Mod Version**
5d5d590865227b88a840a54790b643d8aad19075

**Are you using any submods/mods? If so, which?**
No

**Please explain your issue in as much detail as possible:**
I turned myself undead, I shouldn't say Alas.

**Upload screenshots of the problem localization:**
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/79702987-cee69500-82b9-11ea-8a4b-1d716848fbc1.png)

</details>

**Comment by arithon** [comment]
Not a localisation, but an event option problem. "Alas!" (vanilla answer) must be replaced.
