### ISSUE TITLE
[SUGGESTION] | Visiting emerald dream should not make your character incapable?

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#146]
**Describe your suggestion in full detail below:**
Because "in emerald dream" trait makes your character incapable, your character ambition and focus will be cleared.
So, maybe make this trait effect not "incapable", but like "on pilgrimage"?

**Comment by zumbak04** [comment]
Changed in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/commit/6cd7bc8fec9b9959c531d1510e54030eb50a39fc
