### ISSUE TITLE
[BUG] | KAEL'THAS DOESN'T RETURN HOME

### ISSUE THREAD

**Issue by Zenormus** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1466]
**Your mod version is:**
812f96d4c5e0a92ad5132d4f3002e7f706b35ae2

**What expansions do you have installed?**
All but Sunset Invasion

**Are you using any submods/mods? If so, which?**
No

**Please explain your issue in as much detail as possible:**
After Illidan lost the war against the Scourge in the Frozen Throne Stardate, playing as Kael, i could not return to rule Quel'thalas, and remained Sunfury in Crystalsong Forest in Northrend.

**Steps to reproduce the issue:**
I got the event to decide if i should follow Illidan or not, i chose to not follow which instead of returning to Quel'Thalas, i remained in Northrend. I noticed Quel'Thalas joined the Horde so that might have cause the Title transition issue.

**Upload an attachment below: .zip of your save, or screenshots:**

[Kael Bug.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/4509847/Kael.Bug.zip)

**Comment by zumbak04** [comment]
Testing your saves. Tried the pre-bug, seems fine, got the event.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/79903701-97482c00-8424-11ea-873d-4a43533edfad.png)

</details>

**Comment by zumbak04** [comment]
@Zenormus so, ye, got the event in the post-bug save. You just need to wait a few more days.
