### ISSUE TITLE
[SUGGESTION] | Gorian Empire

### ISSUE THREAD

**Issue by MoffKadir** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1471]
Ogres can be given the opportunity to restore the Gorian Empire, similar to Orsinium in the mod "Elder Kings". Requirement to create: to be independent, king or higher, and possibly be a ogre-mage. Events on flocking orcs (ogres) would be great.

**Comment by zumbak04** [comment]
Joining the development!
