### ISSUE TITLE
[LOCALIZATION] | Founding of Theramore

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#148]
**Mod Version**
Master branch

**Please explain your issue in as much detail as possible:**
No event description

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![ck2_1](https://user-images.githubusercontent.com/46576860/52876686-fb0ffe80-3168-11e9-8751-653d4d680699.png)

</details>

**Comment by zumbak04** [comment]
Added!
