### ISSUE TITLE
[SUGGESTION] | We must join Jaina and flee west!

### ISSUE THREAD

**Issue by BrodieLeSage** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#149]
**DO NOT REMOVE PRE-EXISTING LINES**
----------------------------------------------------------------------------------------------------------
**Describe your suggestion in full detail below:**
While I love slogging it out with the Scourge or the Trolls as much as the next good human, sometimes we all just need to take a vacation, but to where you might ask? Well worry no more! This extremely charismatic and attractive mage happens to be going on one such permanent vacation. And she's looking for volunteers to come join her! I already hear that a Brigade from (insert random one here: Gilneas, Stromgarde, Alterac, Dalaran, Iron forge, and lordaeron) have already made the trip! Plus it also happens to be a fact the Undead Scourge is only a few hours away from your castle M'lord/M'lady so what are your orders? Shall I ready the Fleet? 

So to explain that even further and in more official detail my idea is for coastal players (Or just perhaps players in certain alliance races, who are the title of count (lord/Lady) have the option of abandoning their current territory much like the frostwold event chain but in this instance to flee west with jaina, and being such a "distinguished" noble Jaina gives you one of the lesser islands as your new territory. From here you can carry on the legacy of the people of Lordaeron and perhaps one day return to retake what is yours! Or simply the threat beyond the wall of Gilneas was to much and you won't allow a single fortification dictate your safety. Or perhaps you wished to see the Glory of Stromgarde brought across the sea to this new and strange land. or perhaps you and your stout folk from the mountains seek new minerals and riches to bring back to the great forges within Iron Forge. While the trip would be hard, you may even run aground elsewhere or perhaps even on one of the many islands that block your way. **Hint hint wink wink nudge nudge** it is a very uncertain future ahead but if your people are to survive perhaps it might just be a risk you are willing to take. This event would see Jaina spawning in Kalimdor with a Titular or a new Duchy title of Theramore to allow a player to be one of her vassals. However if the player runs aground elsewhere it would be another story entirely, one in which you are alone against the unknown horrors of the deep or those from the unknown shores you've set foot on. This could in theory to me that is make it possible to fight in the battle against the legion in Kalimdor just like in Warcraft three, now who wouldn't want to send the Demons back to the twisting nether from whence they came?

Each race that would get this option would be Lordaeron Humans, Alterac Humans, Stromgarde Humans, Dalaranian Humans, Gilnean Humans, and or Ironforge dwarves. But letting it be a player only event chain would stop two random AI's from just stealing the two other Islands from Jaina before you can take one. We could possibly extend this flee west to the High Elves as well but that would just be for RP and does not hold much basis in lore. The island you get, or the territory you run aground on along the way or if you were simply nocked off coarse before reaching Kalmindor would become your religion and your culture. From there your destiny is your own. You might even be able to throw in some Naga or direct old god shenanigans along the way.

**Comment by CarlosCSF** [comment]
It would be nice if when you arrive at Kalindor, if you arrive elsewhere, you have a event where you have to fight the shore inhabitants like the horde did in Warcraft 3.

**Comment by zumbak04** [comment]
Implemented!

> It would be nice if when you arrive at Kalindor, if you arrive elsewhere, you have a event where you have to fight the shore inhabitants like the horde did in Warcraft 3.

It's what usually happens when you start expanding here.
