### ISSUE TITLE
[LOCALIZATION] | nick_the_godslayer

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#150]
**Mod Version**
Master branch

**Please explain your issue in as much detail as possible:**
"The godslayer" nickname don't have localisation.

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![ck2_21](https://user-images.githubusercontent.com/46576860/52901506-78914880-3215-11e9-98f5-020c2e492c9b.png)
![ck2_22](https://user-images.githubusercontent.com/46576860/52901507-78914880-3215-11e9-9e79-2c7f21c1279b.png)

</details>

**Comment by sejtalk** [comment]
fixed
