### ISSUE TITLE
Incorrect Temple Localisation

### ISSUE THREAD

**Issue by DukeJeans** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1517]
**Your mod version is:**
30fffc7

**Please explain your issue in as much detail as possible:**
Temple with Tidemother religion is referred to as a workshop. Other temples in realm do not have this.

**Steps to reproduce the issue:**
This is occuring after conquering and purging Booty Bay (Wealthy).

**Upload an attachment below: .zip of your save, or screenshots:**
<details>

<summary>Screenshot below</summary>

![image](https://user-images.githubusercontent.com/32686241/80820398-c38e4600-8ba4-11ea-9819-113bce25e9b5.png)

</details>

**Comment by arithon** [comment]
Is it a technocracy that's ruling? Or a secular group?

**Comment by DukeJeans** [comment]
This is just after purging, so the ruler is Southern Tidemother. Other temples are referred to as Temples, not Workshops.

**Comment by arithon** [comment]
Does it happen after saving/reloading still?

**Comment by DukeJeans** [comment]
You're safe to assume I've run through all the basic fix techniques

**Comment by zumbak04** [comment]
It's not a bug. The temples are called depending on holder's religion.
