### ISSUE TITLE
[BUG] | Demons can get disease

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#152]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Demons can get scurvy through RIP.5051 event

**Steps to reproduce the issue:**
Command army on ships

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_25](https://user-images.githubusercontent.com/46576860/52901886-5e0d9e00-321a-11e9-9cb2-2f6835e33e88.png)
![ck2_17](https://user-images.githubusercontent.com/46576860/52901889-6239bb80-321a-11e9-97ad-4a10b91798bb.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
