### ISSUE TITLE
Loken sacrificing issue

### ISSUE THREAD

**Issue by Regilover** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1544]
**Your mod version is:**
github early version
**What expansions do you have installed?**
All
**Are you using any submods/mods? If so, which?**
GOA music, Model and Font.
**Please explain your issue in as much detail as possible:**
Unable to sacrifice prisoners to Yogg as a corrupted Loken for favor. Failed to meet the requirement of primary title being anything except high lordship of ulduar.
**Steps to reproduce the issue:**
Start as keeper loken (Opening of the Dark Portal bookmark if it matters). Give into despair and fall to the old gods. Select Yogg as your primary old god to worship. Acquire prisoner in whatever flavor you desire. Attempt to sacrifice prisoner through yogg interface and be unable to.
**Upload an attachment below: .zip of your save, or screenshots:**
![image](https://user-images.githubusercontent.com/65082689/81478962-2bb4db80-91e6-11ea-8565-69c3b61c56de.png)

**Comment by zumbak04** [comment]
Most likely you tried to sacrifice a stone titan-forged. They can't be sacrificed for now.

**Comment by zumbak04** [comment]
> They can't be sacrificed for now.

Aaand they're allowed.
