### ISSUE TITLE
[BUG] | Original owner get kingdom with dark pact succession law

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#155]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
After defeat of The Burning Legion, kingdom return to it's original owner with dark pact succession law.

**Steps to reproduce the issue:**
Convert your character to Legion worshiper, join the Burning Legion and convert government type to legion.
Burning Legion must lose invasion.
Your kinsman inherit your kingdom, but dark pact will remain as succession law.

**Upload an attachment below: .zip of your save, or screenshots:**
<details>
<summary>Click to expand</summary>

![ck2_18](https://user-images.githubusercontent.com/46576860/52902110-3966f580-321d-11e9-8ce0-b9304a193cf2.png)
![ck2_19](https://user-images.githubusercontent.com/46576860/52902111-3966f580-321d-11e9-8003-bb53294fb764.png)

</details>

**Comment by zumbak04** [comment]
It was hard, but I fixed.
