### ISSUE TITLE
[BUG] | Legion cultist can change religion

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#156]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Legion cultist are not supposed to change religion

**Steps to reproduce the issue:**
Convert your character to legion through shadow council, your character must openly adopt legion, and if your capital has different religion, your char can convert in religion of the capital.

**Upload an attachment below: .zip of your save, or screenshots:**
<details>
<summary>Click to expand</summary>

![ck2_4](https://user-images.githubusercontent.com/46576860/52902191-b2b31800-321e-11e9-98e0-ad375647b0ce.png)
![ck2_5](https://user-images.githubusercontent.com/46576860/52902192-b2b31800-321e-11e9-9a56-eb4b437d447d.png)

</details>

**Comment by zumbak04** [comment]
It's not a bug. You can change your religion if you're not a demon and warlock.
