### ISSUE TITLE
[SUGGESTION] | Goldrinn Religion Hunting Focus

### ISSUE THREAD

**Issue by fivesanon** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1560]
**Describe your suggestion in full detail below:**
Goldrinn religion should be able to do hunting focus. All religions under the natural group cannot choose this focus.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/57690273/81985327-f7c52600-95ea-11ea-9b8c-08da4b818972.png)

</details>

**Comment by zumbak04** [comment]
Hello! It was suggested here: https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/issues/1556.

**Comment by fivesanon** [comment]
> Hello! It was suggested here: #1556.

oh haha
