### ISSUE TITLE
[BUG] | Random freezes

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#157]
**Mod Version**
abea4e0

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Mod runs pretty fast (5 days/sec), but sometimes freezes for 10-15 seconds.

**Steps to reproduce the issue:**
Load save

**Upload an attachment below: .zip of your save, or screenshots:**

[Burning_Legion818_01_08.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/2874019/Burning_Legion818_01_08.zip)

**Comment by zumbak04** [comment]
Closing since most likely it's a vanilla event: `RIP.11700`
