### ISSUE TITLE
Weird character names

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1572]
**Describe your suggestion in full detail below:**

Change naga weird names

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/82158027-c029d880-988d-11ea-93e4-1abd056fd4e2.png)

</details>

**Comment by arithon** [comment]
I don't see any problem with that name :D
