### ISSUE TITLE
[BUG] | Levy fuckin dead if wrong government

### ISSUE THREAD

**Issue by fivesanon** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1586]
**Your mod version is:**
early version, master branch
**What expansions do you have installed?**
all dlc
**Are you using any submods/mods? If so, which?**
bigger interface, good ultimate tooltip, goa models
**Please explain your issue in as much detail as possible:**
garrisons and levies just instantly vanish if a tribal government owns a castle, city, or temple. I _assume_ the same goes for republics and theocracies if the holding isnt a city or temple respectively but i dont know for sure, as well as other government types. I am unsure if this is just an issue I am having but I've had this issue since yesterday.
**Steps to reproduce the issue:**
Look at any tribal government that directly owns a non tribal holding.
**Upload an attachment below: .zip of your save, or screenshots:**
<details>
<summary>Timbermaw</summary>

![image](https://user-images.githubusercontent.com/57690273/82580966-b7aef780-9b44-11ea-93bc-0bce6ee3973d.png)

</details>
<details>
<summary>Dirtnail</summary>

![image](https://user-images.githubusercontent.com/57690273/82581158-fe045680-9b44-11ea-9f59-31951cd079bc.png)

</details>

**Comment by MemeWizard** [comment]
Tribals can't hold castles and must pillage them or reform to feudalism.

**Comment by fivesanon** [comment]
> Tribals can't hold castles and must pillage them or reform to feudalism.

But there are some rulers that only start with castles and so they have no levies

**Comment by MemeWizard** [comment]
> But there are some rulers that only start with castles and so they have no levies

Known issue, I already reported some in #1104

**Comment by zumbak04** [comment]
I'm leveling up the priority of the #1104 issue and closing this one then.
