### ISSUE TITLE
[BUG] | Ships from the port of the province of LuDei cannot sail to neighboring water locations Vile Reef and South Savage Coast.

### ISSUE THREAD

**Issue by Mikekz** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1597]
**Your mod version is:**

**What expansions do you have installed?**

**Are you using any submods/mods? If so, which?**

**Please explain your issue in as much detail as possible:**

**Steps to reproduce the issue:**

**Upload an attachment below: .zip of your save, or screenshots:**

**Comment by arithon** [comment]
you know, describing the issue/bug in the initial post would help a little...

**Comment by zumbak04** [comment]
Note: you can edit your own issues.

**Comment by Mikekz** [comment]
![1](https://user-images.githubusercontent.com/65672256/82837700-a28eeb80-9eeb-11ea-9bcb-e37d97a51f09.jpg)
CK 3.3.2
Mod ver 1.7.0
Ships from the port of the province of LuDei cannot sail to neighboring water locations Vile Reef and South Savage Coast.

**Comment by zumbak04** [comment]
That's better.
