### ISSUE TITLE
[LOCALIZATION] | All caps religion revolt leader title

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#160]
**Mod Version**
Master branch

**Please explain your issue in as much detail as possible:**
Mod prints cult of wealth religion revolt leader title in all caps

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![ck2_7](https://user-images.githubusercontent.com/46576860/53067870-2e46ea80-34e7-11e9-88b6-0c40698400d7.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
