### ISSUE TITLE
[SUGGESTION] Draenei Wowpedia Links

### ISSUE THREAD

**Issue by LordSilvermane** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1602]
**Describe your suggestion in full detail below:**
Add wowpedia links to the draenei characters who appear in the lore after the exodar crash. Examples include Velen, Iridi, and Menelaous. Theres no real reason for them not to have one, as far as I know, and they are kind of are a standout case, with a lot of lore characters suddenly appearing yet none of them have links.

**Comment by MemeWizard** [comment]
> who appear in the lore after the exodar crash

Well, links are tied to character ID, and since all spawned characters ID are dynamic, you can't give links to characters that spawns after game starts. And we don't have any bookmarks where they are already spawned.

**Comment by LordSilvermane** [comment]
Ahh, fair enough then. Too bad.
