### ISSUE TITLE
Ruled too long penalty

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1606]
**Describe your suggestion in full detail below:**
So, the Paradox planned to add Ruled too long penalty to counter immortal rulers, but it doesn't work both in the vanilla and mod. I suggest adding it back.
P.S. There are events for immortals in `rip_flavor_events`. They need adaptation together with the suggestion.

**Comment by scannik** [comment]
Will there be an upper limit to the „ruled for too long“ penalty? As to make it hard instead of impossible to maintain an immortal ruler? Because I really think that players should at least have the option to play the entire game as an *insert immortal-race-equivalent*, if they wanted to.

**Comment by zumbak04** [comment]
> Will there be an upper limit to the „ruled for too long“ penalty? As to make it hard instead of impossible to maintain an immortal ruler? Because I really think that players should at least have the option to play the entire game as an _insert immortal-race-equivalent_, if they wanted to.

There may be a game rule to disable it for everyone or for players only.

**Comment by robmart** [comment]
IMO the ruled too long debuff should only be a thing if you've ruled 20 years more than your race's life expectancy. Or maybe instead of it being based on the rulers life expectancy it should be based on the vassals (eg human vassals get angry at rulers who ruled for (human life expectancy) + 20 years).
