### ISSUE TITLE
x2 and 2x localization variants

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1609]
**Mod Version**
d1f7c5880

**Are you using any submods/mods? If so, which?**
They don't matter

**Please explain your issue in as much detail as possible:**
Gamerules have both x2 and 2x localization localization variants.

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/83407428-5f67d780-a419-11ea-9c87-9b27db1f1215.png)

</details>

**Comment by arithon** [comment]
The "reduced by 2x" should be "reduced to 0.5x", right?

**Comment by MemeWizard** [comment]
Y
