### ISSUE TITLE
[LOCALIZATION] | Roman horses

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#161]
**Mod Version**
Master branch

**Please explain your issue in as much detail as possible:**
"Master of the horse" minor title description talks about Roman Republic

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![ck2_3](https://user-images.githubusercontent.com/46576860/53075301-e089ac80-34fd-11e9-9098-c6b49921213c.png)

</details>

**Comment by zumbak04** [comment]
The part about Roman Republic removed.
