### ISSUE TITLE
The Illidari Retreat

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1617]
**Mod Version**
eb732801b

**Are you using any submods/mods? If so, which?**
`-`

**Please explain your issue in as much detail as possible:**
"The Illidari Retreat" event text makes no sense if Kael'thas was imprisoned and then turned into undead servant of the Lich King in the middle of war.

Solutions:

1 - Add event text for that specific case
2 - Ban characters from "Turn into Undead" decision if you participate in a war against decision target.

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/83427682-c5645700-a439-11ea-832a-cf1358e470a5.png)

</details>

**Comment by zumbak04** [comment]
> **Mod Version**
> [eb73280](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/commit/eb732801ba7ceff1df64f5bbbda76c2c9f08c46e)
> 
> **Are you using any submods/mods? If so, which?**
> Solutions:
> 
> 1 - Add event text for that specific case
> 2 - Ban characters from "Turn into Undead" decision if you participate in a war against decision target.

Most likely I'll hide the event.
