### ISSUE TITLE
Quel'Delar description

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1619]
**Mod Version**
eacbb84a9

**Are you using any submods/mods? If so, which?**
`-`

**Please explain your issue in as much detail as possible:**
Quel'Delar description talks about the Scourge in 583

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/83432153-217ea980-a441-11ea-95f5-a5122d2e135a.png)

</details>

**Comment by arithon** [comment]
hmm, just read a little about Kalecgos and came to Quel'Delar at some point... the fix right now is that the description doesn't speak of the scourge, but shouldn't actually the blade only exist since the time the scourge attacked?
