### ISSUE TITLE
[LOCALIZATION] | follower_of_nalorakk

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#162]
**Mod Version**
Master branch

**Please explain your issue in as much detail as possible:**
No loc for modifier

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![ck2_8](https://user-images.githubusercontent.com/46576860/53079680-ff8d3c00-3507-11e9-8141-1999509f3dd6.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
