### ISSUE TITLE
[BUG] | Vassals become independent after stopping invader

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#164]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
My vassal become independent after war with the Lich-king

**Steps to reproduce the issue:**
Give kingdom, where Scourge have provinces, to your vassal
Won war against scourge with "Stop invader" CB

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_20](https://user-images.githubusercontent.com/46576860/53095966-1abf7200-352f-11e9-9e68-d8581edc133e.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
