### ISSUE TITLE
References to Far East in ZE_4030

### ISSUE THREAD

**Issue by Nith-ae** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1645]
**Mod version:**
1.7
**Are you using any submods/mods? If so, which?**

**Please explain your issue in as much detail as possible:**
This event mentions the Far East

**Upload screenshots of the problem localization:**
![ck2_3](https://user-images.githubusercontent.com/55211083/84602642-420b2280-ae89-11ea-86f2-ff7962a6f4b7.png)

**Comment by arithon** [comment]
Hmm, could change it to titanic models or something like that.
