### ISSUE TITLE
[BUG] | Trolls can restore the Sunwell

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#165]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
TROLLS YELLS "FOR QUEL'THALAS!"

**Steps to reproduce the issue:**
Have the corrupted Sunwell in your realm and click on "restore the Sunwell" decision

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_23](https://user-images.githubusercontent.com/46576860/53096196-9faa8b80-352f-11e9-960c-59dadb597e4c.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
