### ISSUE TITLE
xalatath Disappears

### ISSUE THREAD

**Issue by Lordmitch** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1650]
**Your mod version is:**
Master
**What expansions do you have installed?**
All
**Are you using any submods/mods? If so, which?**
None
**Please explain your issue in as much detail as possible:**
Xalatath Disappears
**Steps to reproduce the issue:**
Kill The Bishop of Northshire then check his successor  
**Upload an attachment below: .zip of your save, or screenshots:**
![image](https://user-images.githubusercontent.com/47829580/84711208-b1eadd00-af5d-11ea-9998-3697527aabfb.png)
![image](https://user-images.githubusercontent.com/47829580/84711374-19089180-af5e-11ea-9906-ca60bbc07379.png)

**Comment by MemeWizard** [comment]
Xal'atath can't be inherited. It always disappears after owner's death.
