### ISSUE TITLE
Old God Sacrifice

### ISSUE THREAD

**Issue by Lordmitch** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1651]
**Mod version:**
Master
**Are you using any submods/mods? If so, which?**
None
**Please explain your issue in as much detail as possible:**
The Sacrifice god name is Missing
**Upload screenshots of the problem localization:**
![image](https://user-images.githubusercontent.com/47829580/84712455-86b5bd00-af60-11ea-9a97-8ef5553cc990.png)

**Comment by MemeWizard** [comment]
Thanks for the report!
This should be fixed in #1400
