### ISSUE TITLE
[LOCALIZATION] | Human anatomy

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#166]
**Mod Version**
Master branch

**Please explain your issue in as much detail as possible:**
Your char can write book about human anatomy even if he is not human.

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![ck2_13](https://user-images.githubusercontent.com/46576860/53096577-8b1ac300-3530-11e9-9d45-551058c564c2.png)

</details>

**Comment by zumbak04** [comment]
"Human Anatomy" replaced by "Humanoid Anatomy".
