### ISSUE TITLE
[SUGGESTION] Dynamic Seasons

### ISSUE THREAD

**Issue by Malicos** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1661]
**Describe your suggestion in full detail below:**
I would like to suggest an adaptation of vanilla dynamic seasons mechanic for Azeroth. While the existence of permanent snow in zones is kind of justifiable in World of Warcraft because of engine limitations/zone variety, it makes little sense for this state to persist in CK2, since it can easily simulate changing seasons.

Areas like Alterac, Dun Morogh and Winterspring can be adapted to be snowless regions during summer, while eventual snowfall can happen earlier due to high altitude (same with Hyjal, which is even higher than Winterspring). Southern parts of Northrend can be adapted into some kind of tundra regions that have reduced presence of snow during summer, while Icecrown and Storm Peaks can remain areas affected by permanent snow, same with Kun-Lai in Pandaria.

**Comment by zumbak04** [comment]
Suggested in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/issues/1425. Linking it.
