### ISSUE TITLE
[BUG] | War gives you random holdings in non-your provinces

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#167]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
After defeating of the Lich-King, my char get holdings in provinces, that belongs to another realm.

**Steps to reproduce the issue:**
Win "Stop invader" war against big bad guy

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_22](https://user-images.githubusercontent.com/46576860/53096892-3cb9f400-3531-11e9-9466-8437d06e4de4.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
