### ISSUE TITLE
[BUG] | Character can be training by two characters simultaneously

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#168]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
After 2 years of education, you can ask another char to train you, even if you already have mentor.

**Steps to reproduce the issue:**
Have low level class trait
Ask mentor for training (this training also must give you low level class trait)
After 2 years of training you can ask another character to train you, even if you already have mentor

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_9](https://user-images.githubusercontent.com/46576860/53104239-0e8fe080-3540-11e9-95f2-d182a6b53e3e.png)
![ck2_10](https://user-images.githubusercontent.com/46576860/53104240-0e8fe080-3540-11e9-9261-eb02d01ce763.png)
[save games.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/2885307/save.games.zip)

</details>

**Comment by zumbak04** [comment]
Fixed!
