### ISSUE TITLE
[BUG] | Undead children have transparent background

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#169]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Undead children don't have portrait background.

**Steps to reproduce the issue:**
Look at undead child

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_6](https://user-images.githubusercontent.com/46576860/53108081-6f6ee700-3547-11e9-81d3-1433da46391f.png)
![ck2_7](https://user-images.githubusercontent.com/46576860/53108082-70077d80-3547-11e9-99b2-6e3c1ed9f231.png)

</details>

**Comment by MemeWizard** [comment]
OOOPS

**Comment by zumbak04** [comment]
Fixed!
