### ISSUE TITLE
[BUG] | Shadow councilors can be asked to leave court

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#170]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Shadow councilors can be asked to leave court

**Steps to reproduce the issue:**
Right-click on shadow councilor portrait
Ask to leave court

**Upload an attachment below: .zip of your save, or screenshots:**
<details>
<summary>Click to expand</summary>

![ck2_1](https://user-images.githubusercontent.com/46576860/53113878-9cc19200-3553-11e9-8815-5787d3f76e92.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
