### ISSUE TITLE
[BUG] Everyone (even Death God religions) hate lich king.

### ISSUE THREAD

**Issue by aybarsavci** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1703]
**Your mod version is: Newest **

**What expansions do you have installed?= 3.3.3 **

**Are you using any submods/mods? If so, which?= no**

**Please explain your issue in as much detail as possible:When you imprison/exevute/banish someone as lich king you get tyranny on your vassals (i get -670 trynany opinion ), As as lich king this shouldn't be happen i think, because they think you are god and we controll them.**

**Steps to reproduce the issue:Opinion of Head of Religion should be increased to +20000 so they will never hate**

**Comment by arithon** [comment]
And with +20,000, how would the forsaken have happened at all? Btw, tyranny does not simply "happen", you have to do something to get tyranny
