### ISSUE TITLE
[BUG] | ruler designer high and blood elf crash bug

### ISSUE THREAD

**Issue by Lordmitch** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#171]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.3
**What expansions do you have installed?**
All
**Please explain your issue in as much detail as possible:**
Using the ruler designer for high or blood elves cause the game to crash.
**Steps to reproduce the issue:**
Go into the ruler designer can click sin'dorei or Quel'dorei ethnicity
**Upload an attachment below: .zip of your save, or screenshots:**

![elf](https://user-images.githubusercontent.com/47829580/53115752-e3f15800-353e-11e9-8676-d074880b713f.png)

**Comment by zumbak04** [comment]
Fixed!
