### ISSUE TITLE
[BUG] | Blood and high elf trait bug

### ISSUE THREAD

**Issue by Lordmitch** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#172]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.3
**What expansions do you have installed?**
All
**Please explain your issue in as much detail as possible:**
Some but not all elf get both the high and blood elf trait after corrupting the sunwell
**Steps to reproduce the issue:**
Gain the sunwell and then summon the legion and corrupt the well.
**Upload an attachment below: .zip of your save, or screenshots:**
![image](https://user-images.githubusercontent.com/47829580/53117324-8fe87280-3542-11e9-80d5-55b43e5850ba.png)

**Comment by zumbak04** [comment]
Fixed!
