### ISSUE TITLE
Zodiac traits localization

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1721]
**Mod version:**
29b734b4b

**Are you using any submods/mods? If so, which?**
`-`

**Please explain your issue in as much detail as possible:**
Zodiac traits localization refer to RL

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/88011700-b12b0500-cb20-11ea-8cb5-0b9ed472b445.png)

</details>

**Comment by Myrran** [comment]
Patch 1.8.0. I have the same issue:
<details>
  <summary>Gemini Zodiac</summary>

![ck2_1](https://user-images.githubusercontent.com/1375281/88449586-ad64ee80-ce50-11ea-9023-372764591a20.png)
![ck2_2](https://user-images.githubusercontent.com/1375281/88449589-b05fdf00-ce50-11ea-8e14-7f603e893c70.png)
</details>

**Comment by MemeWizard** [comment]
Btw, I'm not sure if zodiac existence is intended or not, since they are assigned when you make someone your apprentice in the alchemists' union.

**Comment by arithon** [comment]
If anyone can provide me with zodiac signs for WoW, I can fix this in the next localisation crusade...

**Comment by zumbak04** [comment]
> If anyone can provide me with zodiac signs for WoW, I can fix this in the next localisation crusade...

WELL
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/88667407-626a0600-d0f2-11ea-937e-b1a0c7ff641f.png)

</details>

**Comment by arithon** [comment]
@zumbak04 you know that something like leo, scale, cancer, aquarius is meant here, right? not just two items...

**Comment by MemeWizard** [comment]
Their names, as is, is not really a problem, imo.

(There is not enough signs anyway)
https://wow.gamepedia.com/Constellation 

The real problem is the second part of their description.

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/88670055-49128b00-d0ed-11ea-9b7b-dfb7b304181c.png)

</details>

Tbh, I think it just can be deleted.

Or you can change it, if you want
https://wow.gamepedia.com/Astromancy

**Comment by arithon** [comment]
ok, will change it later this week. have to open a new LC for it :)
