### ISSUE TITLE
Negative Opinion Modifier for giving away Counties

### ISSUE THREAD

**Issue by Thatchah** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1727]
**Your mod version is:**
1.8

**What expansions do you have installed?**
All

**Are you using any submods/mods? If so, which?**
None

**Please explain your issue in as much detail as possible:**
In both the 603 and 605 Bookmarks,when a Horde Vassal gives away a landed Title,they and the Horde Leader gain a stacking -10(Broken Pact) and -15(Dissolved Alliance) Opinion Modifier. Happens if the AI does it as well.

**Steps to reproduce the issue:**
Play as any Horde Vassal in 603 or 605 with more than one County,and give one to another Character.

**Upload an attachment below: .zip of your save, or screenshots:**
![AAACairne1](https://user-images.githubusercontent.com/68848487/88557876-1902b380-d02b-11ea-8218-667e2e31266f.png)
![AAACairne2](https://user-images.githubusercontent.com/68848487/88557883-1bfda400-d02b-11ea-94fc-4232cfdc9610.png)

**Comment by zumbak04** [comment]
Thanks for the report! Took the issue.
