### ISSUE TITLE
[BUG] | The black dragonflight vassalization

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#173]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Black dragons spamming with messages about vassalization after creating of The Black Empire

**Steps to reproduce the issue:**
Create The Black Empire

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_3](https://user-images.githubusercontent.com/46576860/53117329-bb2b8b80-355b-11e9-85a6-aa00a2390da4.png)
![ck2_4](https://user-images.githubusercontent.com/46576860/53117330-bb2b8b80-355b-11e9-94d7-6e1cae77a12a.png)
![ck2_5](https://user-images.githubusercontent.com/46576860/53117331-bb2b8b80-355b-11e9-9bd6-87c76e02784f.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
