### ISSUE TITLE
Celestial religious revolt leader title is written in all caps

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1743]
**Mod version:**
d2df6541e

**Are you using any submods/mods? If so, which?**
No

**Please explain your issue in as much detail as possible:**
Celestial religious revolt leader title is written in all caps
M O N K

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/89146313-fbb67380-d55b-11ea-92c5-eb4e3208835d.png)

</details>

**Comment by arithon** [comment]
no idea where that comes from, there is no MONK in all capitals in the loc files, at least none that i can see.

**Comment by MemeWizard** [comment]
> there is no MONK in all capitals in the loc files

Well, that's the reason - `MONK` localization line is missing

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/89180708-fc222f00-d59a-11ea-9275-1bef38a952c4.png)

</details>

**Comment by arithon** [comment]
That makes sense 😅
