### ISSUE TITLE
HL.4814 desc

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1744]
**Mod version:**
d2df6541e
**Are you using any submods/mods? If so, which?**
no
**Please explain your issue in as much detail as possible:**
Nomads in the mod don't have horses

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/89149763-e9413780-d565-11ea-8f60-eec8a735249a.png)

</details>

**Comment by arithon** [comment]
fixed in LC 19
