### ISSUE TITLE
the Eastern Wind nickname

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1746]
**Mod version:**
d2df6541e

**Are you using any submods/mods? If so, which?**
`-`
**Please explain your issue in as much detail as possible:**
"the Eastern Wind" don't fit in the setting, there is no nomads in warcraft in the east

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/89151254-3a065f80-d569-11ea-8fa7-e45bf61fdc2d.png)

</details>

**Comment by arithon** [comment]
fixed
