### ISSUE TITLE
You have been at peace for too long description

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1747]
**Mod version:**
d2df6541e
**Are you using any submods/mods? If so, which?**
No

**Please explain your issue in as much detail as possible:**
Are you sure that word "pagan" should be used in description like that?

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/89152944-a3d43880-d56c-11ea-8b80-d88a0167a02a.png)

</details>

**Comment by arithon** [comment]
fixed in LC19 for english and german
