### ISSUE TITLE
[SUGGESTION] | Voidwell is useless

### ISSUE THREAD

**Issue by MrFoxik** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#175]
**DO NOT REMOVE PRE-EXISTING LINES**
----------------------------------------------------------------------------------------------------------
**Describe your suggestion in full detail below:**
That's it, completely useless. Doesn't convert elves into void elves, doesn't give any bonuses, and doesn't have features. Maybe, you should add something? 🤔 
Would be nice, if Voidwell helped Twilight Cultists, to convert elf nation into Shat'yar, whispers of void, and other staff that you get from Voidwell. Huh.

**Comment by zumbak04** [comment]
Implemented! Added modifiers to the Sunwell and the Felwell. Added "Convert High Elves" decision: converts a high elven province if you're a holder or a liege of an active Well building.
