### ISSUE TITLE
Instant Divorce until Pandaria Mist disappear

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1754]
**Your mod version is:**
080b0b690

**What expansions do you have installed?**
All
**Are you using any submods/mods? If so, which?**
Nope
**Please explain your issue in as much detail as possible:**
Everyone in Pandaria get instant divorce until the Mists disappear

**Steps to reproduce the issue:**
Start with standard gamerules and try to marry or get concubine before the Mists disappear

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/89356472-9337d580-d6c6-11ea-86db-ce2a1af16532.png)
![image](https://user-images.githubusercontent.com/46576860/89356494-a64aa580-d6c6-11ea-9010-0db0bf267ec0.png)
![image](https://user-images.githubusercontent.com/46576860/89356510-aba7f000-d6c6-11ea-9410-95a4561641b2.png)

</details>

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/89356562-caa68200-d6c6-11ea-84c5-0c59a1638b75.png)
![image](https://user-images.githubusercontent.com/46576860/89356578-d5f9ad80-d6c6-11ea-99da-6fc855e87968.png)
![image](https://user-images.githubusercontent.com/46576860/89356594-e01bac00-d6c6-11ea-8a92-5042e23bf826.png)
![image](https://user-images.githubusercontent.com/46576860/89356607-e742ba00-d6c6-11ea-87db-e35cedba2906.png)

</details>

**Comment by zumbak04** [comment]
Fixed in a1ff1ff78bf7e316703cb9c29f282662a58de9f7.
