### ISSUE TITLE
[BUG] | Old Gods preferences

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#176]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Yoggy likes concubines and dislike eunuchs. 

**Steps to reproduce the issue:**
Open Yoggy china screen

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_2](https://user-images.githubusercontent.com/46576860/53186718-9d6d2d80-3612-11e9-88ff-ef5a9ef3add4.png)

</details>

**Comment by sejtalk** [comment]
but yoggy loves his concubines :(

**Comment by sejtalk** [comment]
fixed
