### ISSUE TITLE
[BUG] | Kobold in old glade chiefdom is not playable

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#179]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Kobold in old glade chiefdom in 603 is not playable

**Steps to reproduce the issue:**
Load game
YOU NO TAKE CANDLE!﻿

**Upload an attachment below: .zip of your save, or screenshots:**
<details>
<summary>Click to expand</summary>

![67](https://user-images.githubusercontent.com/46576860/53273019-e05afe00-3703-11e9-8482-af738973d9ad.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
