### ISSUE TITLE
[SUGGESTION] | Age Ruler Designer

### ISSUE THREAD

**Issue by Lordmitch** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#180]
**DO NOT REMOVE PRE-EXISTING LINES**
----------------------------------------------------------------------------------------------------------
**Describe your suggestion in full detail below:**
Change or remove max age in the ruler designer.

**Comment by zumbak04** [comment]
It seems to me that it'll be fair to set a limit of 30 since it's a fairly young age for all races.

**Comment by zumbak04** [comment]
> It seems to me that it'll be fair to set a limit of 30 since it's a fairly young age for all races.

Implemented!
