### ISSUE TITLE
Every Yaungol leader in Pandaria has an Emperor Title

### ISSUE THREAD

**Issue by MircoGoA** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1803]
**Your mod version is:**
1.9.0
**What expansions do you have installed?**
All
**Are you using any submods/mods? If so, which?**
Infinite Game and Visible Health and Fertility
**Please explain your issue in as much detail as possible:**
Title
**Steps to reproduce the issue:**

**Upload an attachment below: .zip of your save, or screenshots:**

**Comment by sejtalk** [comment]
That's how nomads work in ck2

**Comment by arithon** [comment]
As sejtalk said. That can't be changed unless nomad system gets reworked.
