### ISSUE TITLE
Two Wastelands

### ISSUE THREAD

**Issue by MircoGoA** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1804]
**Your mod version is:**
1.9.0
**What expansions do you have installed?**
All
**Are you using any submods/mods? If so, which?**

**Please explain your issue in as much detail as possible:**
Zul'mamwe in Stranglethorn and Chaga'jin in Zul'drak are wastelands
**Steps to reproduce the issue:**

**Upload an attachment below: .zip of your save, or screenshots:**

**Comment by zumbak04** [comment]
Fixed this yesterday and updated the download links.
