### ISSUE TITLE
Tor'watha is a wasteland

### ISSUE THREAD

**Issue by MircoGoA** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1805]
**Your mod version is:**
1.9.0
**What expansions do you have installed?**
all
**Are you using any submods/mods? If so, which?**
Infinite Game and Visible Fertility and Health
**Please explain your issue in as much detail as possible:**
Tor'watha (north in amani territory) is a wasteland
**Steps to reproduce the issue:**

**Upload an attachment below: .zip of your save, or screenshots:**

**Comment by zumbak04** [comment]
Fixed this yesterday and updated the download links.
