### ISSUE TITLE
[BUG] | Building chain

### ISSUE THREAD

**Issue by Kyraga** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#181]
**Mod Version**
v1.3
**What expansions do you have installed?**
All of them
**Please explain your issue in as much detail as possible:**
Being stromic Holy Light character and owning a province that has stromic culture and Illidari (Fel) religion allows you to build both "Fel" and "Human" building chain in the same province.
**Steps to reproduce the issue:**
Play as stromic Holy Light character;
Own a province which has stromic culture and Illidari (Fel) religion;
**Upload an attachment below: .zip of your save, or screenshots:**
![ck2_1](https://user-images.githubusercontent.com/1375281/53280954-dc45d500-3731-11e9-906d-f3d6eac1545d.png)

**Comment by zumbak04** [comment]
Screenshots from https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/issues/192
![image](https://user-images.githubusercontent.com/46384992/53351223-4761f800-393a-11e9-9baf-5dbfa1d5b291.png)
![image](https://user-images.githubusercontent.com/46384992/53351231-4af57f00-393a-11e9-83eb-4f34d3bbaf81.png)

**Comment by DukeJeans** [comment]
Fixed in b324003.
