### ISSUE TITLE
[BUG] | Brahmin Pandaren

### ISSUE THREAD

**Issue by Ulthos3** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1819]
**Your mod version is:**
1.9 (after the wasteland fix)
**What expansions do you have installed?**
All.
**Are you using any submods/mods? If so, which?**
GoA Submods:
Models, Music, Music Expansion
Gameplay Mods:
Less Random Deadly Duels, Nicknames+++
Visual Mods:
Bigger Interface, Interface Century Gothic, Interface Stellaris Colors, Orange Ransom, A Revolutionary Borders Mod, A Revolutionary Map Font
**Please explain your issue in as much detail as possible:**
A Sheili Pandaren belonging to Shado-Pan has the Indian Brahmin trait.
**Steps to reproduce the issue:**
Unsure. Even though Pandaren cover half of Pandaria, I've not been able to find any other characters with this trait other than than the one included in the image below.
**Upload an attachment below: .zip of your save, or screenshots:**
![Untitled](https://user-images.githubusercontent.com/69725249/92341631-3a3cd200-f0b6-11ea-9634-76c764275b9f.png)

**Comment by MemeWizard** [comment]
Can confirm - sometimes characters from "recruit court guru"  decision get brahmin trait.

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/92342325-36ff1180-f0c9-11ea-8da0-d12a302526a7.png)

</details>
