### ISSUE TITLE
[BUG] | Player vassal becomes unlanded after liege loses an offensive great war declared by them, leading to a gameover.

### ISSUE THREAD

**Issue by Varus211** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#182]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
Latest Release
**What expansions do you have installed?**
All of them.
**Please explain your issue in as much detail as possible:**
Playing as a vassal under an AI liege, if your liege declares an offensive great war but loses, you become unlanded leading to a game over. 
**Steps to reproduce the issue:**
Be a vassal.
Have liege declare an offensive great war
Have your liege lose.
Game over.
**Upload an attachment below: .zip of your save, or screenshots:**

**Comment by zumbak04** [comment]
Well, it's not a bug, but ok, I'll try to do something with it.

**Comment by zumbak04** [comment]
Player-vassal now becomes independent if player's liege loses "Stop Invader" CB as defender or "Great War" CB as attacker.
