### ISSUE TITLE
[BUG] | Aegwynn dies a natural death in first game months 

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#183]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Aegwynn dies a natural death in first game months 

**Steps to reproduce the issue:**
Launch game

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_7](https://user-images.githubusercontent.com/46576860/53286653-d1676080-3782-11e9-95d6-7fb5a471f024.png)

</details>

**Comment by zumbak04** [comment]
Fixed? It happened because her class trait didn't give immortality. I fixed it, but anyway, there's still a chance to die because she's very old even for mages.
