### ISSUE TITLE
Shenic Faith Triumphant.

### ISSUE THREAD

**Issue by AltertronSteam** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1846]
**Your mod version is:**
1.10.0
**What expansions do you have installed?**
All
**Are you using any submods/mods? If so, which?**
GoA Music and GoA models
**Please explain your issue in as much detail as possible:**
"Shenic" religion automatically becomes triumphant after some time passes in every start date.
In turn, the "titanic" religion becomes a heresy.
**Upload an attachment below: .zip of your save, or screenshots:**
![20210124144503_1](https://user-images.githubusercontent.com/34240986/105632680-bb71e700-5e54-11eb-966b-eb97abacb8b0.jpg)

**Comment by zumbak04** [comment]
Fixed in 18936a80fb424f2a4a797a71f28d0253726a1c25.
