### ISSUE TITLE
[BUG] | Sunwell Cult title got destroyed

### ISSUE THREAD

**Issue by BurnedCrusader** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1847]
**Your mod version is:** 1.10.0

**What expansions do you have installed?** All

**Are you using any submods/mods? If so, which?** Models submod

**Please explain your issue in as much detail as possible:** I was playing as Quel'Thalas as Kael in 605 start date. I was playing normally, when I noticed AI Lor'Theron declaring war on religious head for the Sunwell county. I thought "Eh, he losses land, his problem". Then I see popup about the peace deal and see that previous RH got displaced. I look on the religion screen and I see that there's no RH anymore

**Steps to reproduce the issue:** Play in the 605 start date as Kael and go to Quel'Thalas

**Upload an attachment below: .zip of your save, or screenshots:**
![unknown](https://user-images.githubusercontent.com/59051051/105634218-c8a3cb80-5e7e-11eb-9a57-715d894a5c7a.png)

**Comment by zumbak04** [comment]
Do you have a save?
I need to know what CB Lor'themar used.
I tried to conquer the Sunwell. Nothing happend.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/105861200-e486a900-6007-11eb-9da6-f36c9223db1f.png)

</details>

**Comment by BurnedCrusader** [comment]
Probably was a one time bug, nothing like this happened to me or sunwell cult again
