### ISSUE TITLE
[SUGGESTION] | Larger Political Faction size

### ISSUE THREAD

**Issue by TheJinxleet** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1849]
Pretty self explanatory but it would be nice to see larger options for political faction size I reckon that would require testing though in regards to actual balance but still It'd be nice to see as the alliance and horde should be the two main forces in the world and having them be able to more consistently have members stay in the alliance/horde(mainly an alliance issue because of the relative realm size of some alliance members having more of an impact when they leave)

**Comment by zumbak04** [comment]
> Pretty self explanatory but it would be nice to see larger options for political faction size I reckon that would require testing though in regards to actual balance but still It'd be nice to see as the alliance and horde should be the two main forces in the world and having them be able to more consistently have members stay in the alliance/horde(mainly an alliance issue because of the relative realm size of some alliance members having more of an impact when they leave)

Just to make sure. Do we speak of the political faction size game rule? So you want an option for an even bigger size?
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/106143905-ddd56e80-618c-11eb-8b08-9263a010d73e.png)

</details>

**Comment by TheJinxleet** [comment]
Yeah
