### ISSUE TITLE
[SUGGESTION] Temple Inheritance

### ISSUE THREAD

**Issue by Aszrael** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#185]
**DO NOT REMOVE PRE-EXISTING LINES**
----------------------------------------------------------------------------------------------------------
**Describe your suggestion in full detail below:**
I don't know if this makes a difference, but playing as Stormwind. Every time a temple holder dies the temple reverts back to the top liege. What this does is make the gold that the previous holder has accumulated go to the top liege which results in temples struggling to be upgraded. I would suggest either using the same type of inheritance as city holders or make a way for the liege of the temple holding to be able to choose the next successor. This way the gold accumulated stays with the holding and there is a better chance for them to be upgraded.

**Comment by MemeWizard** [comment]
>Every time a temple holder dies the temple reverts back to the top liege.

Sounds like bug fixed in 700872b

**Comment by Aszrael** [comment]
Ah, I hadn't seen it had already been fixed. Thanks for pointing that out. I'll close this issue then.
