### ISSUE TITLE
[SUGGESTION] | "Bless earth" decision should increase province owner opinion

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#186]
**Describe your suggestion in full detail below:**
"Bless earth" decision should increase province owner opinion.
Right now opinion is not increasing.

<details>
<summary>Click to expand</summary>

![ck2_1](https://user-images.githubusercontent.com/46576860/53299948-51103080-3852-11e9-92ad-15de4a673845.png)
![ck2_2](https://user-images.githubusercontent.com/46576860/53299949-51a8c700-3852-11e9-84e5-ce7ec0ca3372.png)
![ck2_3](https://user-images.githubusercontent.com/46576860/53299950-51a8c700-3852-11e9-93e9-214b0ee35e70.png)

</details>

**Comment by zumbak04** [comment]
Implemented!
