### ISSUE TITLE
[BUG] | "Honor local elemental" decision conditions

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#187]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
"Honor local elemental" decision has 2 similar conditions:
Has personal wealth greater or equal to 50
and
Has personal wealth greater or equal to 25

**Steps to reproduce the issue:**
Play as shamanic char

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_5](https://user-images.githubusercontent.com/46576860/53300133-0f808500-3854-11e9-8f8b-5a6d62927316.png)
![ck2_4](https://user-images.githubusercontent.com/46576860/53300132-0f808500-3854-11e9-967c-155db1038922.png)

</details>

**Comment by sejtalk** [comment]
fixed
