### ISSUE TITLE
40 Year Playthrough As Fel Orcs

### ISSUE THREAD

**Issue by usfshihy** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1872]
So I just finished a nearly 40 year playthrough of the Burning Blade clan in Desolace. My goal was to establish something akin to the Old Horde, visibly consorting with demons and ruling with an iron fist, and while I did have a blast exploring the various events and options that you folk have made for this unique playthrough, there were some problems that eventually forced me to stop the run as a whole. Here's a list of a bunch of them:

- Nomad Agitation is way way too punishing, more than half of the territories in Desolace are nomadic and the idea that I have to pay 450 gold per county to build a castle or a city was insane. Being such a small state meant around 1-2 gold pieces of income monthly and combine that with the idea that I had to wage a new war every year or else risk getting the negative modifier of being a fel worshiper in peace for too long, I usually had around 30-40 gold in my treasury. This was also a problem when it came to titles as I couldn't create any new titles since each cost around 140 gold.

- My court was nearly always empty, I know it makes sense that not many people would like to be in the vicinity of a demonic clan but having only 1 member available for each court decision was too much imo, I had to contend with an average diplomacy value of 3! Now this changed a bit when the Burning Legion invasion began (we'll get back to that) since a load of demons were more than interested to join my court and tbh it felt really cool having a Doomguard, a Succubus, a Satyr and a Dreadlord as my closest advisors, it actually felt that I was on a league of my own visibly consorting with the legion, especially after I realized that the Dreadlord I recruited to my court from a distant realm was no other than the head of the shadow council himself, quite a surprise that was. Final point in this btw, is that I really did love the touch of when the Burning Legion was defeated, my court got blasted with nearly 50 demons, as if they are trying to find a safe, demon friendly, court to escape to after it all went sideways.

- The Summon demon function while very exciting at first, I felt like it was kinda useless tbh. The only real good option was the Succubus since they often had a very high intrigue, in the range of 20s, and made for great spymasters, but other than that, the rest of the options were decent at best. Perhaps it would've been better to make the Felguard be akin to the Succubus as he would probably make for an excellent military commander and warlord in a council. While, the imp could for example allow for certain unique interactions with other characters like stealing artifacts or perhaps cursing someone to bed, something not too far from being imprisoned. More so, perhaps the Felbeast could act as your personal bodyguard making it harder for plots against your life to work. However these options would need for the spell requirements to be revised or otherwise it would be too op I think.

- Soul shards quickly lost their usefulness too, I had 6 in my inventory since draining a soul is a convenient way to kill a prisoner without any of the negative reputation modifiers as I was trying to build my fel power anyway. Perhaps a much more advanced function could be added like Summon Higher Demon which would require the use of 5 soul shards in a ritual to summon a far more menacing being. A Dreadlord for example who can act as an upgraded version of the Succubus, boasting a higher intrigue and being far more ruthless. An Eredar warlock who boasts an exceptionally high Learning and so perfect for the role of warlock in your council chamber. Perhaps even a Pit Lord, I mean why not, the pit lord could act as an insane battle commander who cannot be in your council, where his presence of commanding an army could bridge the gap of 500-1000 soldiers, Mannaroth in the War of the ancients killed hundreds with every swing of his glaive. I can already see the unique interactions appearing of a pit lord commanding my army. Considerable balancing would obviously need to be practiced here, making the cooldown time between each ritual 3-5 years and perhaps allowing only 1 Pit Lord to exist in your army at a time, and making a defeat always resulting in the Pit Lord death, as I can't see something as big as that making an escape.

- A separate but still relevant point is the Shadow Council missions, first of all its almost impossible to find a virgin or a priest in the court I was commanding, I had to marry my vassals and wait for them to have a kid before killing them... yeah it was fucked up. It could use a bit more variety, like recruiting an important member to the Shadow Council or converting a faithful to fel worship and such. I also thought that it could've been really cool if controlled counties can have their unique version of purge population like mass sacrifice to the fel, which could perhaps spawn other unique events.

- It was also nearly impossible to keep good relations with anyone either in the court or outside, you get disliked for being fel, cruel and for the vassals not being in the high council in place of the insanely good demons, and you can't help it, I can only send gifts or award titles every so often and I cannot sway anyone to be my friend because of my fel nature, I ended up with a court of orcs all sharing -50 to -100 opinion of me while the only true loyalist was the Dreadlord I recruited, which is ironic to say the least. This is a larger problem in fact since no one even attempted to communicate with me or deal with me even if I offered them vassalization and they're 5% my size. I don't know how best to fix this problem tbh, perhaps the best way is to counteract it with a dread modifier, making them fear you enough to respect you, that modifier could also be enhanced with having the Felbeast personal bodyguard around you that I mentioned earlier.

- I wished other orcs started embracing high levels of fel corruption on their own, it seems that I had to corrupt every orc to a fel orc by hand, I had hoped that perhaps once they started having Felguards and Dreadlords as their next door neighbors, some will start converting on their own but they didn't, those prejudiced punks! 

- Now let's come back to the Burning Legion invasion; to spare myself from the infighting, I had hoped that I won't have to join them just yet and I could keep working on expanding my lands while the rest of the world fought for survival. I was naïve to say the least, and in 2 months the legion tried to invade me. I do not like the idea of either joining the legion or getting invaded immediately, perhaps a unique chain of events could pop up when the Legion begins their invasion of Azeroth, maybe an uninvited guest would visit my chambers, a Dreadlord, who congratulates me for being such a loyal follower and in his words "bestowes me with the honor" of joining the Legion implying grave consequences if I should turn them away. And perhaps if I do refuse, in typical Nathrezim fashion, I'll start seeing people close to me dying in strange conditions, starting from my advisor, to my wife and perhaps then to my hier, this could really put out the image of fear the Dreadlords are infamous for. Or perhaps another event could spawn, that of a Doomguard marching to my capital with a great horde at his back, demanding that I step down and swear fealty to him and in turn to the Legion or else suffer an early demise, showcasing the less patient and more violent members of the Burning Legion. Now back to the legion invading me, I of course, being the cheater that I am, rolled back to an earlier save and swore fealty to the legion which while it did save me from being invaded, it also meant that I was now part of a large defensive pact against me and I literally could do nothing anymore. Attempting to invade even the tinniest Centaur clan meant that I had to face off with the entirety of Maraudon, something I was just not capable of doing. 

- And so I rolled back my save again and thought of considering other options, and to my surprise I found out that I was capable of swearing fealty and joining either the Qiraji or The Horde of all things, which is very odd. Since the legion goal is to constantly work on stopping the void lords which C'Thun and the Qiraji as a whole are an extension off, it's hard to see how they'll just allow me to join them and I don't think I need to point out how wrong it is for Thrall allowing a fel orc turned demon with a council resembling a circus of the Twisting Nether's best to join him. However even if I did, the same problem showed up as I were now on the back end of large defensive pact that I cannot contend with. This is a more complex problem to solve tbh, and I see this as one of the more major issues currently in the mod as a whole, as in any long playthrough I had nearly the entire world would have joined one of the larger factions around them rather than preferring neutrality.

- On a final and a bit of unrelated note, I have noticed that the naming scheme of the trolls is quite random, some troll kingdoms/empires are named after their tribe while others are named after their capital city. For example, the Gurubashi of Zul'Gurub and the Zandalari of Zuldazar are named after their tribe names (Gurubashi and Zandalari), while others like the Sunfury of Zul'Farrak(The shining jewel of Tanaris) or the Amani of Zul'Aman are named after their capital cities (Zul'Farrak and Zul'Aman).

This has been a very long post, but I have worked on other projects such as this before and I often found long playthrough sessions to have invaluable information and so I hope this can offer you a few unique ideas, thanks!

**Comment by zumbak04** [comment]
Could you split it into a few suggestions, There are too many of them, I can't set any kind of priority.

**Comment by usfshihy** [comment]
> Hello! Could you split it into a few suggestions? There are too many of them, I can't set any kind of priority.

coming right up
