### ISSUE TITLE
[BUG] | Adoption of black pact don't destroy faction(?) title

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#188]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
If orcish Horde create the Horde and then adopt black pact, the Horde title will be destroyed.
However, if orcish Horde don't create the Horde, the Horde title will not be destroyed.

**Steps to reproduce the issue:**
Create the Horde (or don't)
Adopt black pact
Horde will be destroyed (or not, if you don't created the Horde)

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_1](https://user-images.githubusercontent.com/46576860/53301120-009fcf80-3860-11e9-833b-137a4239dbb2.png)
![ck2_2](https://user-images.githubusercontent.com/46576860/53301121-009fcf80-3860-11e9-9c93-b24b67529e6e.png)
![ck2_3](https://user-images.githubusercontent.com/46576860/53301122-01386600-3860-11e9-929f-f2267eae16d6.png)
![ck2_6](https://user-images.githubusercontent.com/46576860/53301124-70ae5580-3860-11e9-9239-7c0479249183.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
