### ISSUE TITLE
Everyone has turned into Harpies and other sorts of creatures

### ISSUE THREAD

**Issue by Varallios** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1885]
**Your mod version is:**
1.10.0

**What expansions do you have installed?**
Sword of Islam, Legacy of Rome, The Republic, The Old Gods, Sons of Abraham, Charlemagne, Way of Life, Conclave, The Reaper's Due, Monks and Mystics, Jade Dragon and Holy Fury (I don't have Sunset Invasion, Rajas of India and Horse Lords)

**Are you using any submods/mods? If so, which?**
I am only using the music + models submod for GoA

**Please explain your issue in as much detail as possible:**
I started in the Reign of Chaos bookmark as Arthas Menethil and played my campaign (not as Scourge) up until the date xx.march.809, after which the game kept crashing and I started playing base ck2 with other submods - what ended up happening as I came back was that everyone has turned into all sorts of creatures from Kalimdor and other places, and all humans have turned into bronze drakes! Very confusing

**Steps to reproduce the issue:**
Not entirely sure, but I played the mod with only the music and models submod, then switched to play ck2 with other submods like "Customize Appearance". When I came back to the GoA mod (I deactivated all other submods and reactivated the music and models), everyone turned into random creatures

**Upload an attachment below: .zip of your save, or screenshots:**
https://gyazo.com/196ba16e80233f7603501d8b0532b2c9 Kael the Qiraji

https://gyazo.com/bfdd4f24504b313b9cba3951856d07a3 Old Terenas the Bronze Wyrm, who also for some reason has Islamic and Zoroastrian traits

https://gyazo.com/c644b19833ee0d28f657545e26978ec8 My great grandfather suddenly became a muslim bronze dragon eunuch, and a death knight 

https://gyazo.com/18e8f85ea685b5a80c418db5150865ec This goblin is both a harpy AND a saurok! Wow!!! interesting family

**Comment by Varallios** [comment]
Sorry if this doesn't help much, I am just awed at how odd this is xD

**Comment by zumbak04** [comment]
> I deactivated all other submods and reactivated the music and models

Check it again. The thing you described happens when you load a savegame with a different set of mods.
Maybe you actually played with Customize Appearance originally thus when you disabled it traits broke.
