### ISSUE TITLE
random incorrect traits and modifiers are given to players/npcs

### ISSUE THREAD

**Issue by JordanB500** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1886]
i started playing a qiraji ruler but was randomly given the traits Demon and eagle warrior(ck2)

my goa version is 10.1.0(i think) and i used the models/music as well as the darkmoon faire submod, the other submods would not work

**Comment by zumbak04** [comment]
You started a new game or loaded a save?

**Comment by JordanB500** [comment]
I started a new game as custom start playing as terezok sargonid of scarab wall

**Comment by zumbak04** [comment]
> I started a new game as custom start playing as terezok sargonid of scarab wall

Try to disable submods, this issue isn't reproducible on a clear GoA version.

**Comment by JordanB500** [comment]
this seems to fix the issue
