### ISSUE TITLE
Issue Title

### ISSUE THREAD

**Issue by JordanB500** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1888]
**Your mod version is:** 1.10.0

**What expansions do you have installed?** what means expansions?

**Are you using any submods/mods? If so, which?**
darkmoon faire/leafwalker

**Please explain your issue in as much detail as possible:**
almost all npcs and even my own character keep recieving incorrect traits such as demon, tol'vir when im not playing as either and also some base game traits etc

**Steps to reproduce the issue:**
play the game as is(occurs when reloading a save or just by playing)

**Upload an attachment below: .zip of your save, or screenshots:**
![New Bitmap Image (12)](https://user-images.githubusercontent.com/9001280/123850501-b7546480-d8df-11eb-8656-8aed153adcc8.jpg)

**Comment by zumbak04** [comment]
https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/issues/1886#issuecomment-869106118
