### ISSUE TITLE
[BUG] | Former faction members keeps alliances

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#189]
**Mod Version**
Sixth Bug Crusade

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Former faction members keeps alliances after leaving faction

**Steps to reproduce the issue:**
Faction member must be conquered by Lich-King

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_4](https://user-images.githubusercontent.com/46576860/53303082-38fed800-3877-11e9-981b-58204786421c.png)

</details>

**Comment by zumbak04** [comment]
Fixed!

**Comment by MemeWizard** [comment]
**Mod Version**
6aaaf9ea

**What expansions do you have installed?**
All

**Steps to reproduce the issue:**
Load save

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/61306623-a1822d80-a7f5-11e9-9102-f916f9397df0.png)
![image](https://user-images.githubusercontent.com/46576860/61306640-a6df7800-a7f5-11e9-95a6-54f6179a08fb.png)

</details>

[Stromgarde608_06_17.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3397784/Stromgarde608_06_17.zip)

**Comment by zumbak04** [comment]
Fixed!
