### ISSUE TITLE
No Female horde ruler title

### ISSUE THREAD

**Issue by Lordmitch2** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1894]
**Mod version:**
Master
**Are you using any submods/mods? If so, which?**
No
**Please explain your issue in as much detail as possible:**
There is no female title for a female ruler of the horde
**Upload screenshots of the problem localization:**
![image](https://user-images.githubusercontent.com/47829580/127916112-99ebb7c6-1109-448b-a13f-ec39dc492c27.png)

**Comment by zumbak04** [comment]
Fixed!
