### ISSUE TITLE
Unfriendly and Friendly Spirits Bug

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#19]
Master branch
Medium

Spirits can be friendly and unfriendly at the same time. I also notice that the modifier "unfriendly spirits" sometimes appears in the province by itself, without notifying me.

<details>
  <summary>Click to expand</summary>

![ck2_1](https://user-images.githubusercontent.com/46576860/51352008-6eb4e200-1abd-11e9-91ca-a885fcf03c16.png)
![ck2_2](https://user-images.githubusercontent.com/46576860/51352009-6eb4e200-1abd-11e9-88de-f4374917f950.png)

</details>

**Comment by sejtalk** [comment]
fixed
