### ISSUE TITLE
[BUG] | Defender in "Stop Invader" war lose prestige at win

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#190]
**Mod Version**
Sixth Bug Crusade

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Defender in "Stop Invader" war lose prestige at win

**Steps to reproduce the issue:**
Look at "surrender" tooltip as attacker in "Stop Invader" war.

**Upload an attachment below: .zip of your save, or screenshots:**
<details>
<summary>Click to expand</summary>

![ck2_1](https://user-images.githubusercontent.com/46576860/53303203-be36bc80-3878-11e9-930e-aa9a74a63cf6.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
