### ISSUE TITLE
[BUG] | Leaving faction don't gives you opinion penalty with faction members

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#191]
**Mod Version**
Sixth Bug Crusade

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
IIRC, leaving faction must give you opinion penalty with faction members, but for some reason this is not happening.

**Steps to reproduce the issue:**
Leave faction

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_2](https://user-images.githubusercontent.com/46576860/53303321-17532000-387a-11e9-9310-c64652a82f27.png)
![ck2_3](https://user-images.githubusercontent.com/46576860/53303322-17ebb680-387a-11e9-8110-d9f8bbe44d6b.png)
![ck2_4](https://user-images.githubusercontent.com/46576860/53303323-17ebb680-387a-11e9-8195-622977544bd5.png)

</details>

**Comment by zumbak04** [comment]
Now it gives bad opinion if you leave faction.
