### ISSUE TITLE
[BUG] | Human buildings in legion holdings

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#192]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
You can (actually can't, because you can't build required buildings) build some human buildings in legion provinces with human culture

**Steps to reproduce the issue:**
Play as legion corrupted human 

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_1](https://user-images.githubusercontent.com/46576860/53304349-3d31f200-3885-11e9-9b2d-3c5972d2273f.png)
![ck2_2](https://user-images.githubusercontent.com/46576860/53304350-3d31f200-3885-11e9-819d-b97a477e238a.png)

</details>

**Comment by Kyraga** [comment]
https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/issues/181

**Comment by zumbak04** [comment]
I posted these screenshots in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/issues/181 and closing this issue.
