### ISSUE TITLE
Elves dying "naturally" at age 33 to around 50.

### ISSUE THREAD

**Issue by ajjr1996** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#193]
Doesn't happen to all of them. It's just strange as I believed they were immortal to a sense but I'm not for sure. It didn't say they had any diseases or anything it was just a random "natural" death at such a young age. Do you think they may have been assassinated?

**Comment by zumbak04** [comment]
What is your version of the mod?

**Comment by ajjr1996** [comment]
1.3, latest version.

**Comment by zumbak04** [comment]
Fixed? Added +2 heath to long-lived races to lower their chances of natural death.
