### ISSUE TITLE
[BUG] | High Elf Ruler Designer

### ISSUE THREAD

**Issue by Lotharingia** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#194]
**Mod Version**
v1.3

**What expansions do you have installed?**
All Expansions

**Please explain your issue in as much detail as possible:**
Crash upon selecting High Elf Ethinicity in Ruler Designer or opening Ruler Designer as existing High Elf character.

**Steps to reproduce the issue:**
Same as above

**Upload an attachment below: .zip of your save, or screenshots:**
Well, it just CTD without any notification window informing cause of crash.

**Comment by zumbak04** [comment]
This issue is known and fixed!
https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/issues/171
