### ISSUE TITLE
[LOCALIZATION] | Sisterhood of Elune localization

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#198]
**Mod Version**
Sixth Bug Crusade

**Please explain your issue in as much detail as possible:**
No or wrong loc

**Upload screenshots of the problem localization:**

Abilities desc
<details>
<summary>Click to expand</summary>

![ck2_17](https://user-images.githubusercontent.com/46576860/53373204-df290b80-3965-11e9-8072-437d2637188b.png)
![ck2_18](https://user-images.githubusercontent.com/46576860/53373205-dfc1a200-3965-11e9-833d-6bbab77e940a.png)
![ck2_19](https://user-images.githubusercontent.com/46576860/53373207-dfc1a200-3965-11e9-8ef4-9675cb414511.png)

</details>

High Priestess is called "Archdruid"

<details>
<summary>Click to expand</summary>

![ck2_7](https://user-images.githubusercontent.com/46576860/53388944-3f3ba400-399e-11e9-85ab-007d6822f762.png)

</details>

Double "A" in tooltip

<details>
<summary>Click to expand</summary>

![ck2_3](https://user-images.githubusercontent.com/46576860/53389046-ad806680-399e-11e9-83d1-b8792cad3341.png)

</details>

**Comment by sejtalk** [comment]
fixed everything but vanilla bug
