### ISSUE TITLE
[BUG] | "Touch of Elune" don't give opinion boost

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#199]
**Mod Version**
Sixth Bug Crusade

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
"Mark of Light" raise character opinion of you, but "Touch of Elune" don't.

**Steps to reproduce the issue:**
Cast "Touch of Elune" on char

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_20](https://user-images.githubusercontent.com/46576860/53373750-65921d00-3967-11e9-84c7-4ac668882dd5.png)
![ck2_21](https://user-images.githubusercontent.com/46576860/53373751-662ab380-3967-11e9-929b-921502e981a6.png)

</details>

**Comment by sejtalk** [comment]
fixed
