### ISSUE TITLE
Characters spawning without the race trait

### ISSUE THREAD

**Issue by MiguelVitta** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#20]
I was playing Durotan, decided to go north, and settled on the coast of northend. Had to hire commanders, holy men and debutants. After some time, 6 years in game, I noticed the courtiers started to spawn without the race trait (creature_orc), and had to add the trait myself. 
After a year or so, the horde was destroyed and some 300 orc characters went to my court (as I was the only orc kingdom, due to the invasion failing, I presume), and I perceived that a minority also hadn't the orc trait. 
This failed character have the correct portraits, but not the trait. I didn't see any child without the trait, neither the ones born on my court, neither the ones arriving with the orc exodus.

**Comment by MiguelVitta** [comment]
Sorry, I didn't know, and didn't wait too. not a problem. And I confirmed that after a time they get the right trait. Thanks for your time. and let me congratulat you on the work you are doing on the military part of the mod, combat tatics, retinues, special troops, etc. I took a look and I am impressed and anxious to play with the new additions.

**Comment by zumbak04** [comment]
No problems. Thanks you for reporting. This's very important for further development.
