### ISSUE TITLE
[LOCALIZATION] | Society leader titles don't have descriptions

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#202]
**Mod Version**
bug-crusade-6

**Please explain your issue in as much detail as possible:**
Society leader titles don't have descriptions

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![ck2_8](https://user-images.githubusercontent.com/46576860/53387408-c3d6f400-3997-11e9-8737-80861293a710.png)
![ck2_18](https://user-images.githubusercontent.com/46576860/53387388-b588d800-3997-11e9-8940-1c5e7f1819d5.png)
![ck2_19](https://user-images.githubusercontent.com/46576860/53387389-b588d800-3997-11e9-98ea-7b6b30dfe70c.png)
![ck2_20](https://user-images.githubusercontent.com/46576860/53387390-b6216e80-3997-11e9-95c2-07a83120bfe1.png)
![ck2_21](https://user-images.githubusercontent.com/46576860/53387491-216b4080-3998-11e9-8791-46a8b1c5439f.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
