### ISSUE TITLE
[SUGGESTION] | Sisterhood of Elune background is too bright

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#203]
**Describe your suggestion in full detail below:**
Srsly, this brightness hurts my eyes.

<details>
<summary>Click to expand</summary>

![ck2_5](https://user-images.githubusercontent.com/46576860/53388499-727d3380-399c-11e9-845f-de2e4e706087.png)

</details>

**Comment by sejtalk** [comment]
I guess it depends on the type of monitor you have. Looks ok on mine.

**Comment by MemeWizard** [comment]
>  sejtalk closed this 2 minutes ago

It's still painfully bright
Moreover, white text on white background is really difficult to read
