### ISSUE TITLE
[LOCALIZATION] | Wrong tooltip

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#204]
**Mod Version**
bug-crusade-6

**Please explain your issue in as much detail as possible:**
Tooltip says that memer of society have -50% to memer score because [GetSheHe] is a [GetClass], but actually that memer of society have -50% to memer score because [GetSheHe] don't have a [GetClass] trait.

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![ck2_22](https://user-images.githubusercontent.com/46576860/53388609-d142ad00-399c-11e9-843c-63902638c5da.png)
![ck2_23](https://user-images.githubusercontent.com/46576860/53388608-d142ad00-399c-11e9-958d-c41bf0d3e7f4.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
