### ISSUE TITLE
[BUG] | Holy orders succession switch

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#205]
**Mod Version**
bug-crusade-6

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
After death of the first holy order grand master, gender succession law in that order switch from absolute cognatic to agnatic

**Steps to reproduce the issue:**
Kill holy order grand master

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_18](https://user-images.githubusercontent.com/46576860/53390222-8a0bea80-39a3-11e9-8385-b6f0c40fc78d.png)
![ck2_21](https://user-images.githubusercontent.com/46576860/53390233-942de900-39a3-11e9-9829-16b8c5d3997c.png)
![ck2_8](https://user-images.githubusercontent.com/46576860/53390223-8a0bea80-39a3-11e9-90b1-e3c392a870b7.png)
![ck2_20](https://user-images.githubusercontent.com/46576860/53390232-93955280-39a3-11e9-804c-9d00bb307b2e.png)

</details>

**Comment by MemeWizard** [comment]
OOOPS

**Comment by zumbak04** [comment]
Fixed!
