### ISSUE TITLE
[BUG] | NE mans can be priestesses

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#206]
**Mod Version**
bug-crusade-6

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
NE priests have "moon priestess" trait

**Steps to reproduce the issue:**
Spawn NE with priest trait

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_24](https://user-images.githubusercontent.com/46576860/53422784-2b6d5d80-39f1-11e9-9626-098c724c8e8b.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
