### ISSUE TITLE
[LOCALIZATION] | Immortals worry about leaving this earthy realm

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#207]
**Mod Version**
bug-crusade-6

**Please explain your issue in as much detail as possible:**
Immortal races don't have to worry about not having enough time to write a book, no?

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![ck2_20](https://user-images.githubusercontent.com/46576860/53424377-21009300-39f4-11e9-9659-b2e85c3b00f4.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
