### ISSUE TITLE
[BUG] | Fifth society rank don't have icon

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#208]
**Mod Version**
bug-crusade-6

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Fifth society rank don't have icon

**Steps to reproduce the issue:**
Look at society (CC/SoH) screen

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_3](https://user-images.githubusercontent.com/46576860/53425458-134c0d00-39f6-11e9-8466-8235234becad.png)
![ck2_5](https://user-images.githubusercontent.com/46576860/53425466-17782a80-39f6-11e9-99c3-dfb2ae7b9f90.png)

</details>

**Comment by sejtalk** [comment]
fixed
