### ISSUE TITLE
[BUG] | Priest description is wrong

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#209]
**Mod Version**
bug-crusade-6

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Priest description says that priest can heal deadly diseases, but actually don't have such ability.

**Steps to reproduce the issue:**
Look at priest description

**Upload an attachment below: .zip of your save, or screenshots:**
<details>
<summary>Click to expand</summary>

![ck2_12](https://user-images.githubusercontent.com/46576860/53425985-2ad7c580-39f7-11e9-9afb-f7c8afe1e21f.png)

</details>

**Comment by zumbak04** [comment]
Fixed! The part about "deadly diseases" is removed.
