### ISSUE TITLE
[BUG] | Lustful NE

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#210]
**Mod Version**
Bug-crusade-6

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
MY LOINS ARE ON FIRE

**Steps to reproduce the issue:**
Your NE must have chaste trait and pick theology focus

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_16](https://user-images.githubusercontent.com/46576860/53426720-95d5cc00-39f8-11e9-9733-6fe0773ddf4c.png)

</details>

**Comment by zumbak04** [comment]
I didn't get it. What is wrong?

**Comment by MemeWizard** [comment]
>Chaste is not virtue and lust in not sin in warcraft lore

Okay, not bug.
