### ISSUE TITLE
[LOCALIZATION] | Unnecessary dots in text

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#211]
**Mod Version**
bug-crusade-6

**Please explain your issue in as much detail as possible:**
>EVTOPTC_WCUND_300;Raise [From.GetHerHim] as a death knight\n;;;;;;;;;;;;;x

**Upload screenshots of the problem localization:**
<details>
<summary>Click to expand</summary>

![ck2_6](https://user-images.githubusercontent.com/46576860/53427142-6e333380-39f9-11e9-8b8c-025409e3a9c3.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
