### ISSUE TITLE
[BUG] | Ancients can be invited to carousing

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#212]
**Mod Version**
bug-crusade-6

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Ancients can be invited to carousing

**Steps to reproduce the issue:**
Pick carousing focus

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_22](https://user-images.githubusercontent.com/46576860/53429567-f61b3c80-39fd-11e9-9c7d-f413fc311199.png)

</details>

**Comment by sejtalk** [comment]
fixed
