### ISSUE TITLE
[BUG/SUGGESTION] | Cites and Theocracies in Quel'Thalas

### ISSUE THREAD

**Issue by estacnhin** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#213]
**DO NOT REMOVE PRE-EXISTING LINES**
----------------------------------------------------------------------------------------------------------
**Describe your suggestion in full detail below:**
In the campaign for Quel'Thalas the Scourge annexed kingdom Tranquilein. 
After retaking it, I wanted to return all titles to the previous owners. The problem is the number of city and temple vassals in the country. It's said that that number limited to 10% of all.
But in Quel'Thalas there are many more such vassals from the beginning and I just couldn't do that.

**Comment by zumbak04** [comment]
This is vanilla restriction. You can change it in the game rules. As I know, in any case, you can grant province to character who isn't ruler of republic and not in court of republican ruler.
