### ISSUE TITLE
[BUG] | "%Elemental% curse" modifier color

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#216]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
"%Elemental% curse" is negative modifier, but instead of "negative red" color, have "positive green" color.

**Steps to reproduce the issue:**
Make elemental angry and look at modifier color

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_1](https://user-images.githubusercontent.com/46576860/53659256-249e4f00-3c6c-11e9-9799-d3836c6324e5.png)

</details>

**Comment by sejtalk** [comment]
fixed
