### ISSUE TITLE
[BUG] | Vanilla religions are visible

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#217]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Vanilla religions are still visible in ledger and religion groups are still visible in ruler designer.

**Steps to reproduce the issue:**
Open ledger or choose religion in ruler designer

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![default](https://user-images.githubusercontent.com/46576860/53671502-b5d2ed00-3c8f-11e9-84fc-ad405dc6160a.png)
![ck2_1](https://user-images.githubusercontent.com/46576860/53671503-b66b8380-3c8f-11e9-92cd-469f4c747f33.png)

</details>

**Comment by zumbak04** [comment]
It's not a bug if you can't pick them. They're needed to prevent problems with vanilla events and decisions.

**Comment by MemeWizard** [comment]
S A D
