### ISSUE TITLE
The new leader of the faction

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#22]
Master branch
High (?)

Localization says that the new leader of the faction should be the most powerful member, but the game chooses not the most powerful member of the faction.

<details>
  <summary>Click to expand</summary>

![ck2_3](https://user-images.githubusercontent.com/46576860/51386003-f9cfbf80-1b31-11e9-8ded-47f0f0efca16.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
