### ISSUE TITLE
[BUG] | Ships are stuck

### ISSUE THREAD

**Issue by DesuBalo** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#220]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.3.1

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
In the provinces of Natha'vor and Kel'vax (Zandalar) ships can be made, but can't be moved as it says "No valid path to this province". They cannot be taken out of the port.

**Steps to reproduce the issue:**

**Upload an attachment below: .zip of your save, or screenshots:**
https://i.imgur.com/hPIU4gS.png

**Comment by zumbak04** [comment]
Fixed!
