### ISSUE TITLE
[LOCALIZATION] | Offmap interface

### ISSUE THREAD

**Issue by DesuBalo** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#221]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.3.1
**Please explain your issue in as much detail as possible:**
Small text problem in the N'Zoth Empire menu - "chinese emperor" is not changed, weird text appears in the policies and the Boon says "Grace" instead of "Insanity".
**Upload screenshots of the problem localization:**
![image](https://user-images.githubusercontent.com/46384992/56867336-0d25dd00-69f5-11e9-8ff5-4d17fc9d9c8b.png)
![image](https://user-images.githubusercontent.com/46384992/56867342-2f1f5f80-69f5-11e9-9137-ba56600a3460.png)
![image](https://user-images.githubusercontent.com/46384992/56867354-4cecc480-69f5-11e9-825a-a5c93578c334.png)
![image](https://user-images.githubusercontent.com/46384992/56867393-a523c680-69f5-11e9-85e5-3a316e4da576.png)

**Comment by sejtalk** [comment]
fixed
