### ISSUE TITLE
[LOCALIZATION] | Fury of the wolf

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#222]
**Mod Version**
Master barnch

**Please explain your issue in as much detail as possible:**
Non-cap "he" and king sending news to the king.

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![ck2_1](https://user-images.githubusercontent.com/46576860/53772633-23815200-3ef8-11e9-9136-99e15a160eac.png)
![ck2_2](https://user-images.githubusercontent.com/46576860/53772671-5297c380-3ef8-11e9-9c45-f38ab0f884a5.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
