### ISSUE TITLE
[LOCALIZATION] | INVADER_INFAMY

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#223]
**Mod Version**
Master branch

**Please explain your issue in as much detail as possible:**
No loc for INVADER_INFAMY threat modifier

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![ck2_3](https://user-images.githubusercontent.com/46576860/53856635-c95dbb00-3fe3-11e9-985d-42d0516a68e6.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
