### ISSUE TITLE
[BUG] | Genn Greymane portrait bug

### ISSUE THREAD

**Issue by TheGuyNamedMoney** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#227]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
CK2 3.0.x Official 1.3.1 Version of Guardians of Azeroth. as released on 03/02/2019
**What expansions do you have installed?**
I currently own and have all expensions installed, the only one i do not have is the Barber DLC, which let's one change hairstyles, etc
**Please explain your issue in as much detail as possible:**
I was playing as Genn Graymane from the first war start (583) But by the point i got to april 12 in 599 (also the date he turns 60) His fancy new portrait al0bgc0000000000000000000d Turned into a standard elderly Gilnean Human king. Instead of his 603 start apperance al0bgc0000000000000000000e where he has a silver-brown coat and white hair.
**Steps to reproduce the issue:**
To recreate the issue. Start up a game, starting from the first war 583, and let it play till 599 april 12th, where Genn will turn into a standard human portrait, instead of his own custom one.
**Upload an attachment below: .zip of your save, or screenshots:**

**Comment by sejtalk** [comment]
fixed
