### ISSUE TITLE
Bless province - localization

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#23]
Master branch
Low

The bless province event says that the druid's power increases soil fertility, but my character is a shaman, not a druid.

<details>
  <summary>Click to expand</summary>

![ck2_6](https://user-images.githubusercontent.com/46576860/51386744-985d2000-1b34-11e9-9f1a-34f4fb1c353e.png)

</details>

**Comment by DukeJeans** [comment]
Localisation adjusted. *Your powers have greatly increased the soil fertility of this region for several years*

**Comment by MemeWizard** [comment]
<details>
<summary>Click to expand</summary>



</details>

**Comment by MemeWizard** [comment]
>earths_blessing_desc;Bless the earth of this province using Nature or Elemental magics.;;;;;;;;;;;;;x
EVTDESC_WCCLS_810_another;Using Nature or Elemental magics, [FromFrom.GetTitledFirstName] has blessed the earth of the province of [target_province.GetName]. Your powers have greatly increased the soil fertility of this region for several years.;;;;;;;;;;;;;x
EVTDESC_WCCLS_810_yourself;Using Nature or Elemental magics, you have blessed the earth of the province of [target_province.GetName]. The power of the druid greatly increased soil fertility for several years.;;;;;;;;;;;;;x

I think wrong line was edited
<details>
<summary>Click to expand</summary>

![ck2_3](https://user-images.githubusercontent.com/46576860/52877221-73c38a80-316a-11e9-875b-d8253a5bdb1b.png)

</details>

**Comment by zumbak04** [comment]
These both localization were edited...
> Magical powers have greatly increased the soil fertility of this region for several years.

This description seems pretty universal.
