### ISSUE TITLE
[BUG] | Undead vassals opinion

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#232]
**Mod Version**
Master Branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Your character is unhappy that his vassal is undead, even if necromancy is allowed in your realm or your char himself turned his vassal into undead.

**Steps to reproduce the issue:**
Turn your vassal undead

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_2](https://user-images.githubusercontent.com/46576860/54148087-a0ef1a00-4444-11e9-99ba-6f3454adf654.png)
![ck2_17](https://user-images.githubusercontent.com/46576860/54148096-a51b3780-4444-11e9-97f7-0d253b5b88c8.png)

</details>

**Comment by zumbak04** [comment]
It was tough, but I fixed it!

> Character no longer show emotional reaction when its vassal, spouse, child etc. turns either demon, undead, void being if it's normal because of its religion or "Status of Magic" laws.
