### ISSUE TITLE
[BUG] | DK education

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#233]
**Mod Version**
Master Branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
>You can not learn to be DK - Zumbak

**Steps to reproduce the issue:**
Ask DK mentor to educate your char

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_16](https://user-images.githubusercontent.com/46576860/54148978-4d7dcb80-4446-11e9-94c7-d811dd3378de.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
