### ISSUE TITLE
[BUG] | Succession law changed after heir's birth

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#234]
**Mod Version**
Master Branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Kingdom succession law is tanistry, but duchy law is primogeniture. After heir's birth, duchy law become tanistry too.

**Steps to reproduce the issue:**
Start as Zul'jin and get a heir

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_3](https://user-images.githubusercontent.com/46576860/54149344-f298a400-4446-11e9-9e69-707ccc64b687.png)
![ck2_4](https://user-images.githubusercontent.com/46576860/54149345-f298a400-4446-11e9-9220-23f792476464.png)
![ck2_5](https://user-images.githubusercontent.com/46576860/54149347-f3313a80-4446-11e9-8c3c-34afe45e9912.png)

</details>

**Comment by zumbak04** [comment]
It's a vanilla bug. Actually, you have Tanistry, but it says that you have Primogeniture.
![image](https://user-images.githubusercontent.com/46384992/54167533-9a33c780-4483-11e9-9e3f-4741641680cd.png)
