### ISSUE TITLE
[LOCALIZATION] | Tooltips

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#235]
**Mod Version**
Master Branch

**Please explain your issue in as much detail as possible:**
No loc for tooltips

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![ck2_1](https://user-images.githubusercontent.com/46576860/54209141-49a58400-44ee-11e9-95ef-a604e3c75576.png)
![ck2_2](https://user-images.githubusercontent.com/46576860/54209142-4a3e1a80-44ee-11e9-88ca-a855145ebe38.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
