### ISSUE TITLE
[BUG] | Landless non-dragon dragons

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#238]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
If non-dragon converts to dragon religion and culture, his government type become landless

**Steps to reproduce the issue:**
Swear fealty to a dragonflight and convert your char to dragon religion and culture

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_2](https://user-images.githubusercontent.com/46576860/54303426-ff96ce00-45d3-11e9-9773-e8476855680b.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
