### ISSUE TITLE
[BUG] | Wrong trigger conditions

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#239]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
"Can marry or have sexual relationship" trigger turns false if character has a betrothal

**Steps to reproduce the issue:**
Chose family focus and arrange betrothal
Focus will be cleared

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_1](https://user-images.githubusercontent.com/46576860/54378089-92e50780-4697-11e9-90e0-9f342fae5bf0.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
