### ISSUE TITLE
Conquest CB description talk about norse pagans

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#24]
Master branch
Low

Conquest CB description talk about norse pagans.

<details>
  <summary>Click to expand</summary>

![ck2_11](https://user-images.githubusercontent.com/46576860/51387055-bd9e5e00-1b35-11e9-9696-70c0ffd3ffbe.png)

</details>

**Comment by MemeWizard** [comment]
Fixed in 85d6b42

**Comment by zumbak04** [comment]
Yep, I'm closing this issue then.
