### ISSUE TITLE
[LOCALIZATION] | Wolvar death

### ISSUE THREAD

**Issue by Domi2333** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#240]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.3.1
**Please explain your issue in as much detail as possible:**
My wolvar character died, and the text had localization problems.
**Upload screenshots of the problem localization:**
![image](https://user-images.githubusercontent.com/46266806/54429958-4eeb1480-4722-11e9-9395-d249c2415793.png)

**Comment by zumbak04** [comment]
Weird. creature_wolvar_death was localized in 1.3.1 and it looks good in my version.
![image](https://user-images.githubusercontent.com/46384992/54560812-9ac8e280-49dc-11e9-970d-5aeba57b2827.png)
Could you leave your checksum here? It should be CLFQ.

**Comment by Domi2333** [comment]
Well, I may or may not have downloaded a probably but not certainly pirate version of the game because I do not own some DLCs needed for the mod to work properly. But the weird thing is that my legal one does not have the right checksum as well. (the not so legal one has PXTU, and the legal one has ONDO)
![image](https://user-images.githubusercontent.com/46266806/54618770-d6f35600-4a63-11e9-991c-daa11c481b60.png)

**Comment by MemeWizard** [comment]
Understandable. Have a great day.

**Comment by zumbak04** [comment]
The very last comment. I doubt it's because of the pirate version. Better reinstal [the last mod patch](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/releases/tag/v.1.3.1).
