### ISSUE TITLE
[BUG] | Boats from Shadowhoof cannot move

### ISSUE THREAD

**Issue by lukej200** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#244]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.0
**What expansions do you have installed?**
All of them
**Please explain your issue in as much detail as possible:**
Boats I've raised from the county Shadowhoof are unable to move into any other sea tiles.
**Steps to reproduce the issue:**
Raise ships in the county Shadowhoof, then try to move them.
[Save.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/2980613/Save.zip)

**Upload an attachment below: .zip of your save, or screenshots:**

**Comment by zumbak04** [comment]
Fixed in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/commit/102a3e508e4eee90804af03c5f6d7fd76fc0fd7d
