### ISSUE TITLE
[BUG] | Incorrect place for harbour

### ISSUE THREAD

**Issue by estacnhin** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#246]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.3.1
**What expansions do you have installed?**
All
**Please explain your issue in as much detail as possible:**
Locations for 2 shipyards in Quel'Thalas are not good. They are Falconwing Square and Sunsail Anchorage
**Steps to reproduce the issue:**
Change location for ships
**Upload an attachment below: .zip of your save, or screenshots:**
![image](https://user-images.githubusercontent.com/22888112/54845875-9b6abd00-4ceb-11e9-9e04-2fb1392eeabd.png)

**Comment by zumbak04** [comment]
Fixed in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/pull/229/commits/102a3e508e4eee90804af03c5f6d7fd76fc0fd7d
