### ISSUE TITLE
[LOCALIZATION] | No loc for WCCC.20

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#248]
**Mod Version**
Master Branch

**Please explain your issue in as much detail as possible:**
No loc for WCCC.20

**Steps to reproduce the issue:**
Leave Cenarion Circle (Society) while playing as Cenarion Circle (Title)

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![ck2_3](https://user-images.githubusercontent.com/46576860/54911000-82862580-4efe-11e9-8ef6-eb78b4d20496.png)

</details>

**Comment by sejtalk** [comment]
fixed
