### ISSUE TITLE
[BUG] | Game put non-kaldorei druids into Cenarion Circle

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#249]
**Mod Version**
Master Branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Sometimes the game places druids with non-kaldorei religion in the Cenarion Circle.
However, such characters cannot see the Cenarius Сircle in the list of available societies.

**Steps to reproduce the issue:**
No conditions, just restart the game until the bug appears.

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_2](https://user-images.githubusercontent.com/46576860/54911260-1f48c300-4eff-11e9-8846-ba34d1a1c71e.png)
![ck2_1](https://user-images.githubusercontent.com/46576860/54912412-a6973600-4f01-11e9-9a8a-18cb0aa40b50.png)
![ck2_4](https://user-images.githubusercontent.com/46576860/54912430-adbe4400-4f01-11e9-8a8e-d569bc9d6363.png)

</details>

**Comment by sejtalk** [comment]
fixed
