### ISSUE TITLE
Missing Trollbane Dynasty CoA

### ISSUE THREAD

**Issue by Feliprins** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#25]
Which version of the mod does this apply to?
1.2
How important is this bug/suggestion (Low/Medium/High/Critical)?
Low
Explain the bug or suggestion below:
Trollbane Dynasty coat of arms is not assigned correctly 
Feel free to attach a **.zip** or a **screenshot** of the bug to better help us understand the issue.
![image](https://user-images.githubusercontent.com/27508292/51416818-4fbc5b80-1b62-11e9-8d25-9abd89d592c0.png)

**Comment by zumbak04** [comment]
Fixed!
