### ISSUE TITLE
[BUG] | Cenarion Hold Has Silver Hand Composition

### ISSUE THREAD

**Issue by Darkmark8910** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#254]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**

**What expansions do you have installed?**

**Please explain your issue in as much detail as possible:**
Cenarion Hold's holy order uses the Silver Hand's mercenary composition

**Steps to reproduce the issue:**

**Upload an attachment below: .zip of your save, or screenshots:**

**Comment by Darkmark8910** [comment]
Cenarion Hold's holy order uses the Silver Hand's mercenary composition

**Comment by zumbak04** [comment]
> Cenarion Hold's holy order uses the Silver Hand's mercenary composition

I'm not sure it's a bug, because the Silver Hand composition looks ok for the Cenarion Hold. Anyway, got it, if we change their composition and add things like paladins, it will look weird.

**Comment by DukeJeans** [comment]
Adjusted in commit 597d50c.
