### ISSUE TITLE
[SUGGESTION] | Gold Road Trade Route

### ISSUE THREAD

**Issue by Velius94** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#259]
**DO NOT REMOVE PRE-EXISTING LINES**
----------------------------------------------------------------------------------------------------------
https://wow.gamepedia.com/Gold_Road

In the RPG (I know, not-canon, but eh) Gold Road is a major trading route stretching from Northern Kalimdor (Nighthaven) towards the Great Lift, with additional starting points in Astranaar and Ratchet. I think this can be represented as a trade route akin to Silkroad/Trans-Saharan Route from vanilla CK2.

**Comment by MemeWizard** [comment]
Implemented
