### ISSUE TITLE
[BUG] | Little sneks has no portraits

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#261]
**Mod Version**
Wonders Branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Sethraks don't have portraits for children

**Steps to reproduce the issue:**
Look at baby sneks

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_16](https://user-images.githubusercontent.com/46576860/55705603-cd686880-59e7-11e9-98fb-ed7ea62d4e71.png)

</details>

**Comment by zumbak04** [comment]
Fixed by @Aruzan in #268.
