### ISSUE TITLE
[BUG] | Corrupted blood remains a symptom and does not develop into a disease.

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#262]
**Mod Version**
Wonders Branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Corrupted blood remains a symptom and does not develop into a disease.

**Steps to reproduce the issue:**
Try to get corrupted blood disease

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_7](https://user-images.githubusercontent.com/46576860/55705939-a2324900-59e8-11e9-8ceb-9bd49846cdd1.png)
![ck2_1](https://user-images.githubusercontent.com/46576860/55705941-a3fc0c80-59e8-11e9-93b4-7161bde53cd2.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
