### ISSUE TITLE
[BUG] | Title of Burning Legion can be usurped by non-legion character

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#263]
**Mod Version**
Wonders Branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
For example, warchief of the horde can get title of Burning Legion through subjugation

**Steps to reproduce the issue:**
Subjugate a burning legion

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_3](https://user-images.githubusercontent.com/46576860/55706065-e9b8d500-59e8-11e9-9f9b-f3cf47810f17.png)
![ck2_4](https://user-images.githubusercontent.com/46576860/55706066-e9b8d500-59e8-11e9-973a-ebbf69e4e3bb.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
