### ISSUE TITLE
Heralds can sacrifice my prisoners without my consent

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#27]
Master branch
High (?)

Heralds can sacrifice my prisoners without my consent.
And their number of murders is incredibly high.

<details>
<summary>Click to expand</summary>

![ck2_13](https://user-images.githubusercontent.com/46576860/51427782-b007d780-1c0c-11e9-8e79-c326a1b56785.png)
![ck2_14](https://user-images.githubusercontent.com/46576860/51427783-b0a06e00-1c0c-11e9-8289-76c4f74802c3.png)
![ck2_4](https://user-images.githubusercontent.com/46576860/51427852-653a8f80-1c0d-11e9-9a60-0e6453270e82.png)

</details>

**Comment by DukeJeans** [comment]
Assigning Sejtalk.

**Comment by MemeWizard** [comment]
Also: the sacrifices of my character are counted not to my character, but to heralds.
<details>
<summary>Click to expand</summary>

![ck2_2](https://user-images.githubusercontent.com/46576860/51753945-1a68be00-20cc-11e9-94e4-2833c26037e9.png)
![ck2_3](https://user-images.githubusercontent.com/46576860/51753958-248abc80-20cc-11e9-8f57-6ddf24b3a3dd.png)


</details>

**Comment by sejtalk** [comment]
> Master branch
> High (?)
> 
> Heralds can sacrifice my prisoners without my consent.
> And their number of murders is incredibly high.
> 
> Click to expand

Fixed temporarily by disabling sacrifice for heralds

**Comment by sejtalk** [comment]
> Also: the sacrifices of my character are counted not to my character, but to heralds.
> 
> Click to expand

Do you mean when you sacrifice them or when heralds sacrifice them from your prison ?

**Comment by MemeWizard** [comment]
> Do you mean when you sacrifice them or when heralds sacrifice them from your prison ?

When my character sacrifices them

**Comment by sejtalk** [comment]
fixed
