### ISSUE TITLE
[BUG] | Voodress does not have a character at any mod bookmarks

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#271]
**Mod Version**
3.1 merging

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Voodress does not have a character at any mod bookmarks.

**Steps to reproduce the issue:**
Launch mod

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/56089132-d1d4cb80-5e96-11e9-893c-a66cac8a2fa7.png)
![image](https://user-images.githubusercontent.com/46576860/56089143-fcbf1f80-5e96-11e9-8dc0-b9352851dfd0.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
