### ISSUE TITLE
[BUG] | The game fires an event about turning into undead for each Qiraji courtier.

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#272]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
The game fires an event about turning into undead for each Qiraji courtier.

**Steps to reproduce the issue:**
Select Qiraji, start the game, run a month.

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_30](https://user-images.githubusercontent.com/46576860/56089451-8670ec00-5e9b-11e9-80a5-22b36c2a683d.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
