### ISSUE TITLE
[LOCALIZATION] | Some decisions descriptions don't have dots.

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#273]
**Mod Version**
Master Branch

**Please explain your issue in as much detail as possible:**
Vanilla decision descriptions have dots, some mod decision descriptions have dots, some don't.

**Upload screenshots of the problem localization:**

![Без имени](https://user-images.githubusercontent.com/46576860/56091914-c34dda80-5ebd-11e9-8c58-40e280ae7ed9.png)

**Comment by sejtalk** [comment]
fixed

**Comment by MemeWizard** [comment]
Also, all non-articles in decisions should be capitalized 
<details>

<summary>Click to expand</summary>

![ck2_2](https://user-images.githubusercontent.com/46576860/57196241-a445e400-6f63-11e9-8959-603196e79ade.png)
![ck2_3](https://user-images.githubusercontent.com/46576860/57196242-a445e400-6f63-11e9-972d-bd0095aa849b.png)

</details>

**Comment by MemeWizard** [comment]
Fixed in 0d083ed38d5b99b864200d110c55ef7411e7c3bd
