### ISSUE TITLE
[BUG] | Temples having their old skin while attempting to build them.

### ISSUE THREAD

**Issue by geffe1** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#275]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
3.1.0 (PXXI)
**What expansions do you have installed?**
ALL
**Please explain your issue in as much detail as possible:**
The temple holding is not changed into the new ones we got for humans in this screen, when built however they change to their new skin.
**Steps to reproduce the issue:**
Build beautiful temples as humans.
**Upload an attachment below: .zip of your save, or screenshots:**
https://cdn.discordapp.com/attachments/527533995479662622/566995126883319901/ck2_6.png

**Comment by zumbak04** [comment]
Not bug, feature. In construction tab you see how temple of religion group looks like.
