### ISSUE TITLE
[BUG] | Non plagued province getting culled.

### ISSUE THREAD

**Issue by geffe1** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#276]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
3.1.0 (PXXI)
**What expansions do you have installed?**
ALL
*Please explain your issue in as much detail as possible:**
A non plagued province got culled, it had a disease in it though but it was not the plague.
**Steps to reproduce the issue:**
Kill or play as Arthas and not getting the event to fire for you personally, or anybody in Lordaeron.
**Upload an attachment below: .zip of your save, or screenshots:**
https://cdn.discordapp.com/attachments/527533995479662622/566968067347709952/ck2_2.png

**Comment by zumbak04** [comment]
Was there an epidemic of another disease?

**Comment by geffe1** [comment]
> Was there an epidemic of another disease?

Most likely, as I got a screenshot from the same save but a few years later with the corrupted blood in Gilneas. Which is 6 years later.. so I highly doubt it was that outbreak if there was one at that time.

**Comment by zumbak04** [comment]
Fixed!
