### ISSUE TITLE
[LOCALIZATION] | Summon a  Man

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#279]
**Mod Version**
Master Branch

**Please explain your issue in as much detail as possible:**
Holy/Unholy prefix don't work

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![ck2_1](https://user-images.githubusercontent.com/46576860/56248963-b3e3b280-60b2-11e9-8cac-f8fcb98919ad.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
