### ISSUE TITLE
Two-headed ogres don't have two heads.

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#28]
Master branch
Medium

Two-headed descendants of two-headed ogres don't have "two-headed" trait.

<details>
<summary>Click to expand</summary>

![ck2_7](https://user-images.githubusercontent.com/46576860/51427997-610f7180-1c0f-11e9-8d1f-b628d12acfa8.png)
![ck2_9](https://user-images.githubusercontent.com/46576860/51427999-64a2f880-1c0f-11e9-9dcd-eab4b482cbe0.png)

</details>

**Comment by zumbak04** [comment]
Fixed.
