### ISSUE TITLE
[BUG] | Summon a Demon

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#280]
**Mod Version**
Master Branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
If there are no valid characters at your court, this event localization will break and you will get bonus from summoning a demon even if you din't sacrificed anyone

**Steps to reproduce the issue:**
Have no valid characters at your court

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_2](https://user-images.githubusercontent.com/46576860/56249044-f60cf400-60b2-11e9-8621-59019f2b91ff.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
