### ISSUE TITLE
[BUG] | The Legion and The Scourge

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#282]
**Mod Version**
Master Branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
1- Event has no loc
2- Game will over if you pick first option

**Steps to reproduce the issue:**
Summon the Legion as The Scourge

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_5](https://user-images.githubusercontent.com/46576860/56258189-5d3c9f80-60d7-11e9-8484-3d2ddcc50dff.png)
![ck2_6](https://user-images.githubusercontent.com/46576860/56258191-5dd53600-60d7-11e9-8300-704ba30eea86.png)

</details>

**Comment by zumbak04** [comment]
> 1- Event has no loc

Fixed!

> 2- Game will over if you pick first option

As it should be, but ok. Now the player switches to a leader of the Burning Legion.
