### ISSUE TITLE
[LOCALIZATION] | Council Authority

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#283]
**Mod Version**
Master Branch

**Please explain your issue in as much detail as possible:**
Council Authority laws description talks about muslims and indians

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![ck2_3](https://user-images.githubusercontent.com/46576860/56258291-b60c3800-60d7-11e9-9ba9-9dfa014d1464.png)
![ck2_4](https://user-images.githubusercontent.com/46576860/56258292-b6a4ce80-60d7-11e9-9056-d9ba0e6d260f.png)

</details>

**Comment by zumbak04** [comment]
Fixed1
