### ISSUE TITLE
[BUG] | Nomads settled - event fires 2 times

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#284]
**Mod Version**
Master Branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
This event should fire only one time

**Steps to reproduce the issue:**
Wait until centaur will settle

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_2](https://user-images.githubusercontent.com/46576860/56258410-2dda6280-60d8-11e9-8ccb-66c566f7711c.png)

</details>

**Comment by zumbak04** [comment]
Report to Paradox, it's vanilla bug.
![image](https://user-images.githubusercontent.com/46384992/56261643-e9a58d00-60ec-11e9-93ee-0f2a7655c722.png)
