### ISSUE TITLE
[BUG] | Event show wrong character's portraits

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#285]
**Mod Version**
Master Branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Event show wrong character's portraits

**Steps to reproduce the issue:**
Check characters portraits in event, for example - Born of the Twilight Hammer Cult 
This event showed character who founded he Twilight Hammer Cult, but now it's shows player’s character.

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_1](https://user-images.githubusercontent.com/46576860/56258762-629ae980-60d9-11e9-8c52-a69d72ebcdaa.png)

</details>

**Comment by zumbak04** [comment]
As it should be. This type of event always shows the player’s portrait.
