### ISSUE TITLE
[SUGGESTION] | General building balance issues

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#286]
**Describe your suggestion in full detail below:**

Buildings are more expensive, builds slower and give less than vanilla analogs.
Compare fortifications (such a comparison can be made with all buildings in the modification, they all have these problems):
* An upgrade from the minimum to the maximum level in vanilla costs only 350. In the mod, this cost is 1875
  * First level in vanilla cost 50, in mod 125
  * Last level in vanilla cost 100, in mod 625
* Total max lvl time to build - 3.5 years in vanilla against 8 in mod
* Total max level in vanilla gives +3.5 to fort level, in the mod total max level gives +2.5

This causes the following problem:
Investment returns - some buildings are simply not worth building. Not all are listed here, but only the most vivid examples.
wc_prison2 - 10 heavy infantry for 140 gold? It is not profitable to build if you play as small rulers. It is better to establish a mercenary company (About 300 soldiers, third of which will be heavy infantry. And it will cost only 50 gold!) and use it. 10 heavy infantry for large states, where the number of troops goes to thousands? It just doesn't make sense. I can build a castle, instead of 3 of these buildings and get several times more profit for the same money.
wc_walls5 - 0.5 fort level for 625 gold?! How many years will it take to make this investment profitable? It’s better not to build this thing at all, I better hire 6k of mercenaries with this money.

Pls, balance this shit

**Comment by MemeWizard** [comment]
>BUILDING_COST_MULT = 0.5,             -- Increase to the build cost of all buildings that cost GOLD

In addition, the game has this define that increases the cost of all buildings by 50%. This is done so that too many modifiers on the cost of construction do not make the cost of construction equal to 1 gold, so do not even think about removing this define and destroying the balance of the game.

>Last level in vanilla cost 100, in mod 625

So, when you look at the comparisons in the first post, always remember that in fact the price in the game is 50% higher

**Comment by SlagartheCruel** [comment]
It is a difficult thing to balance and manage from the original material of the building overhaul, but its doable, and there are some quick and temporary fixes before making larger and more formal overhauls, but I'll leave this up with duke and others;

We can do a major cost nerf across the board for all buildings and reduce all building costs by 50% of their original cost, and reduce building times by 60% of their original costs, along with doing some minor buffs for walls to give them more of a vanilla overview (levy multiplier and tax) along with some general buffs for suggested buildings like the prison chain.

Another solution is to reduce building times only by 60%, followed by larger and more beefer buffs to make better investment returns. 

These are possible temporary solutions that can, theoretically, be done kind of quickly while its still an issue. I am cautious on doing an overhaul of income, but suggestions, comments, and concerns should be made before such work begins in earnest.

**Comment by MemeWizard** [comment]
No longer a problem after Merging MO
