### ISSUE TITLE
[BUG] | Hospital buildings modifiers

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#288]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
The most fully built hospital has 7 levels and 108% disease resistance
In vanilla, hospital has only 6 levels (there is no icon for lvl 7 hospital) and 95% disease resistance

**Steps to reproduce the issue:**
Build Hospital and all buildings in it

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_1](https://user-images.githubusercontent.com/46576860/56397738-eaa20000-624d-11e9-9d1c-e68044eb2443.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
