### ISSUE TITLE
Invite to faction - localization

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#29]
Master branch
Low

Ruler, whom I invite to join my faction, says he is join the Horde, but I am not the Horde.

<details>
<summary>Click to expand</summary>

![ck2_6](https://user-images.githubusercontent.com/46576860/51428189-d2e8ba80-1c11-11e9-88ed-174c55738a4c.png)

</details>

**Comment by DukeJeans** [comment]
Fixed
