### ISSUE TITLE
[SUGGESTION] | Nerf druid forms commands modifiers

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#293]
**Describe your suggestion in full detail below:**

Right now, druid forms give better command modifiers than leadership traits.
It’s just wrong that a bear on a battlefield improves the combat capability of troops better than an experienced commander. For example, shape of the bear is better than unyielding leadership trait, but the shape does not occupy the commanding slot and can be accessible to any druid.
This needs a nerf. Additionally, you can add different debuffs to different forms.
You can also replace these global bonuses for all troops with different small bonuses. For example, the shape of a bird can give specialization on hills and mountains, the shape of a cat in the jungle and forests, etc.

<details>
<summary>Click to expand</summary>

![ck2_14](https://user-images.githubusercontent.com/46576860/56441315-57bca080-62f5-11e9-8d4a-c4e7e626b345.png)
![ck2_15](https://user-images.githubusercontent.com/46576860/56441316-57bca080-62f5-11e9-9f43-bbf0ee8742ec.png)
![ck2_16](https://user-images.githubusercontent.com/46576860/56441317-57bca080-62f5-11e9-82ab-dbb4af046b77.png)

</details>

**Comment by zumbak04** [comment]
Nerfed in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/pull/830.
