### ISSUE TITLE
Bug on the new 1.4.0 feature?

### ISSUE THREAD

**Issue by SimYRuler** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#297]
Since 3.1.0 Merging , when i tryed to play Stormwind , beat the Horde , took the titles , changed them to feudal , after some time the game is crashing to desktop, i don't know if somebody else experienced this , or is just because , 1.4.0 is not finished!

**Comment by zumbak04** [comment]
Need save shortly before it happened.

**Comment by SimYRuler** [comment]
The game crash on desktop when the graphics is loading , what should i do to try the new features for testing or is still not finished and i need to wait ?

**Comment by SimYRuler** [comment]
Also there is a way to ask questions without using the issues tab ?

**Comment by zumbak04** [comment]
> The game crash on desktop when the graphics is loading , what should i do to try the new features for testing or is still not finished and i need to wait ?

When you run the vanilla, what is your checksum?

> Also there is a way to ask questions without using the issues tab ?

Yep, ask it on Discord.
https://discordapp.com/invite/NvvjDEj

**Comment by SimYRuler** [comment]
Tnx you for the assist , indeed i had an old checksum version , now i can try it again.
