### ISSUE TITLE
Treasury Bug

### ISSUE THREAD

**Issue by SimYRuler** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#298]
It says something about duplicate items

![descărcare](https://user-images.githubusercontent.com/49053744/56461773-d599ae00-63c0-11e9-88e7-70b15419675f.png)

**Comment by zumbak04** [comment]
Report to Paradox, it's not ours.
https://forum.paradoxplaza.com/forum/index.php?forums/crusader-kings-ii-bug-reports.680/
