### ISSUE TITLE
[LOCALIZATION] | The game will end in 1452

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#299]
**Mod Version**
Master Branch

**Please explain your issue in as much detail as possible:**
The initial screen tells me that the game will end in 1452

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/56464352-b403eb00-63ef-11e9-91d1-1e588f4904cc.png)

</details>

**Comment by zumbak04** [comment]
Fixed1
