### ISSUE TITLE
Air elemental event - localization

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#30]
Master branch
Low

Dot in the wrong place.

<details>
<summary>Click to expand</summary>

![ck2_1](https://user-images.githubusercontent.com/46576860/51428267-c4e76980-1c12-11e9-9949-073b215d8cd8.png)

</details>

**Comment by DukeJeans** [comment]
Fixed
