### ISSUE TITLE
[LOCALIZATION] | Fel-tainted description is too long for "features" screen.

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#301]
**Mod Version**
Master Branch

**Please explain your issue in as much detail as possible:**
Fel-tainted description is too long for "features" screen.

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/56464367-1230ce00-63f0-11e9-8f48-bd5ec0df7758.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
