### ISSUE TITLE
[LOCALIZATION] | text_effect_mind_control_chance

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#303]
**Mod Version**
Master Branch

**Please explain your issue in as much detail as possible:**
No loc for text_effect_mind_control_chance

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![ck2_8](https://user-images.githubusercontent.com/46576860/56471127-75098000-6457-11e9-8558-abdd23d21e66.png)

</details>

**Comment by zumbak04** [comment]
Localization in #296
