### ISSUE TITLE
[BUG] | No portraits for dryad children and taunka womens

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#304]
**Mod Version**
Master Branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Dryad/Frost Nymph children and taunka womens has no portraits

**Steps to reproduce the issue:**
Look at dryad kids/taunka women

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_6](https://user-images.githubusercontent.com/46576860/56471152-d3366300-6457-11e9-9a57-00a0b757f943.png)
![ck2_7](https://user-images.githubusercontent.com/46576860/56471153-d3366300-6457-11e9-880f-3cf60d27986e.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
