### ISSUE TITLE
[BUG] | Void Creatures can get negative genetic traits

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#305]
**Mod Version**
Master Branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Clubfooted is random trait, so any spawned char with random traits can get this trait

**Steps to reproduce the issue:**
Subdue void creature

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_2](https://user-images.githubusercontent.com/46576860/56475104-625d6e00-648c-11e9-80bf-ec979829f8dd.png)
![ck2_3](https://user-images.githubusercontent.com/46576860/56475105-625d6e00-648c-11e9-9f06-29da16592f8a.png)

</details>

**Comment by zumbak04** [comment]
Couldn't reproduce the issue. add_trait_void_creature_effect removed these traits.

**Comment by zumbak04** [comment]
Ok, found it and fixed!
