### ISSUE TITLE
[BUG] | Game uses wrong loc for the Horde collapse

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#306]
**Mod Version**
Master Branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Game uses wrong loc for the Horde collapse

**Steps to reproduce the issue:**
Orcs must die

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_9](https://user-images.githubusercontent.com/46576860/56475192-d1879200-648d-11e9-9803-b77caae78b0e.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
