### ISSUE TITLE
[LOCALIZATION] | Non-cap name

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#307]
**Mod Version**
Master Branch

**Please explain your issue in as much detail as possible:**
Option description should begin with a capital letter.

**Upload screenshots of the problem localization:**
<details>
<summary>Click to expand</summary>

![ck2_4](https://user-images.githubusercontent.com/46576860/56475229-583c6f00-648e-11e9-815a-85bbcc0dbd3e.png)

</details>

**Comment by zumbak04** [comment]
Fixed!

**Comment by MemeWizard** [comment]
<details>
<summary>Click to expand</summary>

![ck2_1](https://user-images.githubusercontent.com/46576860/57443280-5b897600-7256-11e9-8395-5cedd574f029.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
