### ISSUE TITLE
[BUG] | Original Deathknight don't have dynasty name

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#308]
**Mod Version**
Master Branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Original Deathknight don't have dynasty name

**Steps to reproduce the issue:**
The Horde must create Deathknights

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_1](https://user-images.githubusercontent.com/46576860/56475289-bc5f3300-648e-11e9-97aa-352da31b5162.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
