### ISSUE TITLE
Non-colonized provinces in Kalimdor are not colonized.

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#31]
Master branch
Medium

Durotar cannot be colonized if the Horde did not arrive in Kalimdor, but they can sometimes be vassalized or stop being uncolonized due to rebellion.

<details>
<summary>Click to expand</summary>

![ck2_8](https://user-images.githubusercontent.com/46576860/51428574-35dc5080-1c16-11e9-836b-627fa6cf6c0f.png)
![ck2_1](https://user-images.githubusercontent.com/46576860/51428571-3248c980-1c16-11e9-8c68-45efda92c372.png)

</details>

**Comment by zumbak04** [comment]
Fixed? Added two things to prevent it:

1. Uncolonised rulers now have bad opinion about all religions, so it means that most likely they will refuse vassalisation.
2. Reduced revolt risk if you're uncolonised ruler
