### ISSUE TITLE
[BUG] | Summoning an Qiraji courtier, and they are dead on arrival to your court.

### ISSUE THREAD

**Issue by geffe1** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#310]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
3.1.0 WFEW
**What expansions do you have installed?**
ALL
**Please explain your issue in as much detail as possible:**
Qiraji courtiers that are  getting summoned are dead on arrival to your court.
**Steps to reproduce the issue:**
Launch game, play as Qiraji leader, summon a female, a noble and an unholy man to the court and they will all be dead on arrival.
**Upload an attachment below: .zip of your save, or screenshots:**
![ck2_9](https://user-images.githubusercontent.com/31706375/56498524-56ac8e80-6502-11e9-9ff5-cfb54e7430bd.png)

**Comment by zumbak04** [comment]
Fixed1
