### ISSUE TITLE
[BUG] after biracial marriage request

### ISSUE THREAD

**Issue by Sielentus** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#311]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version** 
1.3.1
**What expansions do you have installed?**
all

**Please explain your issue in as much detail as possible:**
My Son was 15 and i got from a Dwarf King a request, if his 15 y. daughter and my son should marry and i accepted. I got a message "Unfortunately they can't marry" and since then, my son got the "can not marry" trait 

**Steps to reproduce the issue:**
biracial marrige before one ( or both) turn 16

**Upload an attachment below: .zip of your save, or screenshots:**
-
![ck2_2](https://user-images.githubusercontent.com/49923433/56615576-a6cb4400-661b-11e9-890a-1878d98e09c7.png)

**Comment by zumbak04** [comment]
@Sielentus, they were betroth?

**Comment by Sielentus** [comment]
> @Sielentus, they were betroth?

no but u can provoke this bug 
![ck2_5](https://user-images.githubusercontent.com/49923433/56677828-9ff70c80-66c1-11e9-818b-fe108a17f6d2.png)

( as you can see he, does not have the "can not mary trait) after i send a biracial marriage request
![ck2_6](https://user-images.githubusercontent.com/49923433/56677842-a4bbc080-66c1-11e9-9a6a-54120b08a568.png)
i got the trait

**Comment by zumbak04** [comment]
Got it. This issue was fixed in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/commit/b561ba4e0791611c25b08e8066740d07574077b4.
