### ISSUE TITLE
[BUG] | Wrong province placement

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#312]
**Mod Version**
bfd04f43

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Veiled sea, North crossroads and Southgate placed wrongly

**Steps to reproduce the issue:**
Look at Veiled sea, North crossroads and Southgate

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_27](https://user-images.githubusercontent.com/46576860/56652180-71623d00-6693-11e9-8adf-8853b104a945.png)

![ck2_50](https://user-images.githubusercontent.com/46576860/56652102-32cc8280-6693-11e9-933b-2e4b28b0fb35.png)
![ck2_51](https://user-images.githubusercontent.com/46576860/56652103-32cc8280-6693-11e9-97b9-6438db0c1630.png)

![ck2_53](https://user-images.githubusercontent.com/46576860/56652085-25af9380-6693-11e9-8b2a-4d5aa38735e4.png)
![ck2_54](https://user-images.githubusercontent.com/46576860/56652086-26482a00-6693-11e9-860b-3c2f682f1b64.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
