### ISSUE TITLE
[BUG] | Children get stereotypical racial traits at birth

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#313]
**Mod Version**
bfd04f43

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Children get stereotypical racial traits at birth

**Steps to reproduce the issue:**
Playing as race that has stereotypical traits, give birth to a child.

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_4](https://user-images.githubusercontent.com/46576860/56653009-614b5d00-6695-11e9-8a5c-d9e8b63ef314.png)
![ck2_5](https://user-images.githubusercontent.com/46576860/56653010-614b5d00-6695-11e9-998f-6517adf84971.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
