### ISSUE TITLE
[BUG] | Purge Lands available for evil characters

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#314]
**Mod Version**
bfd04f4

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
"Evil" characters can Purge Lands from "Evil"

**Steps to reproduce the issue:**
Play as "Evil" character and have "Evil" neighbors

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_6](https://user-images.githubusercontent.com/46576860/56658260-d709f580-66a2-11e9-85a1-bd4621744e09.png)
![ck2_7](https://user-images.githubusercontent.com/46576860/56658262-d8d3b900-66a2-11e9-8e4c-3f5ff6456c55.png)
![ck2_8](https://user-images.githubusercontent.com/46576860/56658400-3b2cb980-66a3-11e9-8d65-3409909e3251.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
