### ISSUE TITLE
[LOCALIZATION] | Subjugation desc

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#315]
**Mod Version**
bfd04f4

**Please explain your issue in as much detail as possible:**
Subjugation description is wrong

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![ck2_6](https://user-images.githubusercontent.com/46576860/56658479-5dbed280-66a3-11e9-9a8d-71e099310911.png)
![ck2_7](https://user-images.githubusercontent.com/46576860/56658480-5e576900-66a3-11e9-8013-d8ae0a2384c8.png)
![ck2_10](https://user-images.githubusercontent.com/46576860/56658481-5e576900-66a3-11e9-91eb-76d36eef751a.png)
![ck2_11](https://user-images.githubusercontent.com/46576860/56658478-5dbed280-66a3-11e9-8d16-ebc49dbfd8be.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
