### ISSUE TITLE
[BUG] | No orcs knights model

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#316]
**Mod Version**
bfd04f4

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Orcs don't have knights model

**Steps to reproduce the issue:**
Look at orc heavy cavalry model

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_41](https://user-images.githubusercontent.com/46576860/56658612-bbebb580-66a3-11e9-866e-ea603a52d70d.png)

</details>

**Comment by MemeWizard** [comment]
High priority, because if a unit does not have a model, it cannot be selected along with another unit.

**Comment by zumbak04** [comment]
Fixed!
