### ISSUE TITLE
[BUG] | Mossflayer tribe capital

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#317]
**Mod Version**
bfd04f4

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
You must control Benevento in order to create Mossflayer tribe

**Steps to reproduce the issue:**
Mossflayer tribe must have no holder

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_40](https://user-images.githubusercontent.com/46576860/56659092-f0ac3c80-66a4-11e9-84f4-f529b483e27e.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
