### ISSUE TITLE
[BUG] | Old Gods cultist can kill C'thun

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#318]
**Mod Version**
bfd04f43

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Old Gods cultist can kill C'thun

**Steps to reproduce the issue:**
Siege Ahn'qiraj as Old Gods cultist

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_29](https://user-images.githubusercontent.com/46576860/56665739-4be52b80-66b3-11e9-9b9f-82f27379ca21.png)
![ck2_30](https://user-images.githubusercontent.com/46576860/56665740-4be52b80-66b3-11e9-9531-be5551205ab4.png)

</details>

[Horde608_10_21.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3112660/Horde608_10_21.zip)

**Comment by MemeWizard** [comment]
Also, this event localization don't work correctly (#151)

**Comment by sejtalk** [comment]
fixed
