### ISSUE TITLE
[LOCALIZATION] | Observer culture

### ISSUE THREAD

**Issue by geffe1** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#319]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
3.1.0
**Please explain your issue in as much detail as possible:**
Giving an Observer a province and letting them get their culture to that land will give you the result of Oberserves' as a culture, I think it would make more sense with Observer.
**Upload screenshots of the problem localization:**
![ck2_22](https://user-images.githubusercontent.com/31706375/56686282-f1a89280-66d3-11e9-9811-b913e42c887a.png)

**Comment by zumbak04** [comment]
Fixed!
