### ISSUE TITLE
[LOCALIZATION] |  "We shared the same fate"

### ISSUE THREAD

**Issue by Sielentus** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#320]
**DO NOT REMOVE PRE-EXISTING LINES** 
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.3.1
**Please explain your issue in as much detail as possible:**

After religion conversion demmand  on the Kvakdir to the  Shath'Yar religion  i got this undead message 

**Upload screenshots of the problem localization:**
![ck2_7](https://user-images.githubusercontent.com/49923433/56844632-a056f980-68b3-11e9-9e38-906863d9d139.png)

**Comment by zumbak04** [comment]
Fixed!
