### ISSUE TITLE
[SUGGESTION] | Give Gul'dan a hood.

### ISSUE THREAD

**Issue by Varus211** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#323]
**DO NOT REMOVE PRE-EXISTING LINES**
----------------------------------------------------------------------------------------------------------
**Describe your suggestion in full detail below:**
Gul'dan doesn't have a hood, but yet he requires a hood.

**Comment by zumbak04** [comment]
He has a hood starting from https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/pull/295/commits/60d36fa7d0efc4468a86866287c8b9e996ab3981
![image](https://user-images.githubusercontent.com/46384992/56866579-c8e20f00-69eb-11e9-8568-f81635298e44.png)
