### ISSUE TITLE
[LOCALIZATION] | Old gods interface

### ISSUE THREAD

**Issue by geffe1** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#324]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
3.1.0
**Please explain your issue in as much detail as possible:**
The texts appears like this"plotting_something_something" in the Old God interfaces.
**Upload screenshots of the problem localization:**
![ck2_24](https://user-images.githubusercontent.com/31706375/56867335-49047680-69e4-11e9-8e71-438725a976ac.png)
![ck2_26](https://user-images.githubusercontent.com/31706375/56867339-4c97fd80-69e4-11e9-886e-24ecbb271fc9.png)

**Comment by zumbak04** [comment]
Reported in #221.
