### ISSUE TITLE
[BUG] | Graphic noise in purple provinces

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#329]
**Mod Version**
Master Branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
For some reason, provinces with purple color have a lot of graphic noise

**Steps to reproduce the issue:**
Look at dragon isles/quiet highlands in-game

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![ck2_11](https://user-images.githubusercontent.com/46576860/56896007-4f9df700-6a93-11e9-8d11-fbcaf2c96f96.png)
![ck2_39](https://user-images.githubusercontent.com/46576860/56896008-4f9df700-6a93-11e9-9bcb-400b60f8f81d.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
