### ISSUE TITLE
Re-Origination Request

### ISSUE THREAD

**Issue by Domi2333** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#33]
Which version of the mod does this apply to?
1.2
How important is this bug/suggestion (Low/Medium/High/Critical)?
Low
Explain the bug or suggestion below:
Characters can have "the Australian" as nickname
Feel free to attach a **.zip** or a **screenshot** of the bug to better help us understand the issue.
![image](https://user-images.githubusercontent.com/46266806/51430574-b5b9e900-1c1d-11e9-8f0e-70bc9b6f473f.png)

**Comment by zumbak04** [comment]
It's not a bug, it's a feature.
