### ISSUE TITLE
[BUG] | There is a death knight before.. they became a thing.

### ISSUE THREAD

**Issue by geffe1** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#330]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
3.1.0 KOSL
**What expansions do you have installed?**
ALL
**Please explain your issue in as much detail as possible:**
There is a Death Knight before Death Knights became a thing.
**Steps to reproduce the issue:**
Launch the game and use the character search tool. Type "Death" and you will find a Vrykul Death Knight at the beginning of the first war.
**Upload an attachment below: .zip of your save, or screenshots:**
![ck2_17](https://user-images.githubusercontent.com/31706375/56926201-66fbd500-6ad1-11e9-9fb2-6d3c5ad8a22b.png)

**Comment by zumbak04** [comment]
It's not a bug, it's my boi Lucard.
https://wow.gamepedia.com/Blood-Thane_Lucard
