### ISSUE TITLE
[BUG] | Satyr's can not summon females(yet get the option to do so)

### ISSUE THREAD

**Issue by geffe1** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#331]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
3.1.0 KOSL
**What expansions do you have installed?**
ALL
**Please explain your issue in as much detail as possible:**
Satyr's get the option to summon a female to the court, however you only get a man.. so a trap I guess.
**Steps to reproduce the issue:**
Start the game and summon a female to the court.
**Upload an attachment below: .zip of your save, or screenshots:**
![ck2_23](https://user-images.githubusercontent.com/31706375/56926495-294b7c00-6ad2-11e9-8786-366e6cd7d320.png)
![ck2_24](https://user-images.githubusercontent.com/31706375/56926499-2c466c80-6ad2-11e9-96d6-9fbfb87036dd.png)

**Comment by zumbak04** [comment]
Fixed!
