### ISSUE TITLE
[BUG] | Char №141202 has no portrait

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#332]
**Mod Version**
Master Branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Char №141202 has no portrait

**Steps to reproduce the issue:**
Look at char №141202

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/56955819-12953b80-6b4b-11e9-8aa3-132f8786740a.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
