### ISSUE TITLE
[BUG] | Naaru heresy icon shifted to the right

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#336]
**Mod Version**
Master Branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Lightbound icon shifted to the right

**Steps to reproduce the issue:**
Look at Lightbound icon

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![](https://cdn.discordapp.com/attachments/527533995479662622/573205434547306496/unknown.png)
![](https://cdn.discordapp.com/attachments/527533995479662622/573205489484300292/unknown.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
