### ISSUE TITLE
[LOCALIZATION] | lowercase name

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#337]
**Mod Version**
Master Branch

**Please explain your issue in as much detail as possible:**
lowercase gorloc name

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![](https://cdn.discordapp.com/attachments/406500578231975937/572853188466704405/unknown.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
