### ISSUE TITLE
[LOCALIZATION] | a misspell in the N´raqi description

### ISSUE THREAD

**Issue by Sielentus** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#338]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.3.1

**Please explain your issue in as much detail as possible:**
a word is misspelled wrong in the N´raqi description
the "OLG" gods

**Upload screenshots of the problem localization:**

![ck2_14](https://user-images.githubusercontent.com/49923433/57193822-cded1400-6f3f-11e9-99f1-07672dcf0ba5.png)

**Comment by zumbak04** [comment]
Fixed!
