### ISSUE TITLE
[BUG] | Alextrasa  died at childbirth and Orks don't have a demon Portait 

### ISSUE THREAD

**Issue by Sielentus** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#339]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.3.1

**What expansions do you have installed?**
all

**Please explain your issue in as much detail as possible:**
Issue 1: Alextrasa died in childbirth.
issue 2: Ork turn into a demon and does not have a Demon portrait 

**Steps to reproduce the issue:**
Issue 1: -
Issue 2: pump a Ork full with fell Energy untill he turn into a Demon

**Upload an attachment below: .zip of your save, or screenshots:**
issue 1: 
![ck2_15](https://user-images.githubusercontent.com/49923433/57210794-4d312500-6fde-11e9-999a-e7620d05ba74.png)
issue 2: 
![ck2_12](https://user-images.githubusercontent.com/49923433/57210816-6043f500-6fde-11e9-9d2f-450e33750bf1.png)

**Comment by zumbak04** [comment]
> issue 2: Ork turn into a demon and does not have a Demon portrait

It's not a bug, it's how fel orc looks like.

**Comment by Sielentus** [comment]
> It's not a bug, it's how fel orc looks like. 

ah ok, he would be also turn into a demon. well then nevermind about the fel Orcs^^

**Comment by Sielentus** [comment]
> It's not a bug, it's how fel orc looks like.

ah okay, well nvm then. i thought they will also have some sort of demon transformation ^^ 

oh yes, i work at the moment, a flat out event chain idea for the LK and the "choosen one". this week is pretty annoying for me. Probaly i will have time on the weekend to post it complete on the suggestion board. ( this time i try also not to make the wonder list that long :p )

**Comment by zumbak04** [comment]
> Issue 1: Alextrasa died in childbirth.

Fixed! Now only mammal races can get Troubled or Difficult Pregnancy.
