### ISSUE TITLE
Highborne Women change portrait on death.

### ISSUE THREAD

**Issue by AltertronSteam** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#34]
Which version of the mod does this apply to?

1.2

How important is this bug/suggestion (Low/Medium/High/Critical)?

Low

Explain the bug or suggestion below:

Some (not all though) Highborne Elven Women change their portrait to a High Elven when they die.

![20190119223453_1](https://user-images.githubusercontent.com/34240986/51432644-389d6c80-1c3b-11e9-8371-fbb63ff28178.jpg)

![20190119224941_1](https://user-images.githubusercontent.com/34240986/51432717-8797d180-1c3c-11e9-8b1d-6dd68e789338.jpg)

**Comment by Tamamo-no-Bae** [comment]
This is very odd, can you provide the savegame please? I shall investigate

**Comment by MemeWizard** [comment]
Not only the dead, as I noticed.
(Performance jihad branch)

<details>
<summary>Click to expand</summary>

![ck2_3](https://user-images.githubusercontent.com/46576860/51711501-57d23a80-203d-11e9-84b4-ee163e1ae619.png)
[Ahn'qiraj618_12_12.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/2793814/Ahn.qiraj618_12_12.zip)

</details>

**Comment by zumbak04** [comment]
Fixed by @Tamamo-no-Bae!
