### ISSUE TITLE
[LOCALIZATION] | "Jihads and Crusaders"

### ISSUE THREAD

**Issue by Sielentus** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#341]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.3.1

**Please explain your issue in as much detail as possible:**
"we cannot join our vassals wars (exept for **Crusaders/Jihads**...)

**Upload screenshots of the problem localization:**
![ck2_17](https://user-images.githubusercontent.com/49923433/57253089-1d216a80-704e-11e9-92b8-49c713a97b4f.png)

**Comment by zumbak04** [comment]
Fixed! Removed only "Jihads" because DEUS VULT.

**Comment by Sielentus** [comment]
> Fixed! Removed only "Jihads" because DEUS VULT.

the Crusade aprove this!
