### ISSUE TITLE
[BUG] | Undead Grandson can make children (?)

### ISSUE THREAD

**Issue by Sielentus** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#343]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.3.1
**What expansions do you have installed?**
all
**Please explain your issue in as much detail as possible:**
I Abduct my grandson and turned him into a undead Death Knight, i guess not everything turned undead

**Steps to reproduce the issue:**
turn your Grandson to a undead DK and marry him with a human 

**Upload an attachment below: .zip of your save, or screenshots:**
![ck2_18](https://user-images.githubusercontent.com/49923433/57336027-ccc90c00-7124-11e9-8dcd-0b5772dc220a.png)

**Comment by zumbak04** [comment]
When he was turned? And how is real father?

**Comment by Sielentus** [comment]
> When he was turned? And who is real father? Save needed.

how do i post the save file? To be honest idk when i turned into a dk. i just married him, and bam he gets children

**Comment by Sielentus** [comment]
> When he was turned? And who is real father? Save needed.

idk exactly when i turned him, for sure is that he had no children. I arrange after that the marriage. 

here is the save file: 
[test 754.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3154966/test.754.zip)

oh yes and i have a important question. i would love ( if there is space) to join the closed Beta team to test stuff, for the next Patch. unfortunly i can´t support this mod with money, but i want to support this mod this way with my free time and love :3 
u can text me on over Mod DB ( same name as here)

**Comment by zumbak04** [comment]
Your grandson isn't real father. So...
Fixed! Infertile characters like undead, demons no longer can be cuckolded.
