### ISSUE TITLE
[LOCALIZATION] | Likely council position

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#345]
**Mod Version**
Master branch

**Please explain your issue in as much detail as possible:**
Likely council position description is wrong, bcs liege have evil government type

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![ck2_2](https://user-images.githubusercontent.com/46576860/57500332-b8833b80-72eb-11e9-99fa-075c0516d4ac.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
