### ISSUE TITLE
[BUG] | Son does not want Convert 

### ISSUE THREAD

**Issue by Sielentus** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#349]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
Master Branch
**What expansions do you have installed?**
all

**Please explain your issue in as much detail as possible:**
Teach my Son about the Glorious Old Gods. Welp time to rise up and he does not want to convert, even it is his secret Religion

**Steps to reproduce the issue:**
 secret Society teach him about the Twillight, he joined secretly and well.... ( first Son)

**Upload an attachment below: .zip of your save, or screenshots:**
[twillight test.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3167766/twillight.test.zip)

![ck2_9](https://user-images.githubusercontent.com/49923433/57550097-a0e89900-7365-11e9-9cd6-56f495e24dd2.png)

![ck2_10](https://user-images.githubusercontent.com/49923433/57550105-a80fa700-7365-11e9-8cd8-96d33058cde4.png)

**Comment by zumbak04** [comment]
This decision is hardcoded, so AI behavior here isn't moddable.
