### ISSUE TITLE
[LOCALIZATION] | "Chinese Emperor"

### ISSUE THREAD

**Issue by Sielentus** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#350]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
Master Branch

**Please explain your issue in as much detail as possible:**
"Chinese Emperors have varying..." 

**Upload screenshots of the problem localization:**
![ck2_11](https://user-images.githubusercontent.com/49923433/57552161-4c481c80-736b-11e9-9ae9-75f37e47a6ff.png)

![ck2_12](https://user-images.githubusercontent.com/49923433/57552168-579b4800-736b-11e9-8043-70bbe22b0ec9.png)

**Comment by zumbak04** [comment]
Reported in #221.

**Comment by Sielentus** [comment]
> Reported in #221.

oh ok. I will delete it
