### ISSUE TITLE
[LOCALIZATION] | Europe

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#353]
**Mod Version**
Master Branch

**Please explain your issue in as much detail as possible:**
There is no Europe in warcraft

**Upload screenshots of the problem localization:**

<details>

![ck2_8](https://user-images.githubusercontent.com/46576860/57610018-b1bd2880-7578-11e9-8baa-f6e7b2701aa5.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
