### ISSUE TITLE
[BUG] | nomadic interaction with mod governments

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#354]
**Mod Version**
Master Branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Nomads can take tyranny actions for free against tribal and monarchy rulers, but not against tribal monarchy (also any evil government).
Also. tooltip says that nomads can reform to iqta

**Steps to reproduce the issue:**
Play as nomad and have tribal monarchy vassal

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![ck2_2](https://user-images.githubusercontent.com/46576860/57610988-8d624b80-757a-11e9-8932-df8b061d6892.png)
![ck2_3](https://user-images.githubusercontent.com/46576860/57610989-8d624b80-757a-11e9-84da-8df356ca7268.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
