### ISSUE TITLE
[BUG] | HFP.16006

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#355]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
HFP.16006 can destroy indestructible artifacts

**Steps to reproduce the issue:**
See HFP.16006

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![unknown](https://user-images.githubusercontent.com/46576860/57613356-517db500-757f-11e9-9244-6b87e48de36b.png)

</details>

**Comment by zumbak04** [comment]
It can't destroy it, so this event does nothing when artifact is indestructible.
I fixed it, but the bug should be reported to Paradox.
