### ISSUE TITLE
[BUG] | Centaurs can usurp the Horde title

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#356]
**Mod Version**
Master Branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Centaurs can usurp the Horde title

**Steps to reproduce the issue:**
Subjugate the Horde playing as a nomadic horde

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![ck2_9](https://user-images.githubusercontent.com/46576860/57616914-1c299500-7588-11e9-915b-38ef9dac4a1d.png)
![ck2_10](https://user-images.githubusercontent.com/46576860/57616916-1c299500-7588-11e9-95a1-8d283e67f2a6.png)

</details>

**Comment by zumbak04** [comment]
I'm sad that you can usurp empire title via "Subjuication", but it's question to Paradox. The Horde can be usurped... even by nomads, it's not a bug.
