### ISSUE TITLE
[BUG] | Uther has no county in 603 bookmark

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#357]
**Mod Version**
Master Branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Uther does not have a county on 603 bookmark, so the first thing that Uther does is usurping county belonging to Tirion.

**Steps to reproduce the issue:**
Start playing as a Terenas Menethil II

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![ck2_6](https://user-images.githubusercontent.com/46576860/57617267-0ec0da80-7589-11e9-863d-823b49cb91f0.png)

</details>

**Comment by geffe1** [comment]
Give him his tomb as a cruel and sick joke..

**Comment by zumbak04** [comment]
> Give him his tomb as a cruel and sick joke..

Too late. I gave him the Light's Hope Chapel :3
