### ISSUE TITLE
[BUG] | Tanaris kingdom after Zul empire restoration

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#358]
**Mod Version**
Master Branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Tanaris kingdom will become de-jure part of Zul empire after Zul Empire restoration, even if Tanaris is not a part of restorer's realm

**Steps to reproduce the issue:**
Restore Zul Empire without any holding in Tanaris kingdom

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![ck2_7](https://user-images.githubusercontent.com/46576860/57618400-f1d9d680-758b-11e9-9bfc-8adce88371ca.png)
![ck2_1](https://user-images.githubusercontent.com/46576860/57618406-f605f400-758b-11e9-9b32-c2bd1784363e.png)

</details>

**Comment by zumbak04** [comment]
That happened because Tanaris is a part of troll de-jure empire, Zul'farrak.

**Comment by MemeWizard** [comment]
Well. Titles can drift and Zul'farrak empire can no longer contain Tanaris&Zul'farrak kingdoms or have additional drifted kingdoms.
So, for example, Zul'farrak empire can be de-jure empire of Cenarion Circle, so Cenarion Circle will drift into Zul empire, and if Tanaris&Zul'farrak are not in de-jure Zul'farrak empire, Tanaris&Zul'farrak will not drift into Zul empire.

<details>

![ck2_5](https://user-images.githubusercontent.com/46576860/57639415-91ad5980-75b8-11e9-9bae-defcfd03aa13.png)

</details>

**Comment by Velius94** [comment]
It's more or less the case of Zul replacing all de-jure empires since they are obsolete at this point.
