### ISSUE TITLE
[BUG] | Cenarion Circle title can be usurped

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#359]
**Mod Version**
Master Branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
If you have a vassal with Cenarion Circle title, you can revoke Cenarion Circle.
Game will end if leader of Cenarion Circle society die

**Steps to reproduce the issue:**
Make a holder of Cenarion Circle your vassal (for example, through nomadic subjugation)
Revoke Cenarion Circle title
Kill Cenarion Circle society leader

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![ck2_12](https://user-images.githubusercontent.com/46576860/57618816-0ff40680-758d-11e9-8e8b-207ba73df71c.png)

</details>

**Comment by sejtalk** [comment]
fixed
