### ISSUE TITLE
[BUG] | Character can turn into a demon multiple times

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#360]
**Mod Version**
eeb984b6

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
If you have enough fel corruption for turing into a demon, and you get more, you will turn into a demon multiple times

**Steps to reproduce the issue:**
Have 95 or more fel corruption (but less than 100)
Get more fel corruption multiple times

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![](https://cdn.discordapp.com/attachments/406500578231975937/577388394737565706/unknown.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
