### ISSUE TITLE
[BUG] | Fel-tainted characters can be branded as apostates

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#361]
**Mod Version**
eeb984b

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Fel-tainted characters can be viewed as suspicious and then branded as apostates

**Steps to reproduce the issue:**
Use too much fel magic while your char in Shadow Council

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![](https://cdn.discordapp.com/attachments/406500578231975937/577388579920150528/unknown.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
