### ISSUE TITLE
[BUG] | Warchief Gul'dan and the Horde Council

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#362]
**Mod Version**
eeb984b

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Gul'dan will appoint members of Shadow Council to the Horde Council via event even if it's Gul'dan controlling the Horde

**Steps to reproduce the issue:**
Usurp the Horde via faction playing as Gul'dan

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![](https://cdn.discordapp.com/attachments/406500578231975937/577386840730894336/unknown.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
