### ISSUE TITLE
[BUG] | Char can't marry

### ISSUE THREAD

**Issue by Sielentus** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#363]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
Master Branch (https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/pull/352 version)

**What expansions do you have installed?**
all
**Please explain your issue in as much detail as possible:**
my custom char,can't marry

**Steps to reproduce the issue:**
-
**Upload an attachment below: .zip of your save, or screenshots:**
[cant marry.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3175568/cant.marry.zip)
![ck2_1](https://user-images.githubusercontent.com/49923433/57666160-54b88580-75ff-11e9-9205-a39ae9c21d28.png)
![ck2_2](https://user-images.githubusercontent.com/49923433/57666167-5f731a80-75ff-11e9-9e95-43b6f60cffa0.png)
![ck2_3](https://user-images.githubusercontent.com/49923433/57666177-68fc8280-75ff-11e9-90c6-af8fa04f7f3e.png)
![ck2_4](https://user-images.githubusercontent.com/49923433/57666316-da3c3580-75ff-11e9-99b4-95fcb1b93af7.png)

**Comment by zumbak04** [comment]
You char don't have race trait. Couldn't reproduce it, my custom char gets racial on the 2nd day of the game.
![image](https://user-images.githubusercontent.com/46384992/57710372-e36be780-767d-11e9-9795-8c38b838bf4d.png)

**Comment by Sielentus** [comment]
> You char don't have race trait. Couldn't reproduce it, my custom char gets racial on the 2nd day of the game.

hmpf i guess that was the problem. I thought you get the trait direct in game and not after one day passed.
