### ISSUE TITLE
[LOCALIZATION] | no dot

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#365]
**Mod Version**
2f93b1da

**Please explain your issue in as much detail as possible:**
First option desc and tooltip don't have a dot

**Upload screenshots of the problem localization:**

<details>

![ck2_3](https://user-images.githubusercontent.com/46576860/57712647-9d148980-7679-11e9-9bca-d960ae783f9b.png)

</details>

**Comment by zumbak04** [comment]
Fixed!

**Comment by MemeWizard** [comment]
tooltip
<details>

![image](https://user-images.githubusercontent.com/46576860/57815821-b274db00-7781-11e9-8fde-499c697170c0.png)

</details>

**Comment by zumbak04** [comment]
> tooltip

Rule №136: No dots in tooltips

**Comment by MemeWizard** [comment]
weird flex but ok
