### ISSUE TITLE
[LOCALIZATION] | Sunwell power description

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#366]
**Mod Version**
2f93b1d

**Please explain your issue in as much detail as possible:**
Sunwell power description have unnecessary \n in it

>text_effect_sunwell_ruler_convert_county;Can §GBathe in Well Energy§! by right-clicking title shield of High Elven county to convert province religion\n;;;;;;;;;;;;;x

**Upload screenshots of the problem localization:**

<details>

![](https://cdn.discordapp.com/attachments/406500578231975937/577802641883529227/unknown.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
