### ISSUE TITLE
[BUG] | Kaldorei tributaries

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#368]
**Mod Version**
2f93b1da

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Kaldorei tributaries description says that tributary relations can break if either party becomes part of a different realm, but they actually can't, because tributaries don't have such decision

**Steps to reproduce the issue:**
Make Tyrande non-independent

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![](https://cdn.discordapp.com/attachments/406500578231975937/577783811069313025/unknown.png)
![](https://cdn.discordapp.com/attachments/406500578231975937/577784016430956564/unknown.png)
![ck2_3](https://user-images.githubusercontent.com/46576860/57720384-68f59480-768a-11e9-8cf1-697f26f713ab.png)
![image](https://user-images.githubusercontent.com/46576860/57720674-06e95f00-768b-11e9-9ef6-1c9ebfb1b6a8.png)

</details>

**Comment by sejtalk** [comment]
fixed
