### ISSUE TITLE
Re-Origination Request

### ISSUE THREAD

**Issue by SlagartheCruel** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#37]
1.2

Low

While playing in Vol'dun, prosperity level went up to full level and I got the event to increase the holding slot on Sethrellis by 1 for 1200 gold. I spent the gold on two events, but no new building slots appeared.

**Comment by DukeJeans** [comment]
@zumbak04 I thought this event was removed/disabled.

**Comment by zumbak04** [comment]
Nope. I'll disable this event in 1.3 version if I can't find the cause of the issue.

**Comment by zumbak04** [comment]
Fixed.
