### ISSUE TITLE
[LOCALIZATION] | UNHOLY

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#370]
**Mod Version**
919b6ebc

**Please explain your issue in as much detail as possible:**
loa/shamanic/primitive shamanic mans are unholy

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/57881001-e35c1b00-7828-11e9-97df-6802d8219ff3.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
