### ISSUE TITLE
[LOCALIZATION] | Son of %evil god%

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#373]
**Mod Version**
Master Branch

**Please explain your issue in as much detail as possible:**
Many legion/old gods/necromantic rulers are sons of order/light/life

**Upload screenshots of the problem localization:**

<details>

![](https://cdn.discordapp.com/attachments/406500578231975937/516975672636211214/ck2_25.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
