### ISSUE TITLE
Version 1.4.0 keep crashing

### ISSUE THREAD

**Issue by SimYRuler** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#374]
I have installed CK2 v3.1.0 and the mod as suggested but the game is crashing to desktop . I play a little bit , i increase the speed of the game and boom is crashing. I played as Stormwind , first event with the invasion.Can someone have an idea why?

**Comment by zumbak04** [comment]
What's your checksum when you run the mod?

**Comment by SimYRuler** [comment]
Damm , sorry i solved it , yes it was a game instalation problem , Tnx you for asking.

**Comment by zumbak04** [comment]
No problem, you're welcome!
