### ISSUE TITLE
[LOCALISATION] | Runeblade desc

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#375]
**Mod Version**
Master Branch

**Please explain your issue in as much detail as possible:**
Runeblades have no description

**Upload screenshots of the problem localization:**

<details>

![ck2_12](https://user-images.githubusercontent.com/46576860/57973682-804bbf00-79b5-11e9-864f-f76ea4726158.png)

</details>

**Comment by sejtalk** [comment]
Same thing with runeblades (REMINDER)

**Comment by arithon** [comment]
Done together with https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/issues/1036 in LC14
