### ISSUE TITLE
[BUG] | Humans with colonial culture can appear before human sail to Kalimdor

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#376]
**Mod Version**
Republics Branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Humans with colonial culture can appear before human sail to Kalimdor

**Steps to reproduce the issue:**
Check court physicians

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![ck2_16](https://user-images.githubusercontent.com/46576860/57973746-6363bb80-79b6-11e9-8eee-89781f6c8e48.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
