### ISSUE TITLE
[BUG] | Interracial divorce effect don't check character age

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#377]
**Mod Version**
Republic Branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Interracial divorce effect don't check character age, so after divorce underage characters will be forced to marry

**Steps to reproduce the issue:**
arrange interracial betrothal

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![ck2_11](https://user-images.githubusercontent.com/46576860/57973842-abcfa900-79b7-11e9-95cc-ced4277e170a.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
