### ISSUE TITLE
[BUG] | Arthas ain't getting the option for Frostmourne anymore.

### ISSUE THREAD

**Issue by geffe1** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#379]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
Masterbranch.
**What expansions do you have installed?**
ALL
**Please explain your issue in as much detail as possible:**
Mr Arthas won't get his frostmourne anymore, so he won't kill his father if you play as him. 
**Steps to reproduce the issue:**
Play as Arthas.
**Upload an attachment below: .zip of your save, or screenshots:**
![ck2_47](https://user-images.githubusercontent.com/31706375/58061047-b2574f80-7b74-11e9-8487-4dc73f34a61f.png)
![ck2_48](https://user-images.githubusercontent.com/31706375/58061052-bbe0b780-7b74-11e9-872e-91e4c52a4378.png)
![ck2_49](https://user-images.githubusercontent.com/31706375/58061056-be431180-7b74-11e9-81b9-e1ee50462875.png)

**Comment by zumbak04** [comment]
Fixed!
