### ISSUE TITLE
[SUGGESTION] | "has unpleasant trait" tooltip gives too little information

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#380]
**Describe your suggestion in full detail below:**

Replace "has unpleasant trait" tooltip with actual trait list, just like list above this tooltip.

<details>

![Безымянный1](https://user-images.githubusercontent.com/46576860/58070996-c797a280-7ba3-11e9-9721-a0750714d23a.png)

</details>

**Comment by zumbak04** [comment]
It's a long list consisting of 11 traits. These conditions would take most of the screen.

**Comment by MemeWizard** [comment]
Alternatively, write a extended custom tooltip, where all "unpleasant " traits will be included

**Comment by zumbak04** [comment]
> Alternatively, write a extended custom tooltip, where all "unpleasant " traits will be included

Implemented!
