### ISSUE TITLE
[BUG] | Useless void corruption event

### ISSUE THREAD

**Issue by MrFoxik** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#384]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.4.0
**What expansions do you have installed?**
All
**Please explain your issue in as much detail as possible:**
Useless and annoying event, which pops up, always when you use void abilities with max corruption.
**Steps to reproduce the issue:**
Get 100% void corruption, use abilities, get that event always as you try pass the limit of corruption.
**Upload an attachment below: .zip of your save, or screenshots:**
![](https://cdn.discordapp.com/attachments/317370173931913217/581240581452333067/unknown.png)

**Comment by zumbak04** [comment]
Fixed!
