### ISSUE TITLE
[LOCALIZATION] | Piety or Impiety.. that is the question for an old god follower.

### ISSUE THREAD

**Issue by geffe1** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#389]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
3.1.1
**Please explain your issue in as much detail as possible:**
Piety gain instead of impiety gain for the old god followers! On their wonder!
**Upload screenshots of the problem localization:**
![ck2_76](https://user-images.githubusercontent.com/31706375/58385123-ae4f8580-7feb-11e9-9f4a-2fa40b465697.png)

**Comment by zumbak04** [comment]
Vanilla thing...
No special names of "Piety" in wonders.
![image](https://user-images.githubusercontent.com/46384992/58385848-da78ff80-8007-11e9-9b00-60423a1ab0ae.png)
