### ISSUE TITLE
[LOCALIZATION] | Capital letter in the beginning of a sentence for the old gods.

### ISSUE THREAD

**Issue by geffe1** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#390]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
3.1.1
**Please explain your issue in as much detail as possible:**
Not a capital letter in the beginning of "the Old Gods be praised!", sadly forgot to use charinfo on this event. Forgive me Zumb.. for I have sinned.
**Upload screenshots of the problem localization:**
![ck2_78](https://user-images.githubusercontent.com/31706375/58385163-5d8c5c80-7fec-11e9-9e1b-c357f7cf54d6.png)

**Comment by zumbak04** [comment]
Fixed!
