### ISSUE TITLE
[CRASH] | Game Crashes When I Run The Mod

### ISSUE THREAD

**Issue by Tytann01** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#393]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.4.0
**Please explain your issue in as much detail as possible:**
Every time i run the mod, it loads up to "Loading Counties" and then the game crashes. Do i need to install any DLC to allow the mod to work.
**Upload screenshots of the problem localization:**

**Comment by zumbak04** [comment]
You use the compatible CK2 version (3.1.0), right? If yes, disable all mods and tell what's your checksum.

**Comment by Tytann01** [comment]
Using 3.1.0 and checksum is KKAD

**Comment by zumbak04** [comment]
Redownload the mod and do clear installation: delete `Paradox Interactive\Crusader Kings II\mod\Guardians of Azeroth` folder. To make sure, delete all folders in `Paradox Interactive\Crusader Kings II\Guardians of Azeroth` except `save games`.

**Comment by DukeJeans** [comment]
One month later, assuming problem is solved
