### ISSUE TITLE
[SUGGESTION] | Allow interracial marriage for small populations

### ISSUE THREAD

**Issue by Ectheldir** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#398]
**DO NOT REMOVE PRE-EXISTING LINES**
----------------------------------------------------------------------------------------------------------
**Describe your suggestion in full detail below:**

It gets pretty hard to marry off family members a few generations into the game, when playing relatively unimportant and small races like Murlocs. And oftentimes even the marriage options you get are fairly questionable, as most of them are at least cousins. 
Also, getting spammed with marriage proposals from Quillboar Khans, which you cannot accept is getting annoying really quickly.

So, for the gameplay purpose and to avert AI dynasties simply dying off or at least thinning out substantially, because they try to marry all their children to incompatible spouses, I suggest to allow at least some of the smaller populated races to marry each other. This probably isn't lore-friendly at all and I am not entirely sure, yet, which races to group, but I think it would help the gameplay a lot.

Maybe group Gnolls and Wolvar, they... look similiar. And murlocs and.... damn... maybe Nagah, they also got... hmmm... scales?

**Comment by MemeWizard** [comment]
Interracial marriages still will be locked behind a interfaith marriage wall, tho.

**Comment by zumbak04** [comment]
There's a game rule where you can allow it.

> Interracial marriages still will be locked behind a interfaith marriage wall, tho.

There's a game rule about it as well.

**Comment by zumbak04** [comment]
Closing the suggestion since the game rules can handle this.
