### ISSUE TITLE
[BUG] | Two Zuluheds

### ISSUE THREAD

**Issue by sejtalk** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#399]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
Master
**What expansions do you have installed?**

**Please explain your issue in as much detail as possible:**
If you invite the remaining clans it creates Dragonmaw clan Zuluhed despite the fact he's already ingame.

**Steps to reproduce the issue:**
Invite the clans form outland

**Upload an attachment below: .zip of your save, or screenshots:**
![zuluhed](https://user-images.githubusercontent.com/31159937/58824196-d36f7400-863b-11e9-9201-c5b497a8c530.png)

**Comment by zumbak04** [comment]
Fixed!
