### ISSUE TITLE
[BUG] | The Legion does not destroy Nordrassil

### ISSUE THREAD

**Issue by Ectheldir** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#402]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.4.0

**What expansions do you have installed?**
Horse Lords
Monks and Mystics
Reaper's Due
Way of Life

**Please explain your issue in as much detail as possible:**
Don't think this is really a bug. More a strange AI behaviour. The Legion has been holding Nordrassil for almost 3 decades by now and still nobody there decided to burn the worldtree. Maybe the Legion AI should be forced to burn down Nordrassil, if they win it? 

**Steps to reproduce the issue:**
Just wait till the Legion captures Nordrassil. And then wait some more... and more... and more...
I don't really know I only noticed it almost 30 Years later

**Upload an attachment below: .zip of your save, or screenshots:**
![Screenshot (46)](https://user-images.githubusercontent.com/51327482/58993544-1d985700-87ee-11e9-85bf-6dacb59a98f0.png)

**Comment by zumbak04** [comment]
Saved needed.

**Comment by Ectheldir** [comment]
[Nordrassil isn't burning.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3260650/Nordrassil.isn.t.burning.zip)

**Comment by zumbak04** [comment]
Fixed!
