### ISSUE TITLE
[BUG] | Unavoidable crash on January 14 611

### ISSUE THREAD

**Issue by Seimour01** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#403]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
Master branch
**What expansions do you have installed?**
All of them
**Please explain your issue in as much detail as possible:**
Game crashes on January 14 611 consistantly
**Steps to reproduce the issue:**
Launch the provided save and play a few days until it crashes. Zumbak already crashed trying.
**Upload an attachment below: .zip of your save, or screenshots:**
https://www.mediafire.com/file/as5ri14j19z19zx/autosave.ck2/file

**Comment by zumbak04** [comment]
Fixed!
