### ISSUE TITLE
"Elemental Worship" Religion switching causes a wrong revolt.

### ISSUE THREAD

**Issue by AltertronSteam** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#41]
Which version of the mod does this apply to?

1.2

How important is this bug/suggestion (Low/Medium/High/Critical)?

Medium

Explain the bug or suggestion below:

When you switch from a religion within an "Elemental Worship" group ( in this case, Stonemother Worship, screenshot Nr.1 ) to something else, it will trigger a revolt led by Majordomo Executus(screenshot Nr.2), a Fire Lord-Religious Head who will then try to win and make you serve Ragnaros instead of your original Elemental Lord(screenshot Nr.3)

Feel free to attach a **.zip** or a **screenshot** of the bug to better help us understand the issue.

![20190121212332_1](https://user-images.githubusercontent.com/34240986/51497561-cb691300-1dc3-11e9-8d2b-26cfdcbe1f9b.jpg)
![20190121212347_1](https://user-images.githubusercontent.com/34240986/51497564-cf953080-1dc3-11e9-8fc8-eb8d89865476.jpg)
![20190121212408_1](https://user-images.githubusercontent.com/34240986/51497589-dae85c00-1dc3-11e9-956c-2481fee8cb2c.jpg)

**Comment by zumbak04** [comment]
Fixed!
