### ISSUE TITLE
[SUGGESTION] | Connection between Theramore and Sentry Point

### ISSUE THREAD

**Issue by BadAspartame** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#410]
**DO NOT REMOVE PRE-EXISTING LINES**
----------------------------------------------------------------------------------------------------------
**Describe your suggestion in full detail below:**

For now Theramore is too disconnected from Kalimdor's politics and Jaina's AI cant make her way through. Also in WoW there was a bridge between those 2 provinces :)

**Comment by zumbak04** [comment]
Implemented!
