### ISSUE TITLE
[SUGGESTION] | Illidari Offworld power becomes Illidan after Arthas becomes Lich King

### ISSUE THREAD

**Issue by Feliprins** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#412]
Illidan becomes offworld power for illidari religion after frozen throne events
----------------------------------------------------------------------------------------------------------
So, since in the frozen throne events illidan loses and goes to outland to lick his wounds, i was thinking that after arthas becoming Lich King there would be an event for ilidan to take power of the offworld for illidari religion,  so simulate him being in outland growing his power.

Before that illidari religion offworld power could get a inactive placeholder with no power.

This allows the illidari to call upon their master after that to stay relevant after fight against scourge if they lose.

**Comment by sejtalk** [comment]
I'm planning on adding offmap outland and i think it would be better to have him rule over it after his defeat.
