### ISSUE TITLE
[SUGGESTION] | Game rule to turn off static portraits

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#413]
**Describe your suggestion in full detail below:**
Title

**Comment by sejtalk** [comment]
added https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/pull/752/commits/9142cfce4bbea6c5ef72619158a8ab1cb13c539b
