### ISSUE TITLE
[LOCALIZATION] | COURTIER_FEMALE_CAP

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#418]
**Mod Version**
b1b3770e

**Please explain your issue in as much detail as possible:**
COURTIER_FEMALE_CAP

**Upload screenshots of the problem localization:**
<details>

![image](https://user-images.githubusercontent.com/46576860/59415959-2fb95d00-8dcd-11e9-8538-dc690d1039ea.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
