### ISSUE TITLE
[BUG] | Founding of Theramore convert ALL your provinces religion&culture

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#419]
**Mod Version**
b1b3770e

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Founding of Theramore convert ALL your provinces religion&culture

**Steps to reproduce the issue:**
Fire founding of Theramore

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![ck2_10](https://user-images.githubusercontent.com/46576860/59418979-a573f780-8dd2-11e9-9375-e84a5073d103.png)
![ck2_11](https://user-images.githubusercontent.com/46576860/59418981-a573f780-8dd2-11e9-9baf-14fdd1167a0b.png)
![ck2_12](https://user-images.githubusercontent.com/46576860/59418982-a60c8e00-8dd2-11e9-8d69-4f1e4334bc25.png)
![ck2_13](https://user-images.githubusercontent.com/46576860/59418983-a60c8e00-8dd2-11e9-8fd3-f7f69b2f4561.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
