### ISSUE TITLE
[BUG] |  WE HAVE ALREADY WON, THE ORCS WILL NOT REMAIN

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#420]
**Mod Version**
b1b3770e

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Orc can say that he won war against the orcs, even if he didn't wage war with orcs.

**Steps to reproduce the issue:**
Start as the Horde
Give dark portal to your son
Give him independence 
Surrender to Stormwind

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![ck2_6](https://user-images.githubusercontent.com/46576860/59419760-37303480-8dd4-11e9-8c3b-4404d2cac68e.png)
![ck2_7](https://user-images.githubusercontent.com/46576860/59419762-37c8cb00-8dd4-11e9-9a71-89d92850fdb7.png)
![ck2_8](https://user-images.githubusercontent.com/46576860/59419763-37c8cb00-8dd4-11e9-9495-9e7b5386fc70.png)
![ck2_9](https://user-images.githubusercontent.com/46576860/59419764-38616180-8dd4-11e9-8446-f234dc3059bb.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
