### ISSUE TITLE
[BUG] | Dark Portal can be destroyed several times

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#421]
**Mod Version**
b1b3770

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Dark Portal can be destroyed several times

**Steps to reproduce the issue:**
Give your vassal Dark Portal

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![ck2_3](https://user-images.githubusercontent.com/46576860/59423035-081cc180-8dda-11e9-9eab-c356a96a3c34.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
