### ISSUE TITLE
[BUG] | Send alcohol gift tooltip

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#422]
**Mod Version**
b1b3770e

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
You can't send alcohol to characters who can't drink, but tooltip don't say anything about ancients.

**Steps to reproduce the issue:**
Build brewery

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/59423565-0ef80400-8ddb-11e9-81b8-219fd836be08.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
