### ISSUE TITLE
[BUG] | wcdac.150 wrong character mention

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#423]
**Mod Version**
2fea5bfb

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
wcdac.150 says that worgen who is raiding me was bitten by wild worgen

**Steps to reproduce the issue:**
Let worgen raid you

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/59498177-8ee6a280-8e9d-11e9-8451-e8922229800e.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
