### ISSUE TITLE
[LOCALIZATION] | ALliance text after forming the Alliance needs to be fixed.

### ISSUE THREAD

**Issue by geffe1** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#426]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
Bug crusade 10, but I am pretty sure it is the same on the master branch.
**Please explain your issue in as much detail as possible:**
Magni is the one who formed the Alliance of Lordaeron, we should change this to just the Alliance, if other non-Terenas people form it.
**Upload screenshots of the problem localization:**
![ck2_229](https://user-images.githubusercontent.com/31706375/59563413-09e4c000-903a-11e9-8aba-e68c0e293436.png)

**Comment by Velius94** [comment]
Corrected. The description should now mention the 'first Alliance' instead.
