### ISSUE TITLE
[BUG] | You can request the gift multiple times

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#427]
**Mod Version**
4aa4d39b

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
You can request the gift multiple times

**Steps to reproduce the issue:**
request the gift multiple times

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/59566655-ae332a80-906b-11e9-89bd-d9bebfc11135.png)

</details>

**Comment by sejtalk** [comment]
fixed
