### ISSUE TITLE
[BUG] | This Two-headed ogre don't have two heads.

### ISSUE THREAD

**Issue by geffe1** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#429]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
Bug crusade 10, however pretty sure I have seen this guy in the master branch with only one head.
**What expansions do you have installed?**
ALL
**Please explain your issue in as much detail as possible:**
Two headed ogre got one head.
**Steps to reproduce the issue:**
Play as Gul'dan or any other person who occupied the dark portal and let the laughing skull join you.
**Upload an attachment below: .zip of your save, or screenshots:**
![ck2_237](https://user-images.githubusercontent.com/31706375/59568879-e04f8700-9081-11e9-8be7-3a2af086278a.png)

**Comment by zumbak04** [comment]
Fixed!
