### ISSUE TITLE
[LOCALIZATION] | Too long response to the Horde eventchain about the dark portal.

### ISSUE THREAD

**Issue by geffe1** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#430]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
Bug crusade 10.
**Please explain your issue in as much detail as possible:**
Event response is too long. Also most of these needs to be rewritten either way- a lot of errors that needs to be looked at and changed.
**Upload screenshots of the problem localization:**
![ck2_238](https://user-images.githubusercontent.com/31706375/59568890-0d039e80-9082-11e9-8e9e-093fec0b95f9.png)

**Comment by zumbak04** [comment]
Fixed!
