### ISSUE TITLE
[BUG] | negative demesne size modifier don't work

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#435]
**Mod Version**
8964433d

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
negative demesne size from religion don't work

**Steps to reproduce the issue:**
check Dalaran demesne size

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/59713638-9056f880-9218-11e9-9c2a-0319535d65ce.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
