### ISSUE TITLE
[SUGGESTION] | Class Immortality as separate trait

### ISSUE THREAD

**Issue by SlaveToUnreason** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#438]
**DO NOT REMOVE PRE-EXISTING LINES**
----------------------------------------------------------------------------------------------------------
**Describe your suggestion in full detail below:**
Given that level up system (or changing from one class to another) right now removes old class trait and adds a new one instead, character can become immortal at a young age, then advance to the next level of their class while being old, and the game will count it as if they became immortal just now. To fix this, I propose making class immortality a separate trait.

**Comment by zumbak04** [comment]
Found another experimental way to fix it. Fixes the issues you mentioned here, but also if you get immortal trait when you are already old, it will rejuvenate you.
https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/commit/4b5139d54460906764937c0d13c4702ac47b15cf

**Comment by zumbak04** [comment]
Closing the issue. If you think, immortal age is still problematic, reopen the issue or open a new one.
