### ISSUE TITLE
[BUG] | Demonic CC

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#440]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
#434
**What expansions do you have installed?**
All
**Please explain your issue in as much detail as possible:**
Leader of CC can change government type.

**Steps to reproduce the issue:**
1) Become Legion/Scourge/Old Gods follower
2) Change government type via decision

**Upload an attachment below: .zip of your save, or screenshots:**
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/59936530-4e6cc300-9461-11e9-8b68-8f30b51a2716.png)

</details>

**Comment by sejtalk** [comment]
fixed
