### ISSUE TITLE
[BUG] | Legion CC

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#441]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
#434

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Druids that follow the Legion are still part of the CC society.

**Steps to reproduce the issue:**
1) Be druid
2) Convert to Legion
3) Become Lord of the Legion

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/59936856-131ec400-9462-11e9-822c-c317ef903abf.png)

</details>

**Comment by sejtalk** [comment]
fixed
