### ISSUE TITLE
[BUG] | Courtiers don't take child with them when they asked to leave court

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#442]
**Mod Version**
d90d2a07

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Courtiers don't take child with them when they asked to leave court.

**Steps to reproduce the issue:**
Ask courtier with child to leave court

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/59946141-613bc380-9472-11e9-91cb-91c34bf9ef50.png)
![image](https://user-images.githubusercontent.com/46576860/59946153-6993fe80-9472-11e9-8f97-09c86c0de1c3.png)

</details>

**Comment by zumbak04** [comment]
The same happens in the vanilla. Waiting for Paradox to fix it.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/59948328-c1396680-9480-11e9-9628-77238bb3818f.png)

</details>
