### ISSUE TITLE
[BUG] | EVTOPTA_JD_10070_dying

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#443]
**Mod Version**
Master branch

**Please explain your issue in as much detail as possible:**
Immortal chars can get EVTOPTA_JD_10070_dying

**Upload screenshots of the problem localization:**

<details>

![ck2_3](https://user-images.githubusercontent.com/46576860/59968261-99f59e80-953f-11e9-88f7-7510bd416f86.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
