### ISSUE TITLE
[BUG] | Dragonflight have no government icon

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#444]
**Mod Version**
Master Branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Dragonflight have no government icon

**Steps to reproduce the issue:**
Check Dragonflight government icon

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/59968357-53a13f00-9541-11e9-8569-6d93df089049.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
