### ISSUE TITLE
[LOCALIZATION] | Tip is too long

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#445]
**Mod Version**
b743e51e

**Please explain your issue in as much detail as possible:**
Tip is too long for tip box

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/59968938-12ae2800-954b-11e9-966d-4c713977d7d1.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
