### ISSUE TITLE
[BUG] | Ancient's childrens are night elves

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#448]
**Mod Version**
b743e51e

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Ancient's childrens are night elves

**Steps to reproduce the issue:**
Adopt child as Ancient

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/59971690-c0d8c280-9589-11e9-9d1f-d60aebfbbc9c.png)
![image](https://user-images.githubusercontent.com/46576860/59971693-c504e000-9589-11e9-8b97-dd559e36e07a.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
