### ISSUE TITLE
[LOCALIZATION] | gardens_of_planet

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#450]
**Mod Version**
b743e51e

**Please explain your issue in as much detail as possible:**
gardens_of_planet book have RL planets in localization

**Upload screenshots of the problem localization:**

<details>

![ck2_6](https://user-images.githubusercontent.com/46576860/59976833-7465a500-95d2-11e9-87ff-aeb2ef2ffb20.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
