### ISSUE TITLE
[BUG] | bad vooodo is too bad

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#451]
**Mod Version**
b743e51e

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
1. You really shouldn't see curser's portrait
2. Chars with 90+ opinion of you really shouldn't curse you

**Steps to reproduce the issue:**
Let your vassals follow da wae of de loa

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![ck2_9](https://user-images.githubusercontent.com/46576860/59976852-af67d880-95d2-11e9-84f8-e2f219d784b2.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
