### ISSUE TITLE
[LOCALIZATION] | Hold Blood Ritual tooltip

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#452]
**Mod Version**
b743e51e

**Please explain your issue in as much detail as possible:**
This tooltip is too long

**Upload screenshots of the problem localization:**

<details>

![ck2_12](https://user-images.githubusercontent.com/46576860/59976938-e8547d00-95d3-11e9-80d9-156c8581fe0e.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
