### ISSUE TITLE
[BUG] | Necronomicon don't disappear after owner death

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#453]
**Mod Version**
b743e51e

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Necronomicon don't disappear after owner death

**Steps to reproduce the issue:**
1) Get Necronomicon
2) Die

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/59977000-92cca000-95d4-11e9-8743-cd5b792564bf.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
