### ISSUE TITLE
[BUG] | Rulers keep alliances after fraction defeat

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#454]
**Mod Version**
22c26fb6

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Rulers keep alliances after fraction defeat

**Steps to reproduce the issue:**
Fraction must be destroyed

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/59977172-a24ce880-95d6-11e9-8426-5d34c049d185.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
