### ISSUE TITLE
[BUG] | Scarlet Crusade can trigger even if there is no threat for Lordaeron

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#455]
**Mod Version**
22c26fb

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Scarlet Crusade can trigger even if there is no threat for Lordaeron

**Steps to reproduce the issue:**
Lordaeron ruler must defeat Ner'zhul

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/59977608-c828bc00-95db-11e9-86ba-eec887aacdb8.png)

</details>

**Comment by zumbak04** [comment]
Reworked this event. For more details, take a look at the mentioned commit.
