### ISSUE TITLE
[BUG] | Demons can be sacrificed to Hakkar

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#456]
**Mod Version**
b743e51e

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Demons can be sacrificed to Hakkar

**Steps to reproduce the issue:**
Have a demon in your prison
Click on "Hold Blood Ritual" decision

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/59978644-3b83fb00-95e7-11e9-9054-c8320eb181b6.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
