### ISSUE TITLE
[SUGGESTION] | Swap current and change corruption value position in tooltip

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#457]
**Describe your suggestion in full detail below:**

Don't you think that "Current corruption" position in tooltip should be first and "Corruption change" should be second? It's more comfortable to look that way, innit?

<details>

![image](https://user-images.githubusercontent.com/46576860/59979389-f9ab8280-95ef-11e9-9db3-914a688d8f14.png)

</details>

**Comment by zumbak04** [comment]
Implemented!
