### ISSUE TITLE
[BUG] | Patrician houses have de-jure suzerains

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#458]
**Mod Version**
5de551ed

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Patrician houses have de-jure suzerains

**Steps to reproduce the issue:**
No need

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/60105322-c988ee80-976b-11e9-91c7-c4c78fb986b9.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
