### ISSUE TITLE
[BUG] | Scourge can't declare war on the Alliance

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#459]
**Mod Version**
39a5cd73

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Scourge can't declare war on the Alliance

**Steps to reproduce the issue:**
Alliance must be formed before plague of Lordaeron

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/60215249-e575b880-986f-11e9-8e0a-dbcba495887d.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
