### ISSUE TITLE
[BUG] | Arthas don't have education

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#460]
**Mod Version**
f3a6e800

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Arthas don't have education

**Steps to reproduce the issue:**
Load 603 bookmark

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/60219343-bca6f080-987a-11e9-97db-5304cb54eb26.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
