### ISSUE TITLE
[BUG] | unlike in vanilla, trade posts don't have garrison

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#463]
**Mod Version**
f3a6e800

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Trade posts don't have garrison, so they surrender siege instantly

**Steps to reproduce the issue:**
No need

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/60392648-03614880-9b10-11e9-9479-6c9310f09274.png)

</details>

**Comment by DukeJeans** [comment]
Fixed in 5b131234.
