### ISSUE TITLE
[LOCALIZATION] | Cenarion Circle

### ISSUE THREAD

**Issue by geffe1** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#464]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
Masterbranch
**Please explain your issue in as much detail as possible:**
Claims I play as a republic as Malfurion when trying to revoke a vassal's land.
**Upload screenshots of the problem localization:**
![ck2_268](https://user-images.githubusercontent.com/31706375/60401698-a1dbc100-9b85-11e9-998e-31f0ed0b0b2a.png)

**Comment by zumbak04** [comment]
Fixed!
