### ISSUE TITLE
[LOCALIZATION] | Sea name is bad.

### ISSUE THREAD

**Issue by geffe1** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#465]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
MASTER BRANCH
**Please explain your issue in as much detail as possible:**
Sea got bad name, pls change to Forbidden sea.
**Upload screenshots of the problem localization:**
![ck2_272](https://user-images.githubusercontent.com/31706375/60403709-37387e80-9ba1-11e9-8423-b1aa1ff826f3.png)

**Comment by zumbak04** [comment]
Waaait a min... It's real name.
https://wow.gamepedia.com/Forbidding_Sea
