### ISSUE TITLE
[BUG] | Undead Hyldnir Queens are Kings

### ISSUE THREAD

**Issue by DukeJeans** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#469]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
51faf23

**What expansions do you have installed?**
All w/o JD

**Please explain your issue in as much detail as possible:**
Undead Hyldnir Queens are labeled Kings

**Steps to reproduce the issue:**
Grant a king level title to a Hyldnir Undead woman. In this case, Valkyrion.

**Upload an attachment below: .zip of your save, or screenshots:**
![image](https://user-images.githubusercontent.com/32686241/60665493-97921f00-9e32-11e9-8993-a22bf5afad8d.png)

**Comment by zumbak04** [comment]
Fixed!
