### ISSUE TITLE
[BUG] | Can't mentor children

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#472]
**Mod Version**
4297099d

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
My char can't teach his son how to be a paladin.

**Steps to reproduce the issue:**
Start as Thoras, become self-taught paladin, try to mentor son.

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/60694108-a4bc1600-9ee5-11e9-9538-0e3f0b47245e.png)

</details>

[Stromgarde589_02_21.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3360890/Stromgarde589_02_21.zip)

**Comment by zumbak04** [comment]
Fixed!
