### ISSUE TITLE
[BUG] | Muslims

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#473]
**Mod Version**
4297099d

**Please explain your issue in as much detail as possible:**
Holy war CB description talks about muslims.

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/60701683-39823c00-9f05-11e9-99c5-498267d68e8b.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
