### ISSUE TITLE
[BUG] | Nethergarde can get titles that don't belong to dark portal owner

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#474]
**Mod Version**
4297099d

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Ironforge is a dark portal owner, but upon creation, Nethergarde get duchy that belongs to the reformed Horde

**Steps to reproduce the issue:**
_

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/60696316-e486fb80-9eed-11e9-96d0-b0c13007234f.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
