### ISSUE TITLE
[BUG] | The Death Knights

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#475]
**Mod Version**
4297099d

**Please explain your issue in as much detail as possible:**

`>` Did the unthinkable
`>` But Ner'zhul already did it before

`>` 90 years passed since Stormwind returned to the humans hand
`>` Knights corpses still in good condition

`>` The Horde is no longer crazy demon-blood infused peons
`>` Corpses become a elite warriors of the New Horde

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/60721320-33f11a00-9f36-11e9-8fa3-e9cda40aef24.png)

</details>

**Comment by zumbak04** [comment]
Fixed1
