### ISSUE TITLE
[BUG] | Sunwell Cult leader is landless

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#478]
**Mod Version**
55083b85

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Sunwell Cult leader is landless

**Steps to reproduce the issue:**
_

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/60827122-264ac700-a1b8-11e9-96ad-320427794633.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
