### ISSUE TITLE
[LOCALIZATION] | Event WCSAD.30 Spelling Error, ENG

### ISSUE THREAD

**Issue by Doronamo** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#481]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**: Patch 1.4.0

**What expansions do you have installed?**: All

**Please explain your issue in as much detail as possible:** First decision for Earth Mother Ritual has a spelling error. [Prepare a ritual to Eart Mother] should be [Prepare a ritual to Earth Mother].

**Steps to reproduce the issue:** Run event WCSAD.30 (Earth Mother Ritual decision).

**Upload an attachment below: .zip of your save, or screenshots:**
![CK2 Earthmother bug](https://user-images.githubusercontent.com/2343263/60920933-36ad8100-a24e-11e9-820c-76f8e0a10887.png)

**Comment by sejtalk** [comment]
fixed
