### ISSUE TITLE
[BUG] | Blank provinces on Linux(?)

### ISSUE THREAD

**Issue by BadAspartame** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#485]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
Early Access

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Some provinces are blank and without any rulers. 
Here is the *probably* complete list of them:
- zeb'watha
- tor'watha
- pele'ahjin
- zul'mashar
- quel'lithien
- whispering forest
- quel'danil
- shadra'alor
- jintha'alor
- lower jintha'alor
- zul'kunda
- zul'marash
- van'keiki
- zul'mamwe
- jin'kalak
- ominous island
- mugamba
- drak'zin
- zeb'halak
- zim'abwa
- drak'sotra
- heb'valok
- chaga'jin
- zim'torga
- drak'mabwa
- zim'rhuk
- heb'drakkar
- zol'maz
- dubra'jin
- zol'heb
- ulduar
- terrace of makers
- world's precipe
- an'barhan
- hive'regal
- hive'zora
- hive'ashi
- jamba'rrak
- sand'peak
- el'dratir
- dor'danil
- ordil'anar 
- ameth'aran
- bashal'aran
- emer'aran
- morlos'aran
- bwon'alor
- shadra'dar
- kel'theril
- snow'daril
- nae'danar
I hope that's all.

**Steps to reproduce the issue:**
Launch the mod on Linux

**Upload an attachment below: .zip of your save, or screenshots:**
![Zrzut ekranu z 2019-07-11 14-10-48](https://user-images.githubusercontent.com/51532738/61050009-43fd7380-a3e6-11e9-855d-4096891fcf47.png)
![Zrzut ekranu z 2019-07-11 14-11-32](https://user-images.githubusercontent.com/51532738/61050017-46f86400-a3e6-11e9-8ddc-40037397b494.png)

**Comment by zumbak04** [comment]
You use Github Desktop? If you do, is it the master branch? If it's, what's your checksum in the main menu of the game?

**Comment by BadAspartame** [comment]
Same happend when i tried to play last time around ~3weeks ago. I dont use Github Desktop because it's not for Linux, i use other SVN and used standard link for clone https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth.git, so yeah, its rather master branch. My checksum is VPFN and the same happens when i download .zip and unpack instead of clone so its not SVN bug.

**Comment by zumbak04** [comment]
What's your CK2 version?

**Comment by zumbak04** [comment]
Also, delete cashe. Windows store it in `Documents\Paradox Interactive\Crusader Kings II\Guardians of Azeroth`. Delete everything except `save games` folder.

**Comment by BadAspartame** [comment]
My game version is 3.2.1 and i already removed the cashe

**Comment by zumbak04** [comment]
What checksum you see when you run the vanilla?

**Comment by BadAspartame** [comment]
My checksume playing vanilla is AZCE

**Comment by zumbak04** [comment]
Ok, the current master should have PSST checksum. Try to redownload it.

**Comment by BadAspartame** [comment]
I still have VPFN

**Comment by BadAspartame** [comment]
Are You sure with this checksum? I have still the same even when i remove folder with mod and download packed .zip from github mod's site.

**Comment by zumbak04** [comment]
Will see. If you have another Linux or friend with Linux, try to test it there. I asked Mac tester to check checksum.

**Comment by BadAspartame** [comment]
Sadly im the only linux CK2 player among my friends.

**Comment by zumbak04** [comment]
I doubt that checksum may be different because it's just Linux. Also, these provinces get colonized after the start?

**Comment by BadAspartame** [comment]
No, they dont.

**Comment by BadAspartame** [comment]
Oh! i found the fix,

**Comment by BadAspartame** [comment]
Its because of Linux filesystem

**Comment by BadAspartame** [comment]
The linux differs between letters size and for example in /history/provinces province of Quel'donil is named QuelDonil instead of Queldonil. After rename province works like it should. 
![Zrzut ekranu z 2019-07-11 18-08-46](https://user-images.githubusercontent.com/51532738/61067045-f9402380-a406-11e9-919c-fd0c41f05e06.png)

**Comment by zumbak04** [comment]
Just kek.

**Comment by zumbak04** [comment]
Ok, that we can fix.

**Comment by BadAspartame** [comment]
Btw. here i found the fix https://www.tapatalk.com/groups/citadel/lonmont-and-other-inactive-provinces-on-linux-with-t13475.html

**Comment by BadAspartame** [comment]
i fill fix the provinces and send you back if you want

**Comment by zumbak04** [comment]
Try to fix provinces without apostrophe since I ain't sure why they not working. Like Ominous Island and Whispering Gardens.
Also, these provinces...

> * ulduar
> * terrace of makers
> * world's precipe

...are fine. They're empty in Windows too.

**Comment by zumbak04** [comment]
> Try to fix provinces without apostrophe since I ain't sure why they not working. Like Ominous Island and Whispering Gardens.

Get it. It's Whispering Forest, not Gardens. And it's empty as it should be. My bad. Also, looks like I know why Ominous Island not working. So, I'll fix it when done with other tasks. No need to fix it by yourself.

**Comment by BadAspartame** [comment]
I dont know how to fix Omonus Island, but i already fixed the rest (i hope) of the broken provinces. Less work for you and i already can play ;)
[provinces.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3383108/provinces.zip)

**Comment by BadAspartame** [comment]
And ofc. already forgot about one :p 
[3202 - Atelanor.txt](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3383116/3202.-.Atelanor.txt)

**Comment by zumbak04** [comment]
@BadAspartame, please, try this branch...
https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/archive/small-province-rename.zip
...and tell me if it's fixed or not.

**Comment by BadAspartame** [comment]
Yes, its fixed. I see no blank provinces, including Ominous Island :)

**Comment by zumbak04** [comment]
If you find moar provinces, reopen this issue or open a new one.
