### ISSUE TITLE
[LOCALIZATION] | powerful artifacts

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#488]
**Mod Version**
7e25973d

**Please explain your issue in as much detail as possible:**
AI can erase borders between Azeroth and Twisting nether with great magic and powerful artifacts, without powerful artifacts.

**Upload screenshots of the problem localization:**
<details>

![image](https://user-images.githubusercontent.com/46576860/61145621-9622bf80-a4e0-11e9-8dca-d65b7cd4dc82.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
