### ISSUE TITLE
[LOCALIZATION] | Orc clans can not be inherited by another dynasty in the usual way

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#489]
**Mod Version**
dede94d5

**Please explain your issue in as much detail as possible:**
This is simply not true

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/61170153-acc32800-a56d-11e9-9192-207a62f4bbd7.png)
![image](https://user-images.githubusercontent.com/46576860/61170184-f1e75a00-a56d-11e9-9d80-deb0285a7082.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
