### ISSUE TITLE
[LOCALIZATION] | the Void

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#491]
**Mod Version**
dede94d5

**Please explain your issue in as much detail as possible:**
the Void

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/61175757-8331ed00-a5bd-11e9-9e7c-0ea31b197160.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
