### ISSUE TITLE
[BUG] | Game offer kaldorei men to become the priestess of Elune

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#494]
**Mod Version**
850ea51e

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Game offer kaldorei men to become the priestess of Elune, because "female" condition are in "allow" block instead of "potential"

**Steps to reproduce the issue:**
Be male kaldorei

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/61186314-791af780-a66c-11e9-876a-a9d1444d962e.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
