### ISSUE TITLE
[SUGGESTION] | "Pray to Elune" decision is useless

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#495]
Every 3 years you just click on decision to get 10 piety and minor opinion modifier and *that's all*
There is *nothing* interesting in this decision

**Comment by zumbak04** [comment]
On it. Here's my plan:
Rework the decision and make reference to Tyrande's night warrior: most likely giving an option to pick either the dark or light side of Elune giving traits and bonuses/maluses.

Thinking about making it religious branches.
