### ISSUE TITLE
[SUGGESTION] | CC hospital quest

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#497]
You will never be given the mission to build a hospital if you already have at least one.
How about change it?

https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/pull/255/files/2a1d3c8e95a0793060989aa4298a54bf761f9ada#r277071422

**Comment by zumbak04** [comment]
Done in 5157b071562362122671672fbbacbbc8416b68b3.
