### ISSUE TITLE
[SUGGESTION] | Let the Lich-King mindcontrol Arthas

### ISSUE THREAD

**Issue by Ectheldir** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#502]
**DO NOT REMOVE PRE-EXISTING LINES**
----------------------------------------------------------------------------------------------------------
**Describe your suggestion in full detail below:**

It's a bit weird that Arthas can choose to keep the kingdom of Lordareon after he picks up Frostmourn and fight on in the war against the Scourge and thus keep himself independent from the Lich King.

As far as I know, the Lich King should be mind controlling Arthas through the sword, which would give him no choice, but to hand Lordareon over to the Lich King.
I am not sure what exactly the mind control effect (from the ability) does, but it seems as if the sufferer of that effect has to agree with every demand of the caster. So, maybe just give that effect to Arthas as soon as he picks up Frostmourn?

**Comment by MemeWizard** [comment]
AI Arthas or Player Arthas?

Mind control effect don't affect player.

**Comment by zumbak04** [comment]
Yep, players do what they want no matter what. Let's say that their minds are too corrupted :3

**Comment by zumbak04** [comment]
Since it's impossible to implement suggestion, I'm closing it. If you have another idea, reopen the issue or open a new one.
