### ISSUE TITLE
[BUG] | Bells active condition is wrong

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#503]
**Mod Version**
b6c05597

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Condition must be NOT Light/Arakkoa/Tidemother

**Steps to reproduce the issue:**
Loot Bells

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/61223157-cc508100-a724-11e9-8575-385e549c0f72.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
