### ISSUE TITLE
[BUG] | Horde usurp Brotherhood of the Horse castles

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#504]
**Mod Version**
b6c05597

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Horde can usurp Brotherhood of the Horse castles, no matter where they are

**Steps to reproduce the issue:**
Brotherhood of the Horse must have castles before end of First War

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/61223964-5a793700-a726-11e9-98bb-09f3cb153b27.png)
![image](https://user-images.githubusercontent.com/46576860/61224021-754bab80-a726-11e9-9aff-1ed166140355.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
