### ISSUE TITLE
[LOCALIZATION] | Power of the book

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#507]
**Mod Version**
b6c05597

**Please explain your issue in as much detail as possible:**
What book?

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/61243157-071bde80-a750-11e9-8c24-0e1d2ff63a42.png)

</details>

**Comment by DukeJeans** [comment]
THE book

**Comment by zumbak04** [comment]
Fixed!
