### ISSUE TITLE
[BUG] | Holy Light Scourge

### ISSUE THREAD

**Issue by Myth1598** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#509]
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.4.0.
**What expansions do you have installed?**
All
**Please explain your issue in as much detail as possible:**
Scourge leaders following Holy Light
**Steps to reproduce the issue:**
Several of them just pop up after destroying the Scourge
**Upload an attachment below: .zip of your save, or screenshots:**

![ck2_2](https://user-images.githubusercontent.com/52759116/61316819-09d70c00-a802-11e9-8422-e9d1cde014ee.jpg)

**Comment by zumbak04** [comment]
It's not a bug. They can follow any religion.
