### ISSUE TITLE
[SUGGESTION] | Bad Idea: use the buggy CK2 to EU4 converter to convert the CK2 GoA map to the EU4 Warcraft Universalis map

### ISSUE THREAD

**Issue by Darkmark8910** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#510]
**DO NOT REMOVE PRE-EXISTING LINES**
----------------------------------------------------------------------------------------------------------
It's a terrible idea, but a madman did update the Warcraft Universalis mod. Might be fun?

**Comment by MemeWizard** [comment]
>It's a terrible idea

Can't argue with that

**Comment by zumbak04** [comment]
Me too, especially since converting happens in EU4 and you should ask them, not us.
