### ISSUE TITLE
[LOCALIZATION] | Non-centaur nomad government loc

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#512]
**Mod Version**
02fcc8fa

**Please explain your issue in as much detail as possible:**
Mod think that any nomad is a centaur

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/61327641-12d7d580-a822-11e9-8e0c-93d2acdd7ef1.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
