### ISSUE TITLE
[BUG] | Strange behavior of society government

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#519]
**Mod Version**
0ea83d7a

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Society government AI build tribal holding in every province

**Steps to reproduce the issue:**
Check AI behavior

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/61349739-d4680800-a86d-11e9-9c87-c0f40b336b6b.png)
![image](https://user-images.githubusercontent.com/46576860/61349752-dc27ac80-a86d-11e9-91b4-3bdf9b3b0874.png)
![image](https://user-images.githubusercontent.com/46576860/61349906-712aa580-a86e-11e9-8cd0-0d3a96951cf9.png)
![image](https://user-images.githubusercontent.com/46576860/61349911-7687f000-a86e-11e9-9458-db848ae23a31.png)
![image](https://user-images.githubusercontent.com/46576860/61349919-7b4ca400-a86e-11e9-96c5-ed00bf6d3071.png)
![image](https://user-images.githubusercontent.com/46576860/61349921-7ee02b00-a86e-11e9-96f4-6fd22f73680d.png)

</details>

**Comment by MemeWizard** [comment]
Also, ruler of CC revoke titles from barons with different culture, e.g. night elf revoke baronies from dryads and visa versa.

**Comment by zumbak04** [comment]
Fixed!
