### ISSUE TITLE
[LOCALIZATION] | Holy Faith

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#522]
**Mod Version**
00c310dd

**Please explain your issue in as much detail as possible:**
event 20023 loc - unholy man spread holy faith

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/61414098-d1b0f580-a8f5-11e9-8ab2-42e7b70674bc.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
