### ISSUE TITLE
[LOCALIZATION] | The Cult of the Damned mana

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#524]
**Mod Version**
bded889a

**Please explain your issue in as much detail as possible:**
The Cult of the Damned mana name is too big for text box

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/61572249-33fb2900-aaa3-11e9-8803-4bc1f6b36476.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
