### ISSUE TITLE
[Suggestion] | Characters Clones

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#527]
**Mod Version**
d49cc02c

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
There are clones of characters in dynasty trees

**Steps to reproduce the issue:**
Start from 583 and wait until characters will spawn

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![ck2_3](https://user-images.githubusercontent.com/46576860/61591927-d5ce6300-abd4-11e9-825d-c8330c67a90d.png)
![ck2_4](https://user-images.githubusercontent.com/46576860/61591929-d666f980-abd4-11e9-91b2-359281acafb6.png)
![ck2_5](https://user-images.githubusercontent.com/46576860/61591930-d666f980-abd4-11e9-9ce3-b1628a646558.png)

</details>

**Comment by zumbak04** [comment]
It's fine if they're not alive at the same time. One character is used in the second bookmark. Other one spawns if you start from the first bookmark.

**Comment by MemeWizard** [comment]
Then how about duplicate dynasties?
It is not aesthetically pleasing to see a clone of a character in a dynasty tree.
