### ISSUE TITLE
[LOCALIZATION] | Religious change rule

### ISSUE THREAD

**Issue by geffe1** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#528]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
Master branch
**Please explain your issue in as much detail as possible:**
Text name.
**Upload screenshots of the problem localization:**
https://gyazo.com/338a6ff062c6edbc49f189f2cf430946
There are two of these rules being like this.

**Comment by MemeWizard** [comment]
>RULE_INVADERS_STRENGTH_DARK;Dark;;;;;;;;;;;;;x
RULE_INVADERS_STRENGTH_DARK_DESC;Followers of dark religion that follow Fel, Void or Necromantic ways can't change their religion.;;;;;;;;;;;;;x
RULE_INVADERS_STRENGTH_OFF;Free;;;;;;;;;;;;;x
RULE_INVADERS_STRENGTH_OFF_DESC;Only vanilla game restrictions are active.;;;;;;;;;;;;;x

For some reason, loc is named `RULE_INVADERS_STRENGTH`, not `RULE_RELIGION_CHANGE`

**Comment by MemeWizard** [comment]
fixed in b71398f1
