### ISSUE TITLE
C'Thun can be awakened twice

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#53]
Performance jihad branch
Medium

If you awaken C'Thun through decision, after 25 years from the start of the game, he will wake up again.

<details>
<summary>Click to expand</summary>

![ck2_2](https://user-images.githubusercontent.com/46576860/51749122-94467a80-20bf-11e9-815d-888f335aca09.png)

</details>

**Comment by zumbak04** [comment]
Fixed.
