### ISSUE TITLE
[BUG] | Fired from council before game started

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#530]
**Mod Version**
ae144aa6

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Game just started, but the Horde vassals already hate warchief because he fired them from council.
Same with Stormwind and Brotherhood of the Horse

**Steps to reproduce the issue:**
Start playing

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/61597728-7ac05e80-ac1c-11e9-8476-a5d5c3c4142d.png)
![image](https://user-images.githubusercontent.com/46576860/61597766-ddb1f580-ac1c-11e9-95e6-79786411f363.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
