### ISSUE TITLE
[BUG] | Undead can enjoy blessing of the Light

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#531]
**Mod Version**
ae144aa6

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Undead can get bonuses from Mark of Light

**Steps to reproduce the issue:**
Cast Mark of Life on yourself before turning undead

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/61598106-62067780-ac21-11e9-9227-dd4e56035c21.png)

</details>

**Comment by zumbak04** [comment]
Fixed!

**Comment by MemeWizard** [comment]
What about Elune's Blessing?

**Comment by zumbak04** [comment]
Fixed!
