### ISSUE TITLE
[BUG] | all gnomish children use female portraits

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#537]
**Mod Version**
50e9eaa6

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
There is no portraits for gnomish boys

**Steps to reproduce the issue:**
`---`

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/61737722-7ec1bd00-ad91-11e9-82f4-c14c4ade0383.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
