### ISSUE TITLE
[BUG] | Creation of Nethergarde crash the game

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#538]
**Mod Version**
50e9eaa6

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Creation of Nethergarde crash game

**Steps to reproduce the issue:**
Load save

**Upload an attachment below: .zip of your save, or screenshots:**

[r_crash.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3423580/r_crash.zip)

**Comment by zumbak04** [comment]
Fixed!
