### ISSUE TITLE
My character can sacrifice a prisoner who is in the prison of another character.

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#54]
Master branch
Medium

My character can sacrifice a captive who is not in his prison.

<details>
<summary>Click to expand</summary>

![ck2_9](https://user-images.githubusercontent.com/46576860/51749724-3450d380-20c1-11e9-9617-bcf21969453d.png)

</details>

**Comment by zumbak04** [comment]
Fixed.
