### ISSUE TITLE
[SUGGESTION] | Formable kor'kron guard

### ISSUE THREAD

**Issue by Galvador1** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#540]
**DO NOT REMOVE PRE-EXISTING LINES**
----------------------------------------------------------------------------------------------------------
**Describe your suggestion in full detail below:**

Incorporate varangian formation event for korkron guard formation. I'm not sure about the culture locking, but the religion have to be either defined in landed titles or the religion of orgrimmar county, which might curb any chance of non-orc captain.

**Comment by zumbak04** [comment]
Implemented!
