### ISSUE TITLE
[BUG] | Nethergarde getting land in the Blasted Lands ends up crashing the game.

### ISSUE THREAD

**Issue by Varus211** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#541]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
Master version downloaded from Github on the 24/07/19 (Western Australian Time)
**What expansions do you have installed?**
All
**Please explain your issue in as much detail as possible:**
Whenever Ironforge gets the land in the Blasted Lands (Which tends to happen most of the time.) the Nethergarde will be created as a vassal of Dalaran, however the event which transfers the land to them seems to crash the game.
**Steps to reproduce the issue:**
Play in the Eastern Kingdoms
Wait until the second war.
Watch as the Alliance usually wins
Ironforge gets the land.
Get the Nethergarde event as normal.
Wait a few days and watch the game crash
**Upload an attachment below: .zip of your save, or screenshots:**

[Crashing Lmao.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3426026/Crashing.Lmao.zip)

**Comment by Varus211** [comment]
Fix: Giving the Nethergarde some land seems to stop the crash all-together. Seems to be the sudden shift from unlanded to landed causing the crash.

**Comment by zumbak04** [comment]
This issue is already reported here #538, so I'm closing it and referencing this report in the first report.
