### ISSUE TITLE
[BUG] | Can unite faction to get out of war

### ISSUE THREAD

**Issue by rhotus** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#542]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.5.0

**What expansions do you have installed?**
All of them

**Please explain your issue in as much detail as possible:**
The leader of a faction can end a war early by uniting the faction

**Steps to reproduce the issue:**
Head a faction
Go to war with an enemy
Either have a Tolerance of 4 or get one mid-war
Use "Unite the Faction" decision

**Upload an attachment below: .zip of your save, or screenshots:**
![ck2_3](https://user-images.githubusercontent.com/51840631/61826702-99934080-ae28-11e9-9354-f45d4d76314e.png)
![ck2_4](https://user-images.githubusercontent.com/51840631/61826723-a4e66c00-ae28-11e9-8a66-5cf8c69e73ae.png)
![ck2_6](https://user-images.githubusercontent.com/51840631/61826744-b16ac480-ae28-11e9-80fb-127dca985bba.png)

**Comment by zumbak04** [comment]
Fixed!
