### ISSUE TITLE
[SUGGESTION] | Medivh Vassalizable

### ISSUE THREAD

**Issue by alobsang** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#544]
Diplomatic Vassalize Medivh as Stormwind
----------------------------------------------------------------------------------------------------------
**Describe your suggestion in full detail below:**
As Llayne at first start after winning the first war it is possible to diplo-vassalize Medivh because his title is count tier.  Maybe he was supposed to die via event before first war ends but in my game he was basically just a vanilla independent count.
I suggest giving Medivh duke or king tier titular title to prevent this happening as I don't think that the Guardian bows to any king.

**Comment by zumbak04** [comment]
Implemented!
