### ISSUE TITLE
[BUG] | Advanced Administration and Secular Religious Group

### ISSUE THREAD

**Issue by Szarkeu** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#546]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.5
**What expansions do you have installed?**
All of them except music
**Please explain your issue in as much detail as possible:**
Secular and Arcane rulers can't get the Religious Mandate law and because of that they can't get the Advanced Administration law.
![Screenshot_339](https://user-images.githubusercontent.com/50971459/61978152-bf6b4180-aff0-11e9-8457-25f5c859508d.png)
![Screenshot_340](https://user-images.githubusercontent.com/50971459/61978157-c42ff580-aff0-11e9-9c67-1b4263cf9e7f.png)

**Steps to reproduce the issue:**
Should be visible every game
**Upload an attachment below: .zip of your save, or screenshots:**

**Comment by zumbak04** [comment]
Fixed!
