### ISSUE TITLE
[LOCALIZATION] | Excellent

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#548]
**Mod Version**
0030ea36

**Please explain your issue in as much detail as possible:**
Is this char really should be happy about Plague of Lordaeron?

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/61982961-21cf3c80-b007-11e9-90a3-eb799ad01269.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
