### ISSUE TITLE
[BUG] | Nomads can settle down in Cenarion Circle

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#551]
**Mod Version**
0030ea36

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Nomads can settle down in Cenarion Circle

**Steps to reproduce the issue:**
Cenarion Circle must have de-jure lands
Settle down in Cenarion Circle as Nomad

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/61987377-c27d2680-b01e-11e9-98d1-393a85fa28ef.png)

</details>

**Comment by sejtalk** [comment]
fixed #562 branch with commit Cenarion Circle is no longer assimilating duchies
