### ISSUE TITLE
[LOCALIZATION] | Aztec

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#554]
**Mod Version**
0030ea36

**Please explain your issue in as much detail as possible:**
Aztec

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/61989508-21e83000-b039-11e9-9d45-716a5b5cfafd.png)

</details>

**Comment by DukeJeans** [comment]
Fixed in f4ff348
