### ISSUE TITLE
[SUGGESTION] | Change Booty Bay color

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#555]
**Describe your suggestion in full detail below:**

If you make Booty Bay merchant republic, it's very hard to see where tradeposts are located

<details>

![image](https://user-images.githubusercontent.com/46576860/61990068-e30aa800-b041-11e9-8080-00cbc95c276b.png)

</details>

**Comment by zumbak04** [comment]
Implemented!
