### ISSUE TITLE
[BUG] | Placement of armies on vigil isle

### ISSUE THREAD

**Issue by Ghosteu** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#558]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.5.0
**What expansions do you have installed?**
all
**Please explain your issue in as much detail as possible:**
When units get on Vigil Island it doesn't quite look like they're on it
**Steps to reproduce the issue:**
Raise levies on Vigil Island
**Upload an attachment below: .zip of your save, or screenshots:**
![siege](https://user-images.githubusercontent.com/53370029/61993823-ee75c780-b071-11e9-9d97-b3bd2894605d.png)

**Comment by zumbak04** [comment]
Fixed!
