### ISSUE TITLE
"Old God" building gives bonuses regardless of province's/holder's religion.

### ISSUE THREAD

**Issue by AltertronSteam** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#56]
Which version of the mod does this apply to?
1.2

How important is this bug/suggestion (Low/Medium/High/Critical)?
Medium

Explain the bug or suggestion below:
Even after conquering Ahn'Qiraj as a "Mystery of the Makers" "Tol'vir" character and purging all provinces, the "Old God" building is still intact, giving you these awesome bonuses even though you are not worshipping the Void.

Feel free to attach a **.zip** or a **screenshot** of the bug to better help us understand the issue.
![20190125205454_1](https://user-images.githubusercontent.com/34240986/51769926-9cfd7780-20e4-11e9-8645-6fe8e5185844.jpg)

**Comment by sejtalk** [comment]
Fixed
