### ISSUE TITLE
[BUG] | Interface From Featured Ruler

### ISSUE THREAD

**Issue by DukeJeans** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#560]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
8d1937d6

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Interface underneath "Play" for Featured Ruler glitches out to default interface, stretching out across bottom left corner of screen.

**Steps to reproduce the issue:**
Start game

**Upload an attachment below: .zip of your save, or screenshots:**
![image](https://user-images.githubusercontent.com/32686241/61994932-b2ca0600-b04f-11e9-9ce2-4da4e2a0b6ce.png)

**Comment by zumbak04** [comment]
Fixed in 6d313e30310e46bb0c2291df76b2e5e0dd3a256e.
