### ISSUE TITLE
[BUG] | Immortal children don't change portrait

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#561]
**Mod Version**
0030ea3

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Immortal children don't change portrait when they grown up

**Steps to reproduce the issue:**
Mortal child must be immortal from class

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/61995005-70261f00-b08b-11e9-89b4-3ef86f126395.png)

</details>

**Comment by zumbak04** [comment]
Can't reproduce it. Looks like there's more steps.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/61996978-c86d1900-b0ab-11e9-92a2-0499ad2d874a.png)
![image](https://user-images.githubusercontent.com/46384992/61996982-d753cb80-b0ab-11e9-8b29-d0195213de5a.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
