### ISSUE TITLE
[BUG] | Nomadic adventurers

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#564]
**Mod Version**
25ad80a0

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Kvaldir Adventurers can become nomadic 

**Steps to reproduce the issue:**
Adventurer must conquer nomadic country

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62002503-30544b80-b10e-11e9-9dd9-ed037740e3a8.png)
![image](https://user-images.githubusercontent.com/46576860/62002507-4104c180-b10e-11e9-80df-756af45b1c27.png)
![image](https://user-images.githubusercontent.com/46576860/62003425-75cd4480-b11f-11e9-9d85-1c7037043deb.png)
![image](https://user-images.githubusercontent.com/46576860/62003427-7a91f880-b11f-11e9-9747-d7bd42589d92.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
