### ISSUE TITLE
[BUG] | Immortals&Elections

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#565]
**Mod Version**
25ad80a0

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Immortal characters with immortal liege worry that if character with "Immortal" trait get elected, there will no more elections. But they don't care if you are immortal because of race/class/being/etc

**Steps to reproduce the issue:**
Have "Immortal" trait and nominate your character as candidate

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62002784-5d0b6180-b114-11e9-8e19-fac43f1b2912.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
