### ISSUE TITLE
[BUG] | South Sea ship placement

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#566]
**Mod Version**
89a84541

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Ships in South Sea are actually placed outside of South Sea

**Steps to reproduce the issue:**
Place ships in Ta-Kemet&Kag'ram South Sea

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62004713-3f002a00-b131-11e9-9b39-1431e8f5e05c.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
