### ISSUE TITLE
[BUG] | Develop mutation

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#567]
**Mod Version**
89a84541

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
You can fire multiple N'raqi transformations

**Steps to reproduce the issue:**
Continue to develop mutations before clicking on event option

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62004806-60154a80-b132-11e9-94ab-88c19c993483.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
