### ISSUE TITLE
[SUGGESTION] | C'tun reawakening tooltip

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#568]
**Describe your suggestion in full detail below:**

Tooltip in C'tun reawakening event is too big, change it pls.

<details>

![image](https://user-images.githubusercontent.com/46576860/62004860-44f70a80-b133-11e9-9388-1c96c30f0ac6.png)

</details>

**Comment by zumbak04** [comment]
Implemented!
