### ISSUE TITLE
[BUG] | You can board to ship where map says you should't be able to

### ISSUE THREAD

**Issue by Arkkimonni** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#569]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.5

**What expansions do you have installed?**
All DLC, Main mod and music mod

**Please explain your issue in as much detail as possible:**
When standing on Dolanaar province, part of Malfurion's Kingdom, you can jump to a ship that is on Veiled Sea tile, but the map borders show, that the tile you can board can only be accessed from Starbreeze and Shadowglen, thus the borders don't match.

**Steps to reproduce the issue:**
Have a fleet on Veiled sea, that by map, is connected to Starbreeze and Shadowglen, but stand on Dolanaar, then try to move your army from ship to Dolanaar and back to fleet.

**Upload an attachment below: .zip of your save, or screenshots:**

![203770_screenshots_20190728130236_1](https://user-images.githubusercontent.com/53396639/62005282-b46ff880-b139-11e9-8686-c0d9c94d0c9b.jpg)

**Comment by zumbak04** [comment]
Fixed!
