### ISSUE TITLE
[BUG] | Faction members keep alliances after Uniting the Faction

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#570]
**Mod Version**
25ad80a

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Faction members keep alliances after Uniting the Faction
They also keep alliances after leaving the faction

**Steps to reproduce the issue:**
Unite faction
Faction member must leave faction

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62006987-b85b4500-b150-11e9-894b-d6788f7db097.png)
![image](https://user-images.githubusercontent.com/46576860/62006989-bbeecc00-b150-11e9-9328-e9e63a4e9bf4.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
