### ISSUE TITLE
[BUG] | Faction Leader can sell faction members provinces to adventurers

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#571]
**Mod Version**
25ad80a

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Faction Leader can sell faction members provinces to adventurers

**Steps to reproduce the issue:**
Play as faction Leader
Sell your faction member province to adventurer

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62007068-d4131b00-b151-11e9-977f-e3e77c2ee009.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
