### ISSUE TITLE
[LOCALIZATION] | Moon Priestess training loc

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#572]
**Mod Version**
967da100

**Please explain your issue in as much detail as possible:**
Moon Priestess training event has no localization

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62007736-e09b7180-b159-11e9-9806-34190215c61f.png)
![image](https://user-images.githubusercontent.com/46576860/62007810-b0080780-b15a-11e9-9d76-47255546b768.png)

</details>

**Comment by zumbak04** [comment]
Fixed in 97cc5f4aab25272433e166b79036e3b04ad33094 and 910df4ee3f9c13fd7e068f3d29c3046037f9818f .
