### ISSUE TITLE
[SUGGESTION] | Unit speed is too high

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#574]
**Describe your suggestion in full detail below:**

With current mod unit speed:
* Any speed modifier is completely useless
* Because +30% speed modifier from shattered retreat don't make difference in unit speed, shattered retreat is completely useless.
* Attrition is easily to avoid
* Since attrition is easily to avoid, any attrition modifiers are useless for player

**Comment by DukeJeans** [comment]
MO change?

**Comment by zumbak04** [comment]
> MO change?

REE, I'm almost created a branch for it!

**Comment by DukeJeans** [comment]
> > MO change?
> 
> REE, I'm almost created a branch for it!

Then do it!

**Comment by zumbak04** [comment]
Did it!
