### ISSUE TITLE
[SUGGESTION] | Elected Leader of the Alliance

### ISSUE THREAD

**Issue by evviSKY** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#576]
**DO NOT REMOVE PRE-EXISTING LINES**
----------------------------------------------------------------------------------------------------------
**Describe your suggestion in full detail below:**
The creation of the Alliance have some logical issues.

Problem 1: E.g. In my game after Terenas' death, Daelin Proudmore created the Alliance title but he destroyed the Kingdom of Kul Tiras title, after his death the Alliance title passed to the king of Grim Batol.
The problem is that Daelin's heir became Duke and could not recreate the kingdom of Kul Tiras, as all de jure vassals were under the command of the new Alliance leader (who also destroyed the title of king after being elected). In a long game this damages the alliance as most members are kings, and CK2 AI causes a sovereign to destroy the title of king if he becomes emperor. This is not a big problem in the horde since most members are counts or dukes.
Suggestion 1: make the elected Leader not destroy his king title. (Is this posible?)

 ...
Problem 2: Another problem is when a weak count or duke is elected the Alliance leader, this weakens the Alliance, in my game once the leader was an Count of Stormwind, he had a total of 7k troops, while only the King of Kul Tiras had 14k troops.
Suggestion 2: I would like to suggest a voting bonus according to the candidate's title, so a king would receive a bonus greater than a Duke and a Duke a bonus greater than a Count, this makes the Alliance have only strong leaders and finally AI decides to attack Scourge. I never see the Alliance Leader trying stop the scourge invasion.

**Comment by Galvador1** [comment]
![GoA](https://user-images.githubusercontent.com/53247506/62095880-f5881a00-b2ab-11e9-9458-64e4dc2e4c97.PNG)

Suggesting impossible number of king_destruction_title_prestige_cost to impossible number as a workaround. Downside: there might be title stackings

**Comment by zumbak04** [comment]
> Suggestion 1: make the elected Leader not destroy his king title. (Is this posible?)

Not sure. Need to test one thing.

> Suggestion 2: I would like to suggest a voting bonus according to the candidate's title, so a king would receive a bonus greater than a Duke and a Duke a bonus greater than a Count, this makes the Alliance have only strong leaders and finally AI decides to attack Scourge. I never see the Alliance Leader trying stop the scourge invasion.

> Suggesting impossible number of king_destruction_title_prestige_cost to impossible number as a workaround. Downside: there might be title stackings

It will affect all titles and rulers, not only the Alliance.

**Comment by evviSKY** [comment]
@zumbak04
I know I posted this a long time ago, but I had the following idea:
Would it be possible to add the requirement: "don't have the Leader of the Alliance/Horde trait" when destroying Kingdoms titles just like that picture? 
![ck2_1](https://user-images.githubusercontent.com/27867313/64914680-6edcae80-d72c-11e9-9b72-7faafc6442ee.png)

![ck2_2](https://user-images.githubusercontent.com/27867313/64914684-8f0c6d80-d72c-11e9-96a5-288b49d7005c.png)

That way anyone could destroy the titles except the leader of the Alliance or Horde.

**Comment by zumbak04** [comment]
> > Suggestion 1: make the elected Leader not destroy his king title. (Is this posible?)
> 
> Not sure. Need to test one thing.

I finally tested it. The same happens in vanilla... sadly. We must force Paradox to fix it! It's not ok.

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/64926188-bb4aeb80-d80b-11e9-8ff5-917f76450128.png)
![image](https://user-images.githubusercontent.com/46384992/64926194-c69e1700-d80b-11e9-92ce-6c364f42516d.png)

</details>

> I know I posted this a long time ago, but I had the following idea:
> Would it be possible to add the requirement: "don't have the Leader of the Alliance/Horde trait" when destroying Kingdoms titles just like that picture?

Nope, as I know, it's not modable.

**Comment by zumbak04** [comment]
Fixed in #717.
