### ISSUE TITLE
[BUG] | Harpy in bladefist don't have dynasty

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#579]
**Mod Version**
45c51858

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Harpy in bladefist don't have dynasty

**Steps to reproduce the issue:**
Open game

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62220331-8c41fd00-b3b8-11e9-81c2-5239f6d09703.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
