### ISSUE TITLE
[BUG] | Pre-scripted childs of immortal races have adult portraits

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#580]
**Mod Version**
45c51858

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Pre-scripted childs of immortal races have adult portraits

**Steps to reproduce the issue:**
1. Start game
2. Find child with adult portrait in character finder

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62225502-3887e180-b3c1-11e9-9786-5fd8555a02d5.png)
![image](https://user-images.githubusercontent.com/46576860/62225531-4ccbde80-b3c1-11e9-932d-948332b8e7e2.png)
![image](https://user-images.githubusercontent.com/46576860/62225539-505f6580-b3c1-11e9-8ca2-9d59d248e340.png)
![image](https://user-images.githubusercontent.com/46576860/62225562-5f461800-b3c1-11e9-87f1-bf7f0babf74e.png)
![image](https://user-images.githubusercontent.com/46576860/62225579-653bf900-b3c1-11e9-8fa2-79704ece51cf.png)
![image](https://user-images.githubusercontent.com/46576860/62225589-69681680-b3c1-11e9-8659-c7433a72b357.png)
![image](https://user-images.githubusercontent.com/46576860/62226034-35d9bc00-b3c2-11e9-8a94-d3f7dd69933e.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
