### ISSUE TITLE
[SUGGESTION] | Formable kingdoms inside political faction

### ISSUE THREAD

**Issue by mdbpr-iscteiulpt** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#583]
**DO NOT REMOVE PRE-EXISTING LINES**
----------------------------------------------------------------------------------------------------------
**Describe your suggestion in full detail below:**
While inside a political faction, you cant use the form kingdom, with would stop certain rulers from declaring themselves kings after uniting enougth people... this happened in a shattered world dutchies game we had in multiplayer, where westfalled controlled 5 dutchies but because it needed to be int he alliance since it neigthvoured the horde, it was unable to form a kingdom or leave the alliance to do so

**Comment by mdbpr-iscteiulpt** [comment]
to make it clear, the form kingdom of the charlemagne dlc

**Comment by zumbak04** [comment]
Implemented!
