### ISSUE TITLE
[BUG] | The Highborne Company don't have any troops

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#585]
**Mod Version**
f1760504

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
The Highborne Company don't have any troops

**Steps to reproduce the issue:**
Start the game

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62325777-1a9ba900-b4b5-11e9-9e5b-5f1e42ef3ede.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
