### ISSUE TITLE
[BUG] | Cenarius can be excommunicated

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#586]
**Mod Version**
ba5bb074

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Cenarius can be excommunicated

**Steps to reproduce the issue:**
Ask Kaldorei religious head to excommunicate Cenarius

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62332688-44f76180-b4c9-11e9-8651-29e3469fe2e7.png)

</details>

**Comment by zumbak04** [comment]
Fixed!

**Comment by MemeWizard** [comment]
d22eaa51

Have low opinion with religious head

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/66390456-5e3df200-e9d3-11e9-8ea7-4362ea75cfb7.png)

</details>

**Comment by MemeWizard** [comment]
Also. for some reason, Tyrande constantly excommunicate and lift excommunication.

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/66394961-01483900-e9df-11e9-9cf4-603af83706c6.png)

</details>

[Hyjal634_02_05.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3702304/Hyjal634_02_05.zip)

**Comment by zumbak04** [comment]
Disabled excommunication for Druidic religions except Old Way.
