### ISSUE TITLE
[LOCALIZATION] | Double names

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#587]
**Mod Version**
ba5bb074

**Please explain your issue in as much detail as possible:**
Pygmies have double name

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62332808-b46d5100-b4c9-11e9-8682-a2ce77f96a52.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
