### ISSUE TITLE
[SUGGESTION] | Racial Lifespans & Nordrassil

### ISSUE THREAD

**Issue by FinleySpritz** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#589]
**DO NOT REMOVE PRE-EXISTING LINES**
----------------------------------------------------------------------------------------------------------
**Describe your suggestion in full detail below:**
Lifespan Averages in Racial Trait descriptions would be nice.
Also, maybe something to do with Nordrassil giving Night Elves immortality and immunity to disease. But you guys probably already thought about those.

**Comment by zumbak04** [comment]
> Also, maybe something to do with Nordrassil giving Night Elves immortality and immunity to disease. 

Already there. That's the whole point of Nordrassil right now.

**Comment by zumbak04** [comment]
Implemented!
