### ISSUE TITLE
Issues with Fel Characters

### ISSUE THREAD

**Issue by MiguelVitta** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#59]
Which version of the mod does this apply to? 

1.2

How important is this bug/suggestion (Low/Medium/High/Critical)?

Low

Explain the bug or suggestion below:

Issues with playing a Demon. 

I wanted to experience the fel characters. So I started a game on the Reign of Chaos bookmark, as Lord Kazzak of Dead Ravine. (I was disapointed to find no intrigue option to summon doomstack of the Burning Legion hehehe). 

*First issue: lack of summon holy (or unholy) priest option.
*Second issue: lack of acess to the smith decision.

After some time, Archimonde arrived and I had the option to join the burning legion.  I joined, , and immediately Archimoned usurped one of my provinces, and I was nominated marshall. After some time playing, I realized how dumb was the ai invasion of Hyjal, so I loaded the save game where Archimonde first appeared and after chosing to join the burning legion, I changed player to archimonde, took over all Kazzak lands and killed him (using console). 
Is there a way of converting the cultures of my provinces to my culture, without the genocide special decision avalable after conquest? 

I had the same decisions available to Kazzak, and I noticed something else.

*Third Issue: I had no eredars eligible to the warlock position. Even by creating a vassal on the temples this had no effect. The only 2 eligible were eredruin from Kazzak court.

The war continued, and some others fel rulers joined as vassals, some satyrs and the blacksong orcs. As had a good amount of money I consoled, I decided to build more holdings on some vassal lands.

*Fourth issue: While I could gift the holdings to the orc vassals, I could not gift castles (cities I could, and temples I didn't build) to the satyrs. The reason is that they are unable to have children (and I think something about being unable to marry too).

*Fifth issue: on the fel religion page, below moral authority, a text says "No LEGION_INVASION called", and If memory serves, even during Archimonde's invasion it was there. 

Feel free to attach a **.zip** or a **screenshot** of the bug to better help us understand the issue.

Unfortunately I deleted the save files, before I thought about reporting the issues.

**Comment by MiguelVitta** [comment]
I actually just realized that the issue about not being able to give lands to vassals happens with the Scourge too. as the Lich King, I cant give a province to a vassal lich because she/he "must be able to marry and produce heirs"

**Comment by zumbak04** [comment]
It's better to create several separate reports, because for example...
> *First issue: lack of summon holy (or unholy) priest option.
> *Second issue: lack of acess to the smith decision.
The first two issues are more suggestions than bug reports. Anyway, I'll add decision to summmon "Unholy Priest". The smith decision is too peaceful for the demons.
> Is there a way of converting the cultures of my provinces to my culture, without the genocide special decision avalable after conquest?
Nope.
> *Third Issue: I had no eredars eligible to the warlock position. Even by creating a vassal on the temples this had no effect. The only 2 eligible were eredruin from Kazzak court.
Only warlocks can be appointed to the warlock position.
> *Fourth issue: While I could gift the holdings to the orc vassals, I could not gift castles (cities I could, and temples I didn't build) to the satyrs. The reason is that they are unable to have children (and I think something about being unable to marry too).
It's because of "Can not marry" trait. AI gets it trying to marry when lorewise it's impossible. It improves the game performance, but the player can't grant castles to such characters.
> *Fifth issue: on the fel religion page, below moral authority, a text says "No LEGION_INVASION called", and If memory serves, even during Archimonde's invasion it was there.
Got it!

**Comment by MiguelVitta** [comment]
Thanks, I thought spamming the issues would be more prejudicial, but from now on I will keep one subject per post. 
I thought the smith was a bug because it makes  so the demons cant get artifacts as easily. Maybe add a separate method of getting artifact for demons? Will add it as separate suggestion. later, with more details.

Thank you for your time and good work on the mod. Cheers

**Comment by zumbak04** [comment]
> I thought the smith was a bug because it makes so the demons cant get artifacts as easily. Maybe add a separate method of getting artifact for demons? Will add it as separate suggestion. later, with more details.

Yep, I will close this issue then. I fixed LEGION_INVASION and added "Invite Unholy Man" decision.

> Thank you for your time and good work on the mod. Cheers

Thanks you for supporting <3
