### ISSUE TITLE
[SUGGESTION] | Mutations should сlear frail trait 

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#590]
**Describe your suggestion in full detail below:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62361932-a862ad00-b524-11e9-8578-e79aa7b5ec65.png)

</details>

**Comment by zumbak04** [comment]
Implemented!
