### ISSUE TITLE
[BUG] | Independence of Non-direct Faction Vassal

### ISSUE THREAD

**Issue by Dortund** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#597]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.5.0 (steam workshop subscription)
**What expansions do you have installed?**
Every expansion installed and enabled.
**Please explain your issue in as much detail as possible:**
Playing as the dwarven duchy of Dun Modr under the kingdom of Ironforge rule (which are under rule by the alliance emperor). I'm unable to start an independence faction and I also don't have an independence CB.
**Steps to reproduce the issue:**
?
**Upload an attachment below: .zip of your save, or screenshots:**

[Ironman_WoW_Dun_Modr.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3474486/Ironman_WoW_Dun_Modr.zip)
![CB's](https://user-images.githubusercontent.com/4071407/62583300-eb6baa00-b8af-11e9-967d-41185794b2aa.png)

**Comment by zumbak04** [comment]
Fixed!
