### ISSUE TITLE
[BUG] | Buildings Issue

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#598]
**Mod Version**
f1760504

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
`is_rich_holding`, `is_richer_holding`, `can_build_walls_trigger`, `can_build_castle_fortifications_trigger` scripted triggers don't work, because they check if holding have non-existing buildings

`HF.23210`, `HF.23214`, `HF.23219` events don't work, same reason as above

`RIP.4514`, `RIP.4520`, `RIP.4530` not adapted & don't work, same reason as above

I didn't check all buildings, but I definitely sure that nobody want recheck the entire list of buildings every paradox patch.

Imo, it will be far less painful to adapt buildings if it buildings would use vanilla code names + mod stats&localization.

**Steps to reproduce the issue:**
`---`

**Upload an attachment below: .zip of your save, or screenshots:**
`---`

**Comment by MemeWizard** [comment]
>Now both base tribal and fully upgraded tribal gives you the same buildings.
>There is no sense in upgrading them, unlike in vanilla.

https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/pull/614#pullrequestreview-273369572

Also, since convert_to_castle command don't work with multiple buildings, multiple base non-evil / evil buildings instead of single codename+custom localization will cause bugs and crutches.

<details>

![Безымянный42](https://user-images.githubusercontent.com/46576860/62823283-4a733c80-bb98-11e9-8811-2df588b5f09d.png)
![Безымянный9](https://user-images.githubusercontent.com/46576860/62823285-4cd59680-bb98-11e9-8f74-c2447b8e7ea8.png)

</details>

**Comment by zumbak04** [comment]
Most of issues fixed in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/pull/650 .

> `RIP.4514`, `RIP.4520`, `RIP.4530` not adapted & don't work, same reason as above

`RIP.4520` mentioned Soup Kitchen though there wasn't Soup Kitchen building. Fixed in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/commit/f096aeb12639e9cdccf4cac1ab0fd3e1ef85bc22 .
