### ISSUE TITLE
[BUG] | Songs

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#599]
**Mod Version**
f1760504

**Please explain your issue in as much detail as possible:**
Songs added by the mod don't have localization
Ck2 maintitle is replaced, but not renamed

**Upload screenshots of the problem localization:**

<details>
<summary>Vanilla</summary>

![Безымянный9](https://user-images.githubusercontent.com/46576860/62632725-9ffedd80-b93b-11e9-8a95-63fff8054333.png)

</details>

<details>
<summary>Mod</summary>

![Безымянный8](https://user-images.githubusercontent.com/46576860/62632600-6b8b2180-b93b-11e9-802f-d7168650abb8.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
