### ISSUE TITLE
[BUG] | Interspecies marriage

### ISSUE THREAD

**Issue by Blackcat85** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#600]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.5
**What expansions do you have installed?**
All
**Please explain your issue in as much detail as possible:**
1. I married Liam Greymane to a high elf and she only gave birth to girls, they had 7 kids before he died, all of them girls, after that I seduced her to see if it works this way, but she just gave birth to an 8th girl.
**Steps to reproduce the issue:**
Marry a human to a high elf.
![ck2_4](https://user-images.githubusercontent.com/53872043/62639986-443b5100-b949-11e9-81ba-da880b4cedf6.png)

**Upload an attachment below: .zip of your save, or screenshots:**

**Comment by MemeWizard** [comment]
>Marry a human to a high elf

Can't confirm.

<details>

![image](https://user-images.githubusercontent.com/46576860/62644194-3c33df00-b952-11e9-8427-1c7e35f7a634.png)


</details>

**Comment by Blackcat85** [comment]
> 
> 
> > Marry a human to a high elf
> 
> Can't confirm.

I just used console commands to test it once more, this time, the 9th child is a boy, I was sure there was some problem but... it looks like it was purely bad luck 
![ck2_6](https://user-images.githubusercontent.com/53872043/62647906-4f4aad00-b95a-11e9-8769-4101a3a53c15.png)
