### ISSUE TITLE
[SUGGESTION] | Raiders are overtuned

### ISSUE THREAD

**Issue by killshrooms** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#601]
----------------------------------------------------------------------------------------------------------
Raiders and wandering adventurers are an even bigger annoyance than they are in vanilla; there's no warning to tell you if a 4k stack is going to spawn on your capital. It's so bad that it's actually better to have the scourge or black pact as your neighbor, because they don't raid you 24/7. Reduce the spawnrate of adventurers or give a grace period so you don't get raided constantly.

**Comment by MemeWizard** [comment]
Vanilla "rare adventurers" and "no adventurers" gamerules affect these events

**Comment by zumbak04** [comment]
What raiders you mean? Kvaldir, murloc and naga ones that declare war for one county? Or vanilla raiders?

**Comment by zumbak04** [comment]
Closing the issue due to lack of information.
