### ISSUE TITLE
[BUG] | Ask for Dark Gift

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#605]
**Mod Version**
8f73fe29

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
You can ask for Dark Gift when there is no Lick-King
Nothing will happens, tho

**Steps to reproduce the issue:**
Ask for Dark Gift when there is no Lick-King

**Upload an attachment below: .zip of your save, or screenshots:**
`---`

**Comment by DukeJeans** [comment]
> Lick-King

**Comment by DukeJeans** [comment]
Tentative. Title exists w/o land or no?

**Comment by zumbak04** [comment]
Fixed! For more info read the referenced commit.
