### ISSUE TITLE
[LOCALIZATION] | WCUND.300 option 2 text

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#606]
**Mod Version**

**Please explain your issue in as much detail as possible:**

>turn yourself undead

>raise him

:thonk:

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62658292-2255c480-b971-11e9-97f7-79c341432078.png)

</details>

**Comment by zumbak04** [comment]
Fixed in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/commit/03ae7f5915d01c2ed036ff4483fd06dff4f5a0b6
