### ISSUE TITLE
[LOCALIZATION] | Azurebreeze coas*

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#608]
**Mod Version**
ea3767b0

**Please explain your issue in as much detail as possible:**
Azurebreeze coas*

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62701666-86b66980-b9ed-11e9-86a6-5e4caad2a7f5.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
