### ISSUE TITLE
Event stack not taking upkeep?

### ISSUE THREAD

**Issue by Sininu** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#61]
Which version of the mod does this apply to? 
1,2

How important is this bug/suggestion (Low/Medium/High/Critical)?
Low/medium

Explain the bug or suggestion below:
"Event" troops doesn't take any upkeep when they've taken over a region.

So I was playing the nerubian, and there happened to come a 3k stack marching over, and after raiding my captured province they declared war and took over the county. Now they didn't have any other holding or any other income that the captured holding, but they were still keeping the 3k "event unit" stack on the plot, while having a positive income.

Feel free to attach a **.zip** or a **screenshot** of the bug to better help us understand the issue.
![screenshot 35](https://user-images.githubusercontent.com/47060381/51807988-32883b00-228e-11e9-9816-8061d48e876e.png)
![screenshot 36](https://user-images.githubusercontent.com/47060381/51807992-3e73fd00-228e-11e9-8263-69069609436a.png)
![screenshot 37](https://user-images.githubusercontent.com/47060381/51807996-4764ce80-228e-11e9-9510-968282361153.png)

Now I have absolutely no idea how they can maintain a 3k event stack, while still getting + income. The event stack only disappeared when the daughter took over.

**Comment by zumbak04** [comment]
He's an adventurer. His spawned troops have no cost, but disappears after the inheritance. It's not a bug, it's a vanilla feature.
