### ISSUE TITLE
[BUG] | Blood elves can spawn before corruption of Sunwell

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#612]
**Mod Version**
ea3767b0

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Blood elves can spawn before corruption of Sunwell

**Steps to reproduce the issue:**
Character spawned with random culture can be a blood elf

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62778710-c34f9700-bab9-11e9-98ba-0048667729b1.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
