### ISSUE TITLE
[LOCALIZATION] | the Tidemother

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#613]
**Mod Version**
624b5d6d

**Please explain your issue in as much detail as possible:**
the Tidemother

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62784257-c3a25f00-bac6-11e9-9aa1-2c481eafeb90.png)

</details>

**Comment by arithon** [comment]
I think it should be "The Tidemother"...
