### ISSUE TITLE
[BUG] | You can ask for Greatest Gift multiple times

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#615]
**Mod Version**
959d45d0

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
You can ask for Greatest Gift multiple times

**Steps to reproduce the issue:**
Ask for Greatest Gift multiple times before clicking on event

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62807654-8bb70e00-bafe-11e9-87fc-7fb2205e72cc.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
