### ISSUE TITLE
[BUG] | Neverending divorces of gnome barons

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#616]
**Mod Version**
959d45d0

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Gnome barons marry and divorce from time to time

**Steps to reproduce the issue:**
???

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62808183-12201f80-bb00-11e9-812c-b3b4c1d1c48e.png)
![image](https://user-images.githubusercontent.com/46576860/62808184-151b1000-bb00-11e9-952b-85e434d5f77f.png)
![image](https://user-images.githubusercontent.com/46576860/62808188-18ae9700-bb00-11e9-8d23-255efb048b87.png)
![image](https://user-images.githubusercontent.com/46576860/62808191-1b10f100-bb00-11e9-931c-1cc9af7d413e.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
