### ISSUE TITLE
[BUG] | Elections Age problem

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#617]
**Mod Version**
959d45d0

**What expansions do you have installed?**

**Please explain your issue in as much detail as possible:**
71 YO undead thinks that 606 YO undead is too young to rule
47 YO human thinks that 181 YO dwarf is too young to rule

**Steps to reproduce the issue:**
???

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62808889-1b11f080-bb02-11e9-904d-e88ffa562b01.png)
![image](https://user-images.githubusercontent.com/46576860/62809021-7ba12d80-bb02-11e9-9db2-e865053969e6.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
