### ISSUE TITLE
[BUG] | The Void is watching y...

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#618]
**Mod Version**
959d45d0

**Please explain your issue in as much detail as possible:**
MNM.7025
The Void is watching y...

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62811064-fcfbbe80-bb08-11e9-817c-2ad15f152780.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
