### ISSUE TITLE
[BUG] | Force Vassalization as Faction

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#619]
**Mod Version**
959d45d0

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Force Vassalization as Faction is useless, because your new vassal will just leave your faction after war

**Steps to reproduce the issue:**
Vassalize someone by force

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62812070-e7889380-bb0c-11e9-8b8d-ab3c58e74937.png)
![image](https://user-images.githubusercontent.com/46576860/62812172-40f0c280-bb0d-11e9-9825-1065408e3886.png)

</details>

**Comment by zumbak04** [comment]
What is bug here?

**Comment by MemeWizard** [comment]
>What is bug here?

So, it's work as designed that your war become fruitless, because conquered ruler just leave your realm, because he considered a your faction member?
Maybe conquered ruler shouldn't be able to leave your fraction or fractions shouldn't have access to this CB?

**Comment by zumbak04** [comment]
> Maybe conquered ruler shouldn't be able to leave your fraction or fractions shouldn't have access to this CB?

Pick only one. That's what I wanted to hear.

**Comment by MemeWizard** [comment]
>That's what I wanted to hear.

Sorry, I'm not a telepath

>Pick only one.

Any will do

**Comment by zumbak04** [comment]
> Any will do

Good choice since the first option isn't possible anyway.

**Comment by MemeWizard** [comment]
>Good choice since the first option isn't possible anyway.

Is there any problem with banning character from leaving fraction if it has a "defeated me" opinion modifier about liege?

**Comment by zumbak04** [comment]
> Is there any problem with banning character from leaving fraction if it has a "defeated me" opinion modifier about liege?

Yep, only kings can leave faction so by definition they're vassals of the Horde/Alliance, not yours and your dynasty's.

**Comment by zumbak04** [comment]
Fixed!
