### ISSUE TITLE
Genocide does not remove population-related modifiers.

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#62]
Master branch
Low

Genocide does not remove population-related modifiers.

<details>
<summary>Click to expand</summary>

![ck2_5](https://user-images.githubusercontent.com/46576860/51808091-784dff00-22a0-11e9-94a8-fdaf4e559552.png)
![ck2_11](https://user-images.githubusercontent.com/46576860/51808094-800da380-22a0-11e9-9f0b-6d9c3eb43461.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
