### ISSUE TITLE
[BUG] | Can't selectively purge character

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#621]
**Mod Version**
24b4504c

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Can't selectively purge character

**Steps to reproduce the issue:**
Load save

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62821970-cfa12600-bb85-11e9-8cdc-e1d82ad5c2c9.png)

</details>

[Mechagon617_07_21.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3488828/Mechagon617_07_21.zip)

**Comment by zumbak04** [comment]
Fixed!
