### ISSUE TITLE
[LOCALIZATION] | Zul'Dare coast

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#622]
**Mod Version**

**Please explain your issue in as much detail as possible:**
Zul'Dare coast is not in the same place as Zul'Dare

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62822877-48a67a80-bb92-11e9-9a70-2c3deaab48e2.png)
![image](https://user-images.githubusercontent.com/46576860/62822880-4ba16b00-bb92-11e9-867d-f0732c1f8a61.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
