### ISSUE TITLE
[BUG] | No death case

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#623]
**Mod Version**
097cdd37

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
3 characters died without death case in one day

**Steps to reproduce the issue:**
???

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62824553-8b734d00-bba8-11e9-9b0b-8fe82f632296.png)
![image](https://user-images.githubusercontent.com/46576860/62824583-ff155a00-bba8-11e9-94d9-021031f319bb.png)
![image](https://user-images.githubusercontent.com/46576860/62824585-03da0e00-bba9-11e9-99c8-304a49ffd2cb.png)

</details>

Save after character death:
[Mechagon650_02_22.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3489119/Mechagon650_02_22.zip)
Before:
[Mechagon649_07_22.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3489120/Mechagon649_07_22.zip)

**Comment by zumbak04** [comment]
Is it reproducible?

**Comment by MemeWizard** [comment]
Yep, load save before character death

**Comment by zumbak04** [comment]
Fixed!
