### ISSUE TITLE
[BUG] | 40 YO Immortal characters become infertile after game reloading

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#624]
**Mod Version**
097cdd37

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
40 YO Immortal characters become infertile after game reloading

**Steps to reproduce the issue:**
Load save
Wait until Merble is 40 years old
Save and reload the game

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62825900-b3b87700-bbbb-11e9-808e-2e65318b2185.png)
![image](https://user-images.githubusercontent.com/46576860/62825955-b49dd880-bbbc-11e9-847e-b9826666a7dc.png)

</details>

[Mechagon660_10_01.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3489237/Mechagon660_10_01.zip)

**Comment by zumbak04** [comment]
Fixed!
