### ISSUE TITLE
Populations[SUGGESTION] | SUGGESTION TITLE

### ISSUE THREAD

**Issue by SeanBerget** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#625]
**DO NOT REMOVE PRE-EXISTING LINES**
----------------------------------------------------------------------------------------------------------
**Describe your suggestion in full detail below:**
adding populations would be nice

**Comment by MemeWizard** [comment]
What do you mean?
Population size has already been implemented through prosperity.
Also, we can't turn СK2 into Victoria 2 without a significant drop in performance.

**Comment by zumbak04** [comment]
Closing since it's already implemented via Depopulation and Prosperity modifiers.
