### ISSUE TITLE
[LOCALIZATION] | Name problems

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#626]
**Mod Version**
097cdd37

**Please explain your issue in as much detail as possible:**
Name problems thread

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62826536-1a429280-bbc6-11e9-8e57-c35da47f3636.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
