### ISSUE TITLE
[LOCALIZATION] | Titles localization problems

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#627]
**Mod Version**
Titles localization problems

**Please explain your issue in as much detail as possible:**
Titles localization problems thread

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62826585-d3a16800-bbc6-11e9-813b-cc3bdc505ea5.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
