### ISSUE TITLE
[BUG] | Carousing

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#629]
**Mod Version**
097cdd37

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Undeads can't pick carousing focus, but can be invited to carousing

**Steps to reproduce the issue:**
Pick carousing focus

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62827488-7d3d2500-bbd8-11e9-8941-5fe955260f6a.png)
![image](https://user-images.githubusercontent.com/46576860/62827501-ae1d5a00-bbd8-11e9-8feb-9776fe172aec.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
