### ISSUE TITLE
[LOCALIZATION] | Wrong pronoun

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#630]
**Mod Version**
097cdd37

**Please explain your issue in as much detail as possible:**
>Female character

>his body

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62828468-dcf2fa80-bbef-11e9-8bc9-b9c68c827caa.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
