### ISSUE TITLE
[BUG] | Undeads gets infertile trait after reload

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#631]
**Mod Version**
097cdd37

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Undeads gets infertile trait after reload

**Steps to reproduce the issue:**
Have 7+ children as undead
Reload game 

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62828539-dbc2cd00-bbf1-11e9-9a10-4bbd26cdae52.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
