### ISSUE TITLE
[BUG] | Blessing of Goldrinn&Druidic religion group

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#632]
**Mod Version**
097cdd37

**Please explain your issue in as much detail as possible:**
Blessing of Goldrinn gives -10 to druidic opinion
This is misleading, because there are both religion and religion group called druidic

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62834996-14978c00-bc5c-11e9-9e4c-95b9b4862296.png)
![image](https://user-images.githubusercontent.com/46576860/62835005-1b260380-bc5c-11e9-8e53-49203a03ceb7.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
