### ISSUE TITLE
[LOCALIZATION] | The Splintering of the Elves

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#635]
**Mod Version**
097cdd37

**Please explain your issue in as much detail as possible:**

<details>

![Безымянный43](https://user-images.githubusercontent.com/46576860/62837009-b32ee780-bc72-11e9-8c12-86209b44d87d.png)
![Безымянны23й](https://user-images.githubusercontent.com/46576860/62836967-297f1a00-bc72-11e9-947b-37b8231a69e3.png)

</details>

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62836903-3f400f80-bc71-11e9-98dc-b9e06fa8eb71.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
