### ISSUE TITLE
[BUG] | Assasination events descriptions

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#636]
**Mod Version**
097cdd37

**Please explain your issue in as much detail as possible:**
Assasination events descriptions from direct action don't make sense.

**Upload screenshots of the problem localization:**

Some examples:

<details>

![image](https://user-images.githubusercontent.com/46576860/62837391-8d581180-bc77-11e9-9150-18f03a30414b.png)
![image](https://user-images.githubusercontent.com/46576860/62837410-bc6e8300-bc77-11e9-9193-3677f5fce388.png)

</details>

**Comment by arithon** [comment]
So what shall we do? Add special dead events for undead? So the game checks if the killed character is undead in the first place?

**Comment by zumbak04** [comment]
Assassination isn't supported since it's hardcode and antiquated decision.
