### ISSUE TITLE
[SUGGESTION] | Make the map more realistic

### ISSUE THREAD

**Issue by SeanBerget** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#637]
**DO NOT REMOVE PRE-EXISTING LINES**
----------------------------------------------------------------------------------------------------------
**Describe your suggestion in full detail below:**

It would be cool if you guys could make a submod, having both the map that you have right now which is the wow game map, and one another being more realistic lore wise sized map. 
With the realistic map there should be fewer mountains, the would be no city models that take up half the map. The map should just be more realistic with irl world size in your guys wow map.

**Comment by zumbak04** [comment]
The map we have is the realistic one. I believe we removed mountains everywhere we could. Models are just map objects, they don't represent anything.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/62837898-0c544680-bc86-11e9-8632-c2ac14c02d8d.png)

</details>

**Comment by zumbak04** [comment]
Closing the issue. Reopen it if you want to change something specific on the map.
