### ISSUE TITLE
Some titles are not tied to the character's race and culture.

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#64]
Master branch
Medium

So green dragons can rule a tribe of red dragons.

<details>
<summary>Click to expand</summary>

![ck2_10](https://user-images.githubusercontent.com/46576860/51808285-104ce800-22a3-11e9-95ad-66efe83d7bcd.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
