### ISSUE TITLE
[BUG] | education completed typo

### ISSUE THREAD

**Issue by AltanIV** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#643]
![20190813001852_1](https://user-images.githubusercontent.com/42421962/62902710-baccba00-bd60-11e9-80eb-a4da8df68557.jpg)
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.5.0
**Please explain your issue in as much detail as possible:**
I started learning arcane magic. When the formation was completed I saw a word missing in the event text : It should be "[...]However you should be careful with this new power..." instead of "... However you should careful..."
**Upload screenshots of the problem localization:**

**Comment by zumbak04** [comment]
Fixed in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/commit/67a06a26ce71896c06da3d69b59e84bc20f2f8ad
