### ISSUE TITLE
[BUG] | TWO GRIMTOTEM DINASTIES AT 583 !

### ISSUE THREAD

**Issue by sicknot1** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#644]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version** 
1.5

**What expansions do you have installed?**
all
**Please explain your issue in as much detail as possible:**
At the first start date, when you play as Yodol't of the Grimtotem start, he begins with a GRIMTOTEM dinasty DIFFERENT from their brothers, if you die you lose the game as no dinastic heir 
**Steps to reproduce the issue:**
play as him
**Upload an attachment below: .zip of your save, or screenshots:**

![ck2_13](https://user-images.githubusercontent.com/35937937/62911792-03ce3f80-bd5c-11e9-8340-ef604bb3b371.png)
![ck2_14](https://user-images.githubusercontent.com/35937937/62911806-10529800-bd5c-11e9-9230-648b92f0f90d.png)

**Comment by zumbak04** [comment]
Fixed in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/commit/cd816d9dd6d14e0f93704760257666e2b2b1ea64
