### ISSUE TITLE
[BUG] | Druid class health bonus

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#648]
**Mod Version**
02d3f2dd

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
9 druid lvl gives you 1.75 health
10 druid lvl don't give you health

**Steps to reproduce the issue:**
`---`

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62954422-08483600-bdf8-11e9-86fe-337f254ace3e.png)
![image](https://user-images.githubusercontent.com/46576860/62954503-30d03000-bdf8-11e9-8409-d2bbdd51cdc0.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
