### ISSUE TITLE
[LOCALIZATION] | A tributary of China

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#649]
**Mod Version**
02d3f2dd

**Please explain your issue in as much detail as possible:**
OG screen localization

**Upload screenshots of the problem localization:**

<details>

![Безымянный967](https://user-images.githubusercontent.com/46576860/62958120-bfe04680-bdfe-11e9-8d49-7b5cb73c3604.png)

</details>

**Comment by zumbak04** [comment]
Paradox bug.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/62960633-20c24b80-be0c-11e9-9aaa-934283d156d0.png)
![image](https://user-images.githubusercontent.com/46384992/62960650-2d46a400-be0c-11e9-85a7-acd74dc69dfb.png)

</details>

**Comment by sejtalk** [comment]
fixed https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/commit/419b3500abf3dd057d91cae041397a09f21daf79
