### ISSUE TITLE
Tauren Totems are indestructible.

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#65]
Master branch
Low

Tauren Totems are indestructible
<details>
<summary>Click to expand</summary>

![ck2_8](https://user-images.githubusercontent.com/46576860/51808320-5ace6480-22a3-11e9-888b-9c0a3386102b.png)

</details>

**Comment by sejtalk** [comment]
Fixed
