### ISSUE TITLE
[LOCALIZATION] | the Light

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#652]
**Mod Version**
a2c774f4

**Please explain your issue in as much detail as possible:**
lowercase

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/63040287-d2758100-becd-11e9-819b-80b397976fd3.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
