### ISSUE TITLE
[SUGGESTION] | Adjust interracial betrothal break

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#654]
**Describe your suggestion in full detail below:**

It's not ok that noble girls after incompatible betrothal get lowborn mans as fiances with non-matrilineal betrothal

<details>

![image](https://user-images.githubusercontent.com/46576860/63042874-aa891c00-bed3-11e9-8650-0025a69d1f68.png)
![image](https://user-images.githubusercontent.com/46576860/63042921-c55b9080-bed3-11e9-8fd2-a006002589bd.png)

</details>

AI anyway will broke that betrothal after few days

<details>

![image](https://user-images.githubusercontent.com/46576860/63043489-04d6ac80-bed5-11e9-8028-b6cec1d71084.png)
![image](https://user-images.githubusercontent.com/46576860/63043520-1324c880-bed5-11e9-8d90-35735de208e9.png)

</details>

>divorced

Not "Broke betrothal"? Weird

<details>

![image](https://user-images.githubusercontent.com/46576860/63043361-be814d80-bed4-11e9-8bc7-bd311f1a8b20.png)
![image](https://user-images.githubusercontent.com/46576860/63043375-ca6d0f80-bed4-11e9-8f3e-f644ad9b5896.png)

</details>

**Comment by zumbak04** [comment]
@MemeWizard as I know, there's no way to betroth matrilineally via events, so I suggest 3 things:
- Do not betroth girls and kill them.
- Do not betroth girls and keep them alive.
- Betroth non-matrilineally, but on noble mans.

**Comment by MemeWizard** [comment]
> Do not betroth girls and keep them alive.

Ok

> Betroth non-matrilineally, but on noble mans.

AI still can break that

> Do not betroth girls and kill them.

Just how did you come up with such a dumb thing

**Comment by zumbak04** [comment]
> Just how did you come up with such a dumb thing

Ez. No noble girls, no problems.

**Comment by MemeWizard** [comment]
> Well, Terenas AI didn't break anything.

Well, if it's true, then it's ok
