### ISSUE TITLE
[LOCALIZATION] | Too many Uldums

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#655]
**Mod Version**
458123df

**Please explain your issue in as much detail as possible:**

There is:
2 barony of Uldum
Lordship of Uldum
High Lordship of Uldum
Kingdom of Uldum
High Kingdom of Uldum

Lordship of Uldum and 1 barony of Uldum are not belong to High Kingdom/Region of Uldum

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/63131155-65451700-bfc5-11e9-987c-17a068a56dd3.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
