### ISSUE TITLE
[LOCALIZATION] | Forest Lord "Lord of the Forest" of Hyjal Forest

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#656]
**Mod Version**
458123df

**Please explain your issue in as much detail as possible:**
Too many forests

**Upload screenshots of the problem localization:**

<details>

![Безымянный2](https://user-images.githubusercontent.com/46576860/63131335-f916e300-bfc5-11e9-991b-c0d1e2bae564.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
