### ISSUE TITLE
[LOCALIZATION] | Hand of the Twilight

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#657]
**Mod Version**
458123df

**Please explain your issue in as much detail as possible:**
"Hand of the Twilight" title is too big for title box

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/63132920-827ce400-bfcb-11e9-8fc6-ef8d4f76cf62.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
