### ISSUE TITLE
[BUG] | Reviving of the Black Empire reset laws

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#659]
**Mod Version**
458123df

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Reviving of the Black Empire reset laws

**Steps to reproduce the issue:**
Revive the Black Empire

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/63154401-3062af80-c019-11e9-8d3f-2504c8ad1b27.png)
![image](https://user-images.githubusercontent.com/46576860/63154432-3f496200-c019-11e9-9131-a41ac9fb87dc.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
