### ISSUE TITLE
[SUGGESTION] | WCOME.100 is too spammy

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#660]
**Describe your suggestion in full detail below:**

There is no fun in clicking on the same event window 1000 times in one war, it's just tedious

Maybe province modifier instead of holding modifier or reworking it into special CB, like vanilla flower war will improve situation?

**Comment by sejtalk** [comment]
Fixed in Old-God-Content branch
