### ISSUE TITLE
Magocracy Taxes

### ISSUE THREAD

**Issue by alobsang** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#666]
Vassal Magocracies are taxed with burgher obligation laws instead of temple obligation laws.
![20190817223350_1](https://user-images.githubusercontent.com/43768452/63220560-2d61df00-c13f-11e9-934f-f86a4ae1517c.jpg)

**Comment by zumbak04** [comment]
Magocracies and technocracies are republics, so WAD.
