### ISSUE TITLE
[LOCALIZATION] | In the light of the Light!

### ISSUE THREAD

**Issue by geffe1** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#668]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
Shouldn't matter, think I have seen it before.
**Please explain your issue in as much detail as possible:**
In the light of the Light.
**Upload screenshots of the problem localization:**
![ck2_325](https://user-images.githubusercontent.com/31706375/63229943-7cbf1280-c206-11e9-9d18-8c94a422ca33.png)

**Comment by zumbak04** [comment]
Fixed!
