### ISSUE TITLE
[SUGGESTION] | Add gamerule about adding personality traits to spawned characters

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#671]
**Describe your suggestion in full detail below:**

An event, that gives traits to spawned character depending on their culture/religion can give spawned character a lot of personality traits, from 5 to 13(!), and there are multiple problems with it:

1. This ridiculous amount of traits gives character fully radicalized personality, therefore breaks immersion.

<details>

![image](https://user-images.githubusercontent.com/46576860/63259856-31e5df00-c288-11e9-8501-43bbcc0e84f0.png)

</details>

2. It's devalue characters, since they all will have the same traits and don't different much.

<details>

![image](https://user-images.githubusercontent.com/46576860/63260755-770b1080-c28a-11e9-8863-ca0be18287b5.png)

</details>

**Comment by zumbak04** [comment]
These are bad guys. They should be as evil as possible. Your personality doesn't matter, only PAWER MATTERS!

**Comment by epicmarkvan** [comment]
IMO people, even fictional ones, are pretty complex. I don't mind a lot of traits, gives each character personality.

**Comment by MemeWizard** [comment]
>These are bad guys. They should be as evil as possible. Your personality doesn't matter, only PAWER MATTERS!

If an evil character is evil because it's evil, that character don't have personality, it's not even can be considered as a character, it's just evilness simulacrum and the act of creating such abominations is called a bad writing.

>IMO people, even fictional ones, are pretty complex.

That's is just why characters should have less traits.
Since traits give uniqueness to characters, character without any traits looks weird and unnatural, because it's don't have any personality, but character with a lot of traits also looks weird and unnatural, because it's have radical view on everything. For example, while character without cruel/kind traits can sometimes be kind, sometimes be cruel, or neither, cruel or kind character most of the time will have respective deeds. It's limit character in their actions, but symbiosis with their other traits, like just or arbitrary, can create internal character conflict that can be complex and therefore entertaining to watch. If character is limited with 13 "bad" personality traits, without any story behind it, just because it's evil, that character don't have internal character conflict, therefore it's not complex or interesting, it's one of the plain and boring simulacrums.
Imo, vanilla 3-4 personality traits it's ideal number,

**Comment by mdbpr-iscteiulpt** [comment]
Honestly just pull a expanded traits, add more traits to the game with their own warcraft theme events, like conquerer, racist, horde_sypathetic, Alliance_synpathetic, and others

**Comment by MemeWizard** [comment]
>Honestly just pull a expanded traits, add more traits to the game with their own warcraft theme events, like conquerer, racist, horde_sypathetic, Alliance_synpathetic, and others

It does not solve this topic "spawned characters has overflowing number of personality traits" problem.
You can do both - add additional traits and give less traits to spawned characters, tho.

**Comment by MemeWizard** [comment]
Changed suggestion to be more appropriate, since there are people that can like the idea about character with a lot of traits.
