### ISSUE TITLE
[BUG] | Spawned characters problems

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#672]
**Mod Version**
ccc57bc2

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
See below

**Steps to reproduce the issue:**
See below

**Upload an attachment below: .zip of your save, or screenshots:**

1. Sayaadi can be both chaste and lustful, cruel and kind, zealous and cynical, etc
2. Sayaadi can have 2 lifestyle traits
3. Sayaadi spawns with seduction focus, but landless characters can't have focuses

Summon Sayaadi
<details>

![image](https://user-images.githubusercontent.com/46576860/63261594-89864980-c28c-11e9-8933-2f50db1ffa6f.png)

</details>

C'traxxi can have negative genetic traits

Spawn C'traxxi from WCVOD.10015
<details>

![image](https://user-images.githubusercontent.com/46576860/63261880-352f9980-c28d-11e9-94ea-4ed11f386458.png)
![image](https://user-images.githubusercontent.com/46576860/63262130-d61e5480-c28d-11e9-8707-0c31dddaec47.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
