### ISSUE TITLE
Freeze on Map Load

### ISSUE THREAD

**Issue by Varigon1** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#681]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version 1.5 **

**What expansions do you have installed? All recommended DLC's **

**Please explain your issue in as much detail as possible: When starting a new game after setting up the rules my game will freeze upon loading the map. **

**Steps to reproduce the issue: I don't know how I've gotten this issue to occur. **

**Upload an attachment below: .zip of your save, or screenshots: There is no way of showing you this visually. **

**Comment by Varigon1** [comment]
I have tried restarting multiple times I have tried deleting and reinstalling via moddb version. I have tried changing my rules and settings in game around. I have even tried deleting the entire game and reinstalling. But this is the only mod I am having this issue with. Good luck cant wait to be able to play when you do find a solution

**Comment by zumbak04** [comment]
Have you tried disabling city sprites in settings.txt?

**Comment by Varigon1** [comment]
No I haven't. Ill try it

**Comment by Varigon1** [comment]
That seems to have fixed it. I appreciate it sir.

**Comment by zumbak04** [comment]
You're welcome. Closing the issue.
