### ISSUE TITLE
[BUG] | AI don't care about opinion in WCDIP.10/15

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#687]
**Mod Version**
2960662b

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
>[persistent.cpp:40]: Error: "Unexpected token: opinion, near line: 95" in file: "events/wc_diplomacy_events.txt"

ai_chance in `WCDIP.10` and `WCDIP.15` don't work
Also, `EVTOPTA_WCDIP_10` looks weird in `WCDIP.15`

**Steps to reproduce the issue:**
`---`

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/64154132-dc3d3500-ce38-11e9-929f-69c551359e05.png)
![image](https://user-images.githubusercontent.com/46576860/64154317-4229bc80-ce39-11e9-9f1f-58d4225c54a8.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
