### ISSUE TITLE
Cenarius Circle localization

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#69]
Ancient branch
High

The localization of the Cenarius Circle is almost completely broken.
<details>
<summary>Click to expand</summary>

![ck2_1](https://user-images.githubusercontent.com/46576860/51876345-5c6a5c00-2379-11e9-98db-0bd23a3d44c0.png)
![ck2_2](https://user-images.githubusercontent.com/46576860/51876346-5d02f280-2379-11e9-830b-25b223ec897c.png)
![ck2_3](https://user-images.githubusercontent.com/46576860/51876347-5d02f280-2379-11e9-894e-b82f37e44dbc.png)
![ck2_4](https://user-images.githubusercontent.com/46576860/51876348-5d02f280-2379-11e9-8446-f66fb424d512.png)
![ck2_5](https://user-images.githubusercontent.com/46576860/51876349-5d9b8900-2379-11e9-9c63-b48c96d18441.png)
![ck2_6](https://user-images.githubusercontent.com/46576860/51876350-5d9b8900-2379-11e9-88bc-ce49f43c9705.png)
![ck2_10](https://user-images.githubusercontent.com/46576860/51876352-5d9b8900-2379-11e9-8b4f-6b3cfd20ab58.png)
![ck2_11](https://user-images.githubusercontent.com/46576860/51876353-5d9b8900-2379-11e9-91b3-11813bda1105.png)
![ck2_12](https://user-images.githubusercontent.com/46576860/51876354-5e341f80-2379-11e9-92c7-0c6bf18cfa5d.png)
![ck2_15](https://user-images.githubusercontent.com/46576860/51876356-5e341f80-2379-11e9-89c8-1951e667f7e7.png)
![ck2_16](https://user-images.githubusercontent.com/46576860/51876358-5e341f80-2379-11e9-85a8-93601c5fda60.png)

</details>

**Comment by MemeWizard** [comment]
This
<details>
<summary>Click to expand</summary>

![ck2_8](https://user-images.githubusercontent.com/46576860/53393101-76b14d00-39ac-11e9-9a35-a5fa4f78139c.png)
![ck2_18](https://user-images.githubusercontent.com/46576860/53393102-7749e380-39ac-11e9-814b-2775cfa7355f.png)

</details>
And double "A" in tooltip
<details>
<summary>Click to expand</summary>

![ck2_19](https://user-images.githubusercontent.com/46576860/53393126-90eb2b00-39ac-11e9-9b2b-790f9aecf898.png)

</details>
Other things seems fixed

**Comment by MemeWizard** [comment]
>double "A" in tooltip

Looks like vanilla bug
https://forum.paradoxplaza.com/forum/index.php?threads/ck-ii-3-0-1-1-ondo-extra-a-in-the-outcome-tooltip-of-intrigue-decisions.1155618/

**Comment by sejtalk** [comment]
Fixed
