### ISSUE TITLE
[LOCALIZATION] | Bubonic plague

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#691]
**Mod Version**
7581902d

**Please explain your issue in as much detail as possible:**
>The Bubonic plague will appear frequently and be extraordinary deadly.

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/64396239-a9c44f80-d065-11e9-9b97-ce60007130bd.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
