### ISSUE TITLE
[BUG] | misaligned army on north coast province

### ISSUE THREAD

**Issue by IXISparky** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#697]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
Military overhaul units
**What expansions do you have installed?**
all of the above
**Please explain your issue in as much detail as possible:**
the units standing in north coast stand too far to the left making them appear to be in the adjacent province 
**Steps to reproduce the issue:**
send an army to stand in the province of north coast
**Upload an attachment below: .zip of your save, or screenshots:**

![](https://cdn.discordapp.com/attachments/617359291376205834/620501426766086174/unknown.png)

**Comment by zumbak04** [comment]
Fixed!
