### ISSUE TITLE
The horde is falling apart

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#70]
Ancient branch
Critical

A horde falls apart if:
Lord X arranges a plot to revoke the title of his vassal and declares war on him.
Horde conquers the title of vassal.
The war started by Lord X, however, does not stop.
Now Lord X is fighting for this title with the Horde. Because of this, the ruler of the Horde is not considered an independent ruler and therefore the Horde disintegrates.

<details>
<summary>Click to expand</summary>

![ck2_3](https://user-images.githubusercontent.com/46576860/51880890-1073e300-238a-11e9-8926-d38e6f9085b3.png)
[save games.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/2805849/save.games.zip)

</details>

**Comment by zumbak04** [comment]
Fixed? It's a vanilla bug and I can't truly fix it, because it's part of vanilla hard-coded mechanics. At least, I'm 99% sure it won't happen to the Horde again.
