### ISSUE TITLE
[BUG] | Trade Coalition / Merchant republic - Election - Loose all tittles and goverment type

### ISSUE THREAD

**Issue by CasperPedersen** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#704]
------------------------------------------------------------------------------------------------------------
**Mod Version**
Steam 1.5.0

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Firstly, an event occurs sometimes stating that an election is under way, and when the next part triggers, a random other patriarch becomes the ruler of the merchant republic....

Secondly this time, my unlanded sister became ruler, randomly forcing the government to change to Landless, dissolving all trade posts and converting to monarchy government type.

Thirdly - If the game is saved while the new ruler event is open, and reloaded, Government type will not bug out...

**Steps to reproduce the issue:**
Wait until may 15 from save.

**Upload an attachment below: .zip of your save, or screenshots:**
[MechantRepublicBug.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3607115/MechantRepublicBug.zip)

**Comment by zumbak04** [comment]
Fixed!
