### ISSUE TITLE
too many "" in event texts

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#706]
**Mod Version**
5b907d65

**Please explain your issue in as much detail as possible:**
Too many `"` in texts
I blame 4 loc PR https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/pull/493#discussion_r305565622

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/64913851-8af24700-d750-11e9-89bd-9ef9a1c0ec6e.png)

</details>

**Comment by arithon** [comment]
you sure that it was made in localisation crusade?  I'm pretty sure we didn't use excel for that stuff anymore and double "" stinks of excel errors...  however, added the 2 changes to the loc crusade 5

**Comment by MemeWizard** [comment]
>you sure that it was made in localisation crusade?

Well, not quite, but If I'm mistaken, this means I never noticed extra `"` in branches before 4LPR

<details>

![Безымянный1](https://user-images.githubusercontent.com/46576860/64920471-c9bfe580-d7c0-11e9-832c-49a6edb3210a.png)

</details>
