### ISSUE TITLE
Plague event - Player can't declare war on the Scourge

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#709]
**Mod Version**
b5fc8f65

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Plague event don't have "Declare war on the Scourge" option

**Steps to reproduce the issue:**
Start in 603 as Terenas

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/64922674-8c685180-d7da-11e9-8e70-541da117b945.png)

</details>

**Comment by geffe1** [comment]
I found this, I demand the prestige I deserve.. add 1 prestige to the character Caitlyn next patch. okay.

**Comment by zumbak04** [comment]
> I found this, I demand the prestige I deserve.. add 1 prestige to the character Caitlyn next patch. okay.

I'll make it part of bugfix :3

**Comment by geffe1** [comment]
I don't think the AI can declare the war either. as I played some earlier when I checked MO.

**Comment by zumbak04** [comment]
Fixed!
