### ISSUE TITLE
"Press Claim" CB is visible even if you can't use it against selected character

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#712]
**Mod Version**
e41a90df

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
"Press all Claims" and "Claim" CB ends inconclusively immediately, because they are used against CC title, but why they visible in CB selection the first place?

**Steps to reproduce the issue:**
Ask High Priestess for claims on Cenarion Circle lands

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/64953177-d7da3880-d88a-11e9-91ee-b7843a6a1ae0.png)
![image](https://user-images.githubusercontent.com/46576860/64953414-6bac0480-d88b-11e9-9e58-a6751f335200.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
