### ISSUE TITLE
Remove HF sack event

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#714]
**Describe your suggestion in full detail below:**

You shouldn't have this event when you take evil guy's province

<details>

![image](https://user-images.githubusercontent.com/46576860/64963295-b20c5e00-d8a1-11e9-8d6b-632bce40c437.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
