### ISSUE TITLE
EVTOPTB_WCCC.240

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#716]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/commit/b5fc8f65612d842fe53721b673a205fdefddb143

**Please explain your issue in as much detail as possible:**
EVTOPTB_WCCC.240 makes no sense. Get rid of who?

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/64969798-a75bc400-d8b5-11e9-8b08-b30590fa3535.png)

</details>

**Comment by DJScias** [comment]
Hello there,

I'm assuming this implies the crew that's not working as fast as they should.. I made a change in how it's written below, what do you think about that? It's still "them" but the replacing part might give a bit more indication it's about the people excavating.

![image](https://user-images.githubusercontent.com/439655/65503304-f1036a80-dec4-11e9-98b2-0cd9dd057c43.png)

**Comment by MemeWizard** [comment]
> EVTDESC_WCCC.239;The excavation work for your barrow den has been slowed due to kobold attacks. Unless something is done the work will be slowed extensively.;;Die Erdarbeiten fьr Euren Grabhьgel sind durch Koboldangriffe verlangsamt worden. Wenn nichts unternommen wird, wird die Arbeit erheblich verlangsamt.;;;;;;;;;;;x

> EVTOPTB_WCCC.239;I'll pay someone to get rid of them.;;Ich werde jemanden bezahlen, um sie loszuwerden.;;;;;;;;;;;x

I think actual problem is that `EVTOPTB_WCCC.240` it's a copied `EVTOPTB_WCCC.239`, but it don't fit in this event.

**Comment by DJScias** [comment]
Hrrrh, then perhaps it should be something more like:
```
I'll pay for a new taskmaster and have them try to get everything back on track.```

Considering you still pay 100 gold.

**Comment by sejtalk** [comment]
its already fixed here https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/pull/750

**Comment by DJScias** [comment]
Alright, great!
