### ISSUE TITLE
Localization of the old gods are voided

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#72]
Ancient branch
Low

The old gods lack a huge amount of localization.
Some examples below:

<details>
<summary>Click to expand</summary>

![ck2_6](https://user-images.githubusercontent.com/46576860/51882518-37351800-2390-11e9-9cde-99d67141bfe4.png)
![ck2_7](https://user-images.githubusercontent.com/46576860/51882519-37cdae80-2390-11e9-8625-afc4775a0425.png)

</details>

**Comment by sejtalk** [comment]
fixed
