### ISSUE TITLE
WCLOA.1000+ is just copypasted vanilla pagan flavor events without changed localization

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#720]
**Mod Version**
e7dfabfe

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Some have missing localization, some are not adapted

**Steps to reproduce the issue:**
Pick Loa

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/65028605-fdc41380-d944-11e9-89bc-77a71fd84088.png)

</details>

**Comment by zumbak04** [comment]
I liked them more when they were disabled.

**Comment by MemeWizard** [comment]
They didn't work due to a bug
But now you can disable them intentionally
![image](https://user-images.githubusercontent.com/46576860/65067741-e0686700-d98f-11e9-9173-d4fcc1a7c9ce.png)

**Comment by zumbak04** [comment]
Removed them... waiting for the adaptation.
**SAD**
