### ISSUE TITLE
Hospitals for evil characters

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#725]
**Describe your suggestion in full detail below:**

Make dynamic localization for evil character's hospitals and buildings in hospitals

I don't think LK would care about orphans or public baths

<details>

![image](https://user-images.githubusercontent.com/46576860/65167791-eb80cd00-da4b-11e9-9ac1-a6bb9b727b5d.png)

</details>

**Comment by MemeWizard** [comment]
> Make dynamic localization

Or disable them, it will be fine too

**Comment by zumbak04** [comment]
Evils no longer use hospitals since 4b0fc433ebfdae2236568fb8a84cc0b1dd1aa606.
