### ISSUE TITLE
Nomad opinion malus from nomad government don't work

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#727]
**Mod Version**
4f0ce017

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
> [persistent.cpp:40]: Error: "Undefined modifier type! token: nomadic_opinion, near line: 77" in file: "common/governments/nomadic_governments.txt"

Nomad opinion malus from nomad government don't work

**Steps to reproduce the issue:**
`---`

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/65177326-293b2100-da5f-11e9-9f65-926b3f7970f6.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
