### ISSUE TITLE
Shath'Yar Inquisition

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#73]
Ancients branch
Low

The newly appointed priests of the old gods can hunt apostates.

<details>
<summary>Click to expand</summary>

![ck2_3](https://user-images.githubusercontent.com/46576860/51883143-bfb4b800-2392-11e9-85bf-c6fd2b5de9f2.png)

</details>

**Comment by zumbak04** [comment]
Closing since now Shath'yar Inquisition is a real thing.
