### ISSUE TITLE
Characters without legs with one-legged trait

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#736]
**Mod Version**
master branch

**Please explain your issue in as much detail as possible:**
Some characters don't have legs
How about change loc to something like "crippled"?

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/65376848-a8259900-dcad-11e9-881f-12b31743c137.png)

</details>

**Comment by DJScias** [comment]
Hello there,

What do you think of the below? Used your suggestion of going with "crippled" which can imply a lot of more major issues (like having lost a leg).

![image](https://user-images.githubusercontent.com/439655/65505126-d206d780-dec8-11e9-8027-ebccbadbcd91.png)

**Comment by zumbak04** [comment]
> What do you think of the below? Used your suggestion of going with "crippled" which can imply a lot of more major issues (like having lost a leg).

Great!
