### ISSUE TITLE
Children can be assigned to the position of cupbearer

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#74]
Master branch
Low

Children can be assigned to the position of cupbearer
<details>
<summary>Click to expand</summary>

![ck2_4](https://user-images.githubusercontent.com/46576860/51894900-0669d880-23ba-11e9-983c-7c4ec98f0cf0.png)

</details>

**Comment by ManuSwaG** [comment]
This is not a bug, Children are allowed to be a Cup bearer in base Ck2.

Why wouldn't be allowed to grand children the title of Cup Bearer?

**Comment by MemeWizard** [comment]
>Children are allowed to be a Cup bearer in base Ck2.

Okay, it's vanilla bug, so i report it to paradox.

>Why wouldn't be allowed to grand children the title of Cup Bearer?

Well, 0 years old characters shouldn't serve drinks.

**Comment by zumbak04** [comment]
I hope Paradox will fix it soon. Anyway, I made a temporary fix.
