### ISSUE TITLE
Undead children can be born

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#75]
Master branch
Medium

For some reason, the last child of this character does not have a portrait and I cannot click on it and open its character window.
Perhaps this is due to the fact that his wife has given birth to a child after he became undead.

<details>
<summary>Click to expand</summary>

![ck2_8](https://user-images.githubusercontent.com/46576860/51895751-fce17000-23bb-11e9-97fe-2d64cf25a5bf.png)
![ck2_9](https://user-images.githubusercontent.com/46576860/51895753-fce17000-23bb-11e9-8b73-ff0f11ae9506.png)
[Winterhoof598_09_15.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/2806750/Winterhoof598_09_15.zip)

</details>

**Comment by MemeWizard** [comment]
> It's because i didn't add undead vrykul children portraits.

I think that is not the problem.
The problem is that they must be born alive.

**Comment by zumbak04** [comment]
@sejtalk, I'll fix it, but could you add the child portrait anyway?

**Comment by zumbak04** [comment]
Fixed!

**Comment by sejtalk** [comment]
Fixed
