### ISSUE TITLE
True religion change clear modifiers

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#754]
**Mod Version**
Master branch

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
I think it's actually weird that modifier is cleared when character change it's true religion, but some decisions that gives modifiers check only character public religion, so you can get modifier that you shouldn't have.

**Steps to reproduce the issue:**
`---`

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/65471815-56316e80-de79-11e9-900a-0266dbeae224.png)
![image](https://user-images.githubusercontent.com/46576860/65472141-a826c400-de7a-11e9-854c-5b43068bb219.png)

</details>

_https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/pull/747#issuecomment-534337899_

**Comment by zumbak04** [comment]
Fixed in #747
