### ISSUE TITLE
Failed MC outcomes

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#756]
**Mod Version**
96ac9e45

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
WCCLS.617 don't give lunatic trait

**Steps to reproduce the issue:**
Fail mind control spell

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/65558224-93136900-df3e-11e9-9d82-ca05dfaf37d8.png)
![image](https://user-images.githubusercontent.com/46576860/65558231-9c043a80-df3e-11e9-8690-2acee57be8d4.png)

</details>

**Comment by MemeWizard** [comment]
WCCLS.618 give incapable trait only to your character

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/65659941-cdabfd00-e035-11e9-9602-6719672170fb.png)
![image](https://user-images.githubusercontent.com/46576860/65659947-d00e5700-e035-11e9-8c8d-173edb2aea8d.png)
![image](https://user-images.githubusercontent.com/46576860/65659950-d3094780-e035-11e9-83e9-ab72da4df1af.png)


</details>

**Comment by zumbak04** [comment]
Fixed!
