### ISSUE TITLE
WCDAC.4014 can fire from secret cultist

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#757]
**Mod Version**
96ac9e45

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
WCDAC.4014 can fire from secret cultist

**Steps to reproduce the issue:**
???

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/65559076-d8856580-df41-11e9-8ce0-ee05fae68ce1.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
