### ISSUE TITLE
Bug Report: Being able to avoid losing land to the scourge by being in revolt.

### ISSUE THREAD

**Issue by Varus211** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#76]
Which version of the mod does this apply to?
1.2 Release
How important is this bug/suggestion (Low/Medium/High/Critical)?
Low
Explain the bug or suggestion below:
If the Plague appears in your lands during a revolt, you can choose the option to declare war on the Scourge, but when you click it nothing happens. so you can get away from the plague scott free as a vassal by simply being in revolt.

**Comment by zumbak04** [comment]
Fixed!
