### ISSUE TITLE
Change Darrarhor troops location

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#762]
**Describe your suggestion in full detail below:**

Change Darrarhor troops location, since it's not standing in Darrarhor

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/65625004-a1f82b00-dfd3-11e9-86f0-5a43e4707654.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
