### ISSUE TITLE
Change Syndicate Leader

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#771]
**Describe your suggestion in full detail below:**

> Following the demise of Lord Aliden Perenolde, who directed the Syndicate's actions in the Alterac Mountains, Lord Falconcrest became one of the few Syndicate leaders, commanding their forces in Arathi from the semi-abandoned fortress of Stromgarde Keep.

> Aliden has not been seen since the Cataclysm

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/65745340-14682880-e104-11e9-8e4d-26d87ea54fe0.png)

</details>

**Comment by DJScias** [comment]
It seems the current Lord, Willichar, owns the Syndicate and Strahnbrad + Headlands right now.

If this is changed to Aliden, would he own both Strahnbrad and Headlands or would Willichar keep the Headlands? I'm not sure if Willichar was meant to be a placeholder or if he actually held any land as-is.

**Comment by DJScias** [comment]
To add to the above, I have a PR ready but I'm waiting to push it until I got confirmation if Aliden should own Headlands as well or not.

**Comment by zumbak04** [comment]
> To add to the above, I have a PR ready but I'm waiting to push it until I got confirmation if Aliden should own Headlands as well or not.

Let him rule.

**Comment by DJScias** [comment]
It shall be done.
