### ISSUE TITLE
Secret Cults can desecrate their own temple

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#777]
**Mod Version**
98f96324

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Secret Cults can desecrate their own temple

**Steps to reproduce the issue:**
Temple holder in the last event must belong to your character religion
Also, you can revoke title from temple holder after receiving quest or force him to change religion, so you can't fix it by scoping to previous temple holder 🤔

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/65813864-3dabb600-e1e3-11e9-9cb9-1a7e440b221b.png)

</details>

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/65814025-2ec60300-e1e5-11e9-9934-eade31e44123.png)

</details>

**Comment by zumbak04** [comment]
Fixed! For more info, take a look at the commit comment.
