### ISSUE TITLE
Tauren children can spawn with totems.

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#78]
Master branch
Low

I'm not sure if this is a bug or not, but I find it strange that the totem may appear in the treasury of children.
<details>
<summary>Click to expand</summary>

![ck2_3](https://user-images.githubusercontent.com/46576860/51953058-e3880480-244b-11e9-92e1-9cff84cd5440.png)

</details>

**Comment by sejtalk** [comment]
Fixed
