### ISSUE TITLE
Changing religion banish your prisoners

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#781]
**Mod Version**
98f96324

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Changing religion banish your prisoners

**Steps to reproduce the issue:**
Imprison your close relative
Change your character religion to something evil

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/65819588-22629a00-e227-11e9-8991-2c4e804352b0.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
