### ISSUE TITLE
Secret cultists don't get visibility modifier

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#782]
**Mod Version**
98f96324

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Secret cultists don't get "suspicious" visibility modifier

**Steps to reproduce the issue:**
Do any activity that raise your suspicion level

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/65819690-35299e80-e228-11e9-9f75-2339fdec0d47.png)
![image](https://user-images.githubusercontent.com/46576860/65819692-378bf880-e228-11e9-9ef1-95015a97892b.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
