### ISSUE TITLE
Odyn should not be an interactive character

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#79]
Master branch
Medium

Possible player (or AI) interactions with Odyn may be complete nonsense.

<details>
<summary>Click to expand</summary>

![1](https://user-images.githubusercontent.com/46576860/51964512-e13b9f80-2477-11e9-9f14-308dbe3f127e.png)
![2](https://user-images.githubusercontent.com/46576860/51964513-e13b9f80-2477-11e9-83be-f2d8ce80a662.png)
![3](https://user-images.githubusercontent.com/46576860/51964514-e1d43600-2477-11e9-9e59-ca377be54d9c.png)
![4](https://user-images.githubusercontent.com/46576860/51964515-e1d43600-2477-11e9-95d5-5ac9f7f35435.png)
![5](https://user-images.githubusercontent.com/46576860/51964516-e1d43600-2477-11e9-80cc-c60ad6c51b7f.png)
![6](https://user-images.githubusercontent.com/46576860/51964518-e26ccc80-2477-11e9-9baa-19eee35429df.png)
![7](https://user-images.githubusercontent.com/46576860/51964520-e26ccc80-2477-11e9-88cc-302925442b33.png)
![8](https://user-images.githubusercontent.com/46576860/51964522-e26ccc80-2477-11e9-9393-33f5cda50213.png)
![9](https://user-images.githubusercontent.com/46576860/51964523-e26ccc80-2477-11e9-9539-4f84f82c2912.png)
![10](https://user-images.githubusercontent.com/46576860/51964524-e3056300-2477-11e9-8207-f71e277521fc.png)
![11](https://user-images.githubusercontent.com/46576860/51964525-e3056300-2477-11e9-8abf-56d4908f0ed7.png)
![12](https://user-images.githubusercontent.com/46576860/51964526-e3056300-2477-11e9-9649-a7c554d05723.png)

</details>

**Comment by zumbak04** [comment]
Odin isn't interactive since #243.
