### ISSUE TITLE
"Build the Wall" decision bugs

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#790]
**Mod Version**
46bfcd20

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
- Castle infrastructure required in capital, not in Hothills
- You don't need to own Hothills to build wall in it

**Steps to reproduce the issue:**
`---`

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/65841002-bc117080-e327-11e9-8d4d-a5bb621dd6a5.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
