### ISSUE TITLE
Nomads can't pillage Ahn'qiraj

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#793]
**Mod Version**
46bfcd20

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Can't pillage holding because there is "Unique building block it", but there is no unique buildings in this holding after slaying C'thun.

**Steps to reproduce the issue:**
Conquer Ahn'qiraj as Nomad

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/65843476-83c75d80-e33a-11e9-876d-e912cef635f7.png)

</details>

**Comment by zumbak04** [comment]
WAD. Divided "Unique building does NOT block it" condition into 2 conditions: "Unique building does NOT block it" and "Is NOT an important place in event chains".
