### ISSUE TITLE
Not cleared traits after transformation

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#794]
**Mod Version**
46bfcd20

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
> can not get diseases

> lover's pox

**Steps to reproduce the issue:**
Turn character with lover's pox into undead

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/65847993-ae221680-e34c-11e9-81ac-950e171fbfc8.png)
![image](https://user-images.githubusercontent.com/46576860/65848147-69e34600-e34d-11e9-9ba5-05d94a1e369d.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
