### ISSUE TITLE
Traits clearing from rejuvenation

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#798]
**Mod Version**
46bfcd2

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**

> if you get immortal trait when you are already old, it will rejuvenate you.

Infertile and infirm traits are not cleared after rejuvenation

**Steps to reproduce the issue:**
Get infertile and infirm traits before rejuvenation

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/65931300-cb6ce880-e411-11e9-8e51-e4b28386feab.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
