### ISSUE TITLE
Forge Runeblade - Missing Localization

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#80]
Master branch
Low

Missing Localization
<details>
<summary>Click to expand</summary>

![ck2_7](https://user-images.githubusercontent.com/46576860/51965745-8efc7d80-247b-11e9-8f78-91678b31f5ea.png)

</details>

**Comment by DukeJeans** [comment]
Fixed, added event description for finishing of runeblade.
