### ISSUE TITLE
 You can complete "Turn undead" quest without turning character undead

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#801]
**Mod Version**
46bfcd2

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
 You can complete "Turn undead" quest without turning character undead

**Steps to reproduce the issue:**
Click on "turn undead" decision while having "Turn undead" quest

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/65932875-0a05a180-e418-11e9-85da-e45fb08ded9f.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
