### ISSUE TITLE
Nethergarde

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#804]
**Mod Version**
98f96324

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
When Nethergarde forms, Black Morass owner don't sell baronies to Nethergarde

**Steps to reproduce the issue:**
Nethergarde must be formed

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/65949366-c4ab9900-e444-11e9-8a5f-27ae35983f98.png)
![image](https://user-images.githubusercontent.com/46576860/65949375-c8d7b680-e444-11e9-8010-699564031463.png)
![image](https://user-images.githubusercontent.com/46576860/65949412-d7be6900-e444-11e9-9f5a-0a7c60c2be51.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
