### ISSUE TITLE
[BUG] | Im muted

### ISSUE THREAD

**Issue by sejtalk** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#807]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**

**What expansions do you have installed?**

**Please explain your issue in as much detail as possible:**
As the title says

**Steps to reproduce the issue:**

**Upload an attachment below: .zip of your save, or screenshots:**

**Comment by MemeWizard** [comment]
I guess it depends on the type of monitor you have. Looks ok on mine.

![Безымянный2](https://user-images.githubusercontent.com/46576860/65960061-3f33e300-e45c-11e9-9483-f1768e2c47b8.png)

**Comment by sejtalk** [comment]
![image](https://user-images.githubusercontent.com/31159937/65960172-20315300-e454-11e9-92d4-47b1d65d8170.png)

**Comment by geffe1** [comment]
Help.. I'm muted 2
