### ISSUE TITLE
No loc in bloodlines for bloodlines effect

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#808]
**Mod Version**
98f96324

**Please explain your issue in as much detail as possible:**
`cenarius`, `deathwing` bloodlines have `bloodline_heroes` flag, but no text effect
`turalyon` bloodline have `bloodline_inspire_commanders` flag, but no text effect

Also, `tirion` bloodline have `bloodline_effect_inspire_commanders` effect, but don't have `bloodline_inspire_commanders` flag

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/65959193-07c43700-e45a-11e9-82b7-c65a2cd824fa.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
