### ISSUE TITLE
Carousing bugs

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#81]
Master branch
Low

Titan-forged can't invite characters to carousing, but can be invited.
Also, the "invite to carousing" decision requirements talks about muslims.

<details>
<summary>Click to expand</summary>

![ck2_19](https://user-images.githubusercontent.com/46576860/51987481-ab1c1100-24b3-11e9-958f-c70a96cda6b9.png)
![ck2_19](https://user-images.githubusercontent.com/46576860/51985806-d8ff5680-24af-11e9-8d90-67df7df11774.png)
![ck2_20](https://user-images.githubusercontent.com/46576860/51985807-d997ed00-24af-11e9-891e-be515a5b8721.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
