### ISSUE TITLE
Mana restoring too fast

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#813]
**Mod Version**
efdb140b

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Mana should be restored with 1/year speed, but for some reason in this save mana is fully restored (1 -> 4) in 1 year.

**Steps to reproduce the issue:**
Load save

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/66054559-da9c8500-e53c-11e9-86b3-ec207e6d6609.png)
![image](https://user-images.githubusercontent.com/46576860/66054566-dd977580-e53c-11e9-95d9-dfc52b53882e.png)
![image](https://user-images.githubusercontent.com/46576860/66054574-e0926600-e53c-11e9-9964-6eacfaffa496.png)

</details>

[Karazhan588_06_01.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3681711/Karazhan588_06_01.zip)

**Comment by zumbak04** [comment]
Fixed!
