### ISSUE TITLE
Can't abduct quest target

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#817]
**Mod Version**
efdb140

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Can't abduct quest target

**Steps to reproduce the issue:**
???

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/66138031-a7262d00-e606-11e9-8a03-d6136853ce58.png)
![image](https://user-images.githubusercontent.com/46576860/66138036-aa211d80-e606-11e9-9ebf-c607311d9756.png)

</details>

[Caer_Darrow608_04_24.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3686696/Caer_Darrow608_04_24.zip)

**Comment by MemeWizard** [comment]
Same here

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/66397266-1bd0e100-e9e4-11e9-85a0-5fe90afd157e.png)
![image](https://user-images.githubusercontent.com/46576860/66397273-1ecbd180-e9e4-11e9-8961-8f086036306d.png)
![image](https://user-images.githubusercontent.com/46576860/66397284-23908580-e9e4-11e9-8ff6-3691de8882ab.png)

</details>

[Caer_Darrow611_10_10.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3702450/Caer_Darrow611_10_10.zip)

**Comment by zumbak04** [comment]
Will be fixed by implementing https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/issues/799 .
