### ISSUE TITLE
Game-spawned Iron dwarves do not get racial trait

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#82]
Master branch
Medium

It seems that no game-spawned iron dwarf gets a racial trait, even after a significant (10 years) amount of time.
<details>
<summary>Click to expand</summary>

![ck2_24](https://user-images.githubusercontent.com/46576860/51988105-ed921d80-24b4-11e9-8292-a1b865aa4904.png)
![ck2_18](https://user-images.githubusercontent.com/46576860/51988158-11556380-24b5-11e9-80d8-68b106d0f952.png)
![ck2_20](https://user-images.githubusercontent.com/46576860/51988164-14505400-24b5-11e9-8e9f-50a4e282c1f0.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
