### ISSUE TITLE
The Holy Father

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#823]
**Mod Version**
d22eaa51

**Please explain your issue in as much detail as possible:**
> Tyrande

> The Holy Father

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/66390241-f1c2f300-e9d2-11e9-98b3-da0d36cdec51.png)

</details>

**Comment by geffe1** [comment]
Daddy Tyrande UwU I knew she had a donger
