### ISSUE TITLE
Non-warcraft references in game rules

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#827]
**Mod Version**
f66a82f9

**Please explain your issue in as much detail as possible:**
"Titles Named After Dynasties" and "Cultural Title Names" have non-warcraft references in description.

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/66418561-058a4b80-ea0b-11e9-9a5c-1035cce7921e.png)

</details>

**Comment by DukeJeans** [comment]
Rewrote `RULE_DYNASTY_TITLE_NAMES_ON_DESC` to incorporate names like Kolkar and Bloodhood instead in 217a4c2

**Comment by MemeWizard** [comment]
What about cultural title names?

**Comment by DukeJeans** [comment]
I'm just going to simplify the matter and remove the examples of dynasty names, done in 63de33b.

**Comment by MemeWizard** [comment]
> What about cultural title names?

> I'm just going to simplify the matter and remove the examples of dynasty names, done in 63de33b.

It's not the thing I meant...

![image](https://user-images.githubusercontent.com/46576860/68549952-3ea14b80-040f-11ea-83ba-f275c9e17590.png)

**Comment by zumbak04** [comment]
Ok, Cultural Title Names are done.
