### ISSUE TITLE
[SUGGESTION] Add decisions "Borrow money from loan" and and "banish loan sharks".

### ISSUE THREAD

**Issue by TheodericFlavianos** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#831]
I have a small suggestion: add in mod decision "Borrow money from loan sharks" similar to vanilla CK2 "Borrow money from Jews" and "banish loan sharks", similar to vanilla decision. Moneylenders, for example, can be bankers for the Alliance or goblins for the Horde. 

I hope you will add it sometime in the future.

**Comment by DJScias** [comment]
This could technically just be the Steamwheedle Cartel?

They're lore-wise neutral and apparently he's the richest entity that has ever existed on Azeroth (he being Trade Prince Steamwheedle).

**Comment by zumbak04** [comment]
> This could technically just be the Steamwheedle Cartel?
> 
> They're lore-wise neutral and apparently he's the richest entity that has ever existed on Azeroth (he being Trade Prince Steamwheedle).

The Steamwheedle may not exist. I would make decision where you choose from whom you will borrow money.

**Comment by mdbpr-iscteiulpt** [comment]
Ill probably be the one working on this since i already have a mod that dabbled in this cenário. Where you can borrow Money from rulers. Not i just need to make it more specific and natural

**Comment by zumbak04** [comment]
> Ill probably be the one working on this since i already have a mod that dabbled in this cenário. Where you can borrow Money from rulers. Not i just need to make it more specific and natural

Assigned you :3

**Comment by zumbak04** [comment]
@TheodericFlavianos implemented in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/pull/1356 except banishing because you borrow from a specific ruler now instead of vanilla.
