### ISSUE TITLE
CB is visible even if you can't use it against selected character

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#835]
**Mod Version**
93a36baa

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
CB is visible even if you can't use it against selected character

**Steps to reproduce the issue:**
Declare war against faction leader tributary

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/66589802-03092c80-eb98-11e9-9c6b-59134180da8d.png)

</details>

[Zul'aman589_06_19.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3713710/Zul.aman589_06_19.zip)

**Comment by zumbak04** [comment]
Fixed!
