### ISSUE TITLE
manifest_destiny_invasion can be used by an lowborn character

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#836]
**Mod Version**
Master

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
manifest_destiny_invasion can be used by any lowborn character

**Steps to reproduce the issue:**
Dalaran always declare war on Alterac with this CB.

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/66596149-0820a880-eba5-11e9-98f9-d784c95558e6.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
