### ISSUE TITLE
Hospital orphanage - localization is missing.

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#84]
Master branch
Low

Hospital orphanage - localization is missing.
<details>
<summary>Click to expand</summary>

![ck2_17](https://user-images.githubusercontent.com/46576860/51995823-8d0adc80-24c4-11e9-9f4c-2d15bc7ea5e0.png)

</details>

**Comment by DukeJeans** [comment]
Fixed.
