### ISSUE TITLE
The Twilight Horde

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#85]
Master branch
Medium

If you get the title of the twilight hammer, you will get the events of the twilight hammer.
<details>
<summary>Click to expand</summary>

![1](https://user-images.githubusercontent.com/46576860/51998889-98f99d00-24ca-11e9-8625-6d5d16de81b7.png)
![2](https://user-images.githubusercontent.com/46576860/51998890-99923380-24ca-11e9-80eb-bb17b4a1dd92.png)
![3](https://user-images.githubusercontent.com/46576860/51998891-99923380-24ca-11e9-8baa-2cf2f76c6e75.png)
![4](https://user-images.githubusercontent.com/46576860/51998892-99923380-24ca-11e9-9f5f-69d6e0cc06e1.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
