### ISSUE TITLE
Disable request general power

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#850]
**Describe your suggestion in full detail below:**

Right now, you can't get "Cataclysm" or "Ruling over Black Empire" policies, so showing this decision is just nothing more than trolling players with non-existent content.

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/66822169-5db1d800-ef4c-11e9-8cf6-4af6ab3c516d.png)

</details>

**Comment by sejtalk** [comment]
the content exists just not on master branch

**Comment by MemeWizard** [comment]
lame excuse

**Comment by MemeWizard** [comment]
If it don't exist on master branch, it means it mush be removed from master branch and added back on the other branch when it will be ready

**Comment by sejtalk** [comment]
so you want to remove and add something for no reason ?

**Comment by sejtalk** [comment]
youre a big boy

**Comment by sejtalk** [comment]
im too busy

**Comment by zumbak04** [comment]
Commented out in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/commit/da07c727d899b5002720cbc830457cdc0fbe8e06 .
