### ISSUE TITLE
Peaceful and prosperous old gods

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#86]
Master branch
Medium

#85 
For some reason, the game believes that my orc can rule in peace and prosperity, so I can choose not only war or intrigue focus.

<details>
<summary>Click to expand</summary>

![6](https://user-images.githubusercontent.com/46576860/51998951-bc244c80-24ca-11e9-9717-607a96d2ff4f.png)

</details>

**Comment by zumbak04** [comment]
Fixed!

**Comment by zumbak04** [comment]
> Huh? But that was not tied to the religion itself but rather to the government form, the "Black pact". We have the same thing with the "Demonic Legion" and "Undead Horde" governments, did you decide to change it?

Yap...

> Death God, Legion and Shath'yar characters can't now select "Rulership", "Business", "Hunting", "Carousing", "Family", "Scholarship" and "Theology" focuses.

Plus, I changed description of that condition, so now it says about government.
