### ISSUE TITLE
[BUG] Tribal to Tribal Monarchy

### ISSUE THREAD

**Issue by Rebel4ever85** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#862]
The conversion to tribal monarchy from tribal seems to cause some buildings to turn black and unresponsive. I was playing as Harpies not sure if it happens to other races.

All DLCs except - Sunset Invasion, Sword of Islam, Jade Dragon and Raja's of India.

![image](https://user-images.githubusercontent.com/56791113/67205199-1d000600-f407-11e9-83b9-aff41c7dd2fc.png)

**Comment by MemeWizard** [comment]
There is no such problem in main mod, report it to sub-mod author

![image](https://user-images.githubusercontent.com/46576860/67205820-31e59500-f419-11e9-9c0c-8abce8508172.png)
