### ISSUE TITLE
[BUG] | City title name error

### ISSUE THREAD

**Issue by TheOneNation** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#865]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
Current Steam version

**What expansions do you have installed?**
All of them

**Please explain your issue in as much detail as possible:**
After converting Old Glade to my character's religion and culture and then converting the tribe into a castle, the city spawned is called "Aur?lien Trollope" -- I'm guessing the ? appears because there is some sort of incorrect character. I don't know why this happens. I thought I should point it out. I'm not sure what the city title's actual name is supposed to be.

**Steps to reproduce the issue:**
Conquer (or console command) Old Glade, convert it to your religion and culture (quick way is event 55001 if you make it your capital), then right click the tribal holding and click the "Convert to Castle" button.

**Upload an attachment below: .zip of your save, or screenshots:**

**Comment by zumbak04** [comment]
Fixed in 0a2dbb3993a174b10f42977dfc9e25b3a1535dd6 .
