### ISSUE TITLE
Old gods are religiously tolerant

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#87]
Master branch
Medium

#85 
The servants of the old gods may have legion characters in the council.
<details>
<summary>Click to expand</summary>

![8](https://user-images.githubusercontent.com/46576860/51998967-c6dee180-24ca-11e9-983c-686e8a524cbe.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
