### ISSUE TITLE
WCDRN.100 if Legion didn't Invade

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#878]
**Mod Version**
f63a4a0d

**Please explain your issue in as much detail as possible:**

There was no Legion Invasion in this game, but WCDRN.100 event says otherwise
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/67621023-48bf2980-f815-11e9-983d-eb97b3221f81.png)

</details>

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/67620970-efef9100-f814-11e9-9b66-23df651f5d6a.png)

</details>

**Comment by mdbpr-iscteiulpt** [comment]
Well if you remove not so long ago it could be refering to the original burning legion invasion on pre azeroth azeroth
