### ISSUE TITLE
Shadow Council does not automatically dismiss when character changes religion

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#88]
Master branch
Medium
#85 

If the leader of the Horde turns into a servant of the old gods, unemployment does not jump to 100%
<details>
<summary>Click to expand</summary>

![7](https://user-images.githubusercontent.com/46576860/52002110-2987ab80-24d2-11e9-84f3-d3e0cfde0beb.png)

</details>

**Comment by zumbak04** [comment]
100% unemployment! Fixed?

**Comment by zumbak04** [comment]
Forgot to add missing localisation I noticed on screenshots.

**Comment by zumbak04** [comment]
Added localisation.
