### ISSUE TITLE
Cenarion Enclave without Reaper's Due DLC

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#882]
**Mod Version**
Master Branch

**What expansions do you have installed?**
No Reaper's Due

**Please explain your issue in as much detail as possible:**
You can build Cenarion Enclave without Reaper's Due DLC
Nothing will happen, tho

**Steps to reproduce the issue:**
Build Cenarion Enclave without Reaper's Due DLC

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/67640008-44276d80-f908-11e9-9bf9-caefdfa09687.png)
![image](https://user-images.githubusercontent.com/46576860/67640015-4c7fa880-f908-11e9-88c0-62e484a39ab8.png)

</details>

**Comment by sejtalk** [comment]
This mod requires the following DLCs for full functionality: Horse Lords.png Horse Lords, DLC icon Monks and Mystics.png Monks and Mystics, and DLC icon Reaper's Due.png The Reaper's Due.

**Comment by MemeWizard** [comment]
Funny joke.
Reaper's Due required because if there is no Reaper's Due, there is no plague, not because someone made minor decision that is not working without DLC and not DLC-locked.
Fix when

**Comment by sejtalk** [comment]
Ok i'll DLC lock it

**Comment by zumbak04** [comment]
> Ok i'll DLC lock it

Are you from Paradox Interactive?
![image](https://user-images.githubusercontent.com/46384992/67640583-e3eaf880-f914-11e9-83c2-f7298036658e.png)
