### ISSUE TITLE
Summon the Burning Legion tooltips

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#887]
**Mod Version**
36e92cc5

**Please explain your issue in as much detail as possible:**
> use your magic and the power of magical artifacts

Not true, my char don't have any magical artifacts

> you become vassal

Also not true

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/67727418-67cae080-f9fa-11e9-945f-1a227ebbaa89.png)
![image](https://user-images.githubusercontent.com/46576860/67727449-7d400a80-f9fa-11e9-9104-4db29b1decb0.png)

</details>

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/67727509-b9736b00-f9fa-11e9-942b-e15873adc61b.png)
![image](https://user-images.githubusercontent.com/46576860/67727547-de67de00-f9fa-11e9-9a7e-5ba6c6012dfb.png)
![image](https://user-images.githubusercontent.com/46576860/67727535-d14aef00-f9fa-11e9-9acb-e772f90e3b68.png)

</details>

**Comment by arithon** [comment]
1. Is fixed.
2. Are they supposed to become a vassal?
Yes -> Not loc problem.
No -> lemme know

**Comment by zumbak04** [comment]
> 2. Are they supposed to become a vassal?
>    Yes -> Not loc problem.
>    No -> lemme know

Sometimes no.
