### ISSUE TITLE
The Defeat of the Burning Legion

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#888]
**Mod Version**
36e92cc5

**Please explain your issue in as much detail as possible:**

1. Event text is written like it's a player defeated the Burning Legion, even if it's not.

2. Option text is weird. Why Legion character is happy about Azeroth being saved?

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/67727890-34895100-f9fc-11e9-97a4-35fe86482cf3.png)

</details>

**Comment by arithon** [comment]
1. Thing is fixed.
2. I don't see it as cheering, just as stating that Azeroth is save now.

**Comment by zumbak04** [comment]
> 2. Option text is weird. Why Legion character is happy about Azeroth being saved?

On it. Will tweak it a bit.
