### ISSUE TITLE
[BUG] | Black Pact Government no gender equal

### ISSUE THREAD

**Issue by Andronovo** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#889]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.5

**What expansions do you have installed?**
All the important ones, other than sunset invasion.

**Please explain your issue in as much detail as possible:**
If you play as a Black Pact government from a historical start, it's fine. However if you play as one that was generated some point during gameplay, it will say you have absolute cognatic but you will only be able to nominate male heirs and grant titles to males.

**Steps to reproduce the issue:**
Run the game, wait for Scourge, Burning Legion, or naga to spawn, then switch to them.

**Upload an attachment below: .zip of your save, or screenshots:**
![ck2_1](https://user-images.githubusercontent.com/57071060/67736685-83bc8b00-f9d6-11e9-84ed-9262148bc840.png)

![ck2_2](https://user-images.githubusercontent.com/57071060/67737089-fed27100-f9d7-11e9-9b32-002b033f45b4.png)

It should be easy enough to reproduce on your own, I have tested this one a lot with multiple different government types and I have no idea what causes it. You'll probably have to do a lot of testing to narrow this one down. If you want to test it fast just start as Arthas in reign of chaos.

**Comment by zumbak04** [comment]
> It should be easy enough to reproduce on your own

@Andronovo , the biggest lie in my life. Did like... 15 testruns (10 years, from 603 to 613) and noticed this bug in 2 of them on 1 ruler. So, I would say it's random. Anyway, made some fixed, but I ain't sure since the bug is not reproducible on purpose. If you notice it in future versions, reopen this issue.

**Comment by Andronovo** [comment]
In my game it only effects the governments generated during play, not the ones existing from historical starts. Did you check those as well? I tested it about 20 times and it was pretty consistent, on legion, death god, and shaath'yar characters.

**Comment by Andronovo** [comment]
Keep in mind it has to be a government that switched to Black Pact after the historical start. I have tested it with the current build and it definitely is still there, though sometimes it seems to not happen for no reason.

**Comment by zumbak04** [comment]
@Andronovo by the current build you mean the master branch? It's not there.
https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/commit/1717a6b617b3308cc63b24f8747086bdad513138
Fix is located on `bug-crusade-20` .
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/68055163-728eb980-fd09-11e9-8087-1dd6806706e0.png)

</details>
