### ISSUE TITLE
High level classes can't do what lower level classes can

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#895]
**Mod Version**
7c373bfc

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Legendary necro have less choices in "Turn yourself Undead" event, because event check only `is_7_8_magic_class_trigger`, without checking 9-10 lvl classes.

Idk if there may be more such causes

**Steps to reproduce the issue:**
`---`

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/68059237-d2d32a80-fd0c-11e9-98e1-75ae0239febb.png)

![image](https://user-images.githubusercontent.com/46576860/68059232-ccdd4980-fd0c-11e9-907e-5bfe972b33d3.png)

</details>

**Comment by zumbak04** [comment]
Fixed? Noticed this bug only in Turn Undead options.
