### ISSUE TITLE
Lower tier classes should be more common among AI characters

### ISSUE THREAD

**Issue by sicknot1** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#90]
Courtier with high martials skills that ask to join your court but doesn't have warrior class
High learning landed character without priest, mage or paladin class trait
Lack of mages, no court mage minor title

Well basically, there are so many characters in the world without a class. Being a high stewardship administrator tipe of characters makes ok to not have a class. Being an low iq ogre without warrior or hunter class is extremely lore unfriendly. Those are the examples i could come with, just add a way for AI characters to seek training, landed could ask you, or others, via favors (cashing or debting them), unlanded could use gold, friendship, and such, if met criteria for class.

**Comment by zumbak04** [comment]
Tweaked ways to get class traits a few times. High attribute requirements are still there because otherwise classes will be too common, but now invited characters and... just characters with class are more common. If you want MOAAAR, reopen the issue. Want to know your opinion.
