### ISSUE TITLE
Alliance leader remains alliance leader after abdication

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#901]
**Mod Version**
136c94f4

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Alliance leader remains alliance leader after abdication

**Steps to reproduce the issue:**
Load save, surrender.

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/68068024-ffb12d00-fd60-11e9-847d-2f1ad131fd82.png)
![image](https://user-images.githubusercontent.com/46576860/68068025-0770d180-fd61-11e9-9245-7e3f72768f23.png)
![image](https://user-images.githubusercontent.com/46576860/68068033-35eeac80-fd61-11e9-9b9e-2ea8289b1bf1.png)

</details>

[Lordaeron603_12_12.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3800263/Lordaeron603_12_12.zip)

**Comment by zumbak04** [comment]
Interestingu bagu. To fix it, we need to reconsider how the leader of the Alliance works. Will be pretty time consuming.
