### ISSUE TITLE
Old God building can be destroyed in raid

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#904]
**Mod Version**
eec79a27

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Old God building can be destroyed in raid

**Steps to reproduce the issue:**
Loot Ahn'qiraj, be (un)lucky

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/68075255-6ca2e200-fdb6-11e9-9d0a-052cb78868b8.png)
![image](https://user-images.githubusercontent.com/46576860/68075227-15047680-fdb6-11e9-9f23-3c7c089e26b0.png)

</details>

**Comment by sejtalk** [comment]
mechanic reworked

**Comment by zumbak04** [comment]
@sejtalk write this in the changelog of your PR: `Fixes #904`. It will close this issue when you merge the PR.
