### ISSUE TITLE
"Convert to local culture" decision name is too long

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#918]
**Mod Version**
7b6161ec

**Please explain your issue in as much detail as possible:**
"Convert to local culture" decision name is too long

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/68527558-2d661b00-02f9-11ea-8249-0db83b9e64d0.png)

</details>

**Comment by DukeJeans** [comment]
Adjusted to `Convert to [Root.Capital.Culture.GetName]` in b6a8935b
