### ISSUE TITLE
Shields not appearing with models submod

### ISSUE THREAD

**Issue by arithon** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#921]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.6
**What expansions do you have installed?**
all
**Are you using any submods/mods? If so, which?**
a bigger interface, harpies, models
**Please explain your issue in as much detail as possible:**
Shields of, for example, Stormwind, Lordaeron and Horde are gone when models submod is enabled.
**Steps to reproduce the issue:**
download/install models submod, start first bookmark
**Upload an attachment below: .zip of your save, or screenshots:**
![grafik](https://user-images.githubusercontent.com/47716948/68543812-44217600-03bc-11ea-874a-3aa486e6c47d.png)

**Comment by arithon** [comment]
http://imgurl.me/image/Pc0fM

**Comment by Varus211** [comment]
Having the same issue aswell, only using Guardians of Azeroth, GoA Models and GoA Music.
It fixes itself when the model mod is disabled.

**Comment by zumbak04** [comment]
Fixed in the Steam version, other downloads will be fixed with the release of the next patch.
