### ISSUE TITLE
Turning characters into undead does not take gold, but gives gold.

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#93]
Master branch
Low

Turning characters into undead gives you resources, doesn't take them.
<details>
<summary>Click to expand</summary>

![ck2_1](https://user-images.githubusercontent.com/46576860/52027314-04b82600-251c-11e9-9983-3f178e4c62d2.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
