### ISSUE TITLE
Automatic marriage after divorce

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#94]
Master branch
High

Some woman just came to my court and became the wife of my heir.
I suppose it has something to do with automatic divorces.

<details>
<summary>Click to expand</summary>

![ck2_1](https://user-images.githubusercontent.com/46576860/52032167-ef012b80-2530-11e9-94a0-0fd0751938fb.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
