### ISSUE TITLE
Founding of Theramore CTD

### ISSUE THREAD

**Issue by dissatisfieduser** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#942]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
v. 1.6.0
**What expansions do you have installed?**
All of them
**Are you using any submods/mods? If so, which?**
I was using the "GK Static Portraits"; "More Buildable Wonders"; and "Title Manager"
**Please explain your issue in as much detail as possible:**
I get a crash to desktop after the event "The Founding of Theramore" fires.
**Steps to reproduce the issue:**
Play the game? I started on the First War bookmark and played until the founding of Teramore event which always caused a CTD.
**Upload an attachment below: .zip of your save, or screenshots:**
[603_08_16.ck2.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3839767/603_08_16.ck2.zip)

Thank you for the assistance.

**Comment by zumbak04** [comment]
Tried without submods, can't reproduce it.
I would recommend to play on 3.2.2 or 3.2.1. 3.3.0 isn't supported.
@dissatisfieduser , it may be due to "Title Manager" submod. Try to disable it. Tell me if this helps.

**Comment by dissatisfieduser** [comment]
Tried using 3.2.2 and 3.2.1. Save file was not supported so I cannot test the effectiveness of zumbak04's suggestion.

**Comment by zumbak04** [comment]
> Tried using 3.2.2 and 3.2.1. Save file was not supported so I cannot test the effectiveness of zumbak04's suggestion.

@dissatisfieduser 3.3.0 isn't reason of crash. I tried 3.3.0.

**Comment by dissatisfieduser** [comment]
Disabled all mods other than the main mod. Still getting CTD.

**Comment by zumbak04** [comment]
> Disabled all mods other than the main mod. Still getting CTD.

**_SAD._** @dissatisfieduser, still not getting CTD.
What is your OS?
What is your checksum on 3.3.0 without other mods and submods? Mine is DDQF.

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/69437185-3e347900-0d5c-11ea-8802-0c80c99718e5.png)

</details>

**Comment by Mystic-Fox** [comment]
I also regularly have this problem, and would like to contribute details to help.
Ver 1.6.0
All DLCs installed
Using the submods for Models, Music, Bigger Interface mod, and Ruler Designer Unlocked

I don't get the CTD every time, clean reinstalling the game will fix it for a while before it comes back. It happens in multiplayer as well as in singleplayer, regardless of whether or not I'm hosting. It happens for either bookmark, and loading a game made after Theramore is founded doesn't cause a crash.

Sadly I don't have any save games where the crash occurred, I didn't think to hold onto an autosave with it happening. My checksum is XDSW

**Comment by zumbak04** [comment]
@Mystic-Fox do you use 3.3.0 vanilla version too?
I got it reproduced once, but it was on 3.3.0.
[Crash_Scourge603_06_23.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/4082913/Crash_Scourge603_06_23.zip)

**Comment by Mystic-Fox** [comment]
Yes, I run 3.3.0. It could very well be that, since the mod doesn't support that version yet. Its annoyingly inconsistent though, I haven't has the problem in a few weeks.

**Comment by zumbak04** [comment]
> Yes, I run 3.3.0. It could very well be that, since the mod doesn't support that version yet. Its annoyingly inconsistent though, I haven't has the problem in a few weeks.

Better switch to 3.2.2 or 3.2.1. They're more stable. Never had a crash there.

**Comment by Shadowling-McBeard** [comment]
I've been suddenly getting this issue as well.
I'm running CK2 v3.2.2 with all the stuf from the GoA v1.6.0.3 ModDB archive except the Russian localisation, and Leafwalker from the Steam Workshop.

The weird thing is that I've been playing for a whole week now through a multitude of different kingdoms, had the event happen multiple times, and it only started crashing with it two days ago but now it happens every time.
I've tried a clean re-install like recommended here but that changed nothing for the save I copypasted over from the previous install, it's still crashing. Haven't tried starting a new game in the fresh install yet because I figured that won't help fix the bug, it'd just make me not experience it for a while.

Attached the save at the Founding of Theramore choice event firing for my character. The crash happens a couple of months after this (with the actual founding of Theramore) no matter which choice I make.

[Quel'thalas THERAMORE 603_08_15.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/4171451/Quel.thalas.THERAMORE.603_08_15.zip)

**Comment by zumbak04** [comment]
@Shadowling-McBeard thanks for the save. It's reproducible. Trying to fix it right now.

**Comment by Shadowling-McBeard** [comment]
Wow, that was fast.
Glad I was able to provide some meagre assistance and can't wait for the next update (next to the bugfixes, the Frozen Throne stuff looks great too!).

**Comment by zumbak04** [comment]
@Shadowling-McBeard could you help us one more time?
I got the crash reproduced and fixed but it seems like 2 our testers don't get a crash at all.
If you have [the Early Version](https://www.moddb.com/mods/warcraft-kings-of-azeroth/features/how-to-get-early-version) installed, it would be nice if you could test [the Fix](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/pull/1156).

The branch name is `theramore-crashfix`.

**Comment by Shadowling-McBeard** [comment]
This will take a couple of hours since I don't have the early version installed and it's almost time to make dinner but yes, I will try it out.

**Comment by Shadowling-McBeard** [comment]
nvm that all went faster than expected. Can confirm that I am no longer crashing when Theramore gets founded in the save file I shared here. Will try a new playthrough to see if it worked there as well, but that's definitely going to be after dinner.

**Comment by zumbak04** [comment]
> nvm that all went faster than expected. Can confirm that I am no longer crashing when Theramore gets founded in the save file I shared here.

Do you still crash on this save when you're on the `master` branch?

**Comment by Shadowling-McBeard** [comment]
I just thought about trying that for some more info and yes, I am.

**Comment by zumbak04** [comment]
@Shadowling-McBeard aight, thanks for the help!

**Comment by Shadowling-McBeard** [comment]
It's my pleasure.
After dinner I'll try to start a new game on the master branch to see if I still get the crash and then the fixed branch to see if it's fixed just beyond my save file (I'll upload another save if it crashes again on the test branch) but other than that, is it okay if I keep playing on the fixed branch?
I have no idea what the etiquette about that kind of thing is here, I literally made this account to report this bug :')

**Comment by Shadowling-McBeard** [comment]
So, here's the complete results of everything I've tried today:

-loaded my save on the theramore-crashfix branch, did not crash
-loaded my save on the master branch, did crash
-new game on the theramore-crashfix branch, did not crash
-new game on the master branch, did not crash(!)
-new game on the master branch with Leafwalker, did crash
-new game on the theramore-crashfix branch with Leafwalker, did not crash
-new game with the ModDB version including GoA Models and GoA Music, did not crash(!)
-loaded my save with the ModDB version including GoA Models and GoA Music, did crash
-new game with the ModDB version including GoA Models and GoA Music, and Leafwalker, did not crash(!)
-loaded my save on the theramore-crashfix branch with all other mods, did not crash

All of the new games were at the Reign of Chaos start (obviously or this would've taken a lot longer) as Quel'thalas with the standard ruler and made all of the same choices in the events leading up to the founding of Theramore (joining the war against the Scourge etc.) to eliminate as much randomness as possible.

So I'm at a loss why I suddenly started getting this issue 100% of the time or why now it's suddenly not perfectly replicable outside of my save file but it does seem to be fixed entirely on the theramore-crashfix branch.

**Comment by zumbak04** [comment]
New games may not crash because the crash is caused by the political situation of murloc tribes that live near Theramore.

**Comment by zumbak04** [comment]
Even your save don't crash sometimes because the murlocs end a war.

**Comment by Shadowling-McBeard** [comment]
>the crash is caused by the political situation of murloc tribes


You have got to be shitting me. Will I ever be safe from the little bastards :')

**Comment by zumbak04** [comment]
> You have got to be shitting me. Will I ever be safe from the little bastards :')

Never! If you got bugs, first, blame them!

**Comment by zumbak04** [comment]
Closed the issue, thanks to everyone for your saves and reports!
![image](https://user-images.githubusercontent.com/46384992/74108812-3e902380-4b97-11ea-9fb7-1d604cfd419f.png)
