### ISSUE TITLE
Patron characters married from the get go.

### ISSUE THREAD

**Issue by geffe1** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#944]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
Master Branch
**What expansions do you have installed?**
ALL
**Are you using any submods/mods? If so, which?**
NOPE
**Please explain your issue in as much detail as possible:**
Patron characters start with a marriage and children.
**Steps to reproduce the issue:**
Start the game and choose any char, check for patron chars without unpausing.
**Upload an attachment below: .zip of your save, or screenshots:**
![ck2_447](https://user-images.githubusercontent.com/31706375/68908527-ebe7cc80-074b-11ea-86ea-22aabfbbea02.png)

**Comment by zumbak04** [comment]
It's not a bug, it's a game rule.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/68954557-b1c70b00-07dd-11ea-967e-39aa176e9933.png)

</details>
