### ISSUE TITLE
"Pray to Elune" localisation is wrong

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#95]
Master branch
Low

Trolls didn't worship Elune for thousands of years

<details>
<summary>Click to expand</summary>

![ck2_2](https://user-images.githubusercontent.com/46576860/52034378-65099080-2539-11e9-9a63-6cf1ef1971d2.png)

</details>

**Comment by sejtalk** [comment]
fixed

**Comment by MemeWizard** [comment]
Also event text

<details>
<summary>Click to expand</summary>

![ck2_1](https://user-images.githubusercontent.com/46576860/53575766-4c65b800-3b83-11e9-96cd-2ad1c574faaf.png)

</details>

**Comment by sejtalk** [comment]
fixed
