### ISSUE TITLE
Alexander the Great of Zandalari

### ISSUE THREAD

**Issue by Mangasito** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#957]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version** 1.6.0

**Are you using any submods/mods? If so, which?** Dark Ages ( https://steamcommunity.com/workshop/filedetails/?id=1795476655 ) That one, 'cause there's another one with the same name. Also the GoA Unlimited submod but that should only unlock char creator options

**Please explain your issue in as much detail as possible:** A murloc conquered the Zandalari Empire and got a cool bloodline. It said Alexander the great. It should have said "Our great and beloved savior Garithos"

**Upload screenshots of the problem localization:** https://cdn.discordapp.com/attachments/425800842642194445/647439914119594004/unknown.png

**Comment by zumbak04** [comment]
Reported in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/issues/898 .
