### ISSUE TITLE
Culture and religion have the same name

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#958]
**Mod Version**
97b065af

**Are you using any submods/mods? If so, which?**
No

**Please explain your issue in as much detail as possible:**
Culture and religion have the same name and it's confusing

**Upload screenshots of the problem localization:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/69482330-c41ef580-0e2a-11ea-9e11-31b816d990ad.png)
![image](https://user-images.githubusercontent.com/46576860/69482339-d862f280-0e2a-11ea-8faa-0ce4e446cf2b.png)
![image](https://user-images.githubusercontent.com/46576860/69482355-fb8da200-0e2a-11ea-9dd7-5fbd231b5f6b.png)

</details>

**Comment by geffe1** [comment]
Elune or druidism, is the two religions that are fused together in their religion.. it is a hybrid religion of sorts. 

There is no official name to it, it is either Elune worshipping or druidism.

**Comment by zumbak04** [comment]
> There is no official name to it, it is either Elune worshipping or druidism.

What about name "Eluniс"?
![image](https://user-images.githubusercontent.com/46384992/69813248-3d439180-120b-11ea-9661-0473b4744686.png)

**Comment by MemeWizard** [comment]
Also:
Shath'Yar religion and Shath'Yar culture

**Comment by zumbak04** [comment]
Renamed
