### ISSUE TITLE
Gorehowl for Grommash

### ISSUE THREAD

**Issue by ScammiB** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#961]
**DO NOT REMOVE PRE-EXISTING LINES**
----------------------------------------------------------------------------------------------------------
**Describe your suggestion in full detail below:**
https://wow.gamepedia.com/Gorehowl

The Axe is very important to Grom's character, and currently he seems pretty weak in comparison to how he is portrayed in lore and w3, so a strong artifact would bring him in line with what he sould be within the game

**Comment by zumbak04** [comment]
Done in #1006
