### ISSUE TITLE
Losing Tech When Founding Theramore

### ISSUE THREAD

**Issue by traiusbottomfeed** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#962]
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.6
**What expansions do you have installed?**
All of them
**Are you using any submods/mods? If so, which?**
I'm using the regular mod + models and music
**Please explain your issue in as much detail as possible:**
Prior to founding Theramore, I had level 4 in all military tech and level 3 in all econ and culture techs. After founding Theramore, I only had 1 in each tech.
**Steps to reproduce the issue:**
Play as a Lordaeron human and found Theramore.
**Upload an attachment below: .zip of your save, or screenshots:**

**Comment by zumbak04** [comment]
It's not a bug, so I'll turn it into a balance suggestion.
