### ISSUE TITLE
Tauren Totem it's a weapon, but it's not

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#966]
**Mod Version**
6ca57710

**What expansions do you have installed?**
All

**Are you using any submods/mods? If so, which?**
No

**Please explain your issue in as much detail as possible:**
Tauren Totem have combat_weapon flag, but it's not a weapon

**Steps to reproduce the issue:**
Duel with equipped tauren totem

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/69778948-60dcec80-11b7-11ea-8e15-b21b6332aa3c.png)

![image](https://user-images.githubusercontent.com/46576860/69778919-49056880-11b7-11ea-80e4-bd49c3c00721.png)

</details>

**Comment by geffe1** [comment]
Insert pepegoat 
I bet he killed that hoe with his tauren "totem".

**Comment by sejtalk** [comment]
Tauren totems are used as weapon so i suggest changing it's slot to weapon instead of removing flag
