### ISSUE TITLE
Overthrowing Alliance (and Horde!) Leaders

### ISSUE THREAD

**Issue by spacsea** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#973]
**DO NOT REMOVE PRE-EXISTING LINES**
----------------------------------------------------------------------------------------------------------
**Describe your suggestion in full detail below:**
I suggest that instead, the title shift to whoever is the leader of the "overthrow" faction. This will provide more stability and makes more sense. If possible the abdication event could add a third option for the abdication of Alliance/Horde leader where he takes his domain out of the Alliance/Horde as part of the overthrow with the rationale being historical examples such as Slyvannas's latest crazy, or Stormguard standing alone. This would give the player more options so that they aren't railroaded.

**Comment by zumbak04** [comment]
@spacsea 
> If possible the abdication event could add a third option for the abdication of Alliance/Horde leader where he takes his domain out of the Alliance/Horde as part of the overthrow with the rationale being historical examples such as Slyvannas's latest crazy, or Stormguard standing alone. This would give the player more options so that they aren't railroaded.

So, I like this suggestion, BUT!

> I suggest that instead, the title shift to whoever is the leader of the "overthrow" faction. This will provide more stability and makes more sense.

I wouldn't do this one because that's how the claimant revolt works.

**Comment by zumbak04** [comment]
Update:
I tried to implement it but it looks like there's a problem: the faction destroys on revolt (a part of 406cbb921f02f4712caff38bee7e3c13394323fd fix), so I can't say it makes much sense now, anyway, it's done.
