### ISSUE TITLE
Old gods priests are holy

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#99]
Master branch

Twilight hammer cultist can complete the "sacrifice a holy person" mission by sacrificing old gods priest.
<details>
<summary>Click to expand</summary>

![ck2_4](https://user-images.githubusercontent.com/46576860/52126553-ae90d300-2640-11e9-945c-ae7110dffd3b.png)

</details>

**Comment by zumbak04** [comment]
Fixed!
